### ISSUE TITLE
cannot normally start tpot service 

### ISSUE THREAD

**Issue by benny12312311** [telekom-security/tpotce#1002]
🗨️ Please post your questions in [Discussions](https://github.com/telekom-security/tpotce/discussions) and keep the issues for **issues**. Thank you 😁.<br>

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster
Linux dizzydhow 4.19.0-18-amd64  #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
- What T-Pot version are you currently using?
tpot version 20.06.2
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM(virtual box)
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
[install.log](https://github.com/telekom-security/tpotce/files/7966159/install.log)
[install.err.log](https://github.com/telekom-security/tpotce/files/7966160/install.err.log)
- How long has your installation been running?
It never worked normally.
- Did you install upgrades, packages or use the update script?
yes
- Did you modify any scripts or configs? If yes, please attach the changes.
no
- Please provide a screenshot of `glances` and `htop`.
<img width="1440" alt="截圖 2022-01-30 下午11 24 16" src="https://user-images.githubusercontent.com/64942741/151705949-83dba47b-89f2-4528-84f9-dc4e29100755.png">
<img width="1440" alt="截圖 2022-01-30 下午11 24 39" src="https://user-images.githubusercontent.com/64942741/151705976-7d072b62-f7d5-4913-aad3-caac33443fba.png">
- How much free disk space is available (`df -h`)?
<img width="905" alt="截圖 2022-01-30 下午11 29 41" src="https://user-images.githubusercontent.com/64942741/151706162-d216a3aa-746e-4a79-afeb-a8638110b63b.png">
<img width="905" alt="截圖 2022-01-30 下午11 29 48" src="https://user-images.githubusercontent.com/64942741/151706218-561647e5-4aaf-4638-8683-ff576f8e5228.png">
- What is the current container status (`dps.sh`)?
<img width="905" alt="截圖 2022-01-30 下午11 34 39" src="https://user-images.githubusercontent.com/64942741/151706325-acdd5bf3-2425-4dac-8dbf-3dd061f6536c.png">
- What is the status of the T-Pot service (`systemctl status tpot`)?
<img width="905" alt="截圖 2022-01-30 下午11 37 33" src="https://user-images.githubusercontent.com/64942741/151706390-cdb542c0-b817-4759-a755-384fd9093dc0.png">
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
<img width="905" alt="截圖 2022-01-30 下午11 40 20" src="https://user-images.githubusercontent.com/64942741/151706476-20ab1027-b866-4bb2-ba61-52e190b31610.png">
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

#### I've found many issues that are similar to my condition, but I tried to use their solution, I still cannot fix my problems.

**Comment by t3chn0m4g3** [comment]
It seems you are using the post installation method, correct? If yes, please try the iso and check if it has the same problem.
It is also possible it is a bug, since the user `tpot` should be reserved. You can also try a fresh install with a different user (tpot user may not exist).

**Comment by benny12312311** [comment]
Thanks for your reply!
I tried to use the iso file that is offered on GitHub.
But I keep getting failure during "Install the base system" step!
Please help me!
<img width="405" alt="截圖 2022-01-31 下午11 55 25" src="https://user-images.githubusercontent.com/64942741/151827288-00f45cc1-403d-459f-b88d-1eea13f4386c.png">

My syslog:
[syslog.log](https://github.com/telekom-security/tpotce/files/7972187/syslog.log)

My VM configuration:
OS: Debian 10(64 bits)
Ram: 12288 MB
Storage:
<img width="378" alt="截圖 2022-02-01 上午12 00 07" src="https://user-images.githubusercontent.com/64942741/151828150-c58de07e-a5c2-457b-9f68-c13286ad6834.png">
Network: bridged adapter, promiscuous mode: allow all, adapter type: intel pro/1000 MT server

**Comment by t3chn0m4g3** [comment]
If this fails do a fresh post-install installation, but you have to chose a different user than `tpot`.

**Comment by benny12312311** [comment]
Thanks for your reply.
I tried to do a fresh post-install installation and chooser a different user name.
But the container seems to keep restarting.
<img width="350" alt="截圖 2022-02-01 下午2 53 24" src="https://user-images.githubusercontent.com/64942741/151925655-d92806b9-f3ef-46e3-96bb-bbf510333aa1.png">

And the status of head, Kibana, logstash, snare keep down.
Please help me!
Thanks a lot!

**Comment by t3chn0m4g3** [comment]
Please provide the log files from the fresh install.

Also run (as root) do the following ...
```
systemctl stop tpot
docker-compose -f /opt/tpot/etc/tpot.yml up
```
... and provide the logs.

**Comment by t3chn0m4g3** [comment]
Also... according to the `syslog.log` you provided earlier you did modifications as it shows you installed filebeat. This is not supported:
```
Jan 31 00:00:09 nuc181 filebeat[895]: 2022-01-31T00:00:09.892Z#011INFO#011[monitoring]#011log/log.go:184#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cgroup":{"cpuacct":{"total":{"ns":9958861}}},"cpu":{"system":{"ticks":245550,"time":{"ms":5}},"total":{"ticks":585250,"time":{"ms":17},"value":585250},"user":{"ticks":339700,"time":{"ms":12}}},"handles":{"limit":{"hard":524288,"soft":1024},"open":11},"info":{"ephemeral_id":"65beb7cf-2fc4-4e0b-8e63-3d20f92e7979","uptime":{"ms":938943441},"version":"7.16.3"},"memstats":{"gc_next":19512448,"memory_alloc":11118536,"memory_total":30666004296,"rss":32559104},"runtime":{"goroutines":35}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"active":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.12,"15":0.21,"5":0.18,"norm":{"1":0.015,"15":0.0263,"5":0.0225}}}}}}
```

The log also indicates that there are problems with your VirtualBox installation.
At this point please review the `syslog.log` and sort out the issues your host has.

**Comment by benny12312311** [comment]
My fresh install's log files:
[install.log](https://github.com/telekom-security/tpotce/files/7976789/install.log)
[install.err.log](https://github.com/telekom-security/tpotce/files/7976790/install.err.log)
<img width="602" alt="截圖 2022-02-01 下午4 07 00" src="https://user-images.githubusercontent.com/64942741/151932960-59d5e12a-d954-4e61-a853-55075974070c.png">

**Comment by t3chn0m4g3** [comment]
Snare is running on `tcp/80` and according to the log either your host or your `tpot.yml` was adjusted to run something else on `tcp/80`.
`docker-compose down -v` and then run `netstat -tulpen` which should assist finding the culprit.

**Comment by benny12312311** [comment]
![截圖 2022-02-01 下午4 42 40](https://user-images.githubusercontent.com/64942741/151937385-779f1f79-ea2f-4ac6-8b55-3668f4c04ff1.png)
![截圖 2022-02-01 下午4 43 19](https://user-images.githubusercontent.com/64942741/151937396-7fb0fc3f-3fe4-4719-bad9-7d6c06d649aa.png)

So I should change the thing that is running on port 80?

**Comment by t3chn0m4g3** [comment]
Yes, but it seems T-Pot is still running. `systemctl stop tpot` first and then you can check if it is something on the host.

**Comment by benny12312311** [comment]
<img width="540" alt="截圖 2022-02-01 下午6 13 15" src="https://user-images.githubusercontent.com/64942741/151950233-8ed63da3-9033-48e2-b47a-f90a5093ff6f.png">
 This is what I typed   ` netstat -tulpen `   _after_ I had stopped t pot

**Comment by t3chn0m4g3** [comment]
Do any of the containers still run `dps.sh`?
Then you still need `docker-compose -f /opt/tpot/etc/tpot.yml down -v`.

**Comment by Pommaq** [comment]
Not sure if its the exact same issue but the effects were the same. Most containers were reported as down by dps.sh.

Tried pulling directly from repo and ran it from a user named "tpot". Some services would function and roughly half were dead. reinstalling debian 10 and using a different username appears to have fixed it. T-pot is running default config. I will know for sure once kibana boots completely

**Comment by benny12312311** [comment]
@t3chn0m4g3  no, there is nothing running dps.h (everything's status is down)

**Comment by t3chn0m4g3** [comment]
Hmmm, this time you show me a different log :bowtie: 
`netstat -anp` and you should see which service is running `tcp/80`

**Comment by benny12312311** [comment]
I typed that command, but I cannot figure out what is going on... sorry
<img width="899" alt="截圖 2022-02-01 下午8 32 34" src="https://user-images.githubusercontent.com/64942741/151969225-c09b7e1d-1766-488a-b54c-75c2bd13cddd.png">
<img width="899" alt="截圖 2022-02-01 下午8 32 42" src="https://user-images.githubusercontent.com/64942741/151969245-400821e6-86fd-4f7a-a920-0665879be9a9.png">
<img width="899" alt="截圖 2022-02-01 下午8 33 18" src="https://user-images.githubusercontent.com/64942741/151969261-c5fefe5f-139d-4dbe-bfac-5f47affb9179.png">
<img width="899" alt="截圖 2022-02-01 下午8 33 33" src="https://user-images.githubusercontent.com/64942741/151969267-a004d685-c4cf-4e38-9ab2-b23c72bd9088.png">

**Comment by t3chn0m4g3** [comment]
If `netstat -anp` nor `netstat -tulpen` do show any PID / daemon that is occupying `0:0:0:0/80` then I cannot help you either. A fresh Debian Install (from the mini.iso) should only provide you with `tcp/22` and some dhcp related services that in no way collide with the T-Pot services. Which is checked by the installer.

I can only suggest again to run a fresh install (not tpot as user name) and make sure that when you run the installer and it asks you for the services `tcp/80` is not part of the check.

**Comment by benny12312311** [comment]
@t3chn0m4g3 
I've tried to run a fresh install and there is nothing occupying 0.0.0.0/80!
And everything seem to be OK!!
<img width="562" alt="截圖 2022-02-01 下午10 17 17" src="https://user-images.githubusercontent.com/64942741/151984996-133d7ac2-90c9-4734-a43f-d39552b2ae82.png">

I think is my fault to pre-install net-tools package in my post Debian system.
Thank you so much!!
It bothered me for a month..

**Comment by t3chn0m4g3** [comment]
Welcome 😄

**Comment by benny12312311** [comment]
sorry, I have another problem.
That is, I can access my T-Pot via ssh(port 64295) and the Admin UI (port 64294).
But when I tried to connect T-Pot Landing Page(port 64297), it shows that I  am unable to connect.
Can you offer some suggestions? And do I need to provide any infos?

**Comment by t3chn0m4g3** [comment]
You probably locked yourself out. Use `fail2ban-client unban --all`.

**Comment by benny12312311** [comment]
Should I type the command in T-Pot opened or closed?

**Comment by benny12312311** [comment]
I've typed that command!
But it seems to block me whenever I try to access WebUI.
So I still cannot connect to T-Pot Landing Page.

**Comment by t3chn0m4g3** [comment]
I think you are using the wrong credentials then.
Try #875

**Comment by benny12312311** [comment]
My /data/nginx/conf/nginxpasswd file only contains one line.
The line shows webuser:$blablabla$blablabla.

**Comment by benny12312311** [comment]
I try the solution and it works!!!!
Thanks a lot!!

**Comment by t3chn0m4g3** [comment]
Enhanced by 58713e9b840f7c225221b5f2cc013cce1d864dc8
