### ISSUE TITLE
tls: bad record MAC

### ISSUE THREAD

**Issue by NA3** [telekom-security/tpotce#1004]
🗨️ Please post your questions in [Discussions](https://github.com/telekom-security/tpotce/discussions) and keep the issues for **issues**. Thank you 😁.<br>

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

![image](https://user-images.githubusercontent.com/3059879/152129160-2fb45dd4-c8db-4cb8-a3ec-12d4e99c1488.png)

- What T-Pot version are you currently using?

![image](https://user-images.githubusercontent.com/3059879/152129275-179dc139-2bd5-4ec7-a4b4-6c1aef505f77.png)

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
   standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
   vm esxi + vcenter 6.7
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
   yes 

https://pastebin.com/Fa2rR8Sq

![image](https://user-images.githubusercontent.com/3059879/152130798-d29996c9-13fa-4293-a840-94db48e71e66.png)
![image](https://user-images.githubusercontent.com/3059879/152134973-b9745826-dea7-454b-902b-08034a99cbfc.png)

- How long has your installation been running?
    is fresh iso install
- Did you install upgrades, packages or use the update script?
   no
- Did you modify any scripts or configs? If yes, please attach the changes.
   no
- Please provide a screenshot of `glances` and `htop`.
 
![image](https://user-images.githubusercontent.com/3059879/152130431-090c849d-b58d-49dd-9364-16214f9813d4.png)

![image](https://user-images.githubusercontent.com/3059879/152130511-4a5b0b7e-d96b-4f21-adfc-f072a0f642c3.png)

![image](https://user-images.githubusercontent.com/3059879/152131789-2bada282-3e31-4fa9-af2f-2a83aa441964.png)

i can access 64294 and start container manualy  but i cant pull elk
  i have not modifie tpot.yml
- How much free disk space is available (`df -h`)?

![image](https://user-images.githubusercontent.com/3059879/152130655-c0aca31d-dff8-42a1-b647-1576712e9be0.png)

- What is the current container status (`dps.sh`)?

![image](https://user-images.githubusercontent.com/3059879/152130900-07e06990-bf30-4259-96cb-0f4dfe8effa7.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?

![image](https://user-images.githubusercontent.com/3059879/152131068-54cdec0e-4c00-48ae-802e-f277aaf0208b.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

![image](https://user-images.githubusercontent.com/3059879/152131192-13a8a4ed-2a8c-4bbb-a845-cc3d30e51879.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this...
![image](https://user-images.githubusercontent.com/4318452/152136405-4aba8c0d-3d32-4c52-9030-080b8279872a.png)

You try to pull the images manually in the hopes of getting a more detailed error message.
```
docker pull dtagdevsec/elasticsearch:2006
docker pull dtagdevsec/logstash:2006
docker pull dtagdevsec/kibana:2006
```

**Comment by NA3** [comment]
![image](https://user-images.githubusercontent.com/3059879/152138575-4ef8eb72-40b8-4512-b0f7-92bcb3ee48f2.png)
i have to wait 6hours
i will try later thx

**Comment by NA3** [comment]
![image](https://user-images.githubusercontent.com/3059879/152146074-4731606b-417f-48a6-a3b1-ce0939ba9277.png)
 i got it from my local computer, i will try push it to my local harbor and pull it on t-pot vm

**Comment by NA3** [comment]
![image](https://user-images.githubusercontent.com/3059879/152154255-a0388e8b-4e4d-4dc1-a9d7-85951a0f732a.png)
same error but i can pull it on local machine.

**Comment by t3chn0m4g3** [comment]
This usually point to network problems (according to a google search regarding the error message).
Unfortunately nothing I can reproduce or help you with on my end.

**Comment by NA3** [comment]
i have make a new install and still the same error
i have got it working by limiting the bandwich on my opensense firewall using this 
https://docs.opnsense.org/manual/how-tos/shaper_share_evenly.html

![image](https://user-images.githubusercontent.com/3059879/152246338-fa890bce-89fc-4a45-824e-40bd755f8ffa.png)

**Comment by t3chn0m4g3** [comment]
Thanks for sharing your solution!
