### ISSUE TITLE
OS admin user unable to login after post install auto

### ISSUE THREAD

**Issue by alphaDev23** [telekom-security/tpotce#1027]
After installing 20.06.3 using the 'post install auto' method (https://github.com/telekom-security/tpotce#post-install-auto), I'm able to login as a web user but not as the admin (via cockpit) of via ssh.  The image was build using HashiCorp's Packer program using a debian openstack image as a base and the build completed without issue.

My tpot.conf file is per the instructions:

# tpot configuration file
# myCONF_TPOT_FLAVOR=[STANDARD, SENSOR, INDUSTRIAL, COLLECTOR, NEXTGEN, MEDICAL]
myCONF_TPOT_FLAVOR='STANDARD'
myCONF_WEB_USER='<USERNAME>'
myCONF_WEB_PW='<PASSWORD>'

Are there additional settings for the Cockpit and ssh passwords that belong in the tpot conf file and/or are their default usernames/passwords that are used for Cockpit and ssh?  I do not see instructions appears to be a bug.  As a note, if the first commented line is removed from the conf file, the  regarding this.  If now this appears to be a bug.  As a note, if the first commented line is removed from the conf file, the install fails with an error message stating that it is not a tpot conf file.

**Comment by t3chn0m4g3** [comment]
You need to use the Linux user you used to setup Linux.

**Comment by alphaDev23** [comment]
For whatever reason, I was unable to log in using this user with an ssh-key.  A reboot resolved the issue along with fail2ban refusing the connection.
