### ISSUE TITLE
No kernel modules found when installing on Proxmox

### ISSUE THREAD

**Issue by pontiaj2066** [telekom-security/tpotce#1048]
I'm attempting to install on Proxmox using the 20.06.2 iso. No matter which mirror I select, it tells me no kernel modules were found. It looks like issues #733 and #896 had similar issues, and were resolved with another release. Usually Debian updating kernel modules.
Thank you!

**Comment by vibenas** [comment]
for me the same, with vmware, tried yesterday. Lets wait for the release. Or maybe someone knows the workaround?

**Comment by t3chn0m4g3** [comment]
Thanks for reporting!
Updated the [release](https://github.com/telekom-security/tpotce/releases/tag/20.06.2), just download the ISO again.
Should any encounter this, you can simply create your own ISO with `makeiso.sh` or use the post-install method.

**Comment by vibenas** [comment]
> Thanks for reporting! Updated the [release](https://github.com/telekom-security/tpotce/releases/tag/20.06.2), just download the ISO again. Should anyone encounter this, you can simply create your own ISO with `makeiso.sh` or use the post-install method.

Thanks for fast official update, checked - works for me. As I understand, such notification in the future should be raised here, for resolving for everyone.
