### ISSUE TITLE
Installation 22.04.00 nic issue eth0 ens192

### ISSUE THREAD

**Issue by atbohmer** [telekom-security/tpotce#1073]
Hello,

Probably a simple repair, but during installation I configure a static IP address. After T-pot setup the VM host has an dhcp assigned IP address. Now there is an eth0 active with indeed the dhcp address, but no interface with the static ip. The file /etc/network/interfaces points out interface ens192  as the static ip configured interface and no eth0 to be found except commented out. Could not find any rules in /etc/udev/ .
Any idea how to correct this? So skip eth0 and have ens192 act like it should?

Kind regards,
Andre

**Comment by t3chn0m4g3** [comment]
[This](https://github.com/telekom-security/tpotce/blob/master/README.md#network-interface-fails) might help.

**Comment by atbohmer** [comment]
Must be Friday, I modified interfaces and rebooted before and to no avail. Now after your post again and now it works. Time for a beer I guess to rest my fuzzy brain.

**Comment by t3chn0m4g3** [comment]
I have remote hardware healing powers :bowtie:

**Comment by atbohmer** [comment]
I hope you do not have any credits on that gift, like to use it more often ;-)

**Comment by t3chn0m4g3** [comment]
Sadly, every time I use it a piece of legacy hardware stops working 😢
