### ISSUE TITLE
Port conflict results in auto-restarting

### ISSUE THREAD

**Issue by Attila-Deak** [telekom-security/tpotce#1084]
I have been using T-Pot 20.06 version on Debian 10 for almost one year and collected around 170 GB of data :)
I decided to upgrade to Debian 11 and install the newest version of T-Pot  22.04, and unfortunately, I ran into a problem as T-Pot keeps auto-restarting. I installed the Standalone version with Post Install User Method, and the user I created during the Debian install has full root access. 
I tried fresh installations with Debian 11.0, 11.1, 11.2, 11.3 and also with the offered ISO from GitHub, the same issue. The auto-restart can also be replicated in VMware Workstation. 
Hopefully, someone can guide me to fix this issue and further improve this awesome project.

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
Linux farhurt 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

- What T-Pot version are you currently using?
T-Pot 22.04

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standalone version with Post Install User Method

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Hardware specs:
CPU: i5-9400
RAM: 32GB
SSD: 240GB

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No problems 
[install.log](https://github.com/telekom-security/tpotce/files/8601957/install.log)
[install.err.log](https://github.com/telekom-security/tpotce/files/8601960/install.err.log)

- How long has your installation been running?
Never worked, keeps auto-restarting

- Did you install upgrades, packages or use the update script?
No updates, installed git, glances, neofetch and later AnyDesk 

- Did you modify any scripts or configs? If yes, please attach the changes.
No

- Please provide a screenshot of `glances` and `htop`.
![htop](https://user-images.githubusercontent.com/104752574/166213196-c49e26ce-bcb0-4fb2-b6fd-9e168de643a4.png)
![glances](https://user-images.githubusercontent.com/104752574/166213221-40ff6c0c-0a5e-4ec1-858b-a22f3b0b8978.png)

- How much free disk space is available (`df -h`)?
![free space df- h](https://user-images.githubusercontent.com/104752574/166213262-9e48ea07-8e69-4cd3-9294-478b54f9b65d.png)

- What is the current container status (`dps.sh`)?
![dps sh 1](https://user-images.githubusercontent.com/104752574/166213295-e3f8006d-8f57-42ff-8fa4-db9477190fae.png)
![dps sh 2](https://user-images.githubusercontent.com/104752574/166213310-3a4763f6-bbd1-4af9-85e1-f82107fec32e.png)
![dps sh 3](https://user-images.githubusercontent.com/104752574/166213320-e8462f68-385b-4b7f-ab78-01c6d145e6c9.png)
- What is the status of the T-Pot service (`systemctl status tpot`)?
![systemctl tpot services1](https://user-images.githubusercontent.com/104752574/166213379-2dee778b-ec63-4cf7-b830-6ec028cbf89a.png)
![systemctl tpot services2](https://user-images.githubusercontent.com/104752574/166213387-9cb6f78c-af05-4d22-8a80-47f0e6775e28.png)
![systemctl tpot services3](https://user-images.githubusercontent.com/104752574/166213407-519c982b-a9c2-412c-83d6-fef2bfc38df2.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
[netstat -tulpen.log](https://github.com/telekom-security/tpotce/files/8601985/netstat.-tulpen.log)
[netstat -anp.log](https://github.com/telekom-security/tpotce/files/8601988/netstat.-anp.log)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
docker-compose -f 
![docker-compose -f](https://user-images.githubusercontent.com/104752574/166213794-75e62960-eb93-4d72-a0e4-468d359916b5.png)

**Comment by t3chn0m4g3** [comment]
There seems to be a port conflict.
Please stop T-Pot and run `netstat -tulpen`, but it is probably port 631.

**Comment by Attila-Deak** [comment]
Thanks for the prompt response
[new netstat -tulpen.log](https://github.com/telekom-security/tpotce/files/8602117/new.netstat.-tulpen.log)

is this the cause?
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      0          511        629/cupsd

**Comment by t3chn0m4g3** [comment]
Yes, you need to disable that service (`cupsd`). Probably installed as part of your Debian installation.

**Comment by Attila-Deak** [comment]
I disabled the service and rebooted, but the port is still allocated can I somehow force to change?

[ati@farhurt:~]$ sudo systemctl status cupsd
Unit cupsd.service could not be found.
[ati@farhurt:~]$ 


[ati@farhurt:~]$ sudo netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 127.0.0.1:38741         0.0.0.0:*               LISTEN      0          448        645/containerd      
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      0          18476      603/cupsd           
tcp        0      0 0.0.0.0:7070            0.0.0.0:*               LISTEN      0          12726      614/anydesk         
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          12696      627/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:37931           0.0.0.0:*               LISTEN      0          42590      614/anydesk         
tcp6       0      0 ::1:631                 :::*                    LISTEN      0          18475      603/cupsd           
tcp6       0      0 :::64294                :::*                    LISTEN      0          1635       1/init              
tcp6       0      0 :::64295                :::*                    LISTEN      0          12698      627/sshd: /usr/sbin 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           108        18451      538/avahi-daemon: r 
udp        0      0 0.0.0.0:48426           0.0.0.0:*                           108        18453      538/avahi-daemon: r 
udp        0      0 0.0.0.0:631             0.0.0.0:*                           0          19522      628/cups-browsed    
udp6       0      0 :::5353                 :::*                                108        18452      538/avahi-daemon: r 
udp6       0      0 :::33615                :::*                                108        18454      538/avahi-daemon: r 
[ati@farhurt:~]$

**Comment by t3chn0m4g3** [comment]
Unfortunately a T-Pot reinstall will not change anything since it is simply not possible to react on all possible scenarios of other services conflicting with the ones from the honeypots. 

We recommend the [Debian Netinstall](https://github.com/telekom-security/tpotce#post-install) for Post-Install or the T-Pot ISO installation. Just do not install other services than SSH.

**Comment by Attila-Deak** [comment]
_We recommend the [Debian Netinstall](https://github.com/telekom-security/tpotce#post-install) for Post-Install or the T-Pot ISO installation. Just do not install other services than SSH._

As mentioned above, I already tried both install methods and ended up with the same results. It looks like Debian 11 desktop environments come automatically with services that are in port conflict with T-Pot. Some discovered so far are cups and  avahi-daemon.
In VMware, I was able to start up T-Pot by removing  `cups` and  `avahi-daemon.` services first and then installing T-Pot. I will try later on hardware as well.
![running2](https://user-images.githubusercontent.com/104752574/166235840-542a5e4e-692a-44e5-a77b-87256ab65ede.png)
![running1](https://user-images.githubusercontent.com/104752574/166235859-e4ba742e-7360-4314-b798-d1c766ddb1df.png)
![running3](https://user-images.githubusercontent.com/104752574/166235875-6069ecdb-a8f7-42f6-a925-f653115820fb.png)

**Comment by t3chn0m4g3** [comment]
Happy it works.

**Comment by t3chn0m4g3** [comment]
One question, though. Why do you install a desktop environment? This possibly introduces / increases attack surface on systems. Is this something you need in general or do you want to minimize exposure?

**Comment by Attila-Deak** [comment]
Yes, two main reasons:
1) I minimize exposure to my network as I only connect via a KVM switch.
2) It's easier to share pretty graphics on social media with a quick screenshot :)
