### ISSUE TITLE
elk node explansion/cluster install option

### ISSUE THREAD

**Issue by lcia-projects** [telekom-security/tpotce#1093]
**Is your feature request related to a problem? Please describe.**
I'd like long term storage, redundancy and the performance gains of an elk cluster with long term data from the honeypots

**Describe the solution you'd like**
much like you have an install option for hive-sensor/hive server. I think it would be great to have an option for an option for just storage expansion/elk cluster node. I'd like to do long term storage of logs. It think it would be pretty simple to set up an install option for just a docker image of elasticsearch that automatically joined to the master node. Giving the option of a. "hot" node or "warm" node would be great too. 

Once the cluster was set, you'd want to also change some of the shard values for the index and possibly the ILM settings if a warm node was set up. 

**Describe alternatives you've considered**
doing it myself. 

**Additional context**
hot nodes would be on SSD's or fast storage. Warm nodes would be on slow spinning drives for long term storage.

**Comment by t3chn0m4g3** [comment]
Thanks. This has been discussed in the past, however it has been decided to keep T-Pot as maintainable as possible.
If you have a demand for a more sophisticated Elastic Stack setup I recommend to adjust the HIVE_SENSOR Logstash configuration to meet your needs.
Thanks for understanding.
