### ISSUE TITLE
Raise network interfaces error TPOT 19.03

### ISSUE THREAD

**Issue by sudeyuksek** [telekom-security/tpotce#1125]
I installed a T-POT on VirtualBox. Whenever I connect to it, I see this error.
![image](https://user-images.githubusercontent.com/60464361/176887993-72f43113-b79a-4a50-af0e-5625c8d7e0ad.png)
Does anybody know how to fix it ?

**Comment by t3chn0m4g3** [comment]
T-Pot 19.03 is deprecated, you need 22.04. The error is described in the [Readme](https://github.com/telekom-security/tpotce#network-interface-fails).
