### ISSUE TITLE
Web UI side, Kibana has some spare areas with errors

### ISSUE THREAD

**Issue by sudeyuksek** [telekom-security/tpotce#1127]
I'm very new to T-Pot. It's been around 30 minutes after I setup my honeypot. When I search for 64297 port Web UI I can successfully get in but  most of the areas are filled with errors like this. 
![image](https://user-images.githubusercontent.com/60464361/177052972-b97be7fd-46cf-4c32-b872-bc46b5084625.png)

![image](https://user-images.githubusercontent.com/60464361/177052369-7efc540c-1149-49b2-af73-c9e5fe7e13d3.png)
Is there anything I should do ? I can see there are attacks from the Attack Map. And I can say there are surricata alerts
![image](https://user-images.githubusercontent.com/60464361/177052453-edd19b3c-af65-4aa9-8c02-f2e5cd98fe72.png)
@t3chn0m4g3 
![image](https://user-images.githubusercontent.com/60464361/177052951-21ddfb91-fdcf-442b-94c3-5e8a6a2d1ff5.png)

**Comment by t3chn0m4g3** [comment]
Welcome to T-Pot, please see #885, it's normal behavior.
