### ISSUE TITLE
After successful installation containers and Tpot are switching between up and down 

### ISSUE THREAD

**Issue by Filisimus** [telekom-security/tpotce#1129]
Hi,

I installed Tpot on my Strato V server and the installation itself (using git clone / install script with --type=user) went fine. Unfortunately both tpot itself and the containers are frequently restarting as you can see in the provided screenshots and I cant find the reason. As far as I understand the exit code 137 for the containers indicates a memory issue but the server has 16 GB of RAM and nothing else is running. 

Any help would be appreciated, thanks in advance.

--------------------------------------------------------------------------------------------------

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

lsb_release -a:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

uname -a:

Linux h2974193.stratoserver.net 5.4.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux

- What T-Pot version are you currently using?
latest version
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
V Server 
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
maybe 10 minutes?
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/55972194/177285034-3c18c039-fb43-4813-af3c-2cd6a617ed9b.png)

![image](https://user-images.githubusercontent.com/55972194/177285446-267044ba-3469-4dde-96ca-6c268f499d37.png)

- How much free disk space is available (`df -h`)?

Filesystem         Size  Used Avail Use% Mounted on
/dev/ploop10301p1  500G  9,7G  466G   3% /
none               8,0G     0  8,0G   0% /sys/fs/cgroup
none               8,0G     0  8,0G   0% /dev
tmpfs              8,0G     0  8,0G   0% /dev/shm
tmpfs              1,7G  1,4M  1,6G   1% /run
tmpfs              5,0M     0  5,0M   0% /run/lock
none               8,0G     0  8,0G   0% /run/shm
tmpfs              1,6G     0  1,6G   0% /run/user/0

- What is the current container status (`dps.sh`)?

![image](https://user-images.githubusercontent.com/55972194/177285885-54488460-ec39-4d48-a9cd-9d5d7b2e99b0.png)

![image](https://user-images.githubusercontent.com/55972194/177285924-38d5b7b6-144c-487a-916a-122a254a71a0.png)

![image](https://user-images.githubusercontent.com/55972194/177285769-99da2de4-6444-4d49-9809-0e904d238d56.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?

![image](https://user-images.githubusercontent.com/55972194/177286116-3f16da19-8a57-42a3-8e00-e94f9b5087f5.png)

![image](https://user-images.githubusercontent.com/55972194/177288271-cf2601ef-543e-4184-a441-9018a573a842.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

![image](https://user-images.githubusercontent.com/55972194/177286440-783a7ce6-2057-4773-bce6-07ce30c20702.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

If I try to get logs for any container (e. g. nginx) I get this error:  _Error: No such container: nginx_

**Comment by Filisimus** [comment]
Addendum to the last point (docker logs for nginx) - sometimes I get the error message 'No such container' and sometimes the command shows nothing, probably related to the current state of the container?

![image](https://user-images.githubusercontent.com/55972194/177292325-e24295ef-fdbc-424d-b1a1-ddba9599899e.png)

**Comment by t3chn0m4g3** [comment]
For some reason your host has a dns resolver running which conflicts with Ddospot, hence docker-compose senses the [port-conflict ](https://github.com/telekom-security/tpotce#troubleshooting) and fails to start.

**Comment by t3chn0m4g3** [comment]
Follow the Troubleshooting section in the Readme and post the docker-compose output.

**Comment by t3chn0m4g3** [comment]
BTW - Ubuntu is not supported. Closing this.
