### ISSUE TITLE
T-pot log files fill up to 256GB in as little as 2 days

### ISSUE THREAD

**Issue by PythonFiend** [telekom-security/tpotce#1131]
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? **Debian GNU/Linux 11 (bullseye)** / L**inux incrediblehide 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux**
- What T-Pot version are you currently using? **Latest**
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? **Standard**
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? **vSphere ESXi 6.7**
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. No
- How long has your installation been running? **2 days**
- Did you install upgrades, packages or use the update script? **No**
- Did you modify any scripts or configs? If yes, please attach the changes. **Only modified network settings**
- Please provide a screenshot of `glances` and `htop`.

**GLANCES**
![image](https://user-images.githubusercontent.com/75555974/177882541-ecf95504-5ee0-4b46-ac55-d7ba8d5ed406.png)

**HTOP**

![image](https://user-images.githubusercontent.com/75555974/177882713-5b8a1735-88e8-48c5-96bd-284ba073e2f9.png)

- How much free disk space is available (`df -h`)?

![image](https://user-images.githubusercontent.com/75555974/177882783-c6ce4b8b-eff9-4a38-82d8-05c0d9238a79.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/75555974/177883644-cd974713-5b22-44e7-a4af-1833db6936f2.png)
![image](https://user-images.githubusercontent.com/75555974/177883779-f55d89b1-7c5f-43ff-abb7-3ceb925c92f0.png)

- What is the status of the T-Pot service (`systemctl status tpot`)? **Active running**

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

![image](https://user-images.githubusercontent.com/75555974/177884233-4e37dd53-b80d-4bdd-9540-c01b838209c2.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

My apologies in advance if this question has already been asked. I searched for the issue but have not found anything similar. I'm running T-pot in a sandboxed environment, so it is not yet exposed to the Internet. It seems to run fine on all fronts. I have performed several attacks and T-pot caught them all. The main issue I'm having is that despite the fair amount of storage space (256GB), the logs fill up very quickly (2 days!), and then T-pot stops working.

The main culprit is suricata, so I deleted the eve.json file, which was clogging up the system. Now other eve.json files are filling up quickly as well. 
![image](https://user-images.githubusercontent.com/75555974/177885506-47b53a72-104e-4c96-be32-7ac86767cfa6.png)

Additionally, I accessed the docker suricata container and stopped suricata, but it restarted on its own later on, only to continue dumping more data into the files.

So, my question is how I can minimize the amount of logs being produced so that I can run t-pot normally without having to dump files so often. Thank you in advance for your help.

**Comment by t3chn0m4g3** [comment]
Did you check the contents of the `eve.json` log to identify what may trigger this odd behaviour?

**Comment by PythonFiend** [comment]
Really nothing out of the ordinary, at least that I can see. All there is information on each intrusion attempt. Here are some samples.

![image](https://user-images.githubusercontent.com/75555974/178007749-caf25b71-4199-4428-b415-54db532d7d60.png)
![image](https://user-images.githubusercontent.com/75555974/178007879-25af4f8e-fe69-4e85-ae36-d233ff175123.png)
![image](https://user-images.githubusercontent.com/75555974/178008096-de7e982f-f1be-4023-b4cb-1abeca4e37a5.png)

**Comment by t3chn0m4g3** [comment]
You said it is sandboxed, how can there be any traffic from outside the sandbox? All should be contained within, as a result it must be a loop of events permanently reoccurring. You can always stop T-Pot and adjust `/opt/tpot/etc/tpot.yml` to your needs and remove Suricata. Also you can adjust the log rotation in `/opt/tpot/etc/logrotate`, but this is really only managing symptoms and not the cause.
According to the log output Suricata seems to permanently detect SSNs in cleartext, this is either a false/positive, since you are running in a sandbox, or Suricata actually sees traffic matching criteria of ETs SSN Cleartext rule. In either case Suricata operates as designed and logs the traffic accordingly and correctly.
Also be aware that Suricata is running on the hosts network stack and thus sees all traffic to and from the host unless you limited the VMs access accordingly.
Closing this since this is not an issue originating from T-Pot itself and there is really noting I can do to improve the situation.

**Comment by PythonFiend** [comment]
Yeah, I figured that much. Gonna work on the settings. Thanks.

**Comment by t3chn0m4g3** [comment]
Sure thing.

**Comment by t3chn0m4g3** [comment]
Hail Mary then :)
