### ISSUE TITLE
I want to recieve foreign ip attacks from outside with honeypot. Local attacks are caught by kibana

### ISSUE THREAD

**Issue by sudeyuksek** [telekom-security/tpotce#1132]
**My honeypot recieve attacks on kibana when I do nmap search. But I never recieve attacks from foreign IPs. I think  this is related to Network Settings.My honeypot is not available from outside**
**In my opinion using DHCP with static ip might solve the problem.Like shown here:https://inforensec.com//malware-analizi-lab-ortaminin-kurulumu-1-malware-analizi.html
What do you think ? How can I handle this situation? How should I change the network/etc/interfaces and virtual machine settings ???**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- 
![image](https://user-images.githubusercontent.com/60464361/178053738-01a3c02c-2b60-4be0-88d5-662cbe2869ce.png)

- What T-Pot version are you currently using? 22.04.0
- 22.04.0
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- It is VirtualBox virtual machine.
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- No, I didn't.
- How long has your installation been running?
- 24 hours
- Did you install upgrades, packages or use the update script?
- no I did not.
- Did you modify any scripts or configs? If yes, please attach the changes.
- I changed the etc/network/interfaces as shown in Readme :
- 
![image](https://user-images.githubusercontent.com/60464361/178054997-e4642bf4-877b-4d88-8e12-fec07867ca70.png)

- Please provide a screenshot of `glances` and `htop`.
- 
![image](https://user-images.githubusercontent.com/60464361/178054284-f098a4d1-27ca-4f2a-925b-fb1f2cc7a068.png)
![image](https://user-images.githubusercontent.com/60464361/178054434-cbda3421-a0be-41b4-81f1-a595f0bed628.png)

- How much free disk space is available (`df -h`)?
- 
![image](https://user-images.githubusercontent.com/60464361/178054181-77775655-ac56-49d9-b2a3-a6489bf2077c.png)

- What is the current container status (`dps.sh`)? 
- 
![image](https://user-images.githubusercontent.com/60464361/178055301-ce409637-2aec-47fa-910f-74f82f91ebf9.png)

-What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/60464361/178054109-d1114faf-85cd-42f4-8ade-c08950994ad8.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- 
![image](https://user-images.githubusercontent.com/60464361/178055607-23af2ab1-7b9f-4ab8-8a55-86615eaf8571.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
According to your information T-Pot is working just fine. The error is probably connections not being forwarded to T-Pot or being filtered by another network element. Closing this since this is not an issue with T-Pot.

**Comment by sudeyuksek** [comment]
> According to your information T-Pot is working just fine. The error is probably connections not being forwarded to T-Pot or being filtered by another network element. Closing this since this is not an issue with T-Pot.

What do you mean? I want it to work in just the way like every other honeypot does. How can I know is it filtered by a network element or not ? Is it related to virtual machine's network settings?
![image](https://user-images.githubusercontent.com/60464361/178114330-bbdbddaa-bb0b-41fa-9421-dd75dcd5344e.png)

**Comment by acheong08** [comment]
Learn about port forwarding and other networking basics before reporting as issue
