### ISSUE TITLE
tpot.service crash/reboot loop

### ISSUE THREAD

**Issue by amishrabbit** [telekom-security/tpotce#1138]
Hey there. I'm running into a problem where the tpot.service is crashing repeatedly upon startup. It fires up the Docker containers but then within a few seconds they all start to die and the service reports FAILURE and then attempts to restart, cycling through the same process over and over again.

This was an installation built from the 22.02 ISO and then upgraded using the update.sh script.

I'm at a loss to understand why this has been happening, and would appreciate any feedback.

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

Basic support info attached (built from bugcollector.sh)
[20220718_tpot_crash.zip](https://github.com/telekom-security/tpotce/files/9135198/20220718_tpot_crash.zip)

**Comment by t3chn0m4g3** [comment]
According to your logs `iptables` fails to setup via `rules.sh`:

```
Jul 18 12:46:38 xxxxx rules.sh[193602]: iptables: Bad rule (does a matching rule exist in that chain?).
```
This is the reason for T-Pot service to stop working.
Stop T-Pot and manually run `/opt/tpot/bin/rules.sh` to check for errors.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
