### ISSUE TITLE
Alert by email

### ISSUE THREAD

**Issue by Ludovick69** [telekom-security/tpotce#1143]
Hello

Is it possible to have a module to send email alerts on specific (or all) events?

This is not suitable for a public or cloud environment but it would be very useful in a DMZ environment where no events should be triggered.

I found some information about reconfiguring logstash.conf but I couldn't find any simple or step by step documentation for sending emails.

Thanks

**Comment by t3chn0m4g3** [comment]
T-Pot does not provide this functionality, however you can adjust the Logstash configuration to your needs and send alerts using the [eMail Output Plugin](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-email.html).
