### ISSUE TITLE
filebeat instead of logstash

### ISSUE THREAD

**Issue by orcema** [telekom-security/tpotce#1148]
Logstash is an ressource intensive process and replacing it by filebeat would spare a considerable amount of ressources.
If i run docker-stats i can see the logstash consumes nearly 1,5GB of RAM and de cpu usage is oscillating between 2,5% and 5%.<img width="914" alt="image" src="https://user-images.githubusercontent.com/12600222/183599203-2ad66193-bca5-4f54-b18c-e4af2d78402d.png">
Compared to ressources usage on existing filebeat processes of mine I can spot a huge difference like only 80MB of RAM usage and cpu at about 1% or lower
<img width="955" alt="image" src="https://user-images.githubusercontent.com/12600222/183600151-7a9f646f-78c9-4570-9c8f-6e1f5ba0aa59.png">

**Describe the solution you'd like**
Replacing Logstash by Filebeat would save a lot of RAM ressources

**Comment by t3chn0m4g3** [comment]
Replacing Logstash with Filebeat is not possible, since Filebeat does not allow for the necessary modifications on the logs, it is simply a shipper.

**Comment by orcema** [comment]
What kind of log modification do you have in mind that could not be achieved using the "Ingest Pipelines" of Elasticsearch? If there aren't any , "filebeat" + "Ingest Pipelines" would be a lightweight Logstash ;-)
