### ISSUE TITLE
Uploading site not working

### ISSUE THREAD

**Issue by kashmax** [telekom-security/tpotce#1151]
Hi,

Having issues on uploading custom site. So far I did this.

/opt/tpot/docker/tanner/snare/Dockerfile and set --page-dir 10

But every restart it changes to other directories. Also custom pages like test.html will not work because the pages are in meta.json file with hash, tried to put hash for test.html (using md5sum) in the file but it didn't work either.

Thanks

Tpot Version: 22.04

_Originally posted by @kashmax in https://github.com/telekom-security/tpotce/discussions/1150_

**Comment by t3chn0m4g3** [comment]
Not an issue and now duplicate. Converted to discussion #1150.

**Comment by kashmax** [comment]
> Not an issue and now duplicate. Converted to discussion #1150.

Thank your for your reply....

Same issue has been opened while ago. Kindly see.
https://github.com/telekom-security/tpotce/issues/642

Thanks

**Comment by t3chn0m4g3** [comment]
Still not an issue with T-Pot.

**Comment by kashmax** [comment]
> Still not an issue with T-Pot.

I didn't get it? Snare was integrated in tpot.

**Comment by t3chn0m4g3** [comment]
It is not an issue with T-Pot but with the modification you want to achieve. Please get familiar how the Snare / Tanner docker images are setup and check with the documentation of Snare / Tanner to achieve your goal.

T-Pot works as it is supposed to.
