### ISSUE TITLE
Kibana, Map and Spiderfoot not starting/working

### ISSUE THREAD

**Issue by jennyjanetech** [telekom-security/tpotce#1162]
🗨️ Please post your questions in [Discussions](https://github.com/telekom-security/tpotce/discussions) and keep the issues for **issues**. Thank you 😁.<br>

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
-# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
# uname -a
Linux governingthaw 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux

- What T-Pot version are you currently using?
- latest version 22.04.0
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Cloud (Digital Ocean)
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- No
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- No
- Did you modify any scripts or configs? If yes, please attach the changes.
- No
- Please provide a screenshot of `glances` and `htop`.
- 
![image](https://user-images.githubusercontent.com/111695715/185801260-ac42b410-29f5-459a-bc69-f9cb9cbb23ec.png)

![image](https://user-images.githubusercontent.com/111695715/185801301-bb61d521-41e7-4c8d-a777-37bfdaa672eb.png)

- How much free disk space is available (`df -h`)?
- # df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            480M     0  480M   0% /dev
tmpfs            99M  6.0M   93M   7% /run
/dev/vda1        25G  6.3G   18G  26% /
tmpfs           493M     0  493M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           493M     0  493M   0% /sys/fs/cgroup
/dev/vda15      105M  4.4M  100M   5% /boot/efi
tmpfs           493M  5.1M  488M   2% /opt/omd/sites/monitoring/tmp
tmpfs            99M     0   99M   0% /run/user/0
tmpfs            99M     0   99M   0% /run/user/1000
- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/111695715/185798114-ab23e0ab-7522-4d27-b36e-45db6fff58f3.png)         
- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/111695715/185798182-a5078203-1cc1-4435-b3a7-ffffa1e4577d.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
[root@governingthaw:/opt/tpot/etc]# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          51471      10995/docker-proxy  
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      0          51387      10971/docker-proxy  
tcp        0      0 0.0.0.0:1723            0.0.0.0:*               LISTEN      0          49639      10604/docker-proxy  
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      0          49618      10592/docker-proxy  
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      0          49705      10628/docker-proxy  
tcp        0      0 0.0.0.0:7007            0.0.0.0:*               LISTEN      2000       432784     99343/honeytrap     
tcp        0      0 0.0.0.0:7008            0.0.0.0:*               LISTEN      2000       433629     99579/honeytrap     
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      0          50705      10759/docker-proxy  
tcp        0      0 0.0.0.0:1025            0.0.0.0:*               LISTEN      0          50445      10555/docker-proxy  
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      0          50670      10748/docker-proxy  
tcp        0      0 0.0.0.0:2404            0.0.0.0:*               LISTEN      0          429398     98633/docker-proxy  
tcp        0      0 0.0.0.0:135             0.0.0.0:*               LISTEN      0          49738      10640/docker-proxy  
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          12825      781/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:11112           0.0.0.0:*               LISTEN      0          50840      10805/docker-proxy  
tcp        0      0 0.0.0.0:64297           0.0.0.0:*               LISTEN      0          432880     99276/nginx: master 
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      0          50478      10567/docker-proxy  
tcp        0      0 0.0.0.0:42              0.0.0.0:*               LISTEN      0          49846      10676/docker-proxy  
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      0          49585      10580/docker-proxy  
tcp        0      0 127.0.0.1:64298         0.0.0.0:*               LISTEN      0          50322      10507/docker-proxy  
tcp        0      0 127.0.0.1:64299         0.0.0.0:*               LISTEN      0          429341     98610/docker-proxy  
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      0          50000      10864/docker-proxy  
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      0          50579      10712/docker-proxy  
tcp        0      0 127.0.0.1:33005         0.0.0.0:*               LISTEN      0          13010      779/containerd      
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      0          50805      10793/docker-proxy  
tcp        0      0 0.0.0.0:2575            0.0.0.0:*               LISTEN      0          432276     98982/docker-proxy  
tcp        0      0 127.0.0.1:64303         0.0.0.0:*               LISTEN      0          430514     98661/docker-proxy  
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      0          50775      10781/docker-proxy  
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          436771     100178/docker-proxy 
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      0          432703     99255/docker-proxy  
tcp        0      0 0.0.0.0:10001           0.0.0.0:*               LISTEN      0          51043      11044/docker-proxy  
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      0          50740      10770/docker-proxy  
tcp        0      0 0.0.0.0:81              0.0.0.0:*               LISTEN      0          49771      10652/docker-proxy  
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      0          49970      10852/docker-proxy  
tcp        0      0 0.0.0.0:20              0.0.0.0:*               LISTEN      0          50553      10701/docker-proxy  
tcp        0      0 0.0.0.0:50100           0.0.0.0:*               LISTEN      0          50412      10542/docker-proxy  
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      0          50530      10688/docker-proxy  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          50379      10530/docker-proxy  
tcp        0      0 0.0.0.0:631             0.0.0.0:*               LISTEN      0          51506      11007/docker-proxy  
tcp        0      0 0.0.0.0:23              0.0.0.0:*               LISTEN      0          50350      10518/docker-proxy  
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      0          50640      10736/docker-proxy  
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      0          50610      10724/docker-proxy  
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      0          430973     98842/docker-proxy  
tcp        0      0 0.0.0.0:1433            0.0.0.0:*               LISTEN      0          49672      10616/docker-proxy  
tcp6       0      0 :::64294                :::*                    LISTEN      0          12637      1/init              
tcp6       0      0 :::64295                :::*                    LISTEN      0          12827      781/sshd: /usr/sbin 
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           0          50050      10876/docker-proxy  
udp        0      0 0.0.0.0:5000            0.0.0.0:*                           0          51437      10983/docker-proxy  
udp        0      0 0.0.0.0:5060            0.0.0.0:*                           0          49936      10840/docker-proxy  
udp        0      0 0.0.0.0:19              0.0.0.0:*                           0          51205      10911/docker-proxy  
udp        0      0 0.0.0.0:53              0.0.0.0:*                           0          50132      10900/docker-proxy  
udp        0      0 0.0.0.0:69              0.0.0.0:*                           0          49816      10664/docker-proxy  
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          50091      10888/docker-proxy  
udp        0      0 0.0.0.0:161             0.0.0.0:*                           0          430526     98669/docker-proxy  
udp        0      0 0.0.0.0:623             0.0.0.0:*                           0          51009      11032/docker-proxy  

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
**[root@governingthaw:~]# docker logs kibana
Error: No such container: kibana**

[root@governingthaw:~]# docker logs elasticsearch
- no result
[root@governingthaw:~]# docker logs elasticvue
Error: No such container: elasticvue

When i access the link ElasticVue in the main page  it redirects me to - https://IP reducted:64297/elasticvue/setup
1. Configure

You have to setup CORS to use elasticvue. Add the following lines to your elasticsearch.yml:

# allow CORS requests from https://IP reducted:64297
http.cors.enabled: true
http.cors.allow-origin: "https://IP Reducted:64297"

i edited /opt/tpot/docker/elk/elasticsearch/dist/elasticsearch.yml and restarted the server but same setup page is showing.

installed TPOT via git clone > cd tpotce >  ./install.sh --type=user - no error noticed during the installation. I never run ./update.sh -y yet... 

Another Observation - Attack Map and Spider Foot works ON and OFF meaning if i visit the url now i can see the attack map but no data is being shown. for Spider foot i can see the page but when i click 1 of the links or 2 links within spiderfoot it stop working - Unable to connect error in the browser then it will work again after some time

![image](https://user-images.githubusercontent.com/111695715/185801150-0a450ceb-50bf-4ddb-aed2-9d09f45553b6.png)

![image](https://user-images.githubusercontent.com/111695715/185801211-ccc58565-25ed-46a3-9e9a-1c98fbcf395a.png)

**Comment by t3chn0m4g3** [comment]
Please follow the documentation for the T-Pot requirements.

**Comment by jennyjanetech** [comment]
Okay how come kibana container is not installed? even if i have enough disk space... Tpot did not consume even half of my disk space
