### ISSUE TITLE
tpot 22.0 installation issue on debian 11

### ISSUE THREAD

**Issue by honor6x5** [telekom-security/tpotce#1175]
🗨️ Please post your questions in [Discussions](https://github.com/telekom-security/tpotce/discussions) and keep the issues for **issues**. Thank you 😁.<br>

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**
tpot service is showing loaded with error as attached in the below questionaire all service of container showing down dps.sh logs its a new installation on debian 11 amd.iso installed on esxi host vmware (vm host-debian 11)
<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?Debian 11 bulls eye
- 
![image](https://user-images.githubusercontent.com/30012576/189862840-437a9d2f-9a5f-43eb-8ae5-8bf406ad90fa.png)
![image](https://user-images.githubusercontent.com/30012576/189862911-3800ccdd-6206-49c3-b1e0-cc8a545945d1.png)
![image](https://user-images.githubusercontent.com/30012576/189863333-1d000556-d1e0-4d1c-849b-170ecd832975.png)

- What T-Pot version are you currently using?22.04
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.No
- How long has your installation been running?since 2 days trying to troubleshoot
- Did you install upgrades, packages or use the update script?yes i did use upgrade and update script with no luck
- Did you modify any scripts or configs? If yes, please attach the changes.No-new installation
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/30012576/189861835-2f04e117-aecf-4914-9909-a1fdcbf8ae78.png)

- How much free disk space is available (`df -h`)?260G
- What is the current container status (`dps.sh`)?all DOWN in RED
- What is the status of the T-Pot service (`systemctl status tpot`)?Loaded with error attached screenshot 
![image](https://user-images.githubusercontent.com/30012576/189862390-fdc6db88-3feb-4cca-b80e-263d09539141.png)

![image](https://user-images.githubusercontent.com/30012576/189862093-55b54287-3484-413b-a42b-929bc591fb95.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/30012576/189862648-9cc83ace-b922-4062-9dd2-fb17fb4af1d5.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
All container but socker service is showing up however dps.sh shows all container down

**Comment by t3chn0m4g3** [comment]
Based on the info it seems that [ipinfo](https://github.com/telekom-security/tpotce/blob/1122d3728ee9b1dd921f4cb58e69ea76de0441d3/bin/updateip.sh#L15) is running in an error.

**Comment by honor6x5** [comment]
Thanks man for your quick reply it worked actually, but now i can see containers  showing up with docker ps -a and also telnet to server, but there is kind of different issuei i check to see the status of tpot i get below error 
![image](https://user-images.githubusercontent.com/30012576/189881479-1273b901-0d58-43df-a074-f188b5faceb9.png)
![image](https://user-images.githubusercontent.com/30012576/189881577-37e13695-5a85-434e-aa3e-c37ff39f2d3a.png)
then its kind of loop of creating contrainer again and again and then error when i try to do telnet locally on open container like 80 telnet works but after afew seconds it shows connection refused then again after a while it comes up.
i m not sure if this is expected issue or i messed something, any help would be appreciated.
systemctl status tpot is never stable and always shows creating suricata, diaonea and other contrainers everytime i hit systemctl status tpot then the error of docker as mentioned in my screenshot, also chmod and chown permission issue keeps coming after a while and the tpot services fails and starts again immediately.Any help to fix this is appreciated!
![image](https://user-images.githubusercontent.com/30012576/189882592-9c3444a1-7f92-463f-8bd5-45c69b2b14f4.png)

**Comment by honor6x5** [comment]
I did a quick look after restarting tpot service on the dps.sh script and also found the services are fluctuating up and down and some services like kibana and logstash not getting UP
![image](https://user-images.githubusercontent.com/30012576/189888137-b78e7905-63e9-4341-8a81-86cf90b0ff9b.png)
![image](https://user-images.githubusercontent.com/30012576/189888727-b0aea37e-ae32-41cf-85fb-91309c5290c1.png)
![image](https://user-images.githubusercontent.com/30012576/189888785-f14ab17c-12ad-4c24-aed7-8f2a693560ff.png)

**Comment by t3chn0m4g3** [comment]
This is caused by services on your host are in conflict with the ones from [T-Pot](https://github.com/telekom-security/tpotce/blob/master/etc/compose/standard.yml), i.e. port 631 (based on the screenshots from your earlier post). Please follow the [Readme](https://github.com/telekom-security/tpotce#download-debian-netinstall-image)  for the recommended Debian image or adjust your config accordingly.
