### ISSUE TITLE
T-Pot 22.04.0 need update (no kernel modules found)

### ISSUE THREAD

**Issue by shotoz** [telekom-security/tpotce#1176]
Hello ! 

It seems that the T-Pot 22.0.4.0 iso (tpot_amd64.iso) relased on apr 12 2022 need to be updated. I've tried multiple times on different hardware and VM but I got always the same error:

The error is " No kernel modules found" while trying to install. It's  Same error as bug #733 

I think the ISO need to be updated with new kernel modules 

thanks!

**Comment by t3chn0m4g3** [comment]
Thanks. Will look into it. In the mean time you can run the `makeiso.sh` and build the iso yourself.

**Comment by daneb255** [comment]
Withe a fresh builded iso the install process works fine.

**Comment by io43** [comment]
it happen again

**Comment by t3chn0m4g3** [comment]
@io43 I updated the current release with the latest images.
