### ISSUE TITLE
No kernel modules in Proxmox

### ISSUE THREAD

**Issue by jlazkano** [telekom-security/tpotce#1186]
Hi,

Trying to run T-Pot 22.04.0 in Proxmox, I can not install. The error say "No kernel modules found".

Is Proxmox supported as virtualization enviroment?

Kind regards.

**Comment by jlazkano** [comment]
Hi,

I just install a netinstall version and the PostInstall, and it works.

But it will be great to get the T-pot image working.

Ragards.

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this and AFAIK Proxmox does not use any different kernel modules than the netiso T-Pot is based on. What architecture are you using? Have you built your own ISO as suggested?

**Comment by t3chn0m4g3** [comment]
If nobody else experiences any issues as outlined in #1176 I am closing this.
