### ISSUE TITLE
t-pot sends a RST to the Client on some URLs

### ISSUE THREAD

**Issue by jk20004** [telekom-security/tpotce#1189]
We have a load Balancer in front and we use the "new" X-Forwarded-For Option for the Traffic.
When we count the send requests on the Load Balancer and compare them with the result on the tpot there are requests missing.

The Problem is that the tpot sends a RST back.

After further investigation we found that the URL is the reason for the reset from the tpot.

Example:

```
> GET /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession HTTP/1.1
> Host: X.X.X.X
> User-Agent: curl/7.58.0
> Accept: */*
>
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
* stopped the pause stream!
* Closing connection 0
* TLSv1.3 (OUT), TLS Unknown, Unknown (21):
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

What Steps on the tpot will help to get more details of the Reset?
In a _tcpdump -nnvi any port 80 -s0  i cannot find the request

----

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
 No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
Linux rulingprotection 5.10.0-16-cloud-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? Azure
- How long has your installation been running? 6 Months
- Did you install upgrades, packages or use the update script? Yes, Today last time
- Did you modify any scripts or configs? If yes, please attach the changes. No
- How much free disk space is available (`df -h`)?
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G     0  7.9G   0% /dev
tmpfs           1.6G  1.5M  1.6G   1% /run
/dev/sda1       126G   26G   95G  22% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb1        32G   70M   32G   1% /mnt
/dev/sda15      124M  5.9M  118M   5% /boot/efi
tmpfs           1.6G     0  1.6G   0% /run/user/1000

- What is the current container status (`dps.sh`)?
 ========| System |======== ]
     DATE:  Tue Oct 18 11:30:08 CEST 2022
   UPTIME:   11:30:08 up 17:36,  2 users,  load average: 0.13, 0.24, 0.27
    T-POT:  ACTIVE
BLACKHOLE:  DISABLED

NAME                  STATUS                       PORTS
elasticsearch   Up 3 hours (healthy)   127.0.0.1:64298->9200/tcp
fatt            Up 3 hours
honeypots       Up 3 hours             0.0.0.0:21-23->21-23/tcp, 0.0.0.0:25->25/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:53->53/udp, 0.0.0.0:110->110/tcp, 0.0.0.0:123->123/udp, 0.0.0.0:143->143/tcp, 0.0.0.0:389->389/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:445->445/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:1433->1433/tcp, 0.0.0.0:1521->1521/tcp, 0.0.0.0:3306->3306/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp, 0.0.0.0:6379->6379/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:9200->9200/tcp, 0.0.0.0:11211->11211/tcp, 0.0.0.0:161->161/udp
honeytrap       Up 3 hours
kibana          Up 3 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash        Up 3 hours (healthy)
map_data        Up 3 hours
map_redis       Up 3 hours
map_web         Up 3 hours             127.0.0.1:64299->64299/tcp
nginx           Up 3 hours
p0f             Up 3 hours
spiderfoot      Up 3 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata        Up 3 hours

- What is the status of the T-Pot service (`systemctl status tpot`)?
tpot.service - tpot
     Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-10-18 08:40:36 CEST; 2h 50min ago

**Comment by t3chn0m4g3** [comment]
Based on the provided info the response seems to be provided by the [qeeqbox/honeypots'](https://github.com/qeeqbox/honeypots) web honeypot (assuming the forward by the load balancer is also made on `tcp/80`. I recommend to open an upstream issue. There is nothing I can do here.
