### ISSUE TITLE
TPot Hive tunnel test failure

### ISSUE THREAD

**Issue by lullu57** [telekom-security/tpotce#1190]
Hi, I am running the Distributed version of TPot hosted on 2 bridged networking VMs. They are fresh tpot ISO downloads. The required ports for all the honey pots have been opened and directed to the sensor IP as required. When trying to run the `deploy.sh` script, the final connectivity test is failing: 

> T-Pot Hive tunnel test FAILED!
> Tunneled port tcp/64305 unreachable on T-Pot Hive.

Running netstat -tulpn on the Hive shows that it is listening over port 64305 on the normal local address (127.0.0.1). Could you guide me as to how to troubleshoot this issue as I have researched for similar issues but was not able to find any?

**Comment by t3chn0m4g3** [comment]
Please discuss in #1153, thx.
