### ISSUE TITLE
Cannot Start tpot after update

### ISSUE THREAD

**Issue by muffingenie** [telekom-security/tpotce#1191]
Hi all,

Hope you are well :). I have an issue with the tpot I have been using for the last 10 months. After updating it, tpot is not starting anymore. Any help would be very appreciated :).

**⚠️ Basic support information (commands are expected to run as root)
What version of the OS are you currently using lsb_release -a and uname -a?**

```
-# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

uname -a
```
Linux yellowram 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Li
What T-Pot version are you currently using?
22.04.0
```

**What edition (Standard, Nextgen, etc.) of T-Pot are you running?**

Standard

**What architecture are you running on (i.e. hardware, cloud, VM, etc.)?**

Cloud (ovh)

**Did you have any problems during the install? If yes, please attach /install.log /install.err.**

Yes, here are the logs.

[Install_log.txt](https://github.com/telekom-security/tpotce/files/9844551/Install_log.txt)

[install_err.txt](https://github.com/telekom-security/tpotce/files/9844552/install_err.txt)

**How long has your installation been running?**

10month

**Did you install upgrades, packages or use the update script?**

Yes

**Did you modify any scripts or configs? If yes, please attach the changes.**

No

**Please provide a screenshot of glances and htop.**

<img width="454" alt="image" src="https://user-images.githubusercontent.com/60329928/197343927-5bbdfa4b-00d5-48f0-880e-ef0eb57f69e3.png">

(glances is not working)

**How much free disk space is available (df -h)?**

```
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  1.3M  3.2G   1% /run
/dev/md1        1.8T  224G  1.5T  13% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
```

**What is the current container status (dps.sh)?**

 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/60329928/197343940-c6cac46c-f07e-438e-8f49-716b960c1404.png">

**What is the status of the T-Pot service (systemctl status tpot)?**

<img width="454" alt="image" src="https://user-images.githubusercontent.com/60329928/197343957-311726bd-77d0-42ec-9a2d-bb8550839e67.png">

**What ports are being occupied?** 
 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/60329928/197343975-b5226ae1-a733-4def-8edb-82a4da073891.png">

**Comment by t3chn0m4g3** [comment]
Based on the information there is nothing out of the ordinary, except of course that the service breaks at some point.

Updating T-Pot unfortunately comes with risks explained [here](https://github.com/telekom-security/tpotce#updates). You can follow the [Logging section](https://github.com/telekom-security/tpotce#logging) and check the logs against issues and discussions or post the findings. Usually it breaks down to an unavailable dependency and is easily fixable.

**Comment by muffingenie** [comment]
Hello @t3chn0m4g3 Thanks for this quick reply :). Is there a way to reinstall tpot in such a case? Thanks again for you help :)

**Comment by t3chn0m4g3** [comment]
Yes, check the Readme please and follow the installation steps.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
