### ISSUE TITLE
22.04.0 doesn't boot on AMD64

### ISSUE THREAD

**Issue by lyakh** [telekom-security/tpotce#1192]
Flashed 22.04.0 to a USB stick, booted to it on 2 Intel x86-64 systems and both leave me with only a blinking cursor. Tried 22.04.0 that one boots.

**Comment by t3chn0m4g3** [comment]
Check the Readme please, this calls for Post Install method.

**Comment by lyakh** [comment]
> Check the Readme please, this calls for Post Install method.

@t3chn0m4g3 thanks, did that, installed Debian on the machine, then tried installing t-pot - it proceeded with the installation although a few packages were missing (docker.io, python-pip3, dialog, and a few more). It completed the installation but without those packages the installation is now broken. Running `install.sh` for a second time is unsupported. Is there a way to repair this installation or do I have to re-install Debian completely?

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this. You can check the logs in / and check what went wrong. But yes at this point a reinstall is necessary. Post the logs please so we can improve things in the future.

**Comment by lyakh** [comment]
@t3chn0m4g3 attaching the logs, the most sensitive information I see in them are IP addresses, but those are generic enough, so I think it should be safe to post, but maybe we should remove them once you've copied them - please feel free to do that.
[install.err.txt](https://github.com/telekom-security/tpotce/files/9847430/install.err.txt)
[install.log](https://github.com/telekom-security/tpotce/files/9847431/install.log)

**Comment by t3chn0m4g3** [comment]
According to the logs you are trying to install on Ubuntu which is not supported, only Debian is.

**Comment by lyakh** [comment]
> According to the logs you are trying to install on Ubuntu which is not supported, only Debian is.

@t3chn0m4g3 No, sorry, it's under Debian. The machine has both Debian and Ubuntu installed, and I'm installing everything under Debian. Can I delete logs here now?

**Comment by t3chn0m4g3** [comment]
I deleted the logs. Also I noticed missing dependencies, there is something strange going on.

**Comment by lyakh** [comment]
> I deleted the logs. Also I noticed missing dependencies, there is something strange going on.

@t3chn0m4g3 right, as I said - required packages were missing but the installation went through and finished in an unusable state

**Comment by t3chn0m4g3** [comment]
Based on the info there is nothing I can do. Works like charm here when installing as ISO and Post Install.

Based on the logs there is nothing more I can do.
