### ISSUE TITLE
citrixhoneypot log file paths are not consistent

### ISSUE THREAD

**Issue by Shoma-progr-0210** [telekom-security/tpotce#1204]
citrixhoneypot log file is mounted on `/data/citrixhoneypot/logs`.
But other honeypots and tools log file is mounted on `/data/xxx/log`.

I would be grateful if you would do as below.
`- /data/citrixhoneypot/log:/opt/citrixhoneypot/logs`

[citrixhoneypot docker-compose.yml line:22](https://github.com/telekom-security/tpotce/blob/master/docker/citrixhoneypot/docker-compose.yml#L22)

**Comment by t3chn0m4g3** [comment]
Thanks for pointing this out, however it is not a fix I can easily push without breaking things (logstash ingestion i.e.) for everyone else. While the docker containers will be updated automatically the folder in question is host based which will only be updated when running `update.sh`. As such this change will not happen before the next major release of T-Pot and it needs to be discussed if CitrixHoneypot will still be relevant at that point.

**Comment by Shoma-progr-0210** [comment]
Now I understand. 
I was using "SENSOR" and was not able to take Logstash into account.

Hopefully this will be fixed in the next release.

**Comment by t3chn0m4g3** [comment]
Fixed in T-Pot 24.x.
