### ISSUE TITLE
The field "username.keyword" associated with this object no longer exists in the data view. Please use another field.

### ISSUE THREAD

**Issue by ihtisamulhasan** [telekom-security/tpotce#1208]
i had installed tpot with no error, and everything going well, my sensor also catch some attack but at some panel in elastic
specifically username tagcloud and password tag cloud panels seems not synchronize with any honeypot sensor, with error text " The field "username.keyword" associated with this object no longer exists in the data view. Please use another field." 
can anyone help or explain it ? thanks 

![capture 2](https://user-images.githubusercontent.com/50767729/202840668-055d35eb-229e-466a-9fd4-cf39db22a7da.PNG)

![Capture3](https://user-images.githubusercontent.com/50767729/202840851-3e25c9ff-78b7-4002-8865-b2ff6e99bc9b.PNG)

**Comment by MACGadams** [comment]
The same has happenned to me, but in my case I can't see any data in Kibana even though the alerts are stored in the system. :/

![imagen](https://user-images.githubusercontent.com/84122722/203577432-0ab29047-c843-452d-860d-8fa7a1b9fa50.png)

I am still investigating, but I have no clue.

**Comment by t3chn0m4g3** [comment]
@ihtisamulhasan This is normal and expected, only once events have been submitted the fields will be available.
@MACGadams Metrics are not gathered, these dashboards come with Kibana, even deleting them will not help since they will always resurface with a version change.

Duplicate #885

**Comment by fsantanderb** [comment]
The problem persists, no information is displayed in "username" and "password" tagcloud.
Even after generating test accesses
