### ISSUE TITLE
Having issues setting Cowrie dashboard. It says these fields no longer exists. Is there a way to fix this?

### ISSUE THREAD

**Issue by ptester87** [telekom-security/tpotce#1224]
Having issues setting Cowrie dashboard. It says these fields no longer exists. Is there a way to fix this?
![image](https://user-images.githubusercontent.com/45849353/206647396-ac68ac82-2de9-4c5e-a1be-90d9d69cc494.png)

_Originally posted by @ptester87 in https://github.com/telekom-security/tpotce/discussions/1221_

**Comment by t3chn0m4g3** [comment]
Please check #1208
