### ISSUE TITLE
Cockpit 2FA Enablment

### ISSUE THREAD

**Issue by littlejob** [telekom-security/tpotce#1257]
New build, created today following OS recommendations and sizing chart. 
Logged into Cockpit, used web based terminal to run 2fa.sh
Received a banner/warning message to download MFA app of choice, selected "Y" to continue (i think). 
Web page then displays an error that the session was disconnected. 
Upon logging in I am asked for token.. however i was never presented to register MFA app in console.. 

Bug? Or should this be done via SSH? (maybe note that in notes?)

**Comment by t3chn0m4g3** [comment]
You have to run the script in a SSH session for the `tsec`-user or the user you want to grant access.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
