### ISSUE TITLE
Copying Honeypot Log files over SSH / SCP

### ISSUE THREAD

**Issue by ApplenBlackberryPi** [telekom-security/tpotce#1268]
🗨️ Please post your questions in [Discussions](https://github.com/telekom-security/tpotce/discussions) and keep the issues for **issues**. Thank you 😁.<br>

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
      Distributor ID: Debian
      Description:    Debian GNU/Linux 11 (bullseye)
      Release:        11
      Codename:       bullseye

      Linux differentfisherman 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

- What T-Pot version are you currently using?
  20.06

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
  Standard
 
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
   VM

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
   No

- How long has your installation been running?
  60 days

- Did you install upgrades, packages or use the update script?
  Yes

- Did you modify any scripts or configs? If yes, please attach the changes.
  No

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/42312486/223169384-a9211146-07b4-4fb2-baad-342b86772cdf.png)

![image](https://user-images.githubusercontent.com/42312486/223169738-1a8f9611-c9fa-4b9c-9c7c-42ee29720b32.png)

- How much free disk space is available (`df -h`)?
   ![image](https://user-images.githubusercontent.com/42312486/223169859-aea05ccc-5540-4304-967a-f280476e3a87.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/42312486/223175210-11dd7821-1efd-4318-9d9c-a529befea8b6.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/42312486/223170376-c99a79f2-44d3-4c1c-9cc5-b6024b1b82a0.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/42312486/223170655-3d4f9745-9d98-40ba-bd45-08e6f27e3888.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

----------------------------------------------------------------------------------------------------------
I am able to successfully access the honeypot from a Windows machine within my LAN via SSH on port 64295 under the tsec account, navigate to the /data folder.  But when I try to run the 'scp' command, I am unable to copy files from the data folder and subfolders to my local Windows machine via SSH.  Can anybody advise if there are restrictions preventing the scp over SSH?  Is there an alternative method of doing this? 
 
FYI : One of the commands that I used after I have SSH'ed in is below : 

scp tsec@[private IP address of honeypot]:/data/cowrie/downloads.tgz [Windows Username]@[private IP address of Windows machine]:/C:/Users/[Username]/Documents/downloads.tgz

I am asked for my password, I fill in, there is no error message and command appears to complete.  However, when I view the directory on the Windows machine, the file has not saved.

**Comment by t3chn0m4g3** [comment]
Please check if `tsec` was correctly [added](https://github.com/telekom-security/tpotce/blob/668a4d91a7c2d8d5cd50d9efd0d025057419d58b/iso/installer/install.sh#L852) to the `tpot` group (`cat /etc/group`) => `tpot:x:2000:tsec`.

If yes, everything will fork fine...
![image](https://user-images.githubusercontent.com/4318452/223188943-d774cd26-6442-4534-82e2-0bc8ba7a3548.png)

Otherwise you should move to T-Pot 22.04.

**Comment by ApplenBlackberryPi** [comment]
![image](https://user-images.githubusercontent.com/42312486/223415878-0ad11ae9-60ef-49b0-8e7d-fd20981b3ca9.png)


![image](https://user-images.githubusercontent.com/42312486/223416520-c4ee761f-b13a-43ec-aaa2-69dcdf05f3fe.png)

It seems that the permissions are correct for the tsec account, but the tsec password is not being accepted when trying to use scp.  Could you advise?

**Comment by ApplenBlackberryPi** [comment]
P.S. It is the default password for tsec, which has not been changed

**Comment by t3chn0m4g3** [comment]
Please follow the Readme regarding the SSH port to connect to, otherwise you just connect to the Cowrie Honeypot.

**Comment by ApplenBlackberryPi** [comment]
I can manage to SSH into T-Pot on port 64295 under the tsec account with the credentials.  Then I can navigate to the data/cowrie folder.  (I have never used port 22 to do that and used "fail2ban-client unban --all" to make sure no IP address or account are blocked).   However, the issue comes when trying to copy across files with scp.

**Comment by t3chn0m4g3** [comment]
Scp is based on SSH, so you need to connect to tcp/64295 as well.

**Comment by ApplenBlackberryPi** [comment]
I have tried changing the command to incorporate that as well, but still met with the same issue of password not accepted.  The command I used was : 
scp **-P 64295** tsec@192.168.1.24:/data/cowrie/downloads.tgz [user]@192.168.1.23:C:\Users\[user]\Documents\downloads.tgz

**Comment by ApplenBlackberryPi** [comment]
I have run the command from a Windows machine using Putty, then the CLI for scp commands.  I will try WinSCP too and see if I have any better luck with that.  Thanks.

**Comment by ApplenBlackberryPi** [comment]
WinSCP seems to solve the issue.  So obviously, it must be a syntax issue for me somehow.  But thank you.
