### ISSUE TITLE
apt-fast not found

### ISSUE THREAD

**Issue by youwi** [telekom-security/tpotce#1276]
[ 22.04.0 tpot_amd64.iso](https://github.com/telekom-security/tpotce/releases/download/22.04.0/tpot_amd64.iso)

download ISO，then install, that make error.

apt-fast not found. 

i found  "apt-fast" not in $PATH. This should be caused by the new version of debian release.

"22.04.0-tpot_amd64.iso  "  shoud lock debain version.

**Comment by t3chn0m4g3** [comment]
Sorry, but I cannot reproduce this. Anyone else?

**Comment by t3chn0m4g3** [comment]
Seems to be resolved / not reproducable.
