### ISSUE TITLE
T-Pot Attack Map does not go

### ISSUE THREAD

**Issue by aimatgr** [telekom-security/tpotce#1277]
Since a few hours ago the tpot map stop displaying any information, but when i go to the tpot dashboard, it is all okey and it is receiving attacks also.

**Comment by cpyix** [comment]
Same for me, after restarting containers map_web, map_redis and map_data it worked again. Seems that the connection to redis somewhat got lost.

**Comment by lcia-projects** [comment]
same issue, just restart it and everything comes up fine

**Comment by LuXc-NL** [comment]
After clean install I encountered the following issue:

![image](https://user-images.githubusercontent.com/52918681/229284506-ee46a513-eae0-4454-838a-f7f73686079b.png)

T-Pot Honeypot Stats in the top left are showing but nothing else.

**Comment by rocbr** [comment]
Does anyone know how to resolve or mitigate this issue?

**Comment by t3chn0m4g3** [comment]
Without further details, i.e. websocket logs, etc. there is no way to debug this, since I cannot reproduce this for our use-case.

**Comment by Adi-18** [comment]
Same problem. I also get "unable to resolve host majorpink: Name or service not known" while docker restart.
Its an iso installation on ProxMox.

**Comment by Marius-Sheppard** [comment]
I have the same issue there is no error in the docker output or the web console. The header is updated with real data:
`T-Pot Honeypot StatsLast 1m:22 Last 1h:191Last 24h:191` but the page doesn't display anything.

**Comment by bgao-pangeo** [comment]
Hi, we just installed the latest T-POT, we give it a public IP but put the T-POT in a DMZ behind Cisco ASA firewall. Everything works fine however the Attack Map seems to have an issue. it does not show the attack on map or the list, only the counter on the top changes. Every other T-POT function seems to be working fine just fine. 

Here is some the standard information that I have gathered:

dps.sh output:

     DATE:  Tue 26 Sep 2023 05:24:08 PM UTC
   UPTIME:   17:24:08 up 14:30,  1 user,  load average: 0.48, 0.54, 0.54
    T-POT:  ACTIVE       
BLACKHOLE:  DISABLED

NAME                  STATUS                       PORTS
adbhoney              Up 14 hours (healthy)   0.0.0.0:5555->5555/tcp
ciscoasa              Up 14 hours             0.0.0.0:5000->5000/udp, 0.0.0.0:8443->8443/tcp
citrixhoneypot        Up 14 hours             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 14 hours (healthy)   0.0.0.0:10001->10001/tcp
conpot_iec104         Up 14 hours (healthy)   0.0.0.0:161->161/udp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 14 hours (healthy)   0.0.0.0:623->623/udp
conpot_kamstrup_382   Up 14 hours (healthy)   0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 14 hours             0.0.0.0:22-23->22-23/tcp
ddospot               Up 14 hours             0.0.0.0:19->19/udp, 0.0.0.0:53->53/udp, 0.0.0.0:123->123/udp, 0.0.0.0:1900->1900/udp
dicompot              Up 14 hours             0.0.0.0:11112->11112/tcp
dionaea               Up 14 hours (healthy)   0.0.0.0:20-21->20-21/tcp, 0.0.0.0:42->42/tcp, 0.0.0.0:81->81/tcp, 0.0.0.0:135->135/tcp, 0.0.0.0:445->445/tcp, 0.0.0.0:1433->1433/tcp, 0.0.0.0:1723->1723/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:3306->3306/tcp, 0.0.0.0:27017->27017/tcp, 0.0.0.0:69->69/udp
elasticpot            Up 2 hours              0.0.0.0:9200->9200/tcp
elasticsearch         Up 14 hours (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 2 hours              
fatt                  Up 14 hours             
heralding             Up 14 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:465->465/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up 14 hours             
ipphoney              Up 2 hours              0.0.0.0:631->631/tcp
kibana                Up 14 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 14 hours (healthy)   
mailoney              Up 14 hours             0.0.0.0:25->25/tcp
map_data              Up About an hour        
map_redis             Up About an hour        
map_web               Up About an hour        127.0.0.1:64299->64299/tcp
medpot                Up 14 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 14 hours             
p0f                   Up 14 hours             
redishoneypot         Up 14 hours             0.0.0.0:6379->6379/tcp
sentrypeer            Up 14 hours             0.0.0.0:5060->5060/udp
snare                 Up 14 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 14 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 14 hours             
tanner                Up 14 hours             
tanner_api            Up 14 hours             
tanner_phpox          Up 14 hours             
tanner_redis          Up 14 hours             

glances output:

fuzzyinterest (Debian GNU/Linux 11 64bit / Linux 5.10.0-25-amd64)                                                                                                                                                  Uptime: 14:31:19

Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz                                CPU      14.3%  idle    91.0%  ctx_sw     2K                  MEM     51.9%  active   1.46G                  SWAP     0.0%                  LOAD    4core
CPU  [||||||||                                                  14.3%]   user      5.8%  irq      0.0%  inter      2K                  total   15.6G  inacti   10.8G                  total   7.63G                  1 min    0.46
MEM  [|||||||||||||||||||||||||||||                             51.9%]   system    2.8%  nice     0.0%  sw_int    816                  used    8.11G  buffer    642M                  used        0                  5 min    0.51
SWAP [                                                           0.0%]   iowait    0.0%  steal    0.0%                                 free    7.51G  cached   4.89G                  free    7.63G                  15 min   0.53

NETWORK                  Rx/s   Tx/s   TASKS 293 (1491 thr), 1 run, 240 slp, 52 oth Threads sorted automatically by CPU consumption
br-0e2fbc542959            0b     0b
br-4f39e1c09773            0b     0b   CPU%   MEM%  VIRT  RES       PID USER          TIME+ THR  NI S  R/s W/s  Command ('e' to pin | 'k' to kill)
br-5b4c8c54fdbf            0b     0b   >20.8  0.2   190M  37.8M  621579 root           0:01 1     0 R    0 0    python3 /usr/local/bin/glances
br-6a1ea8608c5e            0b     0b    16.9  0.3   51.7M 47.3M  571277 tpot           2:11 1     0 S    0 203K python3 -u /opt/ewsposter/ews.py -l 51
br-7baabac64676            0b     0b    7.1   18.3  33.2G 2.86G    8448 tpot          56:32 85    0 S    0 232K java -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -Djava.security.manager=allow -XX:+
br-29e25ac4a115            0b     0b    5.1   10.8  4.96G 1.68G   10569 tpot          44:56 141   0 S    0 0    java -Xms1g -Xmx1g -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.compile.invokedynamic=true -XX:+HeapDumpO
br-46cbf8507ba6          208b   312b    2.4   2.5   11.2G 403M    10341 tpot          25:19 11    0 S    0 0    node /usr/share/kibana/bin/../src/cli/dist
br-53f6b5dd467c            0b     0b    0.8   3.2   527M  509M     2971 tpot           9:37 8     0 S    0 0    suricata -v -F /etc/suricata/null.bpf -i eth0
br-61f4381af398            0b     0b    0.8   0.9   3.22G 139M      649 root          13:23 68    0 S    0 2K   dockerd -H fd:// --containerd=/run/containerd/containerd.sock
br-63ce6e7cb5f9            0b     0b    0.4   0.7   127M  104M     4415 tpot           2:05 14    0 S    0 0    python3 sf.py -l 0.0.0.0:8080
br-65c78afba772            0b     0b    0.4   0.3   2.29G 53.9M    1344 root           7:10 41    0 S    0 0    python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color
br-67be0bebfbf1            0b     0b    0.4   0.3   51.1M 43.9M    5634 tpot           0:45 6     0 S    0 0    python3 /usr/bin/heralding -c /etc/heralding/heralding.yml -l /var/log/heralding/heralding.log
br-187d88054221            0b     0b    0.4   0.2   44.7M 38.6M  585553 tpot           0:29 3     0 S    0 0    python3 AttackMapServer.py
br-225a914da00c            0b     0b    0.4   0.2   37.7M 34.0M  585671 tpot           0:34 1     0 S    0 0    python3 DataServer_v2.py
br-402d61dd9d64            0b     0b    0.4   0.2   1.46G 24.3M   10295 root           0:24 12    0 S    0 0    containerd-shim-runc-v2 -namespace moby -id 956336e4d8d2b19e60dee09d5161fc4638fcd39fa06ce09ffe68a02796ea5c20 -addre
br-661e89663a7a            0b     0b    0.4   0.1   1.46G 22.8M    5836 root           0:04 12    0 S    0 0    containerd-shim-runc-v2 -namespace moby -id 291b04ca232e8a12759e392e0fa9ade9e5d15a49abcff180e83aba467edb2434 -addre
br-0848d04ea81b            0b     0b    0.4   0.1   1.46G 21.5M   10294 root           0:24 12    0 S    0 0    containerd-shim-runc-v2 -namespace moby -id d8ac6c1d31f72dc63a2ed249e950a108c2c70926be440998f7008cde16ece57e -addre
br-8559b260143b            0b     0b    0.4   0.1   25.8M 19.8M    4331 tpot           2:32 3     0 S    0 0    python3 run.py
br-b2113cb16d16            0b     0b    0.4   0.1   159M  9.30M     526 root           1:58 2     0 S    0 0    vmtoolsd
br-b6828d3ee5e3            0b     0b    0.4   0.0   20.6M 6.26M  585392 tpot           0:09 4     0 S    0 0    redis-server 0.0.0.0:6379   
br-d4988ef7462b            0b     0b    0.4   0.0   216M  6.00M     543 root           0:17 4     0 S    0 3K   rsyslogd -n -iNONE
br-daf0c0734b44            0b     0b    0.4   0.0   3.65M 3.32M    2958 tpot           3:40 1     0 S    0 0    p0f -u p0f -j -o /var/log/p0f/p0f.json -i eth0
eth0                      8Kb   44Kb    0.4   0.0   0     0          12 root           1:02 1     0 I    0 0    [rcu_sched]
lo                       376b   376b    0.4   0.0   0     0      608328 root           0:00 1     0 I    0 0    [kworker/u8:1-ext4-rsv-conversion]
veth1d46f56                0b     0b    0.4   0.0   0     0      613008 root           0:01 1     0 I    0 0    [kworker/3:3-events_power_efficient]
veth6b91c07              97Kb   17Kb    0.0   1.9   514M  299M      274 root           0:57 1     0 S    0 28K  systemd-journald
veth8ae574b                0b     0b    0.0   1.1   206M  170M     7065 tpot           0:03 1     0 S    0 0    tshark -l -n -T pdml -Y tls.handshake.type == 1 || tls.handshake.type == 2 ||ssh.message_code == 20 || ssh.protocol
veth8ba9bfc                0b     0b    0.0   0.7   126M  119M     3954 tpot           0:18 1     0 S    0 0    python3 /usr/bin/conpot --mibcache /tmp/conpot --temp_dir /tmp/conpot --template IEC104 --logfile /var/log/conpot/c
veth8bf59be              24Kb  116Kb    0.0   0.7   2.54G 111M     3416 tpot           1:13 16    0 S    0 0    java -Xms4m -Xmx64m -XX:+UseSerialGC -Dcli.name=server -Dcli.script=/usr/share/elasticsearch/bin/elasticsearch -Dcl
veth54bfe61              312b   312b    0.0   0.7   115M  108M     4038 tpot           0:28 1     0 S    0 0    python3 /usr/bin/conpot --mibcache /tmp/conpot --temp_dir /tmp/conpot --template kamstrup_382 --logfile /var/log/co
veth67dc208                0b     0b    0.0   0.7   114M  107M     3636 tpot           0:14 1     0 S    0 0    python3 /usr/bin/conpot --mibcache /tmp/conpot --temp_dir /tmp/conpot --template ipmi --logfile /var/log/conpot/con
veth69ef096                0b     0b    0.0   0.7   114M  107M     3890 tpot           0:14 1     0 S    0 0    python3 /usr/bin/conpot --mibcache /tmp/conpot --temp_dir /tmp/conpot --template guardian_ast --logfile /var/log/co
veth87c257a                0b     0b    0.0   0.3   1.56G 54.7M     588 root           8:00 13    0 S    0 0    containerd
veth336ce68                0b     0b    0.0   0.3   59.8M 52.2M    5856 tpot           0:01 2     0 S    0 0    python3 /usr/bin/tanner
veth379b3fd                0b     0b
2023-09-26 17:25:00 UTC    0b     0b

df -h output:

[tsec@fuzzyinterest:/opt/tpot/bin]$ sudo df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  3.9M  1.6G   1% /run
/dev/sda2       118G   70G   43G  63% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/1f915122febb74f996c56f99f3bcd804631e22708b28dbb626c7e3d5755928fb/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/a3a17a8120df442eebc153c912e8dbeefe6964a3501577d804d4cbbbb380576f/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/0a6559d21b1e83ab998d35d747851977fdab921007ee37eb77666820f4ded9a9/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/549e5e637a95960fb8566de46bf11c28ca162abc3e8eddc641e1b749e47ffe67/merged
shm              64M     0   64M   0% /var/lib/docker/containers/e9e05278ca2617917c681ff1cbce9024bd92465edc94c123706b5a670b291174/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/076a51c79f7a9646980291f68340e0ad47504a69389dc98621b3a61343f8c488/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/0a5a0363d2867cee5be5efe3029ed551f03e1af796a0b9f2706f13384f3b8d60/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/b218f0c2a7c5ce865ea757d3fff2c32d3a1eb6e2741c3f13aab897b8fcbc89eb/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/7fabbfaaf4118d16a1d41c811a5fda077ba875390b7ea1013ebd7880aa5cc820/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/e05e4879521d0ce07afc223cb1f37036d6b497d745a03ed93c82ebc7b74b9d2e/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/8cd22d1f78610142e201e4113b5d8253962b01528c67d4ae0466f6bbb785ea3c/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/801446061bb4fd690a473f8081074aa770f8f7675335c95d0c8b00ff2315f7f9/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/708108ca3f08d18c77b38bf95ff63801e2c03f76bb066b5edcb20b2a10daab14/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/41831ab899f49433a03f140fae1252d0139df4eeac5bc021b615b5ced99edbc3/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/42c51c6979b8f87f195b61cc3c74b72c8b69359bf0b520dc0ae405a028d5ce0f/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/4491989650dd7be53d5b39e8b27caafbd9cfe979c9e9a0b86f24266877a7be38/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/196b6bdb0fb53a54defc8e0e9c51b0077fd1285e92686574b56f5f5ee9a43897/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/7d3ddb6bedeba14785c1ed7bf55116dd279514c35359bfd8b86fe97caf6cdba6/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/9c143d8f71aab42c2ad6435bf2d7b9ef537cc078ee0ed95c8c25a99a04667a3c/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/646de5c2961692666c83be0911d6895bc181c0e81f89a2106b616688949eea7e/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/9226b0ec87e54ff366ad1c5cd3f9758347d6b96af9570c92d79533b88ae45a82/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/a40ec4c9d5379670dc786c99c93b98f65e7b24b5e6ffe12fdb148480376e1438/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/38d9626bc1c2e5b665c42b7e426e7082f16ebc9e0ea24008cd9e37a0323b7dc4/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/db4bbd32588b5cf92faaf22865ce4a3d9968865707b4334394c97d3c70df3bf0/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/e9258d5fc024d52c840185cfe460e8a96659c1dc265f0272625a4b29ea51423e/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/fde9e86b8849f98e2e5c7a06319e003298a31c0dd5e9f37f1e5820993152eb74/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/41072fdfa9c3c807621fe3d0fa28ec5f95033da1a3c5e59d8386a7e77b2fa619/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/a4c1dffd89604811c2337533f471c83f1ce237256de2ccd7a1d6e556de2314a5/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/c0b380f04b627e765c65252901ebaaaad2a4f36fff325da43bc0ce19fbbf793c/merged
shm              64M     0   64M   0% /var/lib/docker/containers/c1aef1e5be42066193386079ef5173f5fd407ffa26f5947fe7c07312b6df911e/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/eb3787c5c4d8977a3df6f4784b902f37b28490833d5f17530969ddd60c81fcad/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/b83a27b916e78cf37a683a68ec623af898b14f28a64b7e031576190bf8e1e99d/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/18b12e5759367ff9b2815b48d68ceaecce8ad6d4b48668b778f4f07a289edfb0/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bbe2f881ef0cca8fa126a8df60a7125f28176bfb6205f311aee6683e06fe6068/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/449dad74ba92342d49613df3038ca6ffbf850c151ec580cc777eb48441ca142e/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e6578e700f48d524da2d9697f70355e03d79c87703d0755809ed03de0898ea12/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/f952d0794f24a447c376a7c045c44b7a78a276ef982ed664d46964deeff4b7ad/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/49020ef3d10d8d3ac8f6c24d981cab2572f72916538e7503af9b24b6e0269367/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/826c0d54de561dc8a5becb627307e8d76d19ac80fde5e27efcbd6466199cfd60/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/23e82af7a554d3b802322d09a2f776c1a46e6b24a238f0e4e6b4d288c2b034ec/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/80b3ff1bbb2d259101fc6a928438df03ae7fb65ef9f61722424d3edacac12c3b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/4be45fa597f63f3860e40fbd5342fff8c51cd8d81c62f5968709d517257a1040/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/99b1693817488ba90edd2047a596fda25ae76fd178aa311ae54a64d7cada31d5/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/901784bf3dc1b2c70545c2fa3e8ab735e0a863e13a394e53739e31587e801f63/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a2de0e7226e45bb1bae8226240074df27fd0ce4ed60237d65b1e7122842edcca/mounts/shm
shm              64M   12K   64M   1% /var/lib/docker/containers/76ef71d27139ff29ff1044a7221051d8875107fb93e0e93208f8f202247cf8fe/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/403ffdaab18f55e368fd8ac0d257bec67dc6162c1d9271c871eef4d4f418cfd1/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/b121022f6949a170cc51e495619f0a1c30db391b9cb4b1bc633a8767139e4553/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7431a686dc52da383a89c143e589087dd93a313d5d7a11ae631bbb3f9d0bbe58/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7eec43b32815ef2e1bac7f309f700fa176ff3fa6f743232639cd3e46e70550fb/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a639b56811b6a28b880cf437f18debcb7ee0503e7a011071fd1db4b2ece85324/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/96cc32f18f180a6569c54f33694291d4fd7b46f3325b057a59d4947c7e08e2d4/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/f8eda8f26177c5808ccfa04133aa80d800ac89722468a278f4f6d65f97749666/merged
shm              64M     0   64M   0% /var/lib/docker/containers/6c79c2c220876a8de8a0886d0dbb8178ec99cf1dc53b6e4be7af1bd1249f1f48/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/0178fc6d0116213cc917dfe57bfc8bb312f747ef20a717eafa4ffe8ce655b499/merged
shm              64M     0   64M   0% /var/lib/docker/containers/291b04ca232e8a12759e392e0fa9ade9e5d15a49abcff180e83aba467edb2434/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/fed96ba4ac77b8338d2b10f88f958c1535573570368ecbed4396b3ff640034f0/merged
shm              64M   20K   64M   1% /var/lib/docker/containers/f3b7809fa671344a9a18d41f0ae55376edda8d7c5465c3ae0063e1d924b2bcf9/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/9fabf30989f1cd7409765487ef47122dcc026648ef2181aa0fbcb953ebfb86f9/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/a7dba0a1ade40ab78cdefe555adba64da66e7c34370d1360d4e97f3cf93b875f/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/8591f3a0a387d59f4a9b222e9168786c452163cde7e8a1c8f2e9a4f5076887ee/merged
shm              64M     0   64M   0% /var/lib/docker/containers/d8ac6c1d31f72dc63a2ed249e950a108c2c70926be440998f7008cde16ece57e/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/956336e4d8d2b19e60dee09d5161fc4638fcd39fa06ce09ffe68a02796ea5c20/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/9a60538ed2a962d897f5737bc42d54ecb85439a99db1169752b9e53aee0ec500/merged
shm              64M     0   64M   0% /var/lib/docker/containers/e975aaf156ef07af1085d513ef7930eee028a53e1136504354f3023474f5586c/mounts/shm
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/65f51f943198bb45c788db27ac0c0e74f6714d793fa24e26c3b9655ca99a0e3b/merged
overlay         118G   70G   43G  63% /var/lib/docker/overlay2/70c8107a69d5b7b9001313506f5913cb90d1a95f5fd80aa7b86903324afeaeec/merged
shm              64M     0   64M   0% /var/lib/docker/containers/8684c706b38cb72de5df49ac867688a8f41c878c8a4d961a93e2a4e5291edf8c/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/da520e9aaf7cd27388fdaf28b94c1a7e3bf6b8988fbe66cf721929abe9ac4e8d/mounts/shm
tmpfs           1.6G     0  1.6G   0% /run/user/1000
shm              64M     0   64M   0% /var/lib/docker/containers/89ca25bdeb4769f4968f981d90861eca5149f88f6ac568a7f886858e94f9ed91/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/5c1bffb922489d58f916cd63dc652ae038868287afb68a06bfb519f9af92b8dc/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/4be16c1f84be3660e1df030d3ecde3e8ef5cbaf72953930f2b32c6291d1d1a9a/mounts/shm

netstat -tulpen output:

[tsec@fuzzyinterest:/opt/tpot/bin]$ netstat -tulpen
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 127.0.0.1:41185         0.0.0.0:*               LISTEN      0          2769919    -                   
tcp        0      0 127.0.0.1:36193         0.0.0.0:*               LISTEN      1000       2769899    581126/cockpit-brid 
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      0          28877      -                   
tcp        0      0 0.0.0.0:1025            0.0.0.0:*               LISTEN      0          22933      -                   
tcp        0      0 127.0.0.1:36417         0.0.0.0:*               LISTEN      0          13544      -                   
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      0          25509      -                   
tcp        0      0 0.0.0.0:2404            0.0.0.0:*               LISTEN      0          21352      -                   
tcp        0      0 0.0.0.0:135             0.0.0.0:*               LISTEN      0          29241      -                   
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          13516      -                   
tcp        0      0 127.0.0.1:64296         0.0.0.0:*               LISTEN      0          49340      -                   
tcp        0      0 0.0.0.0:11112           0.0.0.0:*               LISTEN      0          24807      -                   
tcp        0      0 0.0.0.0:64297           0.0.0.0:*               LISTEN      0          26944      -                   
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      0          23167      -                   
tcp        0      0 0.0.0.0:42              0.0.0.0:*               LISTEN      0          30777      -                   
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      0          26630      -                   
tcp        0      0 127.0.0.1:64298         0.0.0.0:*               LISTEN      0          19233      -                   
tcp        0      0 127.0.0.1:64299         0.0.0.0:*               LISTEN      0          3226714    -                   
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      0          25751      -                   
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      0          22656      -                   
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      0          29309      -                   
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      0          28233      -                   
tcp        0      0 0.0.0.0:2575            0.0.0.0:*               LISTEN      0          24040      -                   
tcp        0      0 127.0.0.1:64303         0.0.0.0:*               LISTEN      0          24033      -                   
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      0          2713855    -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          35512      -                   
tcp        0      0 0.0.0.0:81              0.0.0.0:*               LISTEN      0          28308      -                   
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      0          27480      -                   
tcp        0      0 0.0.0.0:10001           0.0.0.0:*               LISTEN      0          22158      -                   
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      0          23175      -                   
tcp        0      0 0.0.0.0:20              0.0.0.0:*               LISTEN      0          29455      -                   
tcp        0      0 0.0.0.0:50100           0.0.0.0:*               LISTEN      0          22561      -                   
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      0          30803      -                   
tcp        0      0 0.0.0.0:57782           0.0.0.0:*               LISTEN      2000       3494295    -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          26050      -                   
tcp        0      0 0.0.0.0:631             0.0.0.0:*               LISTEN      0          2715083    -                   
tcp        0      0 0.0.0.0:23              0.0.0.0:*               LISTEN      0          24847      -                   
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      0          26678      -                   
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      0          24827      -                   
tcp        0      0 0.0.0.0:1433            0.0.0.0:*               LISTEN      0          28022      -                   
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      0          20466      -                   
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      2000       3495055    -                   
tcp        0      0 0.0.0.0:1723            0.0.0.0:*               LISTEN      0          28790      -                   
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      0          26839      -                   
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      0          19450      -                   
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          22096      -                   
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      0          28145      -                   
tcp6       0      0 :::64294                :::*                    LISTEN      0          9793       -                   
tcp6       0      0 :::64295                :::*                    LISTEN      0          13518      -                   
udp        0      0 0.0.0.0:19              0.0.0.0:*                           0          28700      -                   
udp        0      0 0.0.0.0:53              0.0.0.0:*                           0          26720      -                   
udp        0      0 0.0.0.0:69              0.0.0.0:*                           0          28397      -                   
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          25096      -                   
udp        0      0 0.0.0.0:161             0.0.0.0:*                           0          23084      -                   
udp        0      0 0.0.0.0:623             0.0.0.0:*                           0          19437      -                   
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           0          22447      -                   
udp        0      0 0.0.0.0:5000            0.0.0.0:*                           0          21469      -                   
udp        0      0 0.0.0.0:5060            0.0.0.0:*                           0          19222      -    


Would appreciate some advice here.

Thank you.

**Comment by robeweb** [comment]
Same issue.
Looking inspect console I have found errors in map.js:
![imagen](https://github.com/telekom-security/tpotce/assets/95315698/0135e43d-bd47-4fa6-97dc-70be4074f481)
Also you can see WebSocket connection established.

**Comment by legendshadow** [comment]
Good afternoon. The truth is that the same thing happened to me and I started messing around with the bin folder. In the end, I used this order and the map started working.

   86  blackhole.sh 
   87  clean.sh 
   88  deploy.sh 
   89  dump_es.sh 
   90  systemctl start tpot
   91  systemctl start tpot
   92  hpfeeds_optin.sh 
   93  hptest.sh 
   94  blackhole.sh 
   95  clean.sh 
   96  dump_es.sh 
   97  systemctl start tpot
   98  hpfeeds_optin.sh 
   99  hptest.sh 
  100  ls
  101  myip.sh 
  102  mytopips.sh 
  103  ls
  104  restore_es.sh 
  105  rules.sh 
  106  setup_builder.sh 
  107  tpdclean.sh 
  108  systemctl stop tpot
  109  tpdclean.sh 
  110  systemctl stop tpot
  111  tpdclean.sh 
  112  tpdclean.sh -y
  113  ls
  114  tped.sh 
  115  ls
  116  unlock_es.sh 
  117  updateip.sh 
  118  unlock_es.sh 
  119  systemctl start tpot
  120  unlock_es.sh 
  121  unlock_es.sh 
  122  unlock_es.sh 
  123  systemctl start tpot
  124  dps.sh
![Screenshot from 2024-03-21 12-56-30](https://github.com/telekom-security/tpotce/assets/53492636/244d7bbb-3987-4014-a156-1c827266dfb0)

I also noticed the color of the elasticvue indicator, which was previously red, now turned green.

![Screenshot from 2024-03-21 12-57-26](https://github.com/telekom-security/tpotce/assets/53492636/319729ab-8975-4d22-96c9-01320b6191b1)

**Comment by idforfast** [comment]
> Does anyone know how to resolve or mitigate this issue?
> 
> I created a shell script to restart the map's docker containers twice a day. Is that enough?
> 
> map_restart.sh
> 
> docker restart map_redis docker restart map_web docker restart map_data

Not working after trying this multiple times and also restarted server multiple times
