### ISSUE TITLE
DDOS (with soft-reboot required) vs T-Pot Sensor possible, by nuking Tanner

### ISSUE THREAD

**Issue by pdolinic** [telekom-security/tpotce#1287]
- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

A: Linux aestheticrat 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
A: 
 
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

- What T-Pot version are you currently using?
22.04

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
A:  Sensor on 1 Server & Hive on 1 Server

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
A: Cloud Virtualization, with Post-Install Script on Both

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
A: No

- How long has your installation been running?
A: ~ 3 Days, as I am testing attacks currently

- Did you install upgrades, packages or use the update script?
A: Yes, full system update & upgrade on raw Debian 11s + Post install

- Did you modify any scripts or configs? If yes, please attach the changes.
A: No

# Attack
---
Reproducing the attack, first I did a), then b, I repeated b) several times until I saw socket errors on Siege, indicating I hit Tanner hard enough: 
```
a) for i in `seq 1 10000`; do curl ip.ip.ip.ip; done
b) siege ip.ip.ip.ip -c 255 -r 100000 -b -v
```
# Result Sensor dead
- First you notice the SSH Shell become unresponsibe, until you get 1 character after 30 seconds, then barely any response
- Then and the Reboot looks very unhealthy, and takes quite a long time
![Tanner down](https://user-images.githubusercontent.com/71389319/227585970-2e0019e4-82de-4acb-a6d3-543ad1471f97.png)
- After the Reboot, I see sensors function again

**Comment by t3chn0m4g3** [comment]
Thanks for opening the issue, however since we just use upstream Tanner I recommend to open the issue on their [repository](https://github.com/mushorg/tanner). When fixed T-Pot will offer the fixed version as well.
Thanks.

**Comment by pdolinic** [comment]
Thanks for the quick response,

I just saw another interesting thing,
there might be more to this, independent of Upstream Tanner:

- I just tested on Standalone,
Trying  to take a T-Pot of 16 Cores, 16 GB Rams  against 22 Attacker Cores ->  it fails (even though I can see the HTOP spike 99% at times)

- Previously I attacked a Distributed Sensor and Hive
 8 Cores / 8GB RAM each managed to take it down with **1** Attacker Core and ~ 20 Minutes of messing with the named curl & siege
