### ISSUE TITLE
logstash.conf changes aren't affecting logs in a distributed install

### ISSUE THREAD

**Issue by I-Simon-I** [telekom-security/tpotce#1307]
Hi ! 

I've been using T-Pot standalone on multiple VM for a few weeks and I managed to set it up the way I wanted. However I was asked to use the distributed deployement rather than multiple standalone. I installed T-Pot on every VM and linked them all to the HIVE using the deploy.sh command. Everything works fine, logs are coming through but I can't find a way to make the email alerts work on this install. For some reason, my logstash.conf file aren't "used" by logstash. It seems like the logstash in the distributed version is using another logstash.conf other than the two I've modified. Email alerts aren't generated and the tag "_geoip_lookup_failure" is present in every log even though I've disabled it. 

That would be very helpful if someone could help me understand where I have to modify the logstash.conf file in order for the logs to be processed (changes described below) the way I need them to be. This would also allow me to better understand how logs are processed between the sensors and the hive.

PS : It's worth noting that whenever I restart tpot on the HIVE, every container goes down and keeps crashing for a few minutes then they all go up. However, when I reboot, it starts normally

> After reboot
![image](https://user-images.githubusercontent.com/116071161/231818672-3625d5ab-9a61-41e3-a284-7a2925411632.png)

> After systemctl restart tpot
![image](https://user-images.githubusercontent.com/116071161/231818622-f16979a3-b15d-4446-984d-b495e5024c20.png)

Thx for your time !

**- What version of the OS are you currently using `lsb_release -a` and `uname -a`?**
![image](https://user-images.githubusercontent.com/116071161/231813209-7ae800d0-74af-477a-b8fb-3f49eca04b78.png)
![image](https://user-images.githubusercontent.com/116071161/231803204-60506a1a-942f-4762-8b56-4202f45eaa0f.png)

**- What T-Pot version are you currently using?**
> T-Pot 22.04.0

**- What edition (Standard, Nextgen, etc.) of T-Pot are you running?**
> Distributed

**- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?**
> VM

**- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.**
> No

**- How long has your installation been running?**
> A few hours

**- Did you install upgrades, packages or use the update script?**
> Yes, on the HIVE SENSOR and the HIVE

**- Did you modify any scripts or configs? If yes, please attach the changes.**
> I've modified the /opt/tpot/docker/elk/logstash/dist/logstash.conf file and made a copy of it under /data/elk on both the HIVE and the HIVE SENSOR and I added the volume in the "Logstash" section of the /opt/tpot/etc/tpot.yml file

Changes : 

- Added throttle that adds the tag "email" for the first 10 logs of each honeypot
![image](https://user-images.githubusercontent.com/116071161/231806283-86a4d08c-609f-411e-a5dc-bc2e03f8ecd8.png)

- Dropped NGINX logs because it was too noisy
![image](https://user-images.githubusercontent.com/116071161/231806499-e9336b5a-d544-4e9c-98bf-2be200a38d4f.png)

- Disabled GEOIP coordinates tags
![image](https://user-images.githubusercontent.com/116071161/231806731-baa1be1b-cda3-4bc4-96f8-a874562a5990.png)

- Added output settings to send email alerts
![image](https://user-images.githubusercontent.com/116071161/231807047-0480c40d-8379-45f4-9160-f09e37f26cb0.png)

- I have disabled the following services : 
- Suricata
- Fatt
- P0f
- Spiderfoot

- Added the volume to the container in tpot.yml
![image](https://user-images.githubusercontent.com/116071161/231814342-dcb6ca7f-d583-4631-89fd-8852181235c8.png)

**- Please provide a screenshot of `glances` and `htop`.**
> The HIVE SENSOR
![image](https://user-images.githubusercontent.com/116071161/231810797-c1570718-d72d-4096-93e1-4f6c46a1e303.png)
![image](https://user-images.githubusercontent.com/116071161/231810906-b29b69fd-1bdf-4893-a21e-5674d00e724a.png)

> The HIVE
![image](https://user-images.githubusercontent.com/116071161/231807613-cde36dad-1d9f-4297-98c4-4976aa231ac7.png)
![image](https://user-images.githubusercontent.com/116071161/231807705-6eb878c3-29fe-42be-b507-05f587be2b3b.png)

**- How much free disk space is available (`df -h`)?-** 
> 35GB on the HIVE
> 35GB on the SENSOR

**- What is the current container status (`dps.sh`)?**
> The HIVE SENSOR
![image](https://user-images.githubusercontent.com/116071161/231808418-d1d2c383-8c1e-47d1-a34e-28a083348094.png)

> The HIVE
![image](https://user-images.githubusercontent.com/116071161/231809729-7385b008-11ee-4ea1-bd73-974cd30d580c.png)

**- What is the status of the T-Pot service (`systemctl status tpot`)?**
> The HIVE SENSOR
![image](https://user-images.githubusercontent.com/116071161/231810034-e37ca55e-8ab8-4bcb-9853-37fb8806944e.png)

> The HIVE
![image](https://user-images.githubusercontent.com/116071161/231809971-4f559d68-7f69-4437-b29c-4fe0c3b2e801.png)

**- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`**
> The HIVE SENSOR
![image](https://user-images.githubusercontent.com/116071161/231810295-b052ccd2-f86b-40d0-9368-5d4421eb3b92.png)

> The HIVE
![image](https://user-images.githubusercontent.com/116071161/231810366-e26671e1-0689-4406-9027-c49ca50f1830.png)

**Comment by t3chn0m4g3** [comment]
Please follow this [comment](https://github.com/telekom-security/tpotce/discussions/1306#discussioncomment-5590814).

**Comment by I-Simon-I** [comment]
I don't want to export the logs to another endpoint, I wanna keep it within the main HIVE but I would like to apply filters and use logstash output to generate alerts but the logstash.conf file doesn't seem to work as it did for the standalone version
