### ISSUE TITLE
tpot service won't start

### ISSUE THREAD

**Issue by Epicism** [telekom-security/tpotce#1345]
Hello,

When trying to start the TPOT service I get the error:
![image](https://github.com/telekom-security/tpotce/assets/10110013/31753dbe-b89f-4cc7-b3d6-77bdbeac117d)

When I manually run the docker compose command I am getting the error
![image](https://github.com/telekom-security/tpotce/assets/10110013/9519fc08-21ac-4a74-92ce-21806f4fb85b)
`In file /opt/tpot/etc/compose/elk_environment: environment variable name '"status: 429' may not contain whitespace.`

---
- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
![image](https://github.com/telekom-security/tpotce/assets/10110013/0d62b326-d676-4615-a282-3f675c98efde)

- What T-Pot version are you currently using?
T-Pot 22.04.0

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Proxmox VM

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No

- How long has your installation been running?
2 days

- Did you install upgrades, packages or use the update script?
No

- Did you modify any scripts or configs? If yes, please attach the changes.
I tried to remove ELK from tpot.yaml but that didn't work so I restored the backup 

- Please provide a screenshot of `glances` and `htop`.
![image](https://github.com/telekom-security/tpotce/assets/10110013/7ed09157-39b8-44d0-acb3-bf8db6cc47bb)
![image](https://github.com/telekom-security/tpotce/assets/10110013/541c9151-87dd-4a9d-90e7-d69756ffbfc1)

- How much free disk space is available (`df -h`)? 
![image](https://github.com/telekom-security/tpotce/assets/10110013/192fa1c7-9914-449e-a0cd-3924fbfc515f)

- What is the current container status (`dps.sh`)?
![image](https://github.com/telekom-security/tpotce/assets/10110013/aacde53c-775a-49d4-af6b-f31ed7bbd880)

- What is the status of the T-Pot service (`systemctl status tpot`)?
Down

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
N/A

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
N/A

**Comment by t3chn0m4g3** [comment]
What are the contents of the elk_environment file?

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.

**Comment by Epicism** [comment]
![image](https://github.com/telekom-security/tpotce/assets/10110013/df306a64-17a9-43df-9eff-fcea5a8cd6b1)
Apologies for the late reply.

**Comment by t3chn0m4g3** [comment]
T-Pot gathers its geo coordinates through external service, I have barely seen this exceeded its limit, which only happens in testing if T-Pot is being restarted over and over again.
If you want to use a different service or add an API key, you can do so by adjusting [updateip.sh](https://github.com/telekom-security/tpotce/blob/c1808161e440eff3b1a334642c03d811d82b4817/bin/updateip.sh#L15-L17).

**Comment by Epicism** [comment]
I'm confused by your reply - the tpot service won't start because docker compose says that spaces cannot be in the elk_environment file, which it has. I'm not sure how the updateip.sh key is associated.

**Comment by t3chn0m4g3** [comment]
Because `elk_environment` will be [created](https://github.com/telekom-security/tpotce/blob/c1808161e440eff3b1a334642c03d811d82b4817/bin/updateip.sh#L68-L75) by `updateip.sh` with an unexpected error due to the rate limit being exceeded which in turn is not accepted by `docker-compose`

**Comment by Epicism** [comment]
Ahh understood. Thank you for the clarification.
