### ISSUE TITLE
Geoip ASN not working

### ISSUE THREAD

**Issue by adamjanzen** [telekom-security/tpotce#1346]
Since code push [f438be7](https://github.com/telekom-security/tpotce/commit/f438be7e2738c4e8be607c0ab8ff354b617aa674), the ASN lookup hasn't worked. I checked, and the MaxMind databases are being updated.

Perhaps the Logstash configuration should be updated to point at the ASN database that is auto-updated  by Logstash (/usr/share/logstash/data/plugins/filters/geoip/...), so that it uses it?

**Comment by t3chn0m4g3** [comment]
Thanks. The `default_database_type` needs to be set as described [here](https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-default_database_type). Setting the path will disable the automatic updates.
Images are being currently build and will be available soon.

**Comment by t3chn0m4g3** [comment]
Images are now available. Thanks again for reporting and please leave feedback if this also fixes it for you.

**Comment by adamjanzen** [comment]
Image change worked, thanks!
