### ISSUE TITLE
Disable specific honeypots and/or setting ammount of ram available

### ISSUE THREAD

**Issue by Toro786** [telekom-security/tpotce#1353]
Hi, I'm trying to properly set my tpot (iso installed version) and I need to either be able to shut down some honeypots and, if possible, to set a specific amount of RAM to some honeypots (ddos to be specific).
I'm running tpot on a 4 core and 16gb of RAM vm.
Thank you in advance.

**Comment by t3chn0m4g3** [comment]
Duplicate, see #1352.
