### ISSUE TITLE
AttackerMap location Marker did not match to my real location

### ISSUE THREAD

**Issue by OhmGun** [telekom-security/tpotce#1375]
Help, 
on my tpot attacker map did not show real location of my IP address,
how do i solve this problem?
my real location in indonesia but the marker in the map was pointing to australia,
<img width="1099" alt="image" src="https://github.com/telekom-security/tpotce/assets/12862916/bdb90228-6b18-4219-8be3-33a74a60f990">

**Comment by t3chn0m4g3** [comment]
Based on the info I cannot reproduce the issue, more explanation can be found in #1313. If there is an error on your geoip it is most likely that it will be fixed in the future with MaxMind updating the db.
Unfortunately there is nothing more that can be done on our end.

**Comment by OhmGun** [comment]
thankz @t3chn0m4g3 there was solve by update my location on maxmind,
