### ISSUE TITLE
Kibana Problem

### ISSUE THREAD

**Issue by AzizKpln** [telekom-security/tpotce#1381]
I cannot see kibana in the features. 
![Ekran Alıntısı](https://github.com/telekom-security/tpotce/assets/28807419/5086080e-dbfa-4339-b990-9602febf1215)

**Comment by Wasifaliqurshi** [comment]
how did you manage to get this interface, i failed to get this output.
![1](https://github.com/telekom-security/tpotce/assets/92079787/f26c2101-4aec-4b66-aa1d-03ebbc21ae84)

**Comment by romeoCYS** [comment]
Hi bro, how do you even bring this landing page? Can you please tell me?
Actually I installed tpot and I had another landing page shown in the image below.

Please tell the detailed process or did you follow any video please share?

and did you use the "docker-compose.yml" in the docker directory?? using docker-compose up

![image](https://github.com/telekom-security/tpotce/assets/96229812/0281b9ec-5440-40ff-b171-45512679ad57)

**Comment by AzizKpln** [comment]
Connect the webui via port number 64297

**Comment by AzizKpln** [comment]
> how did you manage to get this interface, i failed to get this output.
> ![1](https://github.com/telekom-security/tpotce/assets/92079787/f26c2101-4aec-4b66-aa1d-03ebbc21ae84)
> 
> 

Check the failed service first bro

**Comment by romeoCYS** [comment]
> Connect the webui via port number 64297

It doesn't connect with 64297. In our case it works with 64294. But still we don't get this interface. We get the different one

**Comment by AzizKpln** [comment]
> > Connect the webui via port number 64297
> 
> It doesn't connect with 64297. In our case it works with 64294. But still we don't get this interface. We get the different one

64294 is another service. You have to be able to connect the webui via port number 94297 because it's where the honeypot logs are being showed

**Comment by Wasifaliqurshi** [comment]
> > > Connect the webui via port number 64297
> > 
> > 
> > It doesn't connect with 64297. In our case it works with 64294. But still we don't get this interface. We get the different one
> 
> 64294 is another service. You have to be able to connect the webui via port number 94297 because it's where the honeypot logs are being showed

When we try to enter 64297 our browser doesn't connect to to that port. What can be the possible error?

**Comment by AzizKpln** [comment]
There are a few reasons of this issue but my personal thought is that the project doesn't work stabilized.  Still, these could be the possible reasons:

* Using old version may cause this issue be sure that you are using the latest version of this project
* Recieving errors during installation may cause this issue, be sure that the installation process is done without any errors
* Not having enough of space for the project may cause this issue. Be sure that you have at least 150GB of free space
* Tpot service might not be running. Check it via "systemctl status tpot". If the service is not running run it with "systemctl start tpot" but if starting the service fails, try to go to the source of the error or make a fresh setup
* Check if port 64297 is being blocked by the firewall. If it does create a rule for this situation
* Be sure that port 64297 is being listened and not used by another service
