### ISSUE TITLE
Filebeat Certificate Integration

### ISSUE THREAD

**Issue by Naveen-kumar44** [telekom-security/tpotce#1396]
When I'm integrating the zeeklogs of an ubuntu it is throwing an error "Exiting: couldn't connect to any of the configured Elasticsearch hosts. Errors: [error connecting to Elasticsearch at https://192.168.211.129:64297: Get "https://192.168.211.129:64297": x509: certificate signed by unknown authority]" how to slove this

**Comment by t3chn0m4g3** [comment]
We do not support Filebeat.

**Comment by Naveen-kumar44** [comment]
We are not integrating filebeat we are currently integrating the zeeklogs , we want to visualize the logs of one ubuntu machine we configured everything but when we run the command sudo filebeat setup it throws the error "Exiting: couldn't connect to any of the configured Elasticsearch hosts. Errors: [error connecting to Elasticsearch at https://192.168.211.129:64297: Get "https://192.168.211.129:64297": x509: certificate signed by unknown authority]" .   And also can I know where the path tpot , kibana, Elasticsearch ssl certificates
