### ISSUE TITLE
T-Pot : Root access down and TPot user own my /etc folder 

### ISSUE THREAD

**Issue by lilidy** [telekom-security/tpotce#1410]
Hello world

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? **Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux**
- What T-Pot version are you currently using? **2204**
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? **Standard**
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? **Azure VM**
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. **No**
- How long has your installation been running? **1 hour**
- Did you install upgrades, packages or use the update script? **No**
- Did you modify any scripts or configs? If yes, please attach the changes. **Just regenerate a certificate for nginx https://github.com/telekom-security/tpotce/issues/694**
- Please provide a screenshot of `glances` and `htop`. 
![image](https://github.com/telekom-security/tpotce/assets/57851904/d374b016-34b2-4b4f-a44a-bc2d05fe1b19)

- How much free disk space is available (`df -h`)? **/dev/sda1        30G  8.9G   19G  32% /**
- What is the current container status (`dps.sh`)? 
- What is the status of the T-Pot service (`systemctl status tpot`)? **inactive**
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Azure, AWS and GCP tend to change things which will result in strange behavior regarding T-Pot up to 22.04. T-Pot will, even with the Post Install method, change config that might interfere with hyperscaler VM setups.
It will be interesting to know if the [Preview](https://github.com/telekom-security/tpotce/discussions/1325) will work better for you.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
