### ISSUE TITLE
T-pot is going down every 20-30seconds and kabana board is never available

### ISSUE THREAD

**Issue by MohElmoniry** [telekom-security/tpotce#1415]
🗨️<a name="info"></a>
## I've made a fresh install through cloud with a 16 GB Memory / 8 Intel vCPUs / 480 GB Disk / LON1 - Debian 12 x64
after installation was complete i couldn't find kibana tried a couple of times with other copies same issue. I ran dps.sh and I find tpot is down and most services down, so i start it and check still not there. but after the dps.sh shows most services on except kibana. one minute later all services are down and tpot is back down again ( checked through dps.sh ). Can I have any solution for this please bene stuck for 2 days now? 

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using - latest
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? cloud digitalocean
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. none
- How long has your installation been running? been trying for a day with the same issue. current one ~1hour
- Did you install upgrades, packages or use the update script? no
- Did you modify any scripts or configs? If yes, please attach the changes. no
- Please provide a screenshot of `glances` and `htop`.
![image](https://github.com/telekom-security/tpotce/assets/15960456/79831146-ea3a-4398-b0a7-1ff9f6429d86)

- How much free disk space is available (`df -h`)?
- 
![image](https://github.com/telekom-security/tpotce/assets/15960456/b48c237a-98ac-477e-bff0-89333b8be51c)

- What is the current container status (`dps.sh`)?
![image](https://github.com/telekom-security/tpotce/assets/15960456/1000b654-51a6-4f58-8f35-fa6a99481b56)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://github.com/telekom-security/tpotce/assets/15960456/847e85c7-6610-45b9-9c98-934cf670584b)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://github.com/telekom-security/tpotce/assets/15960456/f8c3342e-b956-4edf-a9b6-b23921c6157f)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

Thank you!

**Comment by t3chn0m4g3** [comment]
Is this a post install? Based on the occupied ports `tcp/53` it seems that `ddospot` cannot start successfully and as a result tpot keeps restarting.
Either remove  `ddospot` from `tpot.yml` or find the corresponding service occupying the conflicting port and disable it.
