### ISSUE TITLE
integration with MISP

### ISSUE THREAD

**Issue by Brunohpb** [telekom-security/tpotce#1418]
Has anyone thought about automatically feeding information from tpotce into MISP? https://www.misp-project.org/

**Comment by t3chn0m4g3** [comment]
There is currently no plan to support MISP. If you want to forward events into a MISP channel you can do so with Filebeat by using its [Threat Intel Module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-threatintel.html).
