### ISSUE TITLE
bookworm not supported in the install script

### ISSUE THREAD

**Issue by emilstahl** [telekom-security/tpotce#1427]
Running install.sh returns
Aborting. Debian bookworm is not supported.

But bookworm is supported in the update.sh script? https://github.com/telekom-security/tpotce/commit/81fab84040dd833ad1410bc2b95bb8f841c128e7

This appears to be an oversight?
```
# lsb_release  -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by t3chn0m4g3** [comment]
For now this is intentional.

**Comment by antonengelhardt** [comment]
Same issue, how can i resolve it?
