### ISSUE TITLE
Preseed error exit code 1

### ISSUE THREAD

**Issue by d3athg0d** [telekom-security/tpotce#1436]
trying to install on esxi 7 vm under debian x64

however the installation failed at preseed and after which entered into cli.

![CleanShot 2023-11-17 at 01 31 07](https://github.com/telekom-security/tpotce/assets/78822442/88bbfd48-b9d0-4119-b7be-e02c5cdb3afc)

**Comment by t3chn0m4g3** [comment]
You can use the [Post Install Method](https://github.com/telekom-security/tpotce?tab=readme-ov-file#post-install) instead.
