### ISSUE TITLE
DDOSpot memory leak

### ISSUE THREAD

**Issue by LFBernardo** [telekom-security/tpotce#1437]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? 
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Linux shiveringsynergy 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
- What T-Pot version are you currently using?
 22.04
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM (ESXi 6.7)
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
none
- How long has your installation been running?
2 weeks
- Did you install upgrades, packages or use the update script?
updates through webuit
- Did you modify any scripts or configs? If yes, please attach the changes.
no
- Please provide a screenshot of `glances` and `htop`.
![image](https://github.com/telekom-security/tpotce/assets/18407412/7b321825-05c8-4e05-898f-35fafde83b06)
![image](https://github.com/telekom-security/tpotce/assets/18407412/8c279da1-134f-4c25-bf98-17dfaed5414a)

- How much free disk space is available (`df -h`)?
![image](https://github.com/telekom-security/tpotce/assets/18407412/597cff36-ac2b-4f09-a2cb-1278fb8f5d57)

- What is the current container status (`dps.sh`)?

![image](https://github.com/telekom-security/tpotce/assets/18407412/7d910995-7f7b-464c-b7b1-789bfb8dcdd2)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://github.com/telekom-security/tpotce/assets/18407412/eeea7ae7-f1ef-477b-b1d8-a075a8a485ee)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
NA
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
NA

all services cease to function unless host is rebooted or an existing cockpit window is open and the system journal flush is restarted. 
![image](https://github.com/telekom-security/tpotce/assets/18407412/2dadb0ae-595d-4136-937c-d68abfd293d5)
Performing a "docker restart ddospot" resolves the memory leak temporarily. 
![image](https://github.com/telekom-security/tpotce/assets/18407412/6bd02b79-5e26-4175-ad54-2b8c0f8e03d1)
![image](https://github.com/telekom-security/tpotce/assets/18407412/b63dcd67-24ee-4914-af58-bdc5b013f4ec)

**Comment by t3chn0m4g3** [comment]
Thanks. Based on the information it seems that the reason for the memory leak is caused by opening Cockpit. The Cockpit feature will be removed in the next release of T-Pot.
Right now there is nothing we can do, if you think [Ddospot](https://github.com/aelth/ddospot) is responsible, please open an issue on their repository, once fixed we can include the changes made.

**Comment by LFBernardo** [comment]
Thanks, will remove it from my config
