### ISSUE TITLE
Blank cockpit

### ISSUE THREAD

**Issue by evoke0** [telekom-security/tpotce#1451]
Fresh post-install in debian 11, all honeypots work as expected. After logging in with the credentials for the cockpit, it usually shows a blank screen, no sidebars or anything; if I refresh on that state, I can see the sidebars and menus but no content inside any, at all.
![image](https://github.com/telekom-security/tpotce/assets/59049954/3f1cb42c-3367-45ed-a6ba-24b20c4c9d4c)

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

lsb_release -a:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

uname -a

`Linux eventualpoison 5.10.0-26-arm64 #1 SMP Debian 5.10.197-1 (2023-09-29) aarch64 GNU/Linux`

- What T-Pot version are you currently using?
Latest available, the instalation is 24h old.
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
It's running on a cloud provider with a 4-core arm processor and 24GB RAM with 150GB of storage.
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No, the only error I can see is in `install.err` and is the following part:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: request@3.0.1
npm WARN node_modules/elasticdump/node_modules/request
npm WARN   request@"npm:@cypress/request@^3.0.1" from elasticdump@6.110.0
npm WARN   node_modules/elasticdump
npm WARN     elasticdump@"*" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer request@"2.*.*" from requestretry@7.1.0
npm WARN node_modules/elasticdump/node_modules/requestretry
npm WARN   requestretry@"^7.1.0" from elasticdump@6.110.0
npm WARN   node_modules/elasticdump
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
WARNING: glances 3.4.0.3 does not provide the extra 'docker'
```

- How long has your installation been running?
24 hours
- Did you install upgrades, packages or use the update script?
No, just a fresh upgrade of the OS with just a few packages to update and installed htop.
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
![image](https://github.com/telekom-security/tpotce/assets/59049954/b0b6abe4-d51c-41e6-bf8f-f4433e693c58)
![image](https://github.com/telekom-security/tpotce/assets/59049954/2596e602-b560-40b8-aba0-c49ba9556642)
- How much free disk space is available (`df -h`)?
```
Filesystem      Size  Used Avail Use% Mounted on
udev                12G     0      12G   0% /dev
tmpfs              2.4G  4.1M  2.4G   1% /run
/dev/sda1       148G 12G   131G   8% /
tmpfs              12G     0      12G   0% /dev/shm
tmpfs              5.0M   0      5.0M   0% /run/lock
/dev/sda15    127M  148K  127M   1% /boot/efi
tmpfs             2.4G     0  2.4G   0% /run/user/1000
```
- What is the current container status (`dps.sh`)?
![image](https://github.com/telekom-security/tpotce/assets/59049954/138e1043-929e-4fb8-ba83-3a515ac5d077)
Everything looks fine
- What is the status of the T-Pot service (`systemctl status tpot`)?
Active and running without issues.
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0               0.0.0.0:64295              0.0.0.0:*               LISTEN      0                11953      734/sshd: /usr/sbin 
tcp        0      0               127.0.0.1:34893         0.0.0.0:*               LISTEN      0                 2941       717/containerd      
tcp6      0      0               :::64294                            :::*                    LISTEN      0                12924      1/init              
tcp6      0      0               :::64295                            :::*                    LISTEN      0                11955      734/sshd: /usr/sbin 
udp       0      0              0.0.0.0:68                     0.0.0.0:*                                 0                10833      552/dhclient  
```
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
We use the Cockpit package as provided by Debian and change the port.
Since the functionality declined over the years, i.e. Docker support is no longer provided, we already dropped Cockpit support in the dev branch.
Unfortunately there is nothing we can do other than recommend to check with the Cockpit Project what the issue might be.
Thanks for taking the time to gather enough info for the issue and we you like T-Pot.
