### ISSUE TITLE
SSH access is lost in post-install for Ubuntu

### ISSUE THREAD

**Issue by evoke0** [telekom-security/tpotce#1457]
**Is your feature request related to a problem? Please describe.**
After deciding to perform a fresh post-installation on Ubuntu 22.04 in Oracle Cloud Infrastructure (OCI), I encountered an issue where I couldn't access it using port 64295. I ensured that I used the OS user (also tried "tsec", just in case) and a private key for authentication. However, I kept receiving a "no route to host" error. Upon researching, I found that this error is sometimes associated with firewall issues, which is misleading. OCI has compatibility issues with its VMs' firewalls and UFW (the default firewall management tool in Ubuntu).

To provide more context, when using UFW, the rules don't take effect due to compatibility problems with OCI's VM firewalls. Consequently, you have to disable UFW and utilize the VM firewall in OCI's admin panel. Even after, no access is possible.

Although I examined the installer script in /preview/ubuntu, I couldn't identify where the new rules for port 64295 were added.

**Describe the solution you'd like**
 To regain access, I discovered a workaround by modifying the `/etc/iptables/rules.v4` file. I replaced the rule for port 22 with the one for port 64295, and this allowed me to successfully log back in.

Maybe it is a good idea to add such rule to the script for better compatibility across systems that use iptables?

`nano /etc/iptables/rules.v4`

~~-A INPUT -p tcp -m state --state NEW -m tcp --dport  22 -j ACCEPT~~
-A INPUT -p tcp -m state --state NEW -m tcp --dport  64295 -j ACCEPT

**Additional context**
I know this may sound more like an issue with Oracle's cloud services, but as you probably know, UFW comes disabled by default and OCI VMs' firewalls are just like your router's, so the problem really exists with Ubuntu and how the installer script manages access to the port.

**Comment by t3chn0m4g3** [comment]
Ubuntu is only supported in the dev version which takes care of SSH access on tcp/64295.
