### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by nsk** [telekom-security/tpotce#1468]
**Is your feature request related to a problem? Please describe.**

hello, I only knew t-pot just after the RaspberryPi images, would you one day provide a version for PI again, given the progress of the latest models??

Thanks a lot to you

**Comment by t3chn0m4g3** [comment]
You should check out the dev branch. Raspberry Pi is supported in the next version of T-Pot.
You might need to adjust the `docker-compose` file though as 8GB really scratches the limits. A Pi 5 with NVMe and 8GB of RAM is recommended.
Really hope to see a 16GB version.

Coming soon ...
![image](https://github.com/telekom-security/tpotce/assets/4318452/b39c533d-a8d5-415c-ba0b-4ccf7a9061de)
