### ISSUE TITLE
[DEV] Docker Installation Fails on Ubuntu Due to Incorrect Architecture Naming in Ansible Playbook

### ISSUE THREAD

**Issue by shark4ce** [telekom-security/tpotce#1472]
## Summary

Attempting to install the T-Pot platform on Ubuntu results in a failure during the Docker Engine installation step, with an error indicating that the package `docker-ce` is not available. The root cause is identified as incorrect architecture naming in the Ansible playbook (`tpot.yml`), specifically in the task that adds the Docker Engine repository for Debian, Raspbian, and Ubuntu environments.

## Environment

- **Branch**: `dev`
- **OS**: Ubuntu 22.04.3 LTS Server Edition
- **Playbook**: [tpot.yml](https://github.com/telekom-security/tpotce/blob/dev/installer/install/tpot.yml)

## Issue Description

During the T-Pot installation, the Ansible playbook fails to install Docker Engine due to the repository configuration not recognizing `x86_64` as a valid architecture, which Docker expects to be named `amd64`. The affected task is ["Add Docker Engine repository (Debian, Raspbian, Ubuntu)"](https://github.com/telekom-security/tpotce/blob/2fe2d591296050685be42f0f43205f1d4b5f720c/installer/install/tpot.yml#L280), which lacks the necessary normalization of `ansible_architecture` from `x86_64` to `amd64`.

## Reproduction Steps

1. Run `install.sh` on an Ubuntu system.
2. Observe the failure during the Docker Engine installation phase.

## Expected Behavior

To ensure compatibility across all supported architectures, the playbook must include the normalization of `x86_64` to `amd64` for the Docker Engine repository configuration. Currently, while normalizations for other architectures are in place, this specific conversion is absent. Adding it will guarantee the availability of the `docker-ce` package for installation on systems using the `x86_64` architecture.

## Actual Behavior

The playbook fails to find the `docker-ce` package due to incorrect repository configuration, resulting in the error: `"msg": "No package matching 'docker-ce' is available"`.

## Screenshot

![image](https://github.com/telekom-security/tpotce/assets/46487296/542e82ef-2cec-41b4-9685-174a0a4ae033)

## Suggested Fix

Modify the playbook to include normalization from `x86_64` to `amd64` for the Docker Engine repository configuration step:

```yaml
- name: Add Docker Engine repository (Debian, Raspbian, Ubuntu)
  repo: "deb [arch={{ ansible_architecture | regex_replace('^(aarch64)$', 'arm64') | regex_replace('^(x86_64)$', 'amd64') }}...

**Comment by t3chn0m4g3** [comment]
@shark4ce Thanks for taking the time to test, debug and the solution!
Just pushed the fix, please let me know if this works now.

Thank you!

**Comment by shark4ce** [comment]
@t3chn0m4g3 Yes, it is working. Thank you!

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback @shark4ce!
