### ISSUE TITLE
Attack Map Issue

### ISSUE THREAD

**Issue by tssingtampa** [telekom-security/tpotce#1475]
<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Iso installation on virtual box

- What T-Pot version are you currently using?
T-Pot 22.0.4
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
ISO T-Pot 22.04.0
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
ISO T-Pot 22.04.0
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
No much time.
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
![image](https://github.com/telekom-security/tpotce/assets/142441903/b0de9f39-f28d-45b4-8b0c-4b9d77760acb)
![image](https://github.com/telekom-security/tpotce/assets/142441903/7b7f1cec-11d4-4664-b17e-9a66d7b175a5)

- How much free disk space is available (`df -h`)?
![image](https://github.com/telekom-security/tpotce/assets/142441903/6fe34a68-735f-4fa1-b26c-48a83afdca4f)

- What is the current container status (`dps.sh`)?
![image](https://github.com/telekom-security/tpotce/assets/142441903/3f759c7e-12d9-4868-917c-f654cb5e17dc)

- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
no

- Issue:
The problem is that the attack map does not load, when it has little data (after a snapshot) the attacks load after it is working when you start the map again, it does not work again. I would like to know if there is any solution, thank you.
![image](https://github.com/telekom-security/tpotce/assets/142441903/566357a3-6b4e-4a6e-bda2-6a6ecc04ea18)
![image](https://github.com/telekom-security/tpotce/assets/142441903/574b2c89-68fd-460d-b3be-3cc9a191b333)

**Comment by t3chn0m4g3** [comment]
Based on the screenshots this seems like an older version of the attack map. The latest version which is part of 22.04 does have Connection Awareness built in and shows it with a caption on the upper left with either red or green text.
What do you see when running `docker logs map_web`, `docker logs map_data`?
