### ISSUE TITLE
Error message when making USB boot drive using Etcher

### ISSUE THREAD

**Issue by Dartellum** [telekom-security/tpotce#1481]
Hello,

I pulled down the latest release from here: https://github.com/telekom-security/tpotce/releases/download/22.04.0/tpot_amd64.iso and this error pops up using BalenaEtcher:
![image](https://github.com/telekom-security/tpotce/assets/21960540/94e867d5-9b22-4165-8172-2522eeefa7b7)

We tried to boot from it but it does not work. Do I need to make my own from source? Or, do I install Debian Netinstall Image first?

**Comment by t3chn0m4g3** [comment]
Thanks for reporting. The AMD64 iso files and the `makeiso.sh` have been updated.
