### ISSUE TITLE
error while executing deploy.sh

### ISSUE THREAD

**Issue by whitepoll** [telekom-security/tpotce#1484]
hello everyone
at the end of executing the deployment scritp I get this error returned. I installed the tpot hive sensor on a debian 11 machine as per the guide
how can i fix it?
thanks
![image](https://github.com/telekom-security/tpotce/assets/154346469/5babb65a-03f6-44f1-9491-fd97d4502592)

**Comment by t3chn0m4g3** [comment]
Follow and post in the discussion #1153 for debugging.

Heads up: This type of distributed install will be deprecated with T-Pot 24.x in favour of a more manageable solution.
