### ISSUE TITLE
Prevent to kick myself out of SSH after Port changing

### ISSUE THREAD

**Issue by EvilWatermelon** [telekom-security/tpotce#1497]
It happend recently that I kicked myself out of the VM after installing T-Pot because I forgot allow the new UFW rules in order to get access after a successful installation. 
I would like to request a Shellscript or something similar that asks for permissions to add the common T-Pot Ports for the Post Installation User Method.

**Comment by t3chn0m4g3** [comment]
T-Pot 22.04 is almost EOL. See #1487 for more info including details to test the 24.04.0beta.
