### ISSUE TITLE
Dionaea UPnP and MQTT

### ISSUE THREAD

**Issue by EvilWatermelon** [telekom-security/tpotce#1503]
I saw in the Dockerfile of Dionaea that upnp and mqtt exists but the Port of upnp is not in the docker-compose, the mqtt yml seems to be incomplete and there is no `yaml` for upnp like [here](https://github.com/DinoTools/dionaea/blob/master/conf/services/upnp.yaml.in). Are these missing features? - I would like to have it because I need IoT Botnet traffic.

**Comment by EvilWatermelon** [comment]
I installed another HIVE and after the initial reboot the attack map worked fine except that the geo location is wrong and as long as I use the default `docker-compose.yml` the src IPs are captured too. But when I create a custom yml then I do not see attack map visualizations and not src IP in my chosen Honeypots.

**Comment by t3chn0m4g3** [comment]
We ship T-Pot in the configuration we see is the most compatible. You can adjust all settings and configs on your end as you see fit best your setup.

**Comment by EvilWatermelon** [comment]
Do you know how the `yaml` need to look like in order to add upnp from the dionaea repo?
