### ISSUE TITLE
Problem with daily reboot

### ISSUE THREAD

**Issue by Luis-Muga** [telekom-security/tpotce#1508]
After every reboot some services go down and I have to login and restart the tpot.service mannually. 
I get this from dps.sh after rebooting.
![image](https://github.com/telekom-security/tpotce/assets/163993494/4f71eb59-1756-4e33-ae16-06a6d3e51c13)
Aparently right after rebooting some veth fail to link.
![image](https://github.com/telekom-security/tpotce/assets/163993494/4a268cce-77d0-4142-ba16-c1ad0067ca31)

Once I restart the service everything works fine again.
Is there a way to prevent services from going down after rebooting?

**Comment by t3chn0m4g3** [comment]
Everything looks as expected. Kibana, Logstash and Map_Data are only coming up after Elasticsearch has finished starting up successfully.
