### ISSUE TITLE
Error with mirror server?

### ISSUE THREAD

**Issue by cc374-ual** [telekom-security/tpotce#1509]
Hello!
Some time ago there was a problem with mirror servers. It was impossible to install T-Pot using the ISO Image.
This afternoon I spent some hours trying to install T-Pot from ISO but again I have problems with mirror server.
Is it an bug again or It´s my problem?
Thank you for answering!
![mirror](https://github.com/telekom-security/tpotce/assets/72391616/b6b6502b-65f4-46e0-8e96-a9dbb13e6f46)

**Comment by t3chn0m4g3** [comment]
Thanks, it is related to the ISO image. However, at this point we will no longer fix this issue and recommend to use either the post install method or use 24.04 beta.
T-Pot 24.04 final will be released 2024-04-22.
