### ISSUE TITLE
I can nat connect after installation/reboot via https:MYIP:64297 

### ISSUE THREAD

**Issue by onurhany** [telekom-security/tpotce#1521]
# Successfully raise an issue
Before you post your issue make sure it has not been answered yet and provide **⚠️ BASIC SUPPORT INFORMATION** (as requested below) if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki) and the [discussions](https://github.com/telekom-security/tpotce/discussions)
- 📚 Consult the documentation of 💻 your Linux OS, 🐳 [Docker](https://docs.docker.com/), the 🦌 [Elastic stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [BASIC SUPPORT INFORMATION](#-basic-support-information-commands-are-expected-to-run-as-root) or similar detailed information with regard to your issue or we will close the issue or convert it into a discussion without further interaction from the maintainers**.<br>

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- What OS are you T-Pot running on?
- What is the version of the OS `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
- How long has your installation been running?
  - If it is a fresh install consult the documentation first.
  - Most likely it is a port conflict or a remote dependency was unavailable.
  - Retry a fresh installation and only open the issue if the error keeps coming up and is not resolved using the documentation as described [here](#how-to-raise-an-issue).  
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `htop` and `docker stats`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `grc netstat -tulpen`
  - Stop T-Pot `systemctl stop tpot`
  - Run `grc netstat -tulpen`
  - Run T-Pot manually with `docker compose -f ~/tpotce/docker-compose.yml up` and check for errors
  - Stop execution with `CTRL-C` and `docker compose -f ~/tpotce/docker-compose.yml down -v`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by onurhany** [comment]
![h1](https://github.com/telekom-security/tpotce/assets/33685455/5d34d398-c761-42e7-bda2-41cb928b279c)
![h2](https://github.com/telekom-security/tpotce/assets/33685455/2568fc24-9fce-43fc-a18d-da9e2164c962)
tpod version:24.04.0
![h3](https://github.com/telekom-security/tpotce/assets/33685455/3c5724ee-4c48-4e11-a53a-c03efdba0886)
![h5](https://github.com/telekom-security/tpotce/assets/33685455/dfe89e9d-3239-4ecb-ad41-baa2cf2f8456)

**Comment by t3chn0m4g3** [comment]
Please follow the [Troubleshoot](https://github.com/telekom-security/tpotce?tab=readme-ov-file#troubleshooting) section. Based on the screenshots it is not possible to assess what is going on. Also, answer the questions for raising an issue. Thanks.
