### ISSUE TITLE
Ubuntu 24.04 moved from exa to eza

### ISSUE THREAD

**Issue by iRoot13x18** [telekom-security/tpotce#1525]
# Successfully raise an issue
Before you post your issue make sure it has not been answered yet and provide **⚠️ BASIC SUPPORT INFORMATION** (as requested below) if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki) and the [discussions](https://github.com/telekom-security/tpotce/discussions)
- 📚 Consult the documentation of 💻 your Linux OS, 🐳 [Docker](https://docs.docker.com/), the 🦌 [Elastic stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- ⚙️ The [Troubleshoot Section](https://github.com/telekom-security/tpotce?tab=readme-ov-file#troubleshooting) of the [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md) is a good starting point to collect a good set of information for the issue and / or to fix things on your own.
- **⚠️ Provide [BASIC SUPPORT INFORMATION](#-basic-support-information-commands-are-expected-to-run-as-root) or similar detailed information with regard to your issue or we will close the issue or convert it into a discussion without further interaction from the maintainers**.<br>

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- Ubuntu Server 22.04 live server
- Ubuntu 24.04 LTS
- T-Pot 24.04.0
- VM VirtualBox
![Captura de pantalla 2024-04-27 185512](https://github.com/telekom-security/tpotce/assets/122999018/2f0862d1-5412-4cdf-a968-9976cc0b62ad)

- less 60 secs
  - If it is a fresh install consult the documentation first.
  - Most likely it is a port conflict or a remote dependency was unavailable.
  - Retry a fresh installation and only open the issue if the error keeps coming up and is not resolved using the documentation as described [here](#how-to-raise-an-issue).  
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `htop` and `docker stats`.
- 19GB

**Comment by t3chn0m4g3** [comment]
Thanks, seems `exa` was replaced by `eza`.

**Comment by iRoot13x18** [comment]
I forgot to mention it, I installed eza because I read something like that and it keeps giving me an error.

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this on the recommended Ubuntu 22.04 live server image, `exa` works perfectly fine here.

**Comment by iRoot13x18** [comment]
I'll try it, I downloaded the image from the official ubuntu site

**Comment by JorgeVerdura** [comment]
Good afternoon. 
It seems "exa" is out of the official repository's on ubuntu 22.04, and now is "eza" the maintain one. 
Fresh install with a iso from the official page 

last lines on the installation log. 
![image](https://github.com/telekom-security/tpotce/assets/24916386/a71babfd-ffb3-4277-9124-430c08d8bf86)
and the apt result
![image](https://github.com/telekom-security/tpotce/assets/24916386/a56d1ebe-5533-4f94-b09f-654c29ffcd39)
.

**Comment by shashipapa** [comment]
plz include the iso file

**Comment by t3chn0m4g3** [comment]
Ubuntu 22.04 works still fine with `exa`.

![image](https://github.com/telekom-security/tpotce/assets/4318452/cc2a05bd-67ff-4efd-b05c-c2e48a3c687c)

**Comment by t3chn0m4g3** [comment]
@iRoot13x18 : Installation will now work with Ubuntu 24.04 as well.
