### ISSUE TITLE
Tpot Ram showing 4GB but I have assigned 16 GB ram

### ISSUE THREAD

**Issue by idforfast** [telekom-security/tpotce#1526]
Tpot Ram showing 4GB in Elasticvue but I have assigned 16 GB RAM and its showing 16 gm RAM in Cockpit.

![tpot ram 2](https://github.com/telekom-security/tpotce/assets/140324774/d12aad77-793a-47fb-bc31-c24573485420)
![tpot ram issue](https://github.com/telekom-security/tpotce/assets/140324774/35c0ba59-ed83-403d-90eb-725eb96fe608)

**Comment by t3chn0m4g3** [comment]
This correct, by default we only assign 4GB to Elasticsearch.
