### ISSUE TITLE
install error in task add aliases with exa in rocky linux 9

### ISSUE THREAD

**Issue by oliverbs23** [telekom-security/tpotce#1540]
In the install process I have the fallowing error:
 
fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'exa_install_result is succeeded and ansible_distribution in [\"AlmaLinux\", \"Debian\", \"Fedora\", \"openSUSE Tumbleweed\", \"Raspbian\", \"Rocky\", \"Ubuntu\"]' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to be in '/var/opt/tpotce/installer/install/tpot.yml': line 703, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Add aliases with exa (All)\n      ^ here\n"}

I don't know what I should check in this case.
In Rocky Linux the exa package is installed with the name eza and  it appears in the path /var/opt/tpotce/installer/install/tpot.yml

**Comment by t3chn0m4g3** [comment]
Thanks for reporting. Just pushed the fix. Works fine here, please let us know if it is solved for you as well. Thx.

**Comment by oliverbs23** [comment]
> Thanks for reporting. Just pushed the fix. Works fine here, please let us know if it is solved for you as well. Thx.

Thanks for the help. it worked perfectly!!!

**Comment by t3chn0m4g3** [comment]
Awesome. Thanks for the feedback!
