### ISSUE TITLE
T-pot WebUI connection failed (64297 - 64295)

### ISSUE THREAD

**Issue by LyCrash** [telekom-security/tpotce#1542]
I have successfully installed the latest T-pot version on a debian VM (Vmware Workstation 17) following the exact TL;DR instructions ( curl the installer not manual nor through tpot iso). After rebooting the system, I checked that ssh, tpot, docker are all active and running, but when I try to login from the browser (firefox) and access the T-Pot WebUI and tools with my private ip address (https://192.168.1.34:64297), I get that the website isn't availabe:
![image](https://github.com/telekom-security/tpotce/assets/105780678/8239db7f-26df-467d-98b1-5603a179c9bd)

But if I enter on localhost  (https://127.0.0.1:64297), I get the first loading page, but accessing other links (attackmap, cyberchef, elasticvue, kibana, spiderfoot) would lead to the same issue (connection failed)
![image](https://github.com/telekom-security/tpotce/assets/105780678/ceeac32a-e509-401b-ac0d-d05ca1548cbb)

Note that I can access remotly through ssh :
![image](https://github.com/telekom-security/tpotce/assets/105780678/13b31c5e-e494-418e-8241-24cd354ef6bb)

- What OS are you T-Pot running on?
--> Debian 12 (iso installed from your github readme x64)
- What is the version of the OS `lsb_release -a` and `uname -a`?
![image](https://github.com/telekom-security/tpotce/assets/105780678/39f37498-e7dc-4816-9efa-8b6c4f2d6168)
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
--> T-Pot 24.04.0
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
--> HIVE = Standard
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
--> no such a file
- How long has your installation been running?
--> This is what I did: Retry a fresh installation and only open the issue if the error keeps coming up and is not resolved using the documentation as described [here](#how-to-raise-an-issue).  
- Did you install upgrades, packages or use the update script?
--> No, I only followed TL;DR installer
- Did you modify any scripts or configs? If yes, please attach the changes.
--> No
- Please provide a screenshot of `htop` and `docker stats`.
- htop:
![image](https://github.com/telekom-security/tpotce/assets/105780678/f4bb3dd5-fc0a-4626-be42-269d7e3f93ba)
- docker stats: (this is only the first lines but the list is longer)
![image](https://github.com/telekom-security/tpotce/assets/105780678/c6f1927d-d725-48f8-aaf8-d834f2968630)

- How much free disk space is available (`df -h`)?
![image](https://github.com/telekom-security/tpotce/assets/105780678/c9291845-480b-48c1-a865-0c1f3d8e588c)

- What is the current container status (`dps`)?
![image](https://github.com/telekom-security/tpotce/assets/105780678/3d260b80-2ba8-47a6-b986-705e4e3e2d36)

- Status Of T-Pot service:
![image](https://github.com/telekom-security/tpotce/assets/105780678/d98133ad-5ff9-4a29-8ad0-4871718ab75b)

- Status of Docker service:
![image](https://github.com/telekom-security/tpotce/assets/105780678/eac9cb6e-8818-4d9f-9f1b-06375937f07f)

**Comment by t3chn0m4g3** [comment]
Based on the description it seems the VM is setup as host only, it should use bridge mode.

**Comment by LyCrash** [comment]
> Based on the description it seems the VM is setup as host only, it should use bridge mode.

VM is already set to be bridged (not host-only nor NAT)

**Comment by t3chn0m4g3** [comment]
Works completely fine in VirtualBox, Parallels, VMware and UTM. Even followed up on host mode which works fine as well.
Other than VMNet routing on your host or routing in general I cannot think of anything else.
