### ISSUE TITLE
Challenges with Deploying Sensor to the Hive after upgrading from version 22.04.0 to 24.04.0

### ISSUE THREAD

**Issue by tcpguy** [telekom-security/tpotce#1544]
Hello guys, Here is a brief background. I had a well-running distributed system running on version Tpot 22.04.0. A power issue occurred that caused shard failure and therefore troubleshooting via reconfiguring logstash. In the processes I upgraded the hive via update.sh and that was where I had issues to do with being unable to access the Tpot landing page via [IP]:64297. I managed to fix this by disabling the cockpit.socket and cockpit.service after realizing that port 64294 was conflicting with NGINX. 
![port conflict](https://github.com/telekom-security/tpotce/assets/168958680/cb4b00db-bccb-4c4b-af69-064e506bcf2e)

Now I was able to access the page and access default dashboards and attack maps but I had to set up my custom dashboards as a result of the upgrade. Also, the existing remote sensors that were never upgraded are transmitting logs to the hive without redeploying them. 

The problem I am facing now is that I have this one sensor that I also upgraded from version 22.04.0 to 24.04.0 that failed to deploy as described in distributed deployment giving an unreachable error. 
<img width="948" alt="Sensor deploy error" src="https://github.com/telekom-security/tpotce/assets/168958680/e0f363f4-882e-4117-9800-bae8bea79300">

I only managed to deploy it manually as described in the .env file. 
<img width="764" alt="SENSOR CONFIG" src="https://github.com/telekom-security/tpotce/assets/168958680/d13d119e-28d1-4b92-96a9-0065dd711f68">

However, the problem is that anytime the hive reboots or Tpot services restart, it clears the sensor entries in the lswebpasswd file and therefore the sensor cannot connect to the hive. 
<img width="954" alt="sample sensor error 401 logs" src="https://github.com/telekom-security/tpotce/assets/168958680/f27bcad4-3bf6-4157-83f3-5f71e283fd89">

So for it to send logs to the hive, I have to run the command (htpasswd ~/tpotce/data/nginx/conf/lswebpasswd <user>) or else I get the authentication error 401. Therefore, help me have a lasting solution for this. I can't be doing this every time especially when we have T-Pot Daily Reboot.

Alternatively, is there a way to configure the sensor not to require authentication when connecting to the Hive?

- What OS are you T-Pot running on? Debian GNU/Linux 11 (bullseye)
- What is the version of the OS `lsb_release -a` and `uname -a`? Linux user 5.10.0-29-amd64 #1 SMP Debian 5.10.216-1 (2024-05-03) x86_64 GNU/Linux
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)? 24.04.0
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? VM
- Review the `~/install_tpot.log`, attach the log and highlight the errors. No errors
- How long has your installation been running? 10 days since upgrading
  - If it is a fresh install consult the documentation first.
  - Most likely it is a port conflict or a remote dependency was unavailable.
  - Retry a fresh installation and only open the issue if the error keeps coming up and is not resolved using the documentation as described [here](#how-to-raise-an-issue).  
- Did you install upgrades, packages or use the update script? Yes 
- Did you modify any scripts or configs? If yes, please attach the changes. No
- Please provide a screenshot of `htop` and `docker stats`. Normal
- How much free disk space is available (`df -h`)? Good
- What is the current container status (`dps`)? Up and healthy
- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)? active (running)

**Comment by t3chn0m4g3** [comment]
Recommend to do a fresh Hive and Sensor install. Unless you fix the problem with SSH (as per your screenshot) the sensor will neither be deployed nor will it ever transmit logs correctly. `nginxpasswd` and `lswebpasswd` are being rewritten intentionally on every T-Pot Start based on the `.env` settings.

**Comment by tcpguy** [comment]
Hey, considering that fresh installation requires proper planning and testing and also upgrading to a higher version is just a click away with just a notification.  So, are you able to reproduce this issue of upgrading in your test environment and see if you can resolve something?

This might save time for those of us facing similar challenges.

**Comment by tcpguy** [comment]
By the way, i managed to fix it by manually adding ls_web_user of the troubled sensor in the HIVE's .env config.
