### ISSUE TITLE
Tip for installation when there are user problems.

### ISSUE THREAD

**Issue by crocodyli** [telekom-security/tpotce#1556]
If you are connected via root in the ssh terminal, I recommend that you log out and log in to the new user created or user used to run and install tpot. 

If you are rooted, it will display the following error: 

###Now downloading T-Pot Ansible Installation Playbook ...
tpot.yml: Permission denied
###‘sudo‘ acquired, setting ansible become option to --become.
###Now running T-Pot Ansible Installation Playbook

Just log out of the root user and log in with the non-root user. 

Run the command with curl and be happy :)

**Comment by t3chn0m4g3** [comment]
As mentioned in the [ReadMe](https://github.com/telekom-security/tpotce?tab=readme-ov-file#tldr) 😁
