### ISSUE TITLE
Tanner "Detection Type" shows only index, unknown and xss

### ISSUE THREAD

**Issue by djoker77** [telekom-security/tpotce#1560]
# Successfully raise an issue
Before you post your issue make sure it has not been answered yet and provide **⚠️ BASIC SUPPORT INFORMATION** (as requested below) if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki) and the [discussions](https://github.com/telekom-security/tpotce/discussions)
- 📚 Consult the documentation of 💻 your Linux OS, 🐳 [Docker](https://docs.docker.com/), the 🦌 [Elastic stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- ⚙️ The [Troubleshoot Section](https://github.com/telekom-security/tpotce?tab=readme-ov-file#troubleshooting) of the [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md) is a good starting point to collect a good set of information for the issue and / or to fix things on your own.
- **⚠️ Provide [BASIC SUPPORT INFORMATION](#-basic-support-information-commands-are-expected-to-run-as-root) or similar detailed information with regard to your issue or we will close the issue or convert it into a discussion without further interaction from the maintainers**.<br>

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- What OS are you T-Pot running on? Debian 12
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)? T-Pot 24.04
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? VM
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
- How long has your installation been running? fresh install
- Did you install upgrades, packages or use the update script? No
- Did you modify any scripts or configs? If yes, please attach the changes. Yes, deactivated every Honeypot except for Snare/Tanner, Tools were left as they were.
- What is the current container status (`dps`)? VM is currently shut down
- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)? VM is currently shut down
Hello everyone,
I have a quick question about the results of the Snare/Tanner Honeypot. On the Kibana dashboard, I see that the Tanner Sensor only detected XSS attacks, while categorizing the rest as index or unknown. However, when I analyzed the log data, I found that other attack techniques were also conducted on the honeypot. Do you know why this is happening?
I would greatly appreciate any feedback, as I am currently working on my bachelor's thesis and need to validate the results of the T-POT system. I am unsure why the results turned out this way. Maybe I did something wrong, but I didn't change anything besides the config file and added a custom Snare page for my use case. I also tried it with the default pages provided, same result. Any insights that I can include in my thesis would be extremely helpful.
Thank you very much in advance and a nice weekend!

**Comment by djoker77** [comment]
![image](https://github.com/telekom-security/tpotce/assets/169622154/9a16f2d3-122e-4e2a-8dba-c3c22959e5cc)
Hi,
sure, in the picture above you can see the diagram i meant, the expectation was to see many more techniques such as SQLi, RFI/LFI or XXE. The example logs you can see here (some fields i blackened for security reasons) If you need some more, just let me know
![Screenshot 2024-06-01 153815](https://github.com/telekom-security/tpotce/assets/169622154/87e0a5f1-0ed2-40ba-8515-9ee0b97e5783)

![Screenshot 2024-06-01 154545](https://github.com/telekom-security/tpotce/assets/169622154/7e084e79-6bc0-4bb7-966b-1853daa6b6a0)

**Comment by t3chn0m4g3** [comment]
Based on the logs you provided everything works as expected. All the logs you provided indicate type `index` for the `detection` field. In consequence Kibana will only these types.

**Comment by djoker77** [comment]
Okey strange, do you know what could be the reason for this? Because I have also tried other attack techniques but tanner does not recognise them accordingly

**Comment by t3chn0m4g3** [comment]
At this point I recommend to open an upstream issue with the [developers](https://github.com/mushorg) of snare / tanner.

**Comment by djoker77** [comment]
All right, thank you very much for your time. Could you find more than just XSS-Attacks or. would Tanner normaly detect more attack types?
