### ISSUE TITLE
Need help configuring my CitrixHoneypot Docker File to include my SSL lets encrypt Certificate 

### ISSUE THREAD

**Issue by FloppyDucks** [telekom-security/tpotce#1561]
- What OS are you T-Pot running on?
**_Debian 12 - bookworm_**
- What is the version of the OS `lsb_release -a` and `uname -a`?
**_Linux blackwaters.org 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux_**
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
_**TPOT 24.04.x**_
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
**_cloud provider is linode, and Im 99% sure its running on a VM , so both cloud and VM_**
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
**_no errors, it installs fine and runs fine._**
**_2024-05-29 14:39:30,354 p=1253 u=TPOT n=ansible | PLAY RECAP ***************************************************************************************************************************************************>2024-05-29 14:39:30,354 p=1253 u=TPOT n=ansible | 127.0.0.1                  : ok=36   changed=18   unreachable=0    failed=0    skipped=3    rescued=0    ignored=0_**
- How long has your installation been running?
**_I start and stop it alot but about a day now._**
  - If it is a fresh install consult the documentation first.
  **_I have consulted the documentation and the online issues and have not found any thing related to Citrixhoneypot, only nginx (which i was able to configure)_**
  - Most likely it is a port conflict or a remote dependency was unavailable.
  **_The service runs just fine, it just that the Citrixhoney pot docker doesnt recognize the certificate and priv key file that I gave it in the docker file, and yml_**
  - Retry a fresh installation and only open the issue if the error keeps coming up and is not resolved using the documentation as **_described [here](#how-to-raise-an-issue).  
I did this and it did not fix my issue sadly_**
- Did you install upgrades, packages or use the update script?
**_yes I have changed configuration scripts and yml scripts will attach below_**
- Did you modify any scripts or configs? If yes, please attach the changes.
**_yes I have changed configuration scripts and yml scripts will attach below_**
- Please provide a screenshot of `htop` and `docker stats`.
**_attached below_**
- How much free disk space is available (`df -h`)?
_**plenty of room**_
- What is the current container status (`dps`)?
_**fine, tbh not sure and have no idea where to find this dps**_
- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)?
active, running, working just fine
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `grc netstat -tulpen`
_**attached below**_
  - Stop T-Pot `systemctl stop tpot`
  **_I do this AT least once an hour :) for testing and debugging_**
  - Run `grc netstat -tulpen`
 **_same ports pop up all is fine_**
  - Run T-Pot manually with `docker compose -f ~/tpotce/docker-compose.yml up` and check for errors
  _**yep works like a charm**_
  - Stop execution with `CTRL-C` and `docker compose -f ~/tpotce/docker-compose.yml down -v`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
_**no issues**_

_**Now for the meat and potatoes my real issue is my inability to set up my ssl certificate for the citrixhoneypot over 443. I was able to set up my ssl cert for 64297 for the nginx. So I set up the ssl cert for the nginx management portal using a letsencrypt ssl cert.  So I figured when I went to go and set up an ssl cert for 443 it would be a similar process. I added in the Citrixdocker file a few extra lines to copy my ssl cert to /opt/citrixhoneypot/cert/ I also figured because I am using letsencrypts cert I wont need the self singed cert in the docker file , so I removed that. I made sure to add the paths in the volume area in the docker-compose-yml. Im not sure if the way  the honey pot is set for citrix its not supposed to have an ssl cert? or if it is? 

trouble shoot steps: I have tried to a lot of systemctl daemon-reload (tbh i dont think it does anything i do it for good luck) I also stop tpot when i make changes when to the configs/ yaml/ docker files.  then when I am finished with my modifications I run the daemon reload, docker compose up -d , then systemctl status tpot (make sure its actually down), systemctl start tpot. Then I load up a incognito tab and check to see if port 443 for my website has a valid ssl cert. and it doesn't. 
Then I will change the file permissions to give the certificate 777 file permission, because maybe the user citrixhoneypot cant read the cert and priv key, but that cant be it, because in my Docker file, as you will see I made sure (unless I did it wrong) to 1) give user citrixhoneypot ownership over /opt/citrixhoneypot (the path the cert lives in) and JUST IN CASE, I also made the path /opt/citrixhoneypot 774 file perm ....even tho there is no reason to overwrite a privkey and cert...any who.  If you know what I am missing or what I am doing wrong any help would be MUCH appreciated!

if I missed anything or forgot to add any files or need to add/clarify anything just let me know I check this documentation daily so I should see any msg's figured it was allowed to, because the python code said that http server is wrapping the socket in the ssl/tls layer. **_

[df -h.txt](https://github.com/user-attachments/files/15520855/df.-h.txt)
[docker stats.txt](https://github.com/user-attachments/files/15520856/docker.stats.txt)
[FULL-modded-docker-compose-yml.txt](https://github.com/user-attachments/files/15520857/FULL-modded-docker-compose-yml.txt)
![htop1](https://github.com/telekom-security/tpotce/assets/168114442/07158a3b-05f7-4e70-882b-3b52f994fb22)
![htop2](https://github.com/telekom-security/tpotce/assets/168114442/f320f414-1f24-4a01-b500-401db902d663)
[install_tpot_yaml.txt](https://github.com/user-attachments/files/15520858/install_tpot_yaml.txt)
[modded-citrixhoneypot-docker-compose-yml.txt](https://github.com/user-attachments/files/15520859/modded-citrixhoneypot-docker-compose-yml.txt)
[Modded-DockerFile.txt](https://github.com/user-attachments/files/15520860/Modded-DockerFile.txt)
[netstat.txt](https://github.com/user-attachments/files/15520861/netstat.txt)
![UGLY NET ERR CERT AUTHORITY INVALID](https://github.com/telekom-security/tpotce/assets/168114442/5286b400-5e1e-4d3e-a20e-1b71d35d46f0)
![working ssl for nginx mngmt portal](https://github.com/telekom-security/tpotce/assets/168114442/63d0e9f0-d3e4-4a80-b58e-663ea564fd82)

**Comment by FloppyDucks** [comment]
also If you want me to point out exactly where and what part of the code/script I changed I can do that, I neglected to do that in my first post, wasnt sure how long/ much you needed? I can go more in detail depending on how much you need?

**Comment by t3chn0m4g3** [comment]
Identify the `Dockerfile` in `docker/citrixhoneypot`, you will find all the necessary files / folder names to adjust `docker-compose.yml` in `tpotce` with volumes for the certificate. Examples how to handle docker volumes are available in the Wiki.

**Comment by FloppyDucks** [comment]
wow your fast, thanks ! ok so from what I understood. use the DockerFile from ~/docker/citrixhoneypot/  and then the only .yml file i should modify should be the main one in ~/tpotce thats really long.  let me check out the wiki
