### ISSUE TITLE
Kibana - HTTP 502 and Spiderfoot does not respond

### ISSUE THREAD

**Issue by kromenz** [telekom-security/tpotce#1563]
# Successfully raise an issue
Before you post your issue make sure it has not been answered yet and provide **⚠️ BASIC SUPPORT INFORMATION** (as requested below) if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki) and the [discussions](https://github.com/telekom-security/tpotce/discussions)
- 📚 Consult the documentation of 💻 your Linux OS, 🐳 [Docker](https://docs.docker.com/), the 🦌 [Elastic stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- ⚙️ The [Troubleshoot Section](https://github.com/telekom-security/tpotce?tab=readme-ov-file#troubleshooting) of the [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md) is a good starting point to collect a good set of information for the issue and / or to fix things on your own.
- **⚠️ Provide [BASIC SUPPORT INFORMATION](#-basic-support-information-commands-are-expected-to-run-as-root) or similar detailed information with regard to your issue or we will close the issue or convert it into a discussion without further interaction from the maintainers**.<br>

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- What OS are you T-Pot running on? Debian 11
- What is the version of the OS `lsb_release -a` and `uname -a`? bullseye
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)? T-POT 24.04
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? Cloud
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
- How long has your installation been running? 1 week
- Did you install upgrades, packages or use the update script? yes
- Did you modify any scripts or configs? If yes, please attach the changes.
- What is the current container status (`dps`)? active running
- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)? active running

Hi, i am doing a University project where i have to setup my an honeypot in the cloud, and then get attacked.
The goal is simple analyze the attacks, see the most used ones and that's it.
But i've been encountering some errors in these past weeks, some i've resolved on my own, but others, like the one i'm about to explain i can't figure it out.
Soo everything seems to be normal, the containers are running, but for some reason i can't open Kibana, neither Spiderfoot.
In Kibana i get error 502: 
![imagem_2024-06-02_005447262](https://github.com/telekom-security/tpotce/assets/106329696/a2100df5-c75e-4e7e-83bf-183bfe2c312d)
In Spiderfoot it doesn't even respond:
![imagem_2024-06-02_005646218](https://github.com/telekom-security/tpotce/assets/106329696/cc79082c-6996-4a4b-9852-3047c80fd3cf)
Spidefoot isn't that revelevant, i would just be happy if i could get everything running.

To finish, i would also like to know how to get attacked, this is because i have to finish this project in 2 weeks and 1 week has passed an no attacks.

Thanks for your time!

**Comment by t3chn0m4g3** [comment]
This seems to be an issue with your setup and not T-Pot. Review your routing, firewall settings, cloud provider settings, security groups, etc. Also, T-Pot is not supported on Debian 11.

**Comment by kromenz** [comment]
Update: I've changed to Debian 12, spiderfoot is working, but still the same error in Kibana, i saw somewhere that i needed 8GB of RAM, well i have 16 now and the same HTTP 502 error occurs.

Another question is how am i supposed to test the honeypot? Should i just wait, or post the ip of it in some forum that i don't know about?

Thank you for your patience.
