### ISSUE TITLE
T-Pot Attack Map Issues

### ISSUE THREAD

**Issue by TheGrandMaster01** [telekom-security/tpotce#1569]
Hello,

I'm having issues viewing the attack map in real time, I have events, but no data is being showed in the live map.
(This is from the last 24hrs, the other day I run some tests and send more than 120k)
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/f9b31bd7-45b7-4592-9ace-b9259e7e39ea)

- What OS are you T-Pot running on?
Debian GNU/Linux 12 (bookworm) 

- What is the version of the OS `lsb_release -a` and `uname -a`?
*lsb_release -a:*
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/2f441a11-681b-42f0-b9c4-a6de5fa6b465)

*uname -a:*
Linux debian 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
T-Pot 24.04

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VirtualBox
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/26cad5c7-f704-456d-a297-bd308a82233f)

- Review the `~/install_tpot.log`, attach the log and highlight the errors.
[install_tpot.log](https://github.com/user-attachments/files/15533649/install_tpot.log)

- How long has your installation been running?
2 Weeks

- Did you install upgrades, packages or use the update script?
Only disabled some ports for the Honeys and disabled some honeys
-- Conpot IEC104 service
-- Dicompot service
-- Dionaea service

- Did you modify any scripts or configs? If yes, please attach the changes.
Blank

- Please provide a screenshot of `htop` and `docker stats`.
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/4440455c-74f8-4f1b-9a16-2be9e490009f)
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/3333faa0-fd3c-4b44-bb89-a72a3c81ac9a)

- How much free disk space is available (`df -h`)?
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/00bd2073-2c3d-4fcd-9d53-050342de3012)

- What is the current container status (`dps`)?
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/71ceefdb-8bdf-4fbf-adb3-b24ab4c3f9d9)

- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)?
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/bb79ed49-b54f-45fa-9cdd-2a127db964e2)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `grc netstat -tulpen`
  - Stop T-Pot `systemctl stop tpot`
  - Run `grc netstat -tulpen`
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/0d73534e-f183-4dce-903d-6be6e11025c4)
  - Run T-Pot manually with `docker compose -f ~/tpotce/docker-compose.yml up` and check for errors
  - Stop execution with `CTRL-C` and `docker compose -f ~/tpotce/docker-compose.yml down -v`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Based on the info provided the map is connected, typically the reason for this is events without geo_ip info which cannot be rendered.

**Comment by t3chn0m4g3** [comment]
Do you see geo_ip info for the IPs in question?
If yes, run `docker logs map_data` to see if map_data receives it, but since I cannot reproduce (also using Debian 12) it is either browser related (clear cache), the site needs to be reloaded or the events have no geo_ip info.
What about the T-Pot Live Attack in Kibana?

**Comment by TheGrandMaster01** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/171570567/336086684-020284a2-dca9-47a5-b816-14c6e996fe1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjA5NDYsIm5iZiI6MTcxNzQyMDY0NiwicGF0aCI6Ii8xNzE1NzA1NjcvMzM2MDg2Njg0LTAyMDI4NGEyLWRjYTktNDdhNS1iODE2LTE0YzZlOTk2ZmUxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMzE3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDhmODRjZDE0ZGFjMWFiNjg5ZjBlMGEzNmYwOWEwNjdkOWNlYTRlM2FiMjY4YWVmNTEzNmQzNDliYTU1ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jimUHfSkMulqQUMd1eRrXZ4aN2ksBZNUJcgnyxie3tI)
> 
> ![imagen](https://private-user-images.githubusercontent.com/171570567/336086860-2c4c8657-04b4-4bf9-ae91-295dcd90e803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjA5NDYsIm5iZiI6MTcxNzQyMDY0NiwicGF0aCI6Ii8xNzE1NzA1NjcvMzM2MDg2ODYwLTJjNGM4NjU3LTA0YjQtNGJmOS1hZTkxLTI5NWRjZDkwZTgwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMzE3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTZmMTU4MjA5YjQ3YjYzNWFkZDlmMzNjMjAyYzEzN2Y4NGExOGY1ZDZhY2RkZGRmY2Q4NTBhOTJlOTJlZTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cfbPo8Wg2QmB5gphl04WBoeBTkBjpf1phY4rDUqh1cM)
> 
> Alright, I tried earlier cache, Im trying again.

No changes

**Comment by t3chn0m4g3** [comment]
It seems that the geo_ip info for the src_ip is present, but map_data / map_web need the geo_ip info for both, the source and the destination to render the path. Check if the destination ip (your T-Pot) has geo_ip info in the `geoip_ext` field.

**Comment by TheGrandMaster01** [comment]
Where can I see that? My ip shows the location info

**Comment by t3chn0m4g3** [comment]
Go to Kibana / Discover and browse through the events.

**Comment by TheGrandMaster01** [comment]
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/abe44206-5243-486d-84cd-ca7cd990aaef)

**Comment by t3chn0m4g3** [comment]
Run `more $HOME/tpotce/data/tpotinit.log` and look for `# Updating IP Info ...`, what is happening there?

**Comment by TheGrandMaster01** [comment]
![imagen](https://github.com/telekom-security/tpotce/assets/171570567/5883ff43-5374-4e27-8129-9f4c90eb59ed)

**Comment by TheGrandMaster01** [comment]
And is there a way I set it up manually? Editing the script or writing it in the configuration?

**Comment by t3chn0m4g3** [comment]
You can adjust the script outside the container, it resides in `docker/tpotinit/dist/bin`, then you add a volume to the `tpotservice` in `$HOME/tpotce/docker-compose.yml` pointing to the adjusted script. At start tpotinint will now execute the adjusted script.

**Comment by TheGrandMaster01** [comment]
Thanks, I will be trying that

**Comment by TheGrandMaster01** [comment]
I tried to change it, but its not composing the changes, takes the old script

**Comment by t3chn0m4g3** [comment]
It seems you are not using the correct path for the script. You need to make sure the volume's destination matches exactly the path and filename of the script inside the container.
At this point however there is nothing more that I can do. If you are unsure about docker volumes you can check out our [Wiki](https://github.com/telekom-security/tpotce/wiki), it holds some examples.

**Comment by Ir1z-boop** [comment]
![Captura desde 2024-10-23 12-21-12](https://github.com/user-attachments/assets/f1a49328-fb46-4f78-892f-b1f0f3c08135)
![Captura desde 2024-10-23 12-24-51](https://github.com/user-attachments/assets/0dd8c92f-a1e3-41e6-a03b-612400e0ca65)

Hello, following all the steps mentioned during the conversation, I have an external or public IP but I have the same problem with the real-time attack map.
