### ISSUE TITLE
error del servidor web

### ISSUE THREAD

**Issue by jorge4684** [telekom-security/tpotce#1573]
ya instalado todas las distribuciones y en ninguna me funciona la web me dice que el servidor esta ocupado y apagado y ya cheque y estan funcionando tanto docker como tpot

alguien que me pueda decir el porque esta pasando esto

**Comment by nu11secur1ty** [comment]
Could you please ask this in English? Thank you.

**Comment by jorge4684** [comment]
sorry
I have already installed all the distributions and none of them work, the website tells me that the server is busy and turned off and I already checked and both docker and tpot are working

Can someone tell me why this is happening?

**Comment by nu11secur1ty** [comment]
Could you give me the hardware parameters of your machine, please? And how do you install the software, step by step? 
Best Regards

**Comment by jorge4684** [comment]
amd 8core 24gb ram
After trying and trying so much I managed to access the website but since this repo doesn't create a user for me, I don't know how to enter it?

**Comment by jorge4684** [comment]
I'm trying again with debian11 and the last repo which is the one that gave me access to the website but it won't let me enter for the same reason that it doesn't create me as a user, I'm going to try with the same debian

**Comment by jorge4684** [comment]
I imagine it fences at/or at home?

**Comment by jorge4684** [comment]
Excuse me if you create the username and the web password but it doesn't work, it tells me it's wrong

**Comment by jorge4684** [comment]
![Screenshot 2024-06-06 172028](https://github.com/telekom-security/tpotce/assets/78058039/006101f7-f2bc-4ef9-8ceb-fab0526cb6f3)

**Comment by jorge4684** [comment]
I already managed to enter but the kibana does not work and the attack map appears blank
![Screenshot 2024-06-06 172028](https://github.com/telekom-security/tpotce/assets/78058039/93cf264f-8db9-4350-b649-51d9b67cc778)
![Screenshot 2024-06-06 193753](https://github.com/telekom-security/tpotce/assets/78058039/0c3b60e0-b28a-4954-b30f-08db5c6f80a0)
![Screenshot 2024-06-06 201521](https://github.com/telekom-security/tpotce/assets/78058039/7c39feb9-73ae-410a-a148-2fa265afb3de)
![Screenshot 2024-06-06 201533](https://github.com/telekom-security/tpotce/assets/78058039/3ea47b17-7ecd-4984-8915-02369bab659e)
![Screenshot 2024-06-06 201555](https://github.com/telekom-security/tpotce/assets/78058039/5fadf93b-23f2-40a2-a58b-c3d371b8f932)
![Screenshot 2024-06-06 201611](https://github.com/telekom-security/tpotce/assets/78058039/35438900-3055-4e9b-b6ae-630f5abdad03)

**Comment by jorge4684** [comment]
I am working with virtualbox and it is the latest script that is published on github
One question: would you know why I don't receive an attack and I don't appear on the attack map?
![Screenshot 2024-06-07 102424](https://github.com/telekom-security/tpotce/assets/78058039/5e1808aa-988c-42f2-a127-9835cbf1f0af)

**Comment by jorge4684** [comment]
The rest, everything is excellent, everything works 100%, I only have that little detail left that I don't appear online, it's as if the server was turned off.

**Comment by jorge4684** [comment]
![Screenshot 2024-06-07 103009](https://github.com/telekom-security/tpotce/assets/78058039/b3846bba-b086-47f9-9065-e12e05843e55)
I just realized that some things are also giving errors in the tpot and the meerkat

**Comment by nu11secur1ty** [comment]
Leave the system to collect enough information ;)
BR & exit 0;

**Comment by jorge4684** [comment]
thank you very much it has been a great help

**Comment by nu11secur1ty** [comment]
You are welcome, dear friend. =)

**Comment by JeisonAlvarez** [comment]
''tengo el mismo probla no me abre en la web lo tengo en aws ? @jorge4684 como resolviste

**Comment by jorge4684** [comment]
Me tomo tiempo pero recuerdo que tuve que filtrar las IP de redireccio a mi IP también recuerdo que ví un vídeo en Youtube si logro encontrarlo de nuevo público el link al vídeo
