### ISSUE TITLE
How to customize individual honeypots ?

### ISSUE THREAD

**Issue by DrunKnHigh** [telekom-security/tpotce#1575]
Hello,

I've seen the wiki/doc for "editing the honeypots" but it didn't help. I'm therefore making this ticket to see if someone could help me better understand how to customize the honeypots, this could also help others having the same issue.
The last "issues" created about this is mutiple years old and not 100% clear to me, would just like to be sure that I'm understanding this correctly.

In "tpotce" I can see a "docker" directory with most of the honeypots in it. They have their own docker-compose and config files. Is modifying those config files enough ? Or is their other shananigans to do ?

The old posts I saw were ppl entering the docker container of the honeypot, copying the conf file locally to then edit it and then add it to the honeypot's volume in the tpot.yml file. Now I'm not so well versed in docker but it feels a bit strange to do it this way. If there are already existing conf file, surely the docker already uses those to build the honeypots no ? or are they just used during the installation of said honeypots and not as the actual conf files afterwards ? meaning that we would need to make our own custom conf file in some other dir and point to it in the tpot.yml to erase the default one ?

Thanks.

**Comment by nu11secur1ty** [comment]
Diar friend, this is not an issue ;)
exit 0;

**Comment by t3chn0m4g3** [comment]
@DrunKnHigh You may find all the info you are asking for in the ReadMe.
