### ISSUE TITLE
Honey pots missing after issuing the update.sh command

### ISSUE THREAD

**Issue by smokey3226** [telekom-security/tpotce#1592]
Hello,

I noticed that after I issue the update.sh command, certain honeypot containers go missing. For instance, after a fresh install I have the full set of honey pots, after the update command hellpot, honeypots, and glutton seem to be gone from dps output. Any advice would be greatly appreciated. Thank you for your time, and this incredible honeypot project.

NAMES                 STATUS                    PORTS
adbhoney              Up 32 minutes (healthy)   0.0.0.0:5555->5555/tcp, :::5555->5555/tcp
ciscoasa              Up 32 minutes             0.0.0.0:5000->5000/udp, :::5000->5000/udp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp
citrixhoneypot        Up 32 minutes             0.0.0.0:443->443/tcp, :::443->443/tcp
conpot_guardian_ast   Up 32 minutes (healthy)   0.0.0.0:10001->10001/tcp, :::10001->10001/tcp
conpot_iec104         Up 32 minutes (healthy)   0.0.0.0:161->161/udp, :::161->161/udp, 0.0.0.0:2404->2404/tcp, :::2404->2404/tcp
conpot_ipmi           Up 32 minutes (healthy)   0.0.0.0:623->623/udp, :::623->623/udp
conpot_kamstrup_382   Up 32 minutes (healthy)   0.0.0.0:1025->1025/tcp, :::1025->1025/tcp, 0.0.0.0:50100->50100/tcp, :::50100->50100/tcp
cowrie                Up 32 minutes             0.0.0.0:22-23->22-23/tcp, :::22-23->22-23/tcp
ddospot               Up 32 minutes             0.0.0.0:19->19/udp, :::19->19/udp, 0.0.0.0:53->53/udp, :::53->53/udp, 0.0.0.0:123->123/udp, :::123->123/udp, 0.0.0.0:1900->1900/udp, :::1900->1900/udp
dicompot              Up 32 minutes             0.0.0.0:11112->11112/tcp, :::11112->11112/tcp
dionaea               Up 32 minutes (healthy)   0.0.0.0:20-21->20-21/tcp, :::20-21->20-21/tcp, 0.0.0.0:42->42/tcp, :::42->42/tcp, 0.0.0.0:81->81/tcp, :::81->81/tcp, 0.0.0.0:135->135/tcp, :::135->135/tcp, 0.0.0.0:445->445/tcp, :::445->445/tcp, 0.0.0.0:1433->1433/tcp, :::1433->1433/tcp, 0.0.0.0:1723->1723/tcp, :::1723->1723/tcp, 0.0.0.0:1883->1883/tcp, :::1883->1883/tcp, 0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 0.0.0.0:27017->27017/tcp, :::27017->27017/tcp, 0.0.0.0:69->69/udp, :::69->69/udp
elasticpot            Up 32 minutes             0.0.0.0:9200->9200/tcp, :::9200->9200/tcp
elasticsearch         Up 32 minutes (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 32 minutes             
fatt                  Up 32 minutes             
heralding             Up 32 minutes             0.0.0.0:110->110/tcp, :::110->110/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:465->465/tcp, :::465->465/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 0.0.0.0:995->995/tcp, :::995->995/tcp, 0.0.0.0:1080->1080/tcp, :::1080->1080/tcp, 0.0.0.0:5432->5432/tcp, :::5432->5432/tcp, 0.0.0.0:5900->5900/tcp, :::5900->5900/tcp
honeytrap             Up 32 minutes             
ipphoney              Up 32 minutes             0.0.0.0:631->631/tcp, :::631->631/tcp
kibana                Up 31 minutes (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 31 minutes (healthy)   127.0.0.1:64305->64305/tcp
mailoney              Up 32 minutes             0.0.0.0:29->25/tcp, 0.0.0.0:587->25/tcp, :::29->25/tcp, :::587->25/tcp
map_data              Up 31 minutes             
map_redis             Up 32 minutes             
map_web               Up 32 minutes             127.0.0.1:64299->64299/tcp
medpot                Up 32 minutes             0.0.0.0:2575->2575/tcp, :::2575->2575/tcp
nginx                 Up 32 minutes             
p0f                   Up 32 minutes             
redishoneypot         Up 32 minutes             0.0.0.0:6379->6379/tcp, :::6379->6379/tcp
sentrypeer            Up 32 minutes             0.0.0.0:5060->5060/tcp, 0.0.0.0:5060->5060/udp, :::5060->5060/tcp, :::5060->5060/udp
snare                 Up 32 minutes             0.0.0.0:80->80/tcp, :::80->80/tcp
spiderfoot            Up 32 minutes (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 32 minutes             
tanner                Up 32 minutes             
tanner_api            Up 32 minutes             
tanner_phpox          Up 32 minutes             
tanner_redis          Up 32 minutes             
tpotinit              Up 33 minutes (healthy)   
wordpot               Up 32 minutes             0.0.0.0:8080->80/tcp, :::8080->80/tcp

**Comment by t3chn0m4g3** [comment]
It is expected that changes will be reverted and this is described in the [README](https://github.com/telekom-security/tpotce#update-script).
Even when running the script you will be notified about that:
```

	echo
	echo "### If you made changes to docker-compose.yml please ensure to add them again."
	echo "### We stored the previous version as backup in $myARCHIVE."
	echo "### Some updates may need an import of the latest Kibana objects as well."
	echo "### Download the latest objects here if they recently changed:"
	echo "### https://raw.githubusercontent.com/telekom-security/tpotce/master/etc/objects/kibana_export.ndjson.zip"
	echo "### Export and import the objects easily through the Kibana WebUI:"
	echo "### Go to Kibana > Management > Saved Objects > Export / Import"
	echo
```

**Comment by smokey3226** [comment]
Thanks so much for explaining!
