### ISSUE TITLE
Dont docker work

### ISSUE THREAD

**Issue by fmunsal** [telekom-security/tpotce#1595]
I just opened the cloud. I don't know why I'm getting this error but docker is not working in cloud even though I just installed it.

- What OS are you T-Pot running on?
debian
- What is the version of the OS `lsb_release -a` and `uname -a`?
-  6.1.0-21-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
- T-Pot 24.04.x
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- cloud
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
- is normal
- How long has your installation been running?
  - If it is a fresh install consult the documentation first.

- Did you install upgrades, packages or use the update script?
- no
- Did you modify any scripts or configs? If yes, please attach the changes.
- no
- Please provide a screenshot of `htop` and `docker stats`.
- 
![image](https://github.com/telekom-security/tpotce/assets/119849116/d6f1d021-0a62-47ff-b52e-6a53e7b113a0)

- How much free disk space is available (`df -h`)?
- 
![image](https://github.com/telekom-security/tpotce/assets/119849116/069de241-84a1-4ef4-9eb3-2f1b40d299fb)

- What is the current container status (`dps`)?
- 
![image](https://github.com/telekom-security/tpotce/assets/119849116/eba6cc8d-e3b7-4282-8bc1-426349a2c32b)

**Comment by t3chn0m4g3** [comment]
Please follow the [Troubleshooting Section](https://github.com/telekom-security/tpotce?tab=readme-ov-file#troubleshooting) in the ReadMe.

**Comment by f0rc3ps** [comment]
Yes they are not working! Whatever :)
