### ISSUE TITLE
Elastic did not load properly

### ISSUE THREAD

**Issue by TheGrandMaster01** [telekom-security/tpotce#1596]
Issue with Kibana/Elastic.
Elastic did not load properly. Check the server output for more information.
![image](https://github.com/telekom-security/tpotce/assets/171570567/0bc83759-0f3b-4984-8487-338eb654a436)

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- What OS are you T-Pot running on?
Debian 12 - VirtualBox

- What is the version of the OS `lsb_release -a` and `uname -a`?
![image](https://github.com/telekom-security/tpotce/assets/171570567/f5a47040-87a3-4ef3-bb4b-c1b2c3ce5441)
Linux debian 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
24.04

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VirtualBox

- Review the `~/install_tpot.log`, attach the log and highlight the errors.
[tpotinit.log](https://github.com/user-attachments/files/15955977/tpotinit.log)

- How long has your installation been running?
For more than 3 weeks

- Did you install upgrades, packages or use the update script?
No

- Did you modify any scripts or configs? If yes, please attach the changes.
No

- Please provide a screenshot of `htop` and `docker stats`.
![image](https://github.com/telekom-security/tpotce/assets/171570567/3cc47e0f-5d4c-43b1-bf05-3c5d9a5fc8eb)
![image](https://github.com/telekom-security/tpotce/assets/171570567/3cef8934-9ed7-4b9e-9f4a-6a86588d5041)

- How much free disk space is available (`df -h`)?
![image](https://github.com/telekom-security/tpotce/assets/171570567/7ff6203e-71ca-43b0-a82d-bd803986c616)

- What is the current container status (`dps`)?
![image](https://github.com/telekom-security/tpotce/assets/171570567/f5321402-5863-463f-bad7-cece2516ae9f)

- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://github.com/telekom-security/tpotce/assets/171570567/caa31b9d-e571-468a-a292-88aaa9b3f5b9)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `grc netstat -tulpen`
![image](https://github.com/telekom-security/tpotce/assets/171570567/8289e999-eba9-40c7-b088-957f23aa8847)
![image](https://github.com/telekom-security/tpotce/assets/171570567/372233cb-6a3b-4536-b79a-bdebaed93fe2)

**Comment by t3chn0m4g3** [comment]
The setup is not really recommended. Based on the screenshots you seem to be running a desktop environment. This might lead to standby issues with ES being unable to close indices correctly and thus being unable to recover them correctly.
You can use Elasticvue to further investigate the issue and simply delete indices that are defective, however you will most likely run into the same issues as long you are a using a [desktop environment](https://github.com/telekom-security/tpotce?tab=readme-ov-file#choose-your-distro).
Also `docker logs elasticsearch -f` will provide you with error logs regarding ES.

**Comment by TheGrandMaster01** [comment]
Error response from daemon: No such container: elasticsearch

Alright, so what do you recommend then, physical install?

**Comment by t3chn0m4g3** [comment]
Based on the screenshots the container is up at some point, then you need to run the logging.
Otherwise follow the ReadMe to the recommended installation.
