### ISSUE TITLE
TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark

### ISSUE THREAD

**Issue by TobeCodeNinja** [telekom-security/tpotce#1597]
Hi, having an issue where the disk keeps filling up. I am not sure on what requires to be deleted or if a cron job needs setting up to free up space every week. Due to the disk filling up I presume I am unable to access anything on Kibana, hope you can help:

[Honeypot01 support.docx](https://github.com/user-attachments/files/15967888/Honeypot01.support.docx)

**Comment by TobeCodeNinja** [comment]
Hi, please see attached docx with the support information

**Comment by t3chn0m4g3** [comment]
T-Pot Assistant is here for you: #1564
