### ISSUE TITLE
cowrie.json log improperly formatted

### ISSUE THREAD

**Issue by eyalarkin** [telekom-security/tpotce#1598]
Running T-Pot on EC2 instance with Ubuntu 24.04.
Using T-Pot 24.04

Hoping this is the right place for this. Not a huge error but when analyzing the outputted log files I noticed that the cowrie log, `cowrie.json` located in `tpotce/data/cowrie/log/` is improperly formatted as a JSON file, despite having a JSON extension. Wanted to point this out so others attempting to analyze it using JSON tools don't run into the problems as me. Would suggest either changing the extension or simply fixing the formatting (adding [] around the entire file and adding commas between array entries, for example).

Also, I understand this would be very difficult, but just a suggestion to the team: it would be really useful if there was standardized logging into either one file (or all logs formatted the same) for analysis purposes.

**Thank you T-Pot team for all the hard work you guys put into making this incredibly useful platform!**

**Comment by t3chn0m4g3** [comment]
Thank you 😍

Yes the JSON is not 100% strictly formatted, as all the other `*.json` logs as well. JSON objects as array are particularly hard on  the Elastic Stack for our use in Kibana. Hence we prefer all logs in this format...
```
{"timestamp":"20210812T191730","log_level":"INFO","message":"Hello, World!"}
```
... which works perfectly fine.
