### ISSUE TITLE
AlmaLinux 8 - no available grc - error while running Ansible playbook from install script

### ISSUE THREAD

**Issue by mattroot** [telekom-security/tpotce#1603]
grc is not available in basic Alma repos. I remember stealing grc from Fedora when installing 22.04 on RHEL. Maybe configure additional repos during install? Is it even necessary?

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- What OS are you T-Pot running on? 
AlmaLinux 8.10

- What is the version of the OS `lsb_release -a` and `uname -a`?
```plain
$ uname -a
Linux virusdistributor 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Wed Jun 5 09:12:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```

no lsb_release available, instead:
```plain
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
```

- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
24.04

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? 
hardware, amd64

- Review the `~/install_tpot.log`, attach the log and highlight the errors.
Instead, Ansible log from installation
```plain
PLAY [T-Pot - Bootstrapping Python] *******************************************************

TASK [Get distribution name (All)] ********************************************************
changed: [127.0.0.1]

TASK [Check if python3 is installed (All)] ************************************************
changed: [127.0.0.1]

TASK [Add python package (Alma, Fedora, Rocky)] *******************************************
skipping: [127.0.0.1]

PLAY [T-Pot - Abort if run as tpot, root or on unsupported distribution] ******************

TASK [Gathering Facts] ********************************************************************
ok: [127.0.0.1]

TASK [Check if running as root (All)] *****************************************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "Running as user: <redacted, not root>."
}

TASK [Check if running as tpot (All)] *****************************************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "Running as user: <redacted, not root>."
}

TASK [Check if supported distribution (All)] **********************************************
ok: [127.0.0.1] => {
    "changed": false,
    "msg": "T-Pot will now install on AlmaLinux."
}

PLAY [T-Pot - Install recommended, remove conflicting packages] ***************************

TASK [Gathering Facts] ********************************************************************
ok: [127.0.0.1]

TASK [Syncing clocks (All)] ***************************************************************
changed: [127.0.0.1]

TASK [Install grc from remote repo (AlmaLinux, Rocky)] ************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - nothing provides python needed by grc-1.13.8-1.el7.noarch from @commandline", "rc": 1, "results": []}

PLAY RECAP ********************************************************************************
127.0.0.1                  : ok=8    changed=3    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

### Something went wrong with the Playbook, please review the output and / or install_tpot.log for clues.
### Aborting.
```

- How long has your installation been running?
Problem during installation.

- Did you install upgrades, packages or use the update script?
Just updated AlmaLinux all the way up.

- Did you modify any scripts or configs? If yes, please attach the changes.
No.

- Please provide a screenshot of `htop` and `docker stats`.
Not applicable.

- How much free disk space is available (`df -h`)?
Not applicable.

- What is the current container status (`dps`)?
Not applicable.

- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)?
Not applicable.

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `grc netstat -tulpen`
Not applicable.

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
Not applicable.

**Comment by mattroot** [comment]
Quick note - exa is not available as well, and it doesn't proceed to installing an alternative. Again, is it really necessary?

**Comment by t3chn0m4g3** [comment]
Thanks for taking the time to open this issues.
We do only support Alma Linux 9.4. The full list of supported distros incl. download links can be found [here](https://github.com/telekom-security/tpotce?tab=readme-ov-file#choose-your-distro).
