### ISSUE TITLE
Disk space filled up again

### ISSUE THREAD

**Issue by TobeCodeNinja** [telekom-security/tpotce#1604]
Hi 

Please can you have a look at the attached information provided. I am not sure what is filling up the disk or what I can delete.

**Comment by TobeCodeNinja** [comment]
[Honeypot01 support.docx](https://github.com/user-attachments/files/16046332/Honeypot01.support.docx)

**Comment by t3chn0m4g3** [comment]
Please open an issue as advised without attachments that can hold malware.

Thanks.
