### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by nsk** [telekom-security/tpotce#1612]
hi I've loved Tpot for years, 
do you think you could add a feature that would allow us, like a "butterfly net", to catch malware and other crappy stuff, to be able to analyze them later, 

I know that solutions like that can exist but not for the general public. thanks in advance

**Comment by t3chn0m4g3** [comment]
Thanks for the nice feedback 😍

I am not sure what you mean. T-Pot does exactly that, mainly with ADBHoney, Cowrie, Dionaea, Glutton and Honeytrap.

In case you know an all-the-malware-you-can-eat honeypot just let us know and we will look into it.
