### ISSUE TITLE
Unable to update to 24.04 from 22.04

### ISSUE THREAD

**Issue by boredchilada** [telekom-security/tpotce#1615]
# Ask T-Pot Assistant
- 🤖 Ask [T-Pot Assistant (beta)](https://chatgpt.com/g/g-67OJ5idsQ-t-pot-assistant-beta) if you have not read the documentation yet and do not intent to do so (#1564)

# Successfully raise an issue
Before you post your issue make sure it has not been answered yet and provide **⚠️ BASIC SUPPORT INFORMATION** (as requested below) if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki) and the [discussions](https://github.com/telekom-security/tpotce/discussions)
- 📚 Consult the documentation of 💻 your Linux OS, 🐳 [Docker](https://docs.docker.com/), the 🦌 [Elastic stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- ⚙️ The [Troubleshoot Section](https://github.com/telekom-security/tpotce?tab=readme-ov-file#troubleshooting) of the [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md) is a good starting point to collect a good set of information for the issue and / or to fix things on your own.
- **⚠️ Provide [BASIC SUPPORT INFORMATION](#-basic-support-information-commands-are-expected-to-run-as-root) or similar detailed information with regard to your issue or we will close the issue or convert it into a discussion without further interaction from the maintainers**.<br>

# ⚠️ Basic support information (commands are expected to run as `root`)

**We happily take the time to improve T-Pot and take care of things, but we need you to take the time to create an issue that provides us with all the information we need.** 

- What OS are you T-Pot running on?
- **i installed it via the ISO** debian11
- What is the version of the OS `lsb_release -a` and `uname -a`?
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
- What T-Pot version are you currently using (only **T-Pot 24.04.x** is currently supported)?
22.04 trying to update but the instructions changed and do not apply to my instance. The updater doesnt work because i have to run it as a user, but it cant go past the docker sockets and now im in limbo

### Removing old docker images.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json?filters=%7B%22reference%22%3A%7B%22dtagdevsec%2F%2A%3Adev%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
### Removing old docker images.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json?filters=%7B%22reference%22%3A%7B%22ghcr.io%2Ftelekom-security%2F%2A%3Adev%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
-VM
- Review the `~/install_tpot.log`, attach the log and highlight the errors.
DOES NOT EXIST!
- How long has your installation been running?
It's been up for a while with no issues, i was able to upgrade from 20.04 to 22.04 no problem and running the updater now seems to have broken it and i am not able to run dps.sh - tpotce doesnt exist on the system so all your new instructions dont make sense its all in /opt/tpot.
- Did you install upgrades, packages or use the update script?
trying to
- Did you modify any scripts or configs? If yes, please attach the changes.
no
- Please provide a screenshot of `htop` and `docker stats`.
<img width="1879" alt="image" src="https://github.com/telekom-security/tpotce/assets/82670806/4cb0da75-f560-4709-8b32-ef047d9acc83">
<img width="905" alt="image" src="https://github.com/telekom-security/tpotce/assets/82670806/c833622d-93f8-4e76-b10a-c4c7009fec09">

- How much free disk space is available (`df -h`)?
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  2.4M  1.6G   1% /run
/dev/sdb2        87G   34G   49G  41% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda1       295G   88G  194G  32% /data
tmpfs           1.6G     0  1.6G   0% /run/user/1000
- What is the current container status (`dps`)?
see above
- On Linux: What is the status of the T-Pot service (`systemctl status tpot`)?
● tpot.service - tpot
     Loaded: loaded (/etc/systemd/system/tpot.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-07-09 15:07:57 EDT; 4s ago
    Process: 221205 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
    Process: 221206 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=127)
    Process: 221207 ExecStartPre=/opt/tpot/bin/tpdclean.sh -y (code=exited, status=203/EXEC)
    Process: 221208 ExecStopPost=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset (code=exited, status=203/EXEC)
        CPU: 8ms

am i going to be forced to reinstall to be able to upgrade as my instance now is 100% broken.

**Comment by t3chn0m4g3** [comment]
Sorry to hear that, but an upgrade is unsupported as described in the Breaking Changes of the [Release Notes](https://github.com/telekom-security/tpotce/releases/tag/24.04.0) for 24.04.

**Comment by boredchilada** [comment]
> Sorry to hear that, but an upgrade is unsupported as described in the Breaking Changes of the [Release Notes](https://github.com/telekom-security/tpotce/releases/tag/24.04.0) for 24.04.

alrighty then - didn't see that one my bad

**Comment by boredchilada** [comment]
Closing

**Comment by mattroot** [comment]
I know the issue is now stale, but I found a workaround for this. It basically requires removing old T-Pot installation, upgrading Debian to bookworm and reinstalling, but in case you cannot reinstall the entire unit by itself, it might come in handy.

Perform everything but the last step as root.

**1. Stop T-Pot and cleanup after yourself**
Perform these two commands:
```shell
systemctl disable --now tpot
docker system prune --all --volumes
```

**2. Remove T-Pot Installation**
Remove these files/directories:
- /opt/tpot
- /data
- /etc/systemd/system/tpot.service
- /etc/issue

**3. Perform daemon reload**
```shell
systemctl daemon-reload
```

**4. Clean up your crontab**
```shell
nano /etc/crontab
```
Remove everything added by T-Pot.

**5. Remove your Docker installation**
Theoretically T-Pot installer does it anyway, but there's no reason to keep Docker installed during an upgrade.
```shell
systemctl disable --now docker
apt purge docker.io docker-compose docker-doc podman-docker containerd runc
```

**6. Upgrade Debian to Bookworm**
Follow this: https://wiki.debian.org/DebianUpgrade

**7. Redeploy T-Pot**
Follow normal installation instructions for T-Pot 24.04.

I hope I didn't miss anything. Let me know if I did.
Also, feel free to copy-paste it wherever you need.
