### ISSUE TITLE
Error Adding Tpot Sensor 

### ISSUE THREAD

**Issue by whitepoll** [telekom-security/tpotce#1616]
Hi everyone,

I have a Tpot system made up of a HIVE and two sensors. Now, I want to add two more sensors, and when I deploy on the HIVE, I encounter the following error:

```
logstash  | [ERROR] 2024-07-10 14:39:29.385 [[http_output]>worker1] http - Could not fetch URL {:url=>"https://XXX.XXX.XXX:64294", :method=>:post, :message=>"XXX.XXX.XXX.XXX:64294 failed to respond", :class=>Manticore::ClientProtocolException, :will_retry=>true}
```

The HIVE system is configured in the same way, and the self-signed certificate is the same one used by the two sensors that I have already configured and are working. The problem only occurs with the two additional sensors I want to install now. How can I resolve this?

<img width="990" alt="Screenshot 2024-07-10 alle 16 45 43" src="https://github.com/telekom-security/tpotce/assets/154346469/eb378685-8cc8-4c19-b347-7f6844f6de56">

Thank you for your support

**Comment by t3chn0m4g3** [comment]
Based on the logs you provided the HIVE is not reachable on port `tcp/64294`.
Can you reach the HIVE from the the SENSOR via `curl https://<ip>:64294`?

**Comment by whitepoll** [comment]
Yes the sensor is reachable, the sensors I had put first reach it easily. 

If I make a call with curl:

- Curl https://93.43.4.146:64294
-Curl -k https://93.43.4.146:64294
<img width="679" alt="Screenshot 2024-07-10 alle 18 06 40" src="https://github.com/telekom-security/tpotce/assets/154346469/27f2095a-ff36-463d-ae58-8971ab80b26e">


On the sensor I already tried using the method as well: **LS_SSL_VERIFICATION=none**  but the error does not change

**Comment by t3chn0m4g3** [comment]
@whitepoll Recheck #1614, I mixed up the VAR.

**Comment by whitepoll** [comment]
So the problem is Tpot's and not my configuration? Will it be fixed in the next update?

**Comment by t3chn0m4g3** [comment]
@whitepoll Works perfectly fine here.

**Comment by t3chn0m4g3** [comment]
Updated the documentation.
