### ISSUE TITLE
How to disable ewsposter

### ISSUE THREAD

**Issue by RanushMithila** [telekom-security/tpotce#1625]
I have deployed the tpot honeypot in a distributed architecture. I'm seeing traffic generating for the `160.44.201.156` IP when a request comes for my honeypot. I sent a curl request to check and start tcpdump to capture the data packets. Then I saw every time I execute the curl command it sends traffic to that particular IP. and is owned by `T-Systems International GmbH`

![image](https://github.com/user-attachments/assets/9b8b8f8f-4a5c-486d-93f3-9a97e640795e)

This is the screenshot of tcpdump
![image](https://github.com/user-attachments/assets/bdc74c0e-7a51-420d-b489-5297290410fb)

This VM doesn't have a public IP and it comes through a firewall from that firewall, I allowed only one IP and that is also my VM. So can someone clarify this issue? I need to stop this kind of traffic.

**Comment by t3chn0m4g3** [comment]
This is the event transmission as described in the ReadMe. Follow [this chapter](https://github.com/telekom-security/tpotce?tab=readme-ov-file#community-data-submission) in the ReadMe how to disable it.
