### ISSUE TITLE
Mailoney honeypot not implementedd DATA

### ISSUE THREAD

**Issue by vasokolov** [telekom-security/tpotce#1628]
### Discussed in https://github.com/telekom-security/tpotce/discussions/1627

<div type='discussions-op-text'>

<sup>Originally posted by **vasokolov** July 26, 2024</sup>
Hi there! I have some issue with mailoney honepot.
I am trying to test it with  simple smtp command.
I have a connection to mailoney via telnet and port 25. Everything well but i cannot send any data. What i am doing wrong?

> sokolov@astra:~$ telnet 172.31.3.185 25
Trying 172.31.3.185...
Connected to 172.31.3.185.
Escape character is '^]'.
220 mailrelay.local ESMTP Exim 4.69 #1 Fri, 26 Jul 2024 07:36:47 -0700
MAIL FROM: 123@123.com
250 Ok
RCPT TO: host1@host.ru
250 Ok
DATA
" not implementedd "DATA</div>

**Comment by t3chn0m4g3** [comment]
Closing as duplicate of #1627
