### ISSUE TITLE
unable to download from git

### ISSUE THREAD

**Issue by mpuff** [telekom-security/tpotce#1630]
i installed debian 12 and tried to install tpot

when I try to download from git, I get the error:

git clone https://github.com/telekom-security/tpotce

Klone nach 'tpotce'...
remote: Enumerating objects: 16162, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (124/124), done.
Fehler: 105 Bytes des Bodys werden noch erwartet 833.00 KiB/s 
fetch-pack: unexpected disconnect while reading sideband packet
Schwerwiegend: zu frühes Dateiende
Schwerwiegend: fetch-pack: ungültige index-pack Ausgabe

**Comment by mpuff** [comment]
also when I try with:

env bash -c "$(curl -sL https://github.com/telekom-security/tpotce/raw/master/install.sh)"

I get an error:

TASK [Add aliases with eza (Debian, Raspbian, Ubuntu)] ********************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [Clone / Update T-Pot repository (All)] ******************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin https://github.com/telekom-security/tpotce /home/tpot/tpotce", "msg": "Klone nach '/home/tpot/tpotce'...\nFehler: RPC fehlgeschlagen; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)\nFehler: 3602 Bytes des Bodys werden noch erwartet\nfetch-pack: unexpected disconnect while reading sideband packet\nSchwerwiegend: zu frühes Dateiende\nSchwerwiegend: fetch-pack: ungültige index-pack Ausgabe", "rc": 128, "stderr": "Klone nach '/home/tpot/tpotce'...\nFehler: RPC fehlgeschlagen; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)\nFehler: 3602 Bytes des Bodys werden noch erwartet\nfetch-pack: unexpected disconnect while reading sideband packet\nSchwerwiegend: zu frühes Dateiende\nSchwerwiegend: fetch-pack: ungültige index-pack Ausgabe\n", "stderr_lines": ["Klone nach '/home/tpot/tpotce'...", "Fehler: RPC fehlgeschlagen; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)", "Fehler: 3602 Bytes des Bodys werden noch erwartet", "fetch-pack: unexpected disconnect while reading sideband packet", "Schwerwiegend: zu frühes Dateiende", "Schwerwiegend: fetch-pack: ungültige index-pack Ausgabe"], "stdout": "", "stdout_lines": []}

PLAY RECAP ****************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=29   changed=6    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

### Something went wrong with the Playbook, please review the output and / or install_tpot.log for clues.
### Aborting.

**Comment by t3chn0m4g3** [comment]
This rather sounds like an issue with GitHub, your OS or even your internet connection.
Never tried curl or the git client on a German Debian install, which might come with something else than UTF-8.
Cannot reproduce it on my end.

**Comment by t3chn0m4g3** [comment]
Closing this as neither reproducible nor an issue with T-Pot itself.

[T-Pot Assistant](https://github.com/telekom-security/tpotce/discussions/1564) can help you troubleshoot.
