### ISSUE TITLE
Active: Activating | dps --> T-POT: Inactive | containers failing to start

### ISSUE THREAD

**Issue by MR-Aloner** [telekom-security/tpotce#1700]
# Successfully raise an issue
Before you post your issue make sure it has not been answered yet and provide **⚠️ BASIC SUPPORT INFORMATION** (as requested below) if you come to the conclusion it is a new issue.

- OS:  On GCP(cloud) Debian 11 bullseye version

- `uname -a`? : **Linux instance-20241114-233359 5.10.0-33-cloud-amd64 #1 SMP Debian 5.10.226-1 (2024-10-03) x86_64 GNU/Linux**

- Version: **T-Pot 24.04.0**
- What architecture are you running on (i.e. hardware, cloud, VM, etc.) : Cloud
- Review the `~/install_tpot.log`, attach the log and highlight the errors : 
![image](https://github.com/user-attachments/assets/0637eca1-3961-4094-912f-2e06f2b0c816)

No errors
- How long has your installation been running: **takes normal time to install**

htop:  ![image](https://github.com/user-attachments/assets/2b99194f-79bd-4feb-91b6-631660c31150)
docker stats:  ![image](https://github.com/user-attachments/assets/9a304c8f-4d56-47e8-a9a3-806693d9ac11)

Disk space: ![image](https://github.com/user-attachments/assets/f22b0d92-a73c-4c5d-9410-fecd3c9c6d78)
dps: 
![image](https://github.com/user-attachments/assets/686a36d7-bd4b-4b7b-bbf9-12daea62267a)
![image](https://github.com/user-attachments/assets/14da8744-c997-4207-8ad8-7945b97e11d2)

status : 
![image](https://github.com/user-attachments/assets/b1e6b4a2-980d-4c71-b27f-4d2eafa0afb3)
![image](https://github.com/user-attachments/assets/bb13d70e-73f7-453a-9fd1-0b261bb8bcd7)

- grc netstat -tulpen: 
![image](https://github.com/user-attachments/assets/b29762de-0d24-4dac-bafd-5c7d1126bcaf)

  - Run T-Pot manually with `docker compose -f ~/tpotce/docker-compose.yml up` and check for errors
  - Stop execution with `CTRL-C` and `docker compose -f ~/tpotce/docker-compose.yml down -v`
  - 
  - container nginx : ![image](https://github.com/user-attachments/assets/71012ffb-352c-471c-9482-0f244ff6c9ec)
  - Error:  ![image](https://github.com/user-attachments/assets/75e9cfe8-62ef-44d6-a361-9887b183cb67)

Please help me out to solve the issue.

**Comment by t3chn0m4g3** [comment]
1. A process running on `tcp/25` is preventing T-Pot from starting. Most likely occupied by Exim, another mail server or a dangling container (`docker system prune`).
2. Based on the screenshots and the code structure of T-Pot you are actually trying to run 22.04 which is no longer supported.

Follow the ReadMe to install 24.04.

**Comment by MR-Aloner** [comment]
Actually i was running 24 version the reason i used 22 is for dps.sh tool
only because its giving me a over all view like active inactive.

But I installed 24 version only.

So do u want me to kill those or chage the ports you have mentioned?

Thank you
