### ISSUE TITLE
error on vm Tpot 24.04.x

### ISSUE THREAD

**Issue by cybergomzy** [telekom-security/tpotce#1701]
I have tried to install it, but it fails

screenshot attached. 
![tpot error](https://github.com/user-attachments/assets/03caf921-405b-4f14-acce-dbb1aa5eb414)

**Comment by cybergomzy** [comment]
i am using debian 12. I have tried it 3 times on Virtual box. and it is same issue

**Comment by t3chn0m4g3** [comment]
Based on the screenshot you are not running a minimum installation as required. Please follow the ReadMe. I cannot reproduce.
