### ISSUE TITLE
Cannot acces to the web UI

### ISSUE THREAD

**Issue by Firebleudark** [telekom-security/tpotce#1714]
I am on fully upgrade debian 12 vps.

I decided to install T-pot (Hive version) with your scriptt without any errors. I reboot my system when I want to access to web UI on port 64297, I have this error :  "Unable to connect".
I have no firewall.

Can someone help me ?

Feel free to ask some logs if you want.

**Comment by Firebleudark** [comment]
Picture of the end of the installation : 
![image](https://github.com/user-attachments/assets/4f3dfd58-9769-4444-b7d0-6e5fdea08ce0)

**Comment by Firebleudark** [comment]
I had a Firewall (ufw), I allowed port 80 and 445 but same problem

**Comment by Firebleudark** [comment]
ok, I just modified the .env file (my bad) and now I need to enter my username and my password but when I confirm my infomation, the website ask again the same thing/

**Comment by Firebleudark** [comment]
solved !

**Comment by aaidenharriss** [comment]
> ok, I just modified the .env file (my bad) and now I need to enter my username and my password but when I confirm my infomation, the website ask again the same thing/

how did you modify the .env file? was it a specific code you ran ?
