### ISSUE TITLE
log rotation issue

### ISSUE THREAD

**Issue by ristov** [telekom-security/tpotce#1715]
I have been running T-Pot 24.04.x over a month on a separate hardware, with the underlying OS being Rocky Linux 9.5 with the latest kernel 5.14.0-503.15.1.el9_5.x86_64. T-Pot has been functioning flawlessly, but I have noticed a couple of days ago that log rotation is not working as expected. The issue is not concerning ELK indices, as they are kept for 30 days as they should according to relevant ILM policy. However, the textual log files (with *json and *log extensions) are not going through daily rotation.

When investigatint T-Pot logs a bit, I did find the following messages at the beginning of 'tpotce/data/tpotinit.log' log file which seems to be connected to this issue:

Persistence enabled, now rotating and compressing logs.
warning: Potentially dangerous mode on /opt/tpot/etc/logrotate/logrotate.conf: 0664
error: Ignoring /opt/tpot/etc/logrotate/logrotate.conf because it is writable by group or others.

From these messages, it seems that tpotinit container should take care of the log rotation (although I could be wrong). Nevertheless, when inspecting the data directory of this container, I did find the file 'tpotce/docker/tpotinit/dist/etc/logrotate/logrotate.conf' which contains paths to the log files that are not rotated. When checking the permissions of this file, they are not set to 0664 as reported by the above message, but rather to 0644:

-rw-r--r--. 1 tpotadm tpotadm 1612 Nov 11 14:09 tpotce/docker/tpotinit/dist/etc/logrotate/logrotate.conf

I have tried to change the permissions and the owner:group for that file several times and restart T-Pot, but unfortunately the error message in 'tpotce/data/tpotinit.log' log file stays exactly the same with permissions 0664 reported. I am not sure what are the permissions of logrotate.conf inside the relevant container, though, but somehow it seems to influence the log rotation process.

**Comment by t3chn0m4g3** [comment]
@ristov Thank you for taking the time and explaining the issue. Based on the description I could identify the issue and fix it accordingly. New docker images have been pushed, now when starting you should see this (`docker logs tpotinit -f`):
```
[...]
 ___       _ _   _       _ _     _                     
|_ _|_ __ (_) |_(_) __ _| (_)___(_)_ __   __ _         
 | || '_ \| | __| |/ _` | | |_  / | '_ \ / _` |        
 | || | | | | |_| | (_| | | |/ /| | | | | (_| |  _ _ _ 
|___|_| |_|_|\__|_|\__,_|_|_/___|_|_| |_|\__, | (_|_|_)
                                         |___/         
 _____     ____       _       ____  _  _    ___  _  _    _ 
|_   _|   |  _ \ ___ | |_ _  |___ \| || |  / _ \| || |  / |
  | |_____| |_) / _ \| __(_)   __) | || |_| | | | || |_ | |
  | |_____|  __/ (_) | |_ _   / __/|__   _| |_| |__   _|| |
  |_|     |_|   \___/ \__(_) |_____|  |_|(_)___/   |_|(_)_|
                                                           

# Creating passwd files based on T-Pot .env config ...

# Data folder is present, just cleaning up, please be patient ...

Persistence enabled, now rotating and compressing logs.
[...]
```

**Comment by t3chn0m4g3** [comment]
T-Pot 24.04 tpotinit image has been adjusted as well...
```
 ___       _ _   _       _ _     _                     
|_ _|_ __ (_) |_(_) __ _| (_)___(_)_ __   __ _         
 | || '_ \| | __| |/ _` | | |_  / | '_ \ / _` |        
 | || | | | | |_| | (_| | | |/ /| | | | | (_| |  _ _ _ 
|___|_| |_|_|\__|_|\__,_|_|_/___|_|_| |_|\__, | (_|_|_)
                                         |___/         
 _____     ____       _       ____  _  _    ___  _  _   
|_   _|   |  _ \ ___ | |_ _  |___ \| || |  / _ \| || |  
  | |_____| |_) / _ \| __(_)   __) | || |_| | | | || |_ 
  | |_____|  __/ (_) | |_ _   / __/|__   _| |_| |__   _|
  |_|     |_|   \___/ \__(_) |_____|  |_|(_)___/   |_|  
                                                        

# Creating passwd files based on T-Pot .env config ...

# Data folder is present, just cleaning up, please be patient ...

Persistence enabled, now rotating and compressing logs.
```

**Comment by ristov** [comment]
many thanks for such a quick fix for that issue! Today the logs were rotated successfully :)

**Comment by t3chn0m4g3** [comment]
Great news! Thank you for the feedback.
