### ISSUE TITLE
Docker hub link broken to this source

### ISSUE THREAD

**Issue by alphaDev23** [telekom-security/tpotce#237]
On https://hub.docker.com/r/dtagdevsec/suricata/ the source files point to:

https://github.com/dtag-dev-sec/suricata

Not a source code issue but beneficial to users who want to see the source code from the Docker hub page.

**Comment by t3chn0m4g3** [comment]
Thanks, this is expected since the T-Pot 18.10
has not been released yet and we already cleaned up the source repos.
