### ISSUE TITLE
How to enable TLS/SSL for Elasticsearch?

### ISSUE THREAD

**Issue by jonas-osw** [telekom-security/tpotce#437]
- T-Pot 19.03 Standard Installation on Debian sid
- Hardware (i5-540M)

I'm trying to activate SSL for Elasticsearch because I want to connect to it with remote Logstash instances.

- I generated a certificate with the elasticsearch-certutil following this guide: https://www.elastic.co/guide/en/elasticsearch/reference/7.3/configuring-tls.html
- I placed the certificate in /data/elk/
- I also placed the elasticsearch.yml in /data/elk and added the corresponding volume in tpot.yml (analogous to your wiki guide): 
`- /data/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml`
- I added these lines to my elasticsearch.yml:
`xpack.security.http.ssl.enabled: true`
`xpack.security.http.ssl.keystore.path: /data/elk/elastic-certificates.p12`
`xpack.security.http.ssl.truststore.path: /data/elk/elastic-certificates.p12`

### Problem
- the Elasticsearch docker container doesn't start anymore
- /data/elk/log/tpotcluster.log shows this exception:
`Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 48454144202f20485454502f312e310d0a486f73743a20656c61737469637365617263683a393230300d0a436f6e74656e742d4c656e6774683a20300d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a0d0a
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1182) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
        ... 15 more
`

**Comment by t3chn0m4g3** [comment]
T-Pot 19.03 relies on Elastic Stack 6.6.2 which does not support SSL.

**Comment by jonas-osw** [comment]
Thank you for the fast reply. That's too bad. Will this be possible in 19.10  or any other release in the future?

**Comment by t3chn0m4g3** [comment]
Not decided yet (#250). I personally do not think it is the best idea to use docker for a central instance as already pointed out in #250. While it will work the limits on storage, memory, io will usually lead to a physical installation anyways once you exceed more than a couple of seats.
There will be no 19.10 release in the traditional sense since updates will be within the 19.03 branch. While updating to 7.x will probably make some power users happy, 6.6.2 is the most stable release we had in a long time, and [is supported until July 2020](https://www.elastic.co/support/eol). With regard to the features needed in the T-Pot core it is viable that current installations will not break when we update the docker images. When we update it will be slowly within the 6.x branches working slowly towards 7.x as it matures.

**Comment by jonas-osw** [comment]
Okay. I'm not an ELK expert. Do you think it is possible to install a central ELK instance in the current version and without docker and then deliver the T-Pot events to this instance?
Or will this be a problem because T-Pot uses 6.x and the central instance 7.x?

**Comment by iukea1** [comment]
This can all be done, by modifying the logstash.conf file.

What you can also do is get valid tls/ssl by modifying the Nginx docked
container and registering a domain name and building your own Ngnix image

**Comment by iukea1** [comment]
Also Xpack new "free" security features are not until elk 6.8
Tpot I currently in 6.6.

Elk 7.x is kinda a pain right now.
I went back 6.8 from and had to restore from my elk snapshots

**Comment by jonas-osw** [comment]
Thanks for the input. I just installed the described setup successfully. I now have

- a central instance with the current version of Elasticsearch and Kibana (7.3) running on debian 10 in a VMWare virtual machine
- a T-Pot standard installation 19.03 with Logstash configured to send all events to the central Elasticsearch instance
- so the connection of Logstash 6.6.2 and Elasticsearch/Kibana 7.3 works perfectly fine (you just have to delete _document_type => "doc" _ from the output section in logstash.conf

I will now try to set everything up with TLS/SSL

**Comment by t3chn0m4g3** [comment]
@jonas-osw Thank you, sharing is always appreciated.

**Comment by jonas-osw** [comment]
Okay I got the described setup up and running with Basic User Authentication and TLS/SSL encryption enabled. 
All T-Pot instances are now delivering their events securely to a central ELK instance. 
Imo this is a good way to set up T-Pot as a distributed installation with central logging/dashboard.

If you are interested in the necessary configuration changes I can post them here.

**Comment by t3chn0m4g3** [comment]
@jonas-osw Please do, there are for sure some users who will be happy to have it.

**Comment by jonas-osw** [comment]
Here is what I did:
### Central ELK instance

- Install Debian 10, Java JDK, Elasticsearch 7.3 and Kibana 7.3
- Generate certificates
```
cd /usr/share/elasticsearch/bin/
./elasticsearch-certutil cert --dns <FQDN or IP> --name <hostname> --pem
```
- this generates the CA certificate, instance certificate and instance key in a .zip file one dir above
- move the zip to a desired location and extract it
- edit your elasticsearch.yml
```
cluster.name: t-pot-central
node.name: node1
network.host 0.0.0.0
http.port: 64298
cluster.initial_master_nodes: ["node1"]
xpack.security.enabled: true
# internode communication (required if xpack.security is enabled)
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: /path/to/<hostname>.key
xpack.security.transport.ssl.certificate: /path/to/<hostname>.crt
xpack.security.transport.ssl.certificate_authorities: [ "/path/to/ca.crt" ]
# client to node communication
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.key: /path/to/<hostname>.key
xpack.security.http.ssl.certificate: /path/to/<hostname>.crt
xpack.security.http.ssl.certificate_authorities: [ "/path/to/ca.crt" ]
#Workaround for logstash error Encountered a retryable error. Will retry with exponential backoff
http.max_content_length: 1gb
```
- enable built-in users and set passwords
`/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive`
- edit your kibana.yml
```
server.host: "0.0.0.0"
elasticsearch.hosts: ["https://<FQDN or IP>:64298"]
elasticsearch.username: "kibana"
elasticsearch.password: "<your pw>"
elasticsearch.ssl.certificate: /path/to/<hostname>.crt
elasticsearch.ssl.key: /path/to/<hostname>.key
elasticsearch.ssl.certificateAuthorities: ["/path/to/ca.crt"]
```
- restart ES and Kibana
- you should now be able to acces Kibana at <hostname>:5601
- Create logstash index pattern in Kibana: Kibana->Management->Index Patterns->create-> logstash-*
- Create logstash user in Kibana
    - Management->Roles->Create role
Role name: logstash_writer
cluster privileges: manage_index_templates, monitor
Indices: logstash-* Privileges: write, delete, create_index
    - Management->Users->Create user
Username: logstash_internal
Roles: logstash_writer
### T-Pot instances
- copy the CA certificate of your central ELK instance onto your T-Pot instances
- follow this guide (without the adjustments): https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-logstash.conf
- edit your logstash.conf
```
outputs{
		elasticsearch{
			hosts => ["https://<FQDN or IP>:64298"]
			#document_type => "doc" #or remove this line
			ssl => true
			cacert => '/data/elk/ca.crt'
			user => 'logstash_internal'
			password => '<your pw>'
		}
	}
```
### Notes
- decide if you want to user your FQDN or IP address and use it **everywhere**
- whichever you choose, generate your certificate accordingly and use it in every configuration file
- otherwise the communication between E, L and K will fail because some specified hostname doesn't match the certificate hostname

**Comment by ctminime** [comment]
This is great. We are looking to do multiple t-pots with centralized logging in AWS. In an effort to reduce the size of the instances, what services can I completely disable on the t-pot nodes when doing this? I would guess Kibana and Elastic Search. How should I properly disable them to survive reboots?

**Comment by nbglink** [comment]
Here is a vide which can give you some guidelines - https://youtu.be/dhZqXvZmtiM

**Comment by lcia-projects** [comment]
@ctminime this is similar to a project i'm working on. (sorry for the late replay, i just saw this)
If you're still trying to do this.. my approach was this:

- install a sensor version of tpot 
- install filebeat on tpot, configure filebeat to watch honeypot logs and transmit logs to central logstash server
- logstash sends directly to your central ES cluster.. or to a message queue (reddis, rabbitmq, etc) for load balancing then to es cluster

i've have it working for about a year. i've got 5 sensors around the state sending to my central office
