### ISSUE TITLE
Bug ticket log collector script

### ISSUE THREAD

**Issue by amishrabbit** [telekom-security/tpotce#630]
Hey there. I had a funny five minutes and wrote you all a bash script to collect the various disparate log data that you request by default when someone files a bug ticket about the T-Pot. 

The script pulls together the requested data and zips it into a single package which the bug submitter can then attach to their ticket. It needs to be run as root, and it will install two new applications, zip and aha, on a barebones T-Pot installation. (It uses aha to create an html "screenshot" of the htop and glances screens)

Sorry I didn't know how to share the file with you another way. Feel free to share with others, if you find it useful.
[bugcollect.sh.txt](https://github.com/dtag-dev-sec/tpotce/files/4590059/bugcollect.sh.txt)

**Comment by t3chn0m4g3** [comment]
Thanks. Looks good, will be building up on that and provide a solution.
