### ISSUE TITLE
How to send data to another destination.

### ISSUE THREAD

**Issue by austinsonger** [telekom-security/tpotce#685]
How to send the event data to another destination like to Elastic SIEM.

I followed this https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-logstash.conf

But there is no `/logstash.conf`  in `/data/elk`

**Comment by t3chn0m4g3** [comment]
It seems you did not extract `logstash.conf` as described.

**Comment by austinsonger** [comment]
Okay. Nevermind. 

How would I add the following to `/data/elk/logstash.conf` 

```
cloud.id: "######:#######"
cloud.auth: "######:####### "
```

**Comment by austinsonger** [comment]
If a add username and password would it look like this.

```
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    auth => {
     "username" => "'elastic'"
     "password" => "'changeme'"
    }
    # With ILM in place we need to set the daily index manually, if not => FUBAR
    index => "logstash-%{+YYYY.MM.dd}"
#    document_type => "doc"
  }
```

I'm going off basic authentication.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html

Or Elastic API

```
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
     auth: {
       "apiKey" => "'base64EncodedKey'"
     }
    # With ILM in place we need to set the daily index manually, if not => FUBAR
    index => "logstash-%{+YYYY.MM.dd}"
#    document_type => "doc"
  }
```
