### ISSUE TITLE
Some dashboards missing after update

### ISSUE THREAD

**Issue by xcampax** [telekom-security/tpotce#688]
## ⚠️ Basic support information (commands are expected to run as `root`)

--> see attached files

[bugticket_log.zip](https://github.com/telekom-security/tpotce/files/5167808/bugticket_log.zip)

I upgraded to the latest version from 19.x this morning (NextGen edition), and although I see the new honeypots running (via dps.sh), I am not seeing all dashboards, specifically the new honeysap and ipp are not listed. What did I miss?

**Comment by t3chn0m4g3** [comment]
You need to download, extract and import the new objects:
https://github.com/telekom-security/tpotce/blob/master/etc/objects/kibana_export.ndjson.zip

**Comment by xcampax** [comment]
Thanks. Once I had figured out how to [import](https://github.com/telekom-security/tpotce/wiki/Import---Export-Kibana-Objects#import) the file, I was all set :+1:
