### ISSUE TITLE
Docker container issues

### ISSUE THREAD

**Issue by sirgos69420** [telekom-security/tpotce#692]
Hi T-Pot team.

I'm very new to using T-Pot. The issue I'm having is I noticed that after I installed T-Pot, I have this issue where whenever I run a docker image (such as nginx, logstash, conpot, ciscoasa, glutton, heralding, honeypy, etc)

It would exit immediately.

I even tried running the containers from Terminal, and Admin UI.

I Assumed that it could be something was wrong with the installation, to the point I think I'm starting to consider reinstalling T-Pot.

And also I can't access the Web UI
![image](https://user-images.githubusercontent.com/70746982/92558354-e9d59800-f2a0-11ea-92a4-addcdd6b441b.png)

What do you think?
Let me know if there are some things you would like to clarify, any logs do you want see, or any issue number I would like to take a look.
Thank you.

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
![image](https://user-images.githubusercontent.com/70746982/92557420-c4e02580-f29e-11ea-9c8e-a125e22a2d5b.png)
- What T-Pot version are you currently using?
**20.06**
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
**Standard**
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
**VM**
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
**NO**
- How long has your installation been running?
**Only few hours**
- Did you install upgrades, packages or use the update script?
**Yes**
- Did you modify any scripts or configs? If yes, please attach the changes.
**No**
- Please provide a screenshot of `glances` and `htop`.
glances
![image](https://user-images.githubusercontent.com/70746982/92557579-17214680-f29f-11ea-8b7e-84bf10b5ad3b.png)

htop
![image](https://user-images.githubusercontent.com/70746982/92557648-433cc780-f29f-11ea-9719-79a23c910ebd.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/70746982/92557683-5d76a580-f29f-11ea-97e7-c48ab284588d.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/70746982/92557795-9e6eba00-f29f-11ea-891f-b7e0500f3f0c.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/70746982/92557907-eee61780-f29f-11ea-86dc-caafa9f4f7b2.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/70746982/92557981-19d06b80-f2a0-11ea-8e10-3c5c2b573563.png)

**Comment by t3chn0m4g3** [comment]
It seems you started some containers individually and you did not stop and removed them. This might prevent `docker-compse` from starting the `tpot.service` properly. T-Pot's container are always meant to be started with the service `systemctl [start, stop] tpot` which is done automatically.

**Comment by sirgos69420** [comment]
Thanks for the reply, I think the first time I started T-Pot, all of the containers were not running so I went to the Admin UI to run them individually. Maybe I'll try to to stop all of the container and off and on T-Pot, to see if it does fix the problem. 

Are there any other things I should be concern about?

**Comment by sirgos69420** [comment]
Sorry, no luck. Even if I restarted tpot, its still the same result.
![image](https://user-images.githubusercontent.com/70746982/92573521-7f305680-f2b8-11ea-8a72-9bef8c10169f.png)

Do you think docker could be the only problem here? or are there any other factors that I did not see based on the basic support info I've provided?

**Comment by t3chn0m4g3** [comment]
You can try ...
`systemstl status tpot`, `journalctl -u tpot -f` or after `systemctl stop tpot` a `docker-compose -f /opt/tpot/etc/tpot.yml up` to see if there are any helpful error messages.

**Comment by sirgos69420** [comment]
**systemctl status tpot**
![image](https://user-images.githubusercontent.com/70746982/92583914-988bcf80-f2c5-11ea-9de6-5db80de88592.png)

**journalctl -u tpot -f**
![image](https://user-images.githubusercontent.com/70746982/92585433-8874ef80-f2c7-11ea-8e6a-b3ffe1701017.png)
![image](https://user-images.githubusercontent.com/70746982/92585433-8874ef80-f2c7-11ea-8e6a-b3ffe1701017.png)
![image](https://user-images.githubusercontent.com/70746982/92585433-8874ef80-f2c7-11ea-8e6a-b3ffe1701017.png)
![image](https://user-images.githubusercontent.com/70746982/92585782-fde0c000-f2c7-11ea-84fd-df5b92fc5d54.png)
![image](https://user-images.githubusercontent.com/70746982/92585900-28cb1400-f2c8-11ea-803a-3877caabc0b4.png)
![image](https://user-images.githubusercontent.com/70746982/92585976-3da7a780-f2c8-11ea-8706-d408b8978141.png)
![image](https://user-images.githubusercontent.com/70746982/92586026-4ef0b400-f2c8-11ea-8b43-ab0b157c338a.png)
![image](https://user-images.githubusercontent.com/70746982/92586073-6039c080-f2c8-11ea-80fb-bc12d82e5291.png)
![image](https://user-images.githubusercontent.com/70746982/92586145-76478100-f2c8-11ea-8599-92232695f2d0.png)
![image](https://user-images.githubusercontent.com/70746982/92586207-88292400-f2c8-11ea-9917-4d68f1d91f65.png)
![image](https://user-images.githubusercontent.com/70746982/92586262-9b3bf400-f2c8-11ea-878b-fee8e7071957.png)
![image](https://user-images.githubusercontent.com/70746982/92586321-a98a1000-f2c8-11ea-8bc3-e8f2e5e3279c.png)
![image](https://user-images.githubusercontent.com/70746982/92586461-d6d6be00-f2c8-11ea-9739-90c0adeea6e7.png)
![image](https://user-images.githubusercontent.com/70746982/92586517-e950f780-f2c8-11ea-89cf-94f39169f2ef.png)
![image](https://user-images.githubusercontent.com/70746982/92586595-084f8980-f2c9-11ea-92a0-e28bfdf190c5.png)
![image](https://user-images.githubusercontent.com/70746982/92586658-25845800-f2c9-11ea-8e6f-32a2303d15e4.png)
![image](https://user-images.githubusercontent.com/70746982/92586708-3634ce00-f2c9-11ea-8b76-ad0997346666.png)
![image](https://user-images.githubusercontent.com/70746982/92586768-4cdb2500-f2c9-11ea-8597-116201135e8c.png)
![image](https://user-images.githubusercontent.com/70746982/92586835-5ebcc800-f2c9-11ea-91cf-50290311f724.png)


Oh! there's also that one time, we tried to see the running containers using docker ps -a
sadly no container was running
so we tried to run docker hello world container for debugging
then we check if the containers start to run
then after that the hello world disappeared
so then we tried to stop and start docker

systemctl stop docker
systemctl start docker

then we tried it again then the hello world, then starts to work.
Let me know if you need some clarification.

**Comment by t3chn0m4g3** [comment]
What about `docker-compose -f /opt/tpot/etc/tpot.yml up`. However, if that does not work try a reinstall or the post-install method as described in the *README*.

**Comment by sirgos69420** [comment]
**docker-compose -f /opt/tpot/etc/tpot.yml up**
![image](https://user-images.githubusercontent.com/70746982/92671975-3a550000-f34a-11ea-9e00-e1605ca60bef.png)

**Comment by t3chn0m4g3** [comment]
There seems to be something very wrong with the installation, because that's how it should look like on a fresh installation:
```
docker-compose -f /opt/tpot/etc/tpot.yml up
Creating network "etc_adbhoney_local" with the default driver
Creating network "etc_ciscoasa_local" with the default driver
Creating network "etc_citrixhoneypot_local" with the default driver
Creating network "etc_conpot_local_IEC104" with the default driver
Creating network "etc_conpot_local_guardian_ast" with the default driver
Creating network "etc_conpot_local_ipmi" with the default driver
Creating network "etc_conpot_local_kamstrup_382" with the default driver
Creating network "etc_cowrie_local" with the default driver
Creating network "etc_dicompot_local" with the default driver
Creating network "etc_dionaea_local" with the default driver
Creating network "etc_elasticpot_local" with the default driver
Creating network "etc_heralding_local" with the default driver
Creating network "etc_honeypy_local" with the default driver
Creating network "etc_honeysap_local" with the default driver
Creating network "etc_ipphoney_local" with the default driver
Creating network "etc_mailoney_local" with the default driver
Creating network "etc_medpot_local" with the default driver
Creating network "etc_rdpy_local" with the default driver
Creating network "etc_tanner_local" with the default driver
Creating network "etc_cyberchef_local" with the default driver
Creating network "etc_default" with the default driver
Creating network "etc_ewsposter_local" with the default driver
Creating network "etc_spiderfoot_local" with the default driver
Creating conpot_iec104       ... done
Creating ewsposter           ... done
Creating cyberchef           ... done
Creating conpot_kamstrup_382 ... done
Creating tanner_phpox        ... done
Creating glutton             ... done
Creating nginx               ... done
Creating honeypy             ... done
Creating honeysap            ... done
Creating dicompot            ... done
Creating citrixhoneypot      ... done
Creating rdpy                ... done
Creating cowrie              ... done
Creating mailoney            ... done
Creating tanner_redis        ... done
Creating dionaea             ... done
Creating fatt                ... done
Creating p0f                 ... done
Creating elasticpot          ... done
Creating ipphoney            ... done
Creating adbhoney            ... done
Creating elasticsearch       ... done
Creating medpot              ... done
Creating conpot_ipmi         ... done
Creating heralding           ... done
Creating ciscoasa            ... done
Creating suricata            ... done
Creating conpot_guardian_ast ... done
Creating spiderfoot          ... done
Creating tanner_api          ... done
Creating tanner              ... done
Creating snare               ... done
```

This can have all kinds of causes, in Windows 10 mostly if WSL or WSL2 is activated and VirtualBox is being used as hypervisor, since VirtualMachinePlatform from Microsoft and VirtualBox are not playing well together (yet). Even a reinstall of T-Pot might not solve things unless VMP and WSL/2 are taken care of.

**Comment by sirgos69420** [comment]
**Post-install auto**
![image](https://user-images.githubusercontent.com/70746982/92689715-1b6a6400-f372-11ea-8679-a6af8f23c6ec.png)

**Post-Install user**
![image](https://user-images.githubusercontent.com/70746982/92690014-b6fbd480-f372-11ea-9a44-45c845f9ac28.png)

Looks like the Post-Install Methods didn't work as well. 

I was thinking about reinstalling though, but it was sad to see that it would not solve the problem as well.

**Comment by t3chn0m4g3** [comment]
You cannot run the installer on top of an existing T-Pot installation, you will need a fresh Debian install as described in the Readme.
