### ISSUE TITLE
my tpot docker always Exited

### ISSUE THREAD

**Issue by NeverMore00wolf** [telekom-security/tpotce#693]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux deafline 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

- What T-Pot version are you currently using?
20
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
no  i have runing 2days
- How long has your installation been running? 
2days
- Did you install upgrades, packages or use the update script?
no
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
disk is enough
- What is the current container status (`dps.sh`)?
NAME                  STATUS                       PORTS
adbhoney              Exited (137) 5 hours ago
ciscoasa              Exited (137) 5 hours ago
citrixhoneypot        Exited (137) 5 hours ago
conpot_guardian_ast   Exited (137) 5 hours ago
conpot_iec104         Exited (137) 5 hours ago
conpot_ipmi           Exited (137) 5 hours ago
conpot_kamstrup_382   Exited (137) 5 hours ago
cowrie                Exited (137) 5 hours ago
cyberchef             Exited (137) 5 hours ago
dicompot              Exited (2) 5 hours ago
dionaea               Exited (137) 5 hours ago
elasticpot            Exited (137) 5 hours ago
elasticsearch         Exited (137) 5 hours ago
ewsposter             Exited (137) 5 hours ago
fatt                  Exited (137) 5 hours ago
head                  Exited (137) 5 hours ago
heralding             Exited (137) 5 hours ago
honeysap              Exited (137) 5 hours ago
honeytrap             Exited (0) 5 hours ago
kibana                Exited (137) 5 hours ago
logstash              Exited (137) 5 hours ago
mailoney              Exited (137) 5 hours ago
medpot                Exited (2) 5 hours ago
nginx                 Exited (137) 5 hours ago
p0f                   Exited (0) 5 hours ago
rdpy                  Exited (137) 5 hours ago
snare                 Exited (137) 5 hours ago
spiderfoot            Exited (137) 5 hours ago
suricata              Exited (137) 5 hours ago
tanner                Exited (137) 5 hours ago
tanner_api            Exited (137) 5 hours ago
tanner_phpox          Exited (137) 5 hours ago
tanner_redis          Exited (137) 5 hours ago

- What is the status of the T-Pot service (`systemctl status tpot`)?
 tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-09-10 05:12:58 CST; 5h 5min ago
  Process: 8829 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 8853 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 8979 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 11193 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 11196 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 11229 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 11262 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 11297 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 11333 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, st
  Process: 11339 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=
  Process: 11345 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SU
  Process: 11351 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
  Process: 11374 ExecStart=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color (code=exited, status=0/SUCCESS)
  Process: 9125 ExecStop=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=1/FAILURE)
  Process: 19257 ExecStopPost=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset (code=exited, status=0/SUCCESS)
 Main PID: 11374 (code=exited, status=0/SUCCESS)

9月 10 05:12:58 deafline rules.sh[19257]: All arguments met. Continuing.
9月 10 05:12:58 deafline rules.sh[19257]: Detected honeytrap as NFQ based honeypot, iptables-legacy rules needed. Continuing.
9月 10 05:12:58 deafline rules.sh[19257]: /opt/tpot/bin/rules.sh:行36: yq：
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Please provide answers to all the questions.

**Comment by t3chn0m4g3** [comment]
Probably resolved.
