### ISSUE TITLE
nginx missing certificates

### ISSUE THREAD

**Issue by flngkttn** [telekom-security/tpotce#694]
Hello 
Thank you for your work
I have an issue with nginx. Because of that I'm unable to open WebUI.

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? debian 10.5 buster
- What T-Pot version are you currently using? master
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. - none
- How long has your installation been running? - 1 day
- Did you install upgrades, packages or use the update script? - I used update script
- Did you modify any scripts or configs? If yes, please attach the changes. - no
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)? - enough
- What is the current container status (`dps.sh`)? - nginx and elasticpot is down, others are healthy
- What is the status of the T-Pot service (`systemctl status tpot`)? - active
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

nginx logs in /data/nginx/log says following:

2020/09/10 04:40:08 [emerg] 1#1: cannot load certificate "/etc/nginx/cert/nginx.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/cert/nginx.crt','r') error:2006D080:BIO ro$
2020/09/10 04:41:01 [emerg] 1#1: cannot load certificate "/etc/nginx/cert/nginx.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/cert/nginx.crt','r') error:2006D080:BIO ro$
2020/09/10 04:42:02 [emerg] 1#1: cannot load certificate "/etc/nginx/cert/nginx.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/cert/nginx.crt','r') error:2006D080:BIO ro$

**Comment by flngkttn** [comment]
Problem is solved by running this script

  fuBANNER "NGINX Certificate"
  myINTIP=$(hostname -I | awk '{ print $1 }')
  mkdir -p /data/nginx/cert
  openssl req \
          -nodes \
          -x509 \
          -sha512 \
          -newkey rsa:8192 \
          -keyout "/data/nginx/cert/nginx.key" \
          -out "/data/nginx/cert/nginx.crt" \
          -days 3650 \
          -subj '/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd' \
          -addext "subjectAltName = IP:$myINTIP"

**Comment by t3chn0m4g3** [comment]
Thank you. That's odd. The certificate is generated upon installation.
