### ISSUE TITLE
can't access https://x.x.x.x:64297

### ISSUE THREAD

**Issue by zaijianbch** [telekom-security/tpotce#695]
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux scottishbrochure 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
- What T-Pot version are you currently using?
20.06
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
KVM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
50 days
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
/opt/tpot/docker/suricata/dist/suricata/dist/suricata.yaml
#- emerging-trojan.rules > - emerging-trojan.rules
/opt/tpot/bin/rules.sh
![88275813-94552400-cd10-11ea-84ad-8c6ef88e4c81](https://user-images.githubusercontent.com/23326846/92689413-8ff0d300-f371-11ea-9250-2f06500078a7.png)
- Please provide a screenshot of `glances` and `htop`.
glances
![1599718909(1)](https://user-images.githubusercontent.com/23326846/92689517-b6167300-f371-11ea-9903-e76a3475b4d8.jpg)
htop
![1599718943](https://user-images.githubusercontent.com/23326846/92689532-badb2700-f371-11ea-84a5-87cf380d2929.jpg)
- How much free disk space is available (`df -h`)?
106G
- What is the current container status (`dps.sh`)?
![1599719409(1)](https://user-images.githubusercontent.com/23326846/92689665-faa20e80-f371-11ea-876a-70ec639267e8.jpg)
- What is the status of the T-Pot service (`systemctl status tpot`)?
![1599719031(1)](https://user-images.githubusercontent.com/23326846/92689677-04c40d00-f372-11ea-9b23-139847db857d.jpg)
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
It's OK
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
No

I have installed TPOT 50 days , it runs very well.
But today I find I can't open the https://x.x.x.x:64297
![1599719592(1)](https://user-images.githubusercontent.com/23326846/92689857-6c7a5800-f372-11ea-8727-2c108af3e6ca.jpg)
But I can open https://x.x.x.x:64297/kibana/
![1599719705(1)](https://user-images.githubusercontent.com/23326846/92689995-ae0b0300-f372-11ea-9edd-312d719ba6ea.jpg)
I also can open https://x.x.x.x:64294
I want know why I cant open https://x.x.x.x:64297 
Thank you.

**Comment by t3chn0m4g3** [comment]
Just to make sure you are running all the latest settings and images, please run `update.sh` from `/opt/tpot` as `root`.
Checked the image, works perfectly fine in Chrome and Firefox on Windows.

**Comment by zaijianbch** [comment]
> Just to make sure you are running all the latest settings and images, please run `update.sh` from `/opt/tpot` as `root`.
> Checked the image, works perfectly fine in Chrome and Firefox on Windows.

Thank you.After update, It runs well.

**Comment by t3chn0m4g3** [comment]
Welcome.
