### ISSUE TITLE
Downloading Files

### ISSUE THREAD

**Issue by SomeInfosecGuy** [telekom-security/tpotce#696]
How can I download files from Cowrie? I've tried using scp without success.

**Comment by t3chn0m4g3** [comment]
Files which are uploaded to Cowrie are being moved via cronjob; see `/etc/crontab`. This avoids Cowrie being misused.

**Comment by SomeInfosecGuy** [comment]
I see where dionaea uploaded files are moved, but not cowrie. I still see the files uploaded to cowrie yesterday are still in the data/downloads folder.

**Comment by t3chn0m4g3** [comment]
I don't think this is even possible.

**Comment by SomeInfosecGuy** [comment]
I could bring tpot down and mount the drive, but I would prefer if it remained running. The reason I want the malware is to sandbox it for analysis.

**Comment by t3chn0m4g3** [comment]
Hmm, that's all on the host in the data folder.
