### ISSUE TITLE
tpotce via serial console on PCengine APU4D4: no serial output after 1st inst-step

### ISSUE THREAD

**Issue by RogerWeihrauch** [telekom-security/tpotce#697]
Howdy Community

I did not really find any hints/help/further steps on my issue, so I opened a new 'issue'.
1st: thank you all for your incredible work on this very helpful tool
2nd: I try to install TpotCE via iso image on a PCengine's APU4D4 machine:
        succesfully mastered first round of install from ISO with cli command/serial console output:
        '... vga=off ... verbose console=ttyS0,115200n8' to get the visual output to the serial console.
So far so good for this 1st install step.
3rd: BUT, after this 1st install step is done, after reboot the output on serial console is gone, so no further config/install with any visual information/feedback from machine possible; sda/machine still working (?); not sure.
4th: I saw some txt/config files in txt form where things like autoinstall, expertinstall and so on can be configured.
Which files do I have to (re-) configure/extend with above mentioned 'çonsole='-option to have further visual output for further config?

Any further help on my issue will be really appreciated.

Thank you all and kind regards,
Roger

**Comment by t3chn0m4g3** [comment]
Thanks. You probably cannot use the ISO image since we second part of the installation takes place before TTYs are available. You can however use the [PostInstall](https://github.com/telekom-security/tpotce#postinstall) with a Debian 10 image.
