### ISSUE TITLE
Kibana Visu error

### ISSUE THREAD

**Issue by N0NameN0** [telekom-security/tpotce#698]
since some days it seems i have too much data to parse... ( but i have logstash only since 7/7/2020 )

when i try the last two months : 

![Screenshot_20200915_124044](https://user-images.githubusercontent.com/1048113/93201489-8a203680-f751-11ea-82e5-d4512b0b636d.png)

here is an example of error
![Screenshot_20200915_124157](https://user-images.githubusercontent.com/1048113/93201511-93a99e80-f751-11ea-9a9c-0a9366822dc1.png)

but it use only a little part of my ram....
![Screenshot_20200915_124401](https://user-images.githubusercontent.com/1048113/93201553-a2905100-f751-11ea-82c4-ef69984a6e2e.png)

do i have to increase a value somewhere ? ;)

**Comment by t3chn0m4g3** [comment]
That's not too much data, however with huge datasets Kibana can be picky. Have you tried upgrading to the latest 20.06.1 (`/opt/tpot/update.sh`)?

**Comment by N0NameN0** [comment]
same after update : 

![image](https://user-images.githubusercontent.com/1048113/93206283-6a8d0c00-f759-11ea-9902-a108da46c135.png)

any hint to look at ?

**Comment by N0NameN0** [comment]
here is what i can read on the kibana container output : 

`doc['task.retryAt'].value.toInstant().toEpochMilli();\\\\n}\\\\nif (doc['task.runAt'].size()!=0) {\\\\n  return doc['task.runAt'].value.toInstant().toEpochMilli();\\\\n}\\\\n    \\\"}}}],\\\"seq_no_primary_term\\\":true,\\\"script\\\":{\\\"source\\\":\\\"ctx._source.task.ownerId=params.ownerId; ctx._source.task.status=params.status; ctx._source.task.retryAt=params.retryAt;\\\",\\\"lang\\\":\\\"painless\\\",\\\"params\\\":{\\\"ownerId\\\":\\\"kibana:1a5fee71-bce4-4fac-a9a8-4aae02fe3dd3\\\",\\\"status\\\":\\\"claiming\\\",\\\"retryAt\\\":\\\"2020-09-15T11:53:02.830Z\\\"}}}\",\"statusCode\":429,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [2063628510/1.9gb], which is larger than the limit of [1972122419/1.8gb], real usage: [2063621320/1.9gb], new bytes reserved: [7190/7kb], usages [request=480/480b, fielddata=5243870/5mb, in_flight_requests=7190/7kb, accounting=121866396/116.2mb]\\\"`

**Comment by t3chn0m4g3** [comment]
ES seems to need more RAM. You can change Xms/Xmx lines to 4096 in `/opt/tpot/etc/tpot.yml`.

**Comment by N0NameN0** [comment]
All seems ok now ;) thx ;)

**Comment by t3chn0m4g3** [comment]
Welcome
