### ISSUE TITLE
Suricata Logs CSV

### ISSUE THREAD

**Issue by SomeInfosecGuy** [telekom-security/tpotce#699]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
20.06.1
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Baremetal, 16GB RAM, FX 8320e
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
One week
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
1.6TB
- What is the current container status (`dps.sh`)?
Up
- What is the status of the T-Pot service (`systemctl status tpot`)?
Active
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

I want to download the Suricata logs for specific searches from honeypot dashboards (e.g. cowrie) to a CSV file but the error "We couldn't generate your CSV at this time." is displayed. I want to create a pivot table to analyze the data and put it in a threat intelligence platform.

**Comment by t3chn0m4g3** [comment]
Sorry, works perfectly fine here.

Please describe exactly what you are doing incl. screenshots and provide logs from Kibana (`docker logs kibana`) and ES (`docker logs elasticsearch`) at the timestamp when the error occurs.

**Comment by SomeInfosecGuy** [comment]
I've edited the Cowrie dashboard to include Suricata logs. When I click the three horizontal buttons then click Download CSV I get an error stating that the CSV couldn't be generated.

![image](https://user-images.githubusercontent.com/47999472/93499700-5542e980-f8e1-11ea-9bbc-ebccf4a90d79.png)
![image](https://user-images.githubusercontent.com/47999472/93499784-6c81d700-f8e1-11ea-9b96-da4909c3ce89.png)

Kibana:
time 16:40z

![image](https://user-images.githubusercontent.com/47999472/93501230-275ea480-f8e3-11ea-9b8e-a27015db7d61.png)
![image](https://user-images.githubusercontent.com/47999472/93501282-38a7b100-f8e3-11ea-9f58-d6a9523610b0.png)

Elasticsearch:
no related logs to the issue it appears

![image](https://user-images.githubusercontent.com/47999472/93501404-655bc880-f8e3-11ea-9073-8b30414ac45e.png)

**Comment by t3chn0m4g3** [comment]
I can confirm this does not work and seems to be a limitation of Kibana, at least according to googling the error.

You can follow this guide however which works for me:
https://reelyactive.github.io/diy/kibana-export-data-csv-file/

**Comment by SomeInfosecGuy** [comment]
That certainly works. Thank you!

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback. Closing this.
