### ISSUE TITLE
some confusion on user management/handling in freshly installed TpotCE 20.06: no login possible

### ISSUE THREAD

**Issue by RogerWeihrauch** [telekom-security/tpotce#702]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info">
Hello Support
I freshly installed TpotCE 20.06 w/ auto-install --user option. Inst ran smoothly and no issues while inst.
After reboot I wanted to log into (web) pages named on visual console output: IP and related ports.
But, the only one which really works is the ADMIN page, I tried all other users created/intended for use, like the webuser, for other webpages with no success.
So, my question is:
1st) which user is used for which webpage? (in this kind of installation)
2nd) where/how does tpot store (any additional) user/login information on them?
3rd) are there any further option/possibilities to influence/config user/pswd during auto-install --user?
Also, I am not able to change/add any user information on ADMIN webpage; even with ordinary user created in base debian installation.
Could you please tell me what I am doing (probably) wrong during inst process/using available users for this fresh sytem?
Any hint/help will be highly appreciated.
Thanks to all of you,
Roger
</a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

- What T-Pot version are you currently using?
I am running tpotce 20.06 install with 'auto-install --user' on debian buster 10
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
I'am running tpotce 20.06 on debian Buster (10.5, kernel: v4.19-xxx)
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
It's an (AMDAPU: screenshot 'architecture') apu4d4 from PCEngines w/ console ttyS0 interface, mainly used for admin
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No probs during install, but hereafter using/admin it any further (-> user management)
- How long has your installation been running?
It's a freshly installed one (yesterday evening)
- Did you install upgrades, packages or use the update script?
no, not yet
- Did you modify any scripts or configs? If yes, please attach the changes.
no, not yet since user management (for web and admin page) is not clear to me
- Please provide a screenshot of `glances` and `htop`.
(screenshot: glances)
- How much free disk space is available (`df -h`)?
(screenshot: df_h)
- What is the current container status (`dps.sh`)?
(screenshot: dps_sh): STRANGE, script not to be found
- What is the status of the T-Pot service (`systemctl status tpot`)?
(screenshot: systemctl_status_tpot)
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
(screenshot: netstat_tulpen)
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
Well, no entries here until now

[tpotce_user_problem.zip](https://github.com/telekom-security/tpotce/files/5281003/tpotce_user_problem.zip)

**Comment by t3chn0m4g3** [comment]
Please follow the [documentation](https://github.com/telekom-security/tpotce#post-install-auto). Also please keep in mind that it is highly likely (#697) that your hardware is not [supported](https://github.com/telekom-security/tpotce#post-install-auto).
