### ISSUE TITLE
Suricata Alerts - detecting own system

### ISSUE THREAD

**Issue by paedi18** [telekom-security/tpotce#703]
Hello

I am running a T-Pot for 3 days now. On the Suricata Dashboard there is the ip-adress of my T-Pot the first place in the "Suricata Source IP - Top 10". At this time there are already 110000 Events only from that ip-adress.

Any solutions or explanations?

Best regards,
Patrick

**Comment by t3chn0m4g3** [comment]
This seems to be normal behavior, since Suricata will record *all* ingress and egress traffic and as such all TCP replies as well.
