### ISSUE TITLE
Help setting up a distributed secure install of TPot (sensors -> Manager / Collector)

### ISSUE THREAD

**Issue by MelCrypto** [telekom-security/tpotce#704]
Hello, 
I have been looking for clear instructions / docos on how to deploy a distributed honeypot network with multiple sensors reporting to the same Collector/Manager for the current version or at least running on Debian and it is not easy,

Can someone share their config or doco in regards to how to deploy this either using SSH tunneling or Linux VPN, or plain TLS/Cert authentication it would be great,

Also, how to integrate HPFeeds to DShield would be lovely 👍 

And a recommended way of automating deployment (happy to be ansible) can be anything really,

Thanks for the help, and AMAZING product this TPot of yours !!!!

**Comment by t3chn0m4g3** [comment]
Thanks for the kind words. Please check out #250 regarding a distributed setup. We do not support DShield.
