### ISSUE TITLE
### Checking for installer dpendencies: [ OK ] Aborting. Debian kali-rolling is not supported.

### ISSUE THREAD

**Issue by skilltroll** [telekom-security/tpotce#705]
trying to install this on my last kali linux update and it gives me this error and i had the tool on kali vmware like 4 months ago and it was working fine and i have installed it without any problems is it just not supporting kali anymore ?

**Comment by t3chn0m4g3** [comment]
Kali was never supported, only Debian 10.x is. If it was working it was a happy coincidence.

**Comment by BartBoxi** [comment]
Hi, 
for me Debian 10 on GCP is not supported. Why? Should I try higher version?
