### ISSUE TITLE
Install succeeds but docker appears not to be installed

### ISSUE THREAD

**Issue by ruimmpires** [telekom-security/tpotce#709]
I installed in a VM running in VMWare from the ISO mounted in the virtual CD. All seemed fine, but the service fails as well the update. I tried to install docker by myself but I wasn't able.
Yes, I am a newbie, so I may have overlloked something basic.
Any suggestions?

**STARTING SERVICE**
systemctl start tpot
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'tpot.service'.
Authenticating as: tsec,,, (tsec)
Password: 
==== AUTHENTICATION COMPLETE ===
Failed to start tpot.service: Unit docker.service not found.

**UPDATE**
[root@domesticvalley:/opt/tpot]# ./update.sh -y

######  Now cleaning up containers. 
./update.sh: line 128: docker: command not found

### Now checking for newer files in repository ...
Fetching origin
###### Pulling updates from repository.
HEAD is now at 1afbb89 Merge pull request #691 from brianlechthaler/patch-1
Already up to date.

### Installing apt-fast
--2020-10-06 08:40:39--  https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.132.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.132.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21748 (21K) [text/plain]
Saving to: ‘/usr/local/sbin/apt-fast’

/usr/local/sbin/apt-fast       100%[===================================================>]  21.24K  --.-KB/s    in 0.02s   

2020-10-06 08:40:39 (1.19 MB/s) - ‘/usr/local/sbin/apt-fast’ saved [21748/21748]

### Removing repository based install of elasticsearch-curator
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package elasticsearch-curator
### Now upgrading packages ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Err:1 http://mirrors.ptisp.pt/debian stable InRelease
  403  Forbidden [IP: 130.185.80.122 80]
Hit:2 http://security.debian.org stable/updates InRelease
Reading package lists... Done                
E: Failed to fetch http://mirrors.ptisp.pt/debian/dists/stable/InRelease  403  Forbidden [IP: 130.185.80.122 80]
E: The repository 'http://mirrors.ptisp.pt/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Working... this may take a while.
E: Package 'aufs-tools' has no installation candidate
E: Package 'bash-completion' has no installation candidate
E: Unable to locate package build-essential
E: Package 'cgroupfs-mount' has no installation candidate
E: Unable to locate package cockpit
E: Unable to locate package cockpit-docker
E: Package 'debconf-utils' has no installation candidate
E: Unable to locate package docker-compose
E: Package 'ethtool' has no installation candidate
E: Package 'fail2ban' has no installation candidate
E: Unable to locate package genisoimage
E: Unable to locate package glances
E: Unable to locate package haveged
E: Unable to locate package html2text
E: Unable to locate package htop
E: Unable to locate package iw
E: Unable to locate package jq
E: Package 'libltdl7' has no installation candidate
E: Unable to locate package libpam-google-authenticator
E: Unable to locate package man
E: Unable to locate package mosh
E: Unable to locate package multitail
E: Package 'npm' has no installation candidate
E: Package 'ntp' has no installation candidate
E: Unable to locate package pass
E: Package 'pigz' has no installation candidate
E: Unable to locate package prips
E: Package 'syslinux' has no installation candidate
E: Package 'psmisc' has no installation candidate
E: Unable to locate package pv
E: Unable to locate package python3-elasticsearch-curator
E: Unable to locate package python3-pip
E: Package 'unzip' has no installation candidate
E: Package 'vim' has no installation candidate
E: Unable to locate package wireless-tools
Package manager quit with exit code.
info: Trying to set 'docker.io/restart' [boolean] to 'true'
info: Loading answer for 'docker.io/restart'
info: Trying to set 'debconf/frontend' [select] to 'noninteractive'
info: Loading answer for 'debconf/frontend'

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
./update.sh: line 203: npm: command not found
./update.sh: line 204: npm: command not found
./update.sh: line 205: pip3: command not found
./update.sh: line 207: pip3: command not found
### Removing and holding back problematic packages ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mailutils
E: Unable to locate package pcp
E: Unable to locate package cockpit-pcp
E: Unable to locate package elasticsearch-curator
exim4-base set on hold.
E: Unable to locate package mailutils
E: Unable to locate package pcp
E: Unable to locate package cockpit-pcp
E: Unable to locate package elasticsearch-curator

###### This might take a while, please be patient!
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found

**Comment by drphr4ud** [comment]
Please confirm which ISO you used for the install and what its checksum is on your machine. 

Did you use [this ISO ](https://github.com/telekom-security/tpotce/releases/download/20.06.1/tpot.iso) with sha256sum
`EC82438F1F15D0BEB645F0E91ABD9A843AE25699FC733CA17D1D19C775BEC5EA`

What resources (RAM etc) did you allocate to this VM, did you allocate a NIC that has internet access ? Installer needs uninterrupted internet access to work.

**Comment by ruimmpires** [comment]
sorry, long delay!
```
sha256sum tpot.iso 
ec82438f1f15d0beb645f0e91abd9a843ae25699fc733ca17d1d19c775bec5ea  tpot.iso
```
The same.

I in fact didn't give a lot of storage as I hadn't much available. Trying again. The network should be fine.

**Comment by ruimmpires** [comment]
got the same issue
![image](https://user-images.githubusercontent.com/46453695/95757000-74455900-0c9e-11eb-8bf0-3ffc3aed292f.png)
docker, among others is not installed.

**Comment by ruimmpires** [comment]
Here is the log of the update
[root@fixedpoppy:/opt/tpot]# cat update.log 

### Checking for Release ID
### Checking for version tag ...
###### 20.06.1 is eligible for the update procedure. [ OK ]

### Checking for T-Pot configuration file ...
###### /opt/tpot/etc/tpot.yml [ OK ]

### Now checking availability of ...
###### https://index.docker.io [ OK ]
###### https://github.com [ OK ]
###### https://pypi.python.org [ OK ]
###### https://debian.org [ OK ]

### Need to stop T-Pot ...
######  Now stopping T-Pot. [ OK ]
######  Now cleaning up containers. 

### Create a backup, just in case ... 
######  Building archive in /root/202010121428_tpot_backup.tgz [ OK ]

### Now checking for newer files in repository ...
Fetching origin
###### Pulling updates from repository.
HEAD is now at 6b37578 Merge pull request #706 from brianlechthaler/patch-2
Already up to date.

### Installing apt-fast
### Removing repository based install of elasticsearch-curator
Reading package lists...
Building dependency tree...
Reading state information...
### Now upgrading packages ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://security.debian.org stable/updates InRelease
Err:2 http://mirrors.ptisp.pt/debian stable InRelease
  403  Forbidden [IP: 130.185.80.122 80]
Reading package lists...
[apt-fast 14:28:20]
[apt-fast 14:28:20]Working... this may take a while.
[apt-fast 14:28:20]
[apt-fast 14:28:20]Working... this may take a while.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
### Removing and holding back problematic packages ...
Reading package lists...
Building dependency tree...
Reading state information...
exim4-base set on hold.

### Now replacing T-Pot related config files on host

### Ensure some T-Pot defaults with regard to some folders, permissions and configs.

### Now pulling latest docker images
###### This might take a while, please be patient!
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
./update.sh: line 176: docker: command not found
### If you made changes to tpot.yml please ensure to add them again.
### We stored the previous version as backup in /root/.
### Some updates may need an import of the latest Kibana objects as well.
### Download the latest objects here if they recently changed:
### https://raw.githubusercontent.com/telekom-security/tpotce/master/etc/objects/kibana_export.ndjson.zip
### Export and import the objects easily through the Kibana WebUI:
### Go to Kibana > Management > Saved Objects > Export / Import
### Or use the command:
### import_kibana-objects.sh /opt/tpot/etc/objects/kibana-objects.tgz
### All objects will be overwritten upon import, make sure to run an export first if you made changes.

### Done.

**Comment by t3chn0m4g3** [comment]
> got the same issue
> ![image](https://user-images.githubusercontent.com/46453695/95757000-74455900-0c9e-11eb-8bf0-3ffc3aed292f.png)
> docker, among others is not installed.

1. Your host does not meet the requirements. You need at least 8GB
2. As @drphr4ud posted your system cannot reach the mirrors.

Please follow the steps of the post-install method as described in the readme.

**Comment by ruimmpires** [comment]
hi,
I've defined 8GB RAM what was shown in the previous snapshot was the effective memory used. Below is a screenshot of the settings.
![image](https://user-images.githubusercontent.com/46453695/95793998-c7d79700-0cde-11eb-9a24-ba3158ec5215.png)

I found that I couldn't install anything at all until I noticed this error: Updating from such a repository can't be done securely, and is therefore disabled by default.

So, I googl around and added the 
"You can set options in your sources.list (located at /etc/apt/sources.list):
deb [trusted=yes]"
Credits: https://askubuntu.com/questions/732985/force-update-from-unsigned-repository

It is runnig the update now with quite a lot of software being installed.

**Comment by ruimmpires** [comment]
WOW!
![image](https://user-images.githubusercontent.com/46453695/95798044-da56ce00-0ce8-11eb-9538-4726167c7726.png)

**Comment by t3chn0m4g3** [comment]
Yay 😄
