### ISSUE TITLE
tsec user not all rights in the cockpit to view logs, containers and updates

### ISSUE THREAD

**Issue by mpuff** [telekom-security/tpotce#710]
Hello,

I have installed t-pot with the tpot.iso (20.06.1).
When i log in with the tsec user, i have no rights to reboot ore shutdown the server from the gui.
The Protocol tap is emty, also the container tap, but when i add the tsec user to the docker group, i can see the containers.
The tsec user has full server admin rights (it is checked in the accounts tap), also container admin rights after add to the docker group, but i can not create a new user.
When i click on the updates tap, i get the error: **Failed to obtain authentication.**

**Comment by t3chn0m4g3** [comment]
Please follow the [Cockpit documentation](https://cockpit-project.org/guide/latest/privileges#:~:text=The%20user%20can%20change%20the,the%20session%20the%20same%20privileges.) to resolve this.
