### ISSUE TITLE
No such file or directory (http://ipxe.org/2d03e13b) after reinstall iso in Proxmox

### ISSUE THREAD

**Issue by Adi-18** [telekom-security/tpotce#711]
Have to install new tpot 20.06.1 on my Proxmox-VM using iso file.
After successful(?) install and reboot I get error "Nothing to boot. No such file or directory (http://ipxe.org/2d03e13b)"

What is the problem? First installation works without any problem.

![image](https://user-images.githubusercontent.com/29123730/95615911-43301300-0a69-11eb-9238-e3c1fb5ff5f6.png)

**Comment by t3chn0m4g3** [comment]
Works perfectly fine here. Based on the information given I cannot see what the problem might be.
