### ISSUE TITLE
Install SENSOR and send to STANDARD

### ISSUE THREAD

**Issue by AntoninHL** [telekom-security/tpotce#714]
Hi,

I'm looking for the solution to just install SENSOR config on hundreds/thousands servers and to send results to a large STANDARD machine.
But as there is no ELK in SENSOR, so how to do this?
Maybe someone has a better idea for this kind of project?

Thanks a lot.

**Comment by t3chn0m4g3** [comment]
In #250 you should find some clues. Basically you would need logstash / beats to forward all events to a central ELK.

**Comment by AntoninHL** [comment]
Thanks for your reply...
I will try to do that... Not sure to success...

**Comment by t3chn0m4g3** [comment]
Unfortunately there is no single correct answer on regarding the implementation. Even when using Logstash to forward logs you will still be missing out on artefacts which will remain on the sensor host. Forwarding the artefacts will either require Filebeats or using [PEBA](https://github.com/telekom-security/PEBA) as backend while shipping logs and files with the [ewsposter](https://github.com/telekom-security/ewsposter).
