### ISSUE TITLE
Support for Proxies

### ISSUE THREAD

**Issue by an-schall** [telekom-security/tpotce#716]
In our organization, we would like to deploy honeypots to various segments of the network. While some of the honeypots will have direct Internet access (DMZ, etc.), some of the network segments can reach the Internet only via a proxy.

Currently, the description of T-Pot explicitly states that no proxified connections are support and will break the installation of T-Pot.

Ideally, support for proxies shall be added in order to allow deployment to such network segments that have no direct access to the Internet. This way, not only the perimeter could be monitored by honeypot solutions.

An alternative would be to use T-Pot for network segments with direct Internet access and home-brew solutions (i.e. installations of the individual honeypot implementations for other segments).

**Comment by t3chn0m4g3** [comment]
Please use the `makeiso.sh` and build your own ISO with proxy support builtin or setup a Debian 10.x according to your requirements, run the [post-install method](https://github.com/telekom-security/tpotce#postinstall) for T-Pot on top and setup proxy for OS and Docker according to the Debian and Docker documentation and your requirements.
The docker images we are providing however do not come with proxy support. Some of the honeypots do not even support proxies and as a consequence we cannot generally support this. The main importance is that T-Pot is able to update the docker images and the OS automatically so security updates will be downloaded alongside features.
Requests for proxy support are so limited that building this as a feature is not on the foreseeable roadmap (leaving the limited proxy support amongst the honeypots aside).

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
