### ISSUE TITLE
Database Error 

### ISSUE THREAD

**Issue by NeverMore00wolf** [telekom-security/tpotce#717]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux deafline 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
- What T-Pot version are you currently using?
20
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
dps.sh shows all docker are runing
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
hardware
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
no
- How long has your installation been running?
run about a week
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
adbhoney              Up 20 minutes             0.0.0.0:5555->5555/tcp
ciscoasa              Up 20 minutes
citrixhoneypot        Up 20 minutes             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 20 minutes             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 20 minutes             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 20 minutes             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 20 minutes             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 20 minutes             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 20 minutes (healthy)   127.0.0.1:64299->8000/tcp
dicompot              Up 20 minutes             0.0.0.0:11112->11112/tcp
dionaea               Up 20 minutes             0.0.0.0:20-21->20-21/tcp, 0.0.0.0:42->42/tcp, 0.0.0.0:81->81/tcp, 0.0.0.0:135->135/tcp, 0.0.0.0:445->445/tcp, 0.0.0.0:1433->1433/tcp, 0.0.0.0:1723->1723/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:3306->3306/tcp, 0.0.0.0:69->69/udp, 0.0.0.0:5060-5061->5060-5061/tcp, 0.0.0.0:27017->27017/tcp, 0.0.0.0:5060->5060/udp
elasticpot            Up 20 minutes             0.0.0.0:9200->9200/tcp
elasticsearch         Up 20 minutes (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 20 minutes
fatt                  Up 20 minutes
head                  Up 19 minutes (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 20 minutes             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeysap              Up 20 minutes             0.0.0.0:3299->3299/tcp
honeytrap             Up 20 minutes
kibana                Up 19 minutes (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 19 minutes (healthy)
mailoney              Up 20 minutes             0.0.0.0:25->25/tcp
medpot                Up 20 minutes             0.0.0.0:2575->2575/tcp
nginx                 Up 20 minutes
p0f                   Up 20 minutes
rdpy                  Up 20 minutes             0.0.0.0:3389->3389/tcp
snare                 Up 19 minutes             0.0.0.0:80->80/tcp
spiderfoot            Up 20 minutes (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 20 minutes
tanner                Up 20 minutes
tanner_api            Up 20 minutes
tanner_phpox          Up 20 minutes
tanner_redis          Up 20 minutes             6379/tcp

- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

when i access https://ip:64297 i get this info.
Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 11 database disk image is malformed (SQL: select * from sqlite_master where type = 'table' and name = settings)
Previous exceptions
SQLSTATE[HY000]: General error: 11 database disk image is malformed (HY000)

**Comment by t3chn0m4g3** [comment]
Running the same docker `nginx` image and it works perfectly fine. You can run `systemctl stop tpot` and then delete the `nginx` docker image and repull it.

**Comment by NeverMore00wolf** [comment]
thanks!!!!     and  where do i pull ngix docker ?

**Comment by t3chn0m4g3** [comment]
The following example is based on GHCR, if you are on Docker Hub still adjust accordingly.

```
[root@electricalsculpture:/]# systemctl stop tpot
[root@electricalsculpture:/]# docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
node                                      10.22.1-alpine      57006130ce4b        2 weeks ago         83.5MB
ghcr.io/t3chn0m4g3/slack-watchman         latest              3e4c64fa5741        6 weeks ago         55.6MB
ghcr.io/telekom-security/suricata         2006                22aacb3d3dad        6 weeks ago         111MB
ghcr.io/telekom-security/conpot           2006                04381d75f8d8        6 weeks ago         332MB
ghcr.io/telekom-security/snare            2006                66a14f8f5c05        6 weeks ago         127MB
ghcr.io/telekom-security/tanner           2006                69356045ae5a        6 weeks ago         242MB
ghcr.io/telekom-security/phpox            2006                5471f74cc65f        6 weeks ago         88MB
ghcr.io/telekom-security/redis            2006                e71d3f45e16a        6 weeks ago         32.9MB
ghcr.io/telekom-security/spiderfoot       2006                cdef00973502        6 weeks ago         211MB
ghcr.io/telekom-security/rdpy             2006                0583603818c9        6 weeks ago         96.9MB
ghcr.io/telekom-security/p0f              2006                5259fd52353a        6 weeks ago         9.59MB
ghcr.io/telekom-security/medpot           2006                3728a234e731        6 weeks ago         18.6MB
ghcr.io/telekom-security/mailoney         2006                442aeaeef087        6 weeks ago         53.7MB
ghcr.io/telekom-security/ipphoney         2006                cf5c0e0dee5f        6 weeks ago         128MB
ghcr.io/telekom-security/honeytrap        2006                85a4f45addb3        6 weeks ago         217MB
ghcr.io/telekom-security/honeysap         2006                a2e3ea5c13dd        6 weeks ago         70.2MB
ghcr.io/telekom-security/honeypy          2006                983433bad785        6 weeks ago         135MB
ghcr.io/telekom-security/heralding        2006                3d41110f518e        6 weeks ago         145MB
ghcr.io/telekom-security/logstash         2006                b3aa04f539ce        6 weeks ago         549MB
ghcr.io/telekom-security/nginx            2006                f76995662e02        6 weeks ago         111MB
ghcr.io/telekom-security/kibana           2006                25cd9c06d869        6 weeks ago         1.14GB
ghcr.io/telekom-security/glutton          2006                a010a966d666        6 weeks ago         56.4MB
ghcr.io/telekom-security/fatt             2006                3850b4afd933        6 weeks ago         179MB
ghcr.io/telekom-security/elasticsearch    2006                552f6f5a0c11        6 weeks ago         678MB
ghcr.io/telekom-security/ewsposter        2006                c0e8eed06e1b        6 weeks ago         81.5MB
ghcr.io/telekom-security/head             2006                5ffc237ccd77        6 weeks ago         65.9MB
ghcr.io/telekom-security/elasticpot       2006                3770384c12c5        6 weeks ago         134MB
ghcr.io/telekom-security/dionaea          2006                2e2eb63683d7        6 weeks ago         195MB
ghcr.io/telekom-security/dicompot         2006                e47f54f92c0a        6 weeks ago         47.2MB
ghcr.io/telekom-security/cyberchef        2006                fe028b97c347        7 weeks ago         221MB
ghcr.io/telekom-security/cowrie           2006                6202d4cc4149        7 weeks ago         114MB
ghcr.io/telekom-security/citrixhoneypot   2006                d88a1cd55424        7 weeks ago         58.9MB
ghcr.io/telekom-security/ciscoasa         2006                4513c8928d8a        7 weeks ago         72.9MB
ghcr.io/telekom-security/adbhoney         2006                add8f64381ad        7 weeks ago         59MB
node                                      10.22.0-alpine      8e473595b853        3 months ago        83.5MB
alpine                                    edge                3c791e92a856        3 months ago        5.57MB
alpine                                    3.12                a24bb4013296        4 months ago        5.57MB
[root@electricalsculpture:/]# docker rmi ghcr.io/telekom-security/nginx:2006
Untagged: ghcr.io/telekom-security/nginx:2006
Untagged: ghcr.io/telekom-security/nginx@sha256:a7c24ed166479a7a945e2a18dc9d3b9482f212d8f8d146462da298e787eaf21d
Deleted: sha256:f76995662e021272aaeaafbb748f91319aa0d3c302bdecaa2bf8c2de99fcde36
Deleted: sha256:8b6355dd6786b58b4f0c466120fdd17dc3dd5571d411aff7586c967037ddd679
Deleted: sha256:e32161ca0c782286716b270c2e3d81a2628f7f68c7dcd0f19798fe48c39c5625
Deleted: sha256:ff43ac04880aef015dd7fe17327a2d0106e21b2ae6ec086aa5851da432330d8c
Deleted: sha256:a19b6a03296a1be6d811d0f36d590e1b6e4ff75fca15a015615c256ee0ea6483
[root@electricalsculpture:/]# docker pull ghcr.io/telekom-security/nginx:2006
2006: Pulling from telekom-security/nginx
df20fa9351a1: Already exists
ba4f06d03bfc: Pull complete
33bdbdb55e90: Pull complete
Digest: sha256:a7c24ed166479a7a945e2a18dc9d3b9482f212d8f8d146462da298e787eaf21d
Status: Downloaded newer image for ghcr.io/telekom-security/nginx:2006
ghcr.io/telekom-security/nginx:2006
[root@electricalsculpture:/]# systemctl start tpot
[root@electricalsculpture:/]#
```
Should the problem persist please check if you enabled persistence for heimdall in the `tpot.yml` and remove it (probably not activated if `/data/nginx/heimdall` is empty).

**Comment by NeverMore00wolf** [comment]
thanks man , i try again!

**Comment by NeverMore00wolf** [comment]
i did as you saying.
dtagdevsec/suricata              2006                91b88f07e1fa        6 weeks ago         111MB
dtagdevsec/honeysap              2006                448668379a98        6 weeks ago         70.2MB
dtagdevsec/mailoney              2006                2de17fd5b1ce        6 weeks ago         53.7MB
dtagdevsec/cyberchef             2006                964f4db5fec5        6 weeks ago         221MB
dtagdevsec/heralding             2006                60fa850c9310        6 weeks ago         145MB
dtagdevsec/rdpy                  2006                8a38fab0f2c5        6 weeks ago         96.9MB
dtagdevsec/fatt                  2006                1d4bb5741205        6 weeks ago         179MB
dtagdevsec/citrixhoneypot        2006                be5f74c0d0bc        6 weeks ago         58.9MB
dtagdevsec/adbhoney              2006                c2c4c5f7679a        6 weeks ago         59MB
dtagdevsec/p0f                   2006                252a04b04415        6 weeks ago         9.59MB
dtagdevsec/medpot                2006                b9d71b42bc5c        6 weeks ago         18.6MB
dtagdevsec/ciscoasa              2006                75a5e2560ff7        6 weeks ago         72.9MB
dtagdevsec/head                  2006                cdebc71d20c8        6 weeks ago         65.9MB
dtagdevsec/honeytrap             2006                141a746bb256        6 weeks ago         208MB
dtagdevsec/phpox                 2006                516e0192425e        6 weeks ago         88MB
dtagdevsec/snare                 2006                1d3de8ed0c03        6 weeks ago         127MB
dtagdevsec/tanner                2006                18154956e14a        6 weeks ago         242MB
dtagdevsec/redis                 2006                de34c950f1e2        6 weeks ago         33.5MB
dtagdevsec/dionaea               2006                0da7b12074a9        6 weeks ago         187MB
dtagdevsec/ewsposter             2006                a187eb38fa27        6 weeks ago         81.5MB
dtagdevsec/cowrie                2006                64456a7a7cb7        6 weeks ago         114MB
dtagdevsec/spiderfoot            2006                154c35fb25a3        6 weeks ago         211MB
dtagdevsec/elasticpot            2006                fb1c1510d701        6 weeks ago         134MB
dtagdevsec/conpot                2006                12338c1ec17c        6 weeks ago         332MB
dtagdevsec/elasticsearch         2006                73a2a652d88c        6 weeks ago         678MB
dtagdevsec/kibana                2006                360bc9176012        6 weeks ago         1.14GB
dtagdevsec/logstash              2006                a0bb4fba1c9f        6 weeks ago         549MB
ghcr.io/telekom-security/nginx   2006                f76995662e02        7 weeks ago         111MB
dtagdevsec/dicompot              2006                354095b20076        4 months ago        38.3MB

use your nginx docker images but i still have this error.

**Comment by t3chn0m4g3** [comment]
> The following example is based on GHCR, if you are on Docker Hub still adjust accordingly.

Since you are on Docker Hub you need to use `dtagdevsec/nginx:2006` for my given example.

If this does not work I recommend a reinstall.
