### ISSUE TITLE
IP Addresses

### ISSUE THREAD

**Issue by kalodis** [telekom-security/tpotce#718]
I setup the T-Pot in a VM on my network (behind a firewall) 
I noticed the only IP address that is showing up is 10.200.1.1 (my router/firewall) IP Address. 
I reinstalled thinking it was an install issue but its the same thing? 

The T-Pot IP is 10.200.1.9 so they are on the same VLAN as well.

Ideas?

Thank you

**Comment by t3chn0m4g3** [comment]
You did use `BRIDGED` instead of `NAT`?

**Comment by kalodis** [comment]
My network is NAT.

**Comment by t3chn0m4g3** [comment]
Follow this [video](https://www.youtube.com/watch?v=XpZBXlwrOZg) on how to setup the brigdge mode. Ignore the RAM / DISK settgins, those are out of date.

**Comment by kalodis** [comment]
So i am running this through Hyper V and noticed the network is already set to bridge on the VM side.

**Comment by t3chn0m4g3** [comment]
Sorry, I am not familiar with Hyper-V. But I do not think it works too much differently from VMWare or VirtualBox which work perfectly fine when using the corresponding bridge modes.

**Comment by kalodis** [comment]
So again, the network is set to bridge, but only getting the 10.200.1.1 address. Even with Virtualbox

**Comment by t3chn0m4g3** [comment]
This seems to be related to your network setup. I just set it up with VirtualBox and VMWare Workstation on Windows and macOS and it works perfectly fine.
