### ISSUE TITLE
tpot.iso Installation

### ISSUE THREAD

**Issue by TheZLabs** [telekom-security/tpotce#719]
Haven't had problems with this method of install in the past but thought it worth mentioning. When you are going through the installation process and you have to select a mirror for the software install, all of them fail. It does not matter which location you choose. I will just install Debian and install T-Pot the other way but wanted to let someone know as the iso install has always worked for me in the past. Beyond that, love the project and will continue to use it! Thanks!

**Comment by TheZLabs** [comment]
Welp, so much for that lol. This is a clean install of Debian 10, cloned the repo and ran install script as instructed in the readme...

./install.sh --type=user

![image](https://user-images.githubusercontent.com/59536236/97652698-6846ee80-1a35-11eb-83d9-0cebe7fd4de2.png)

**Comment by t3chn0m4g3** [comment]
Please provide us with proper debug info as requested, since we cannot reproduce this behavior. Thanks.

**Comment by t3chn0m4g3** [comment]
Logs should be in the root folder /

Also, you need to allow ICMP and Traceroute so netselect-apt can work.

What country are you installing from?

When you open a new issue you see all debugs we are requesting.

**Comment by TheZLabs** [comment]
Well I used the .iso on another ESXI host and it worked fine so I guess you can close this one and I will sort out what is wrong with this other host. Little confused on where to start though. All runs through the same network, firewall, DNS, etc. And there are about 5 other Linux servers running on it. We'll assume this one is on my end.
