### ISSUE TITLE
Best Practice for Forwarding syslog to SIEM

### ISSUE THREAD

**Issue by an-schall** [telekom-security/tpotce#720]
Hi everyone,

I am trying to forward security-related events of all active honeypots via syslog to a central syslog poller. I was looking at previous issues and identified at least three different approaches in doing so:

- modify logstash.conf as explained here: https://github.com/telekom-security/tpotce/wiki/Reconfigure-logstash.conf
- use the syslog output plugin: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html
- use rsyslog as suggested here: https://github.com/telekom-security/tpotce/issues/129

My first question is whether there is a best practice for this purpose?

Second question is dedicated to the first approach. Looking at the standard logstash.conf that is shipped with a "Standard" installation type there seem to be already a lot of entries à la:

`mutate {
      rename => {
        "server_port" => "dest_port"
        "server_ip" => "dest_ip"
        "client_port" => "src_port"
        "client_ip" => "src_ip"
      }
    }` 

Would it be sufficient to replace every instance of dest_port and dest_ip to the configuration of my syslog server? Sorry for this basic question as I am not experienced with ELK at all and might need to read up on it a bit.

Thanks!

**Comment by t3chn0m4g3** [comment]
Sorry, but this is rather a matter of configuring the ELK stack to your needs, please understand that we cannot go into details in that regard. I will leave this issue open for a couple of days in case someone else can.
While we do support the `logstash-output-syslog` I recommend getting familiar with the [ELK stack](https://www.elastic.co/guide/index.html) first and you may want to concentrate on the output section...

```
# Output section
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    # With templates now being legacy and ILM in place we need to set the daily index with its template manually. Otherwise a new index might be created with differents settings configured through Kibana.
    index => "logstash-%{+YYYY.MM.dd}"
    template => "/etc/logstash/tpot_es_template.json"
#    document_type => "doc"
  }

  #if [type] == "Suricata" {
  #    file {
  #      file_mode => 0770
  #      path => "/data/suricata/log/suricata_ews.log"
  #    }
  #}
  # Debug output
  #if [type] == "CitrixHoneypot" {
  #  stdout {
  #    codec => rubydebug
  #  }
  #}
  # Debug output
  #stdout {
  #  codec => rubydebug
  #}

}
```
