### ISSUE TITLE
ngixn database disk image is malformed

### ISSUE THREAD

**Issue by hex0wn** [telekom-security/tpotce#721]
same issue with [https://github.com/telekom-security/tpotce/issues/717](https://github.com/telekom-security/tpotce/issues/717)
I build container from Dockerfile  `docker/heimdall/Dockerfile`, and then `docker-compose up -d`

when i access https://ip:64297 i get this info.
```
Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 11 database disk image is malformed (SQL: select * from sqlite_master where type = 'table' and name = settings)
Previous exceptions
SQLSTATE[HY000]: General error: 11 database disk image is malformed (HY000)
```

I try to open app.sqlite directly, `sqlite3 app.sqlite ".database"`. It returns `Error: database disk image is malformed`.
May be something wrong with file `docker/heimdall/dist/app/app.sqlite`

**Comment by t3chn0m4g3** [comment]
We can only take care of issues resulting from our provided docker images. If you are having issues with heimdall please visit their [repository](https://github.com/linuxserver/Heimdall).
Thanks for understanding.
