### ISSUE TITLE
elasticsearch-curator fails to install

### ISSUE THREAD

**Issue by tdkmp4n4** [telekom-security/tpotce#722]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Linux knownkiosk 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

- What T-Pot version are you currently using?
20.06.1

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM (ESXi)

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Attached install.err:
Using distribution stable.
Retrieving the list of mirrors from www.debian.org...

--2020-11-16 17:18:32--  http://www.debian.org/mirror/mirrors_full
Resolving www.debian.org (www.debian.org)... 130.89.148.77, 2001:67c:2564:a119::77
Connecting to www.debian.org (www.debian.org)|130.89.148.77|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.debian.org/mirror/mirrors_full [following]
--2020-11-16 17:18:32--  https://www.debian.org/mirror/mirrors_full
Connecting to www.debian.org (www.debian.org)|130.89.148.77|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 168322 (164K) [text/html]
Saving to: ‘/tmp/netselect-apt.0b6MO7’

     0K .......... .......... .......... .......... .......... 30%  556K 0s
    50K .......... .......... .......... .......... .......... 60% 1.40M 0s
   100K .......... .......... .......... .......... .......... 91% 2.28M 0s
   150K .......... ....                                       100% 14.2M=0.1s

2020-11-16 17:18:33 (1.09 MB/s) - ‘/tmp/netselect-apt.0b6MO7’ saved [168322/168322]

Choosing a main Debian mirror using netselect.
netselect: 355 (22 active) nameserver request(s)...
Duplicate address 213.129.232.18 (http://ftp.at.debian.org/debian/, http://debian.sil.at/debian/); keeping only under first name.
netselect: 352 (24 active) nameserver request(s)...
Duplicate address 195.234.45.114 (http://ftp.be.debian.org/debian/, http://mirror.as35701.net/debian/); keeping only under first name.
netselect: 348 (23 active) nameserver request(s)...
Duplicate address 93.187.162.100 (http://ftp.am.debian.org/debian/, http://mirrors.asnet.am/debian/); keeping only under first name.
netselect: 344 (24 active) nameserver request(s)...
Duplicate address 200.236.31.3 (http://debian.c3sl.ufpr.br/debian/, http://ftp.br.debian.org/debian/); keeping only under first name.
netselect: 335 (23 active) nameserver request(s)...
Duplicate address 212.50.0.19 (http://debian.mobiltel.bg/debian/, http://ftp.bg.debian.org/debian/); keeping only under first name.
netselect: 326 (23 active) nameserver request(s)...
Duplicate address 129.132.53.171 (http://ftp.ch.debian.org/debian/, http://debian.ethz.ch/debian/); keeping only under first name.
netselect: 321 (22 active) nameserver request(s)...
Duplicate address 82.209.230.71 (http://ftp.byfly.by/debian/, http://ftp.by.debian.org/debian/); keeping only under first name.
netselect: 320 (23 active) nameserver request(s)...
Duplicate address 207.210.46.249 (http://ftp.ca.debian.org/debian/, http://debian.mirror.rafal.ca/debian/); keeping only under first name.
netselect: 311 (23 active) nameserver request(s)...
Duplicate address 45.125.0.6 (http://ftp2.cn.debian.org/debian/, http://ftp.cn.debian.org/debian/); keeping only under first name.
netselect: 306 (23 active) nameserver request(s)...
Duplicate address 150.203.164.37 (http://ftp.au.debian.org/debian/, http://mirror.linux.org.au/debian/); keeping only under first name.
netselect: 306 (24 active) nameserver request(s)...
Duplicate address 78.128.211.127 (http://ftp.cz.debian.org/debian/, http://ftp.debian.cz/debian/); keeping only under first name.
netselect: 297 (22 active) nameserver request(s)...
Duplicate address 137.226.34.46 (http://ftp2.de.debian.org/debian/, http://ftp.halifax.rwth-aachen.de/debian/); keeping only under first name.
netselect: 292 (23 active) nameserver request(s)...
Duplicate address 141.76.2.4 (http://ftp.de.debian.org/debian/, http://debian.inf.tu-dresden.de/debian/); keeping only under first name.
netselect: 289 (23 active) nameserver request(s)...
Duplicate address 200.75.30.181 (http://ftp.cl.debian.org/debian/, http://200.75.30.181/debian/); keeping only under first name.
netselect: 238 (22 active) nameserver request(s)...
Duplicate address 130.225.254.116 (http://mirrors.dotsrc.org/debian/, http://ftp.dk.debian.org/debian/); keeping only under first name.
netselect: 237 (23 active) nameserver request(s)...
Duplicate address 82.194.78.250 (http://ftp.es.debian.org/debian/, http://ulises.hostalia.com/debian/); keeping only under first name.
netselect: 232 (23 active) nameserver request(s)...
Duplicate address 212.27.32.66 (http://ftp.fr.debian.org/debian/, http://debian.proxad.net/debian/); keeping only under first name.
netselect: 213 (24 active) nameserver request(s)...
Duplicate address 193.40.0.5 (http://ftp.eenet.ee/debian/, http://ftp.ee.debian.org/debian/); keeping only under first name.
netselect: 208 (24 active) nameserver request(s)...
Duplicate address 78.129.164.123 (http://ftp.uk.debian.org/debian/, http://ftp.is.debian.org/debian/); keeping only under first name.
netselect: 190 (22 active) nameserver request(s)...
Duplicate address 45.125.0.6 (http://ftp2.cn.debian.org/debian/, http://ftp.hk.debian.org/debian/); keeping only under first name.
netselect: 188 (22 active) nameserver request(s)...
Duplicate address 45.125.0.6 (http://ftp2.cn.debian.org/debian/, http://mirror.xtom.com.hk/debian/); keeping only under first name.
netselect: 178 (22 active) nameserver request(s)...
Duplicate address 195.228.252.133 (http://ftp.fsn.hu/debian/, http://ftp.hu.debian.org/debian/); keeping only under first name.
netselect: 178 (24 active) nameserver request(s)...
Duplicate address 78.129.164.123 (http://ftp.uk.debian.org/debian/, http://free.hands.com/debian/); keeping only under first name.
netselect: 176 (23 active) nameserver request(s)...
Duplicate address 147.102.222.211 (http://debian.noc.ntua.gr/debian/, http://ftp.gr.debian.org/debian/); keeping only under first name.
netselect: 170 (23 active) nameserver request(s)...
Duplicate address 161.53.160.11 (http://ftp.hr.debian.org/debian/, http://debian.carnet.hr/debian/); keeping only under first name.
netselect: 161 (23 active) nameserver request(s)...
Duplicate address 103.22.220.133 (http://ftp.kaist.ac.kr/debian/, http://ftp.kr.debian.org/debian/); keeping only under first name.
netselect: 160 (23 active) nameserver request(s)...
Duplicate address 85.94.199.210 (http://ftp.it.debian.org/debian/, http://ftp.linux.it/debian/); keeping only under first name.
netselect: 151 (23 active) nameserver request(s)...
Duplicate address 158.129.159.169 (http://debian.mirror.vu.lt/debian/, http://ftp.lt.debian.org/debian/); keeping only under first name.
netselect: 145 (23 active) nameserver request(s)...
Duplicate address 178.17.160.48 (http://ftp.md.debian.org/debian/, http://mirror.as43289.net/debian/); keeping only under first name.
netselect: 139 (24 active) nameserver request(s)...
Duplicate address 133.5.166.3 (http://ftp.jp.debian.org/debian/, http://dennou-q.gfd-dennou.org/debian/); keeping only under first name.
netselect: 130 (23 active) nameserver request(s)...
Duplicate address 130.89.149.21 (http://ftp.nl.debian.org/debian/, http://debian.snt.utwente.nl/debian/); keeping only under first name.
netselect: 102 (24 active) nameserver request(s)...
Duplicate address 129.240.118.47 (http://ftp.uio.no/debian/, http://ftp.no.debian.org/debian/); keeping only under first name.
netselect: 101 (23 active) nameserver request(s)...
Duplicate address 132.248.182.159 (http://mmc.geofisica.unam.mx/debian/, http://ftp.mx.debian.org/debian/); keeping only under first name.
netselect: 85 (24 active) nameserver request(s)...
Duplicate address 193.136.216.34 (http://ftp.pt.debian.org/debian/, http://debian.uevora.pt/debian/); keeping only under first name.
netselect: 84 (23 active) nameserver request(s)...
Duplicate address 194.71.11.165 (http://194.71.11.165/debian/, http://194.71.11.165/debian/); keeping only under first name.
netselect: 83 (23 active) nameserver request(s)...
Duplicate address 194.71.11.173 (http://194.71.11.173/debian/, http://194.71.11.173/debian/); keeping only under first name.
netselect: 81 (23 active) nameserver request(s)...
Duplicate address 85.143.112.112 (http://ftp.ru.debian.org/debian/, http://mirror.mephi.ru/debian/); keeping only under first name.
netselect: 72 (23 active) nameserver request(s)...
Duplicate address 194.71.11.165 (http://194.71.11.165/debian/, http://194.71.11.165/debian/); keeping only under first name.
netselect: 71 (23 active) nameserver request(s)...
Duplicate address 194.71.11.173 (http://194.71.11.173/debian/, http://194.71.11.173/debian/); keeping only under first name.
netselect: 67 (24 active) nameserver request(s)...
Duplicate address 213.129.232.18 (http://ftp.at.debian.org/debian/, http://ftp.si.debian.org/debian/); keeping only under first name.
netselect: 65 (23 active) nameserver request(s)...
Duplicate address 195.80.174.186 (http://ftp.sk.debian.org/debian/, http://ftp.debian.sk/debian/); keeping only under first name.
netselect: 52 (22 active) nameserver request(s)...
Duplicate address 193.140.98.183 (http://ftp.linux.org.tr/debian/, http://ftp.tr.debian.org/debian/); keeping only under first name.
netselect: unknown host ftp.citylink.co.nz
netselect: 49 (22 active) nameserver request(s)...
Duplicate address 163.7.134.112 (http://mirror.fsmg.org.nz/debian/, http://ftp.nz.debian.org/debian/); keeping only under first name.
netselect: 30 (21 active) nameserver request(s)...
Duplicate address 208.80.154.15 (http://208.80.154.15/debian/, http://mirrors.wikimedia.org/debian/); keeping only under first name.
netselect: 29 (23 active) nameserver request(s)...
Duplicate address 64.50.233.100 (http://64.50.233.100/debian/, http://64.50.233.100/debian/); keeping only under first name.
netselect: 29 (24 active) nameserver request(s)...
Duplicate address 64.50.236.52 (http://64.50.236.52/debian/, http://64.50.236.52/debian/); keeping only under first name.
netselect: 13 (13 active) nameserver request(s)...
Duplicate address 103.2.186.81 (http://103.2.186.81/debian/, http://103.2.186.81/debian/); keeping only under first name.
netselect: 12 (12 active) nameserver request(s)...
Duplicate address 103.2.186.80 (http://103.2.186.80/debian/, http://103.2.186.80/debian/); keeping only under first name.
netselect: 3 (3 active) nameserver request(s)...
Duplicate address 140.110.240.80 (http://ftp.tw.debian.org/debian/, http://opensource.nchc.org.tw/debian/); keeping only under first name.
Running netselect to choose 10 out of 349 addresses.
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
The fastest 10 servers seem to be:

Of the hosts tested we choose the fastest valid for HTTP:
        http://debian.redimadrid.es/debian/

Writing sources.list.
info: Trying to set 'docker.io/restart' [boolean] to 'true'
info: Loading answer for 'docker.io/restart'
info: Trying to set 'debconf/frontend' [select] to 'noninteractive'
info: Loading answer for 'debconf/frontend'
W: --force-yes is deprecated, use one of the options starting with --allow instead.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Error: Timeout was reached
E: Sub-process /usr/bin/dpkg returned an error code (1)
Adding password for user alisec
Generating a RSA private key
..................................................+++
...........................................................+++
writing new private key to '/data/nginx/cert/nginx.key'
-----
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.20 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-fsx9daai/elasticsearch-curator/
Created symlink /etc/systemd/system/multi-user.target.wants/tpot.service → /etc/systemd/system/tpot.service.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.19.0-12-amd64
Found initrd image: /boot/initrd.img-4.19.0-12-amd64
Found linux image: /boot/vmlinuz-4.19.0-11-amd64
Found initrd image: /boot/initrd.img-4.19.0-11-amd64
done
Trying: dig +short myip.opendns.com @resolver2.opendns.com
Trying: dig +short -4 -t a whoami.akamai.net @ns1-1.akamaitech.net

- How long has your installation been running?
N/A

- Did you install upgrades, packages or use the update script?
No

- Did you modify any scripts or configs? If yes, please attach the changes.
No

- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
All of this is fine. However, the honeypot is unable to delete old ES indexes

Hi, I just did a fresh install of T-Pot 20.06.1 using "tpot.iso" file from the releases section. However, the elasticsearch-curator package appears to be failing as "curator" command does not work. As I've said, it's just a fresh install from "tpot.iso" file. I suppose there is some kind of bug with elasticsearch-curator package. I tried to install it manually but it didn't actually work. I am investigating the issue. Has anyone experienced this problem before?

Thanks in advance.

**Comment by tdkmp4n4** [comment]
Nevermind, solved by installing elasticsearch-curator from source code. Just in case anyone is having trouble with this the following commands should fix it:

cd /opt && git clone https://github.com/elastic/curator.git
cd curator
python3 setup.py install

**Comment by t3chn0m4g3** [comment]
Thank you, I will into it!

**Comment by t3chn0m4g3** [comment]
I can confirm, installation from PyPi seems is broken. An issue has been opened [upstream](https://github.com/elastic/curator/issues/1567).

**Comment by t3chn0m4g3** [comment]
A new [version](https://pypi.org/project/elasticsearch-curator/) has been pushed to PyPi fixing the described problem.

@tdkmp4n4: Can you test this please by removing your manual install and run `update.sh` as root?
