### ISSUE TITLE
web port 64297 cannot be reached

### ISSUE THREAD

**Issue by Haotian-Shi-cyber** [telekom-security/tpotce#723]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
debian GNU/Linux 10 (buster)
- What T-Pot version are you currently using?
20.06.1
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
vm
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
no, btw where is the install.log
- How long has your installation been running?
2days
- Did you install upgrades, packages or use the update script?
used update.sh
- Did you modify any scripts or configs? If yes, please attach the changes.
no
- Please provide a screenshot of `glances` and `htop`.
![Screenshot 2020-11-18 180531](https://user-images.githubusercontent.com/62081228/99569607-bd3cab80-29c8-11eb-8995-302377f21bef.png)

- How much free disk space is available (`df -h`)?
51g
- What is the current container status (`dps.sh`)?
![Screenshot 2020-11-18 180715](https://user-images.githubusercontent.com/62081228/99569759-eeb57700-29c8-11eb-9863-57fc2b4b463e.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![Screenshot 2020-11-18 180856](https://user-images.githubusercontent.com/62081228/99569945-291f1400-29c9-11eb-851c-d5ba72db2835.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![Screenshot 2020-11-18 181022](https://user-images.githubusercontent.com/62081228/99570092-5b307600-29c9-11eb-854a-ffa97fc85658.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
![Screenshot 2020-11-18 181147](https://user-images.githubusercontent.com/62081228/99570239-8e730500-29c9-11eb-9388-aa75c5c0f6b3.png)

**Comment by t3chn0m4g3** [comment]
The installation failed. Please attach logs as kindly requested. You find them in the root folder 
```
cd /
cat install.err
cat install.log
```

**Comment by Haotian-Shi-cyber** [comment]
error
![image](https://user-images.githubusercontent.com/62081228/99588478-85daf880-29e2-11eb-86b7-6274b660d4ab.png)
![image](https://user-images.githubusercontent.com/62081228/99588565-ac992f00-29e2-11eb-8cfa-75c55e00781a.png)

**Comment by Haotian-Shi-cyber** [comment]
how can i copy these two logs from vm and copy it here.. the VM has no gui

**Comment by Haotian-Shi-cyber** [comment]
anyone please could give me a hand,, I'll will try to download it again, i mean first time after i downloaded it and the VM restarted, it asked me to do process again which seems like a loop for me , so i removed iso file from the VM and it works fine. i choosed the standard type, i can access port 64294 and couldn't access 64297!!!

**Comment by Haotian-Shi-cyber** [comment]
> The installation failed. Please attach logs as kindly requested. You find them in the root folder
> 
> ```
> cd /
> cat install.err
> cat install.log
> ```

![image](https://user-images.githubusercontent.com/62081228/99724815-192c3080-2aac-11eb-8782-a82ba1286524.png)
now i didn't delete the VM and just attach iso and it asks me to install it again? is it a bug or something?

**Comment by RantMaster** [comment]
I have found on new installs that not all the required iptables rules are installed. 

I found the fix is to run the update script like so:
```
sudo su -
systemctl stop tpot
cd /opt/tpot
update.sh -y
systemctl start tpot
```
Give that a shot

**Comment by t3chn0m4g3** [comment]
After install you need to eject the ISO file, normal for VirtualBox.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
