### ISSUE TITLE
Dionaea hardening

### ISSUE THREAD

**Issue by an-schall** [telekom-security/tpotce#730]
**Is your feature request related to a problem? Please describe.**
Nmap detects a couple of services exposed by Dionaea.

**Describe the solution you'd like**
I suggest to perform some hardening in order to mitigate identification of the services to be honeypots by nmap. This can be done by having a look at /usr/share/nmap/nmap-service-probes and implementing changes to the respective .py file in dionaea:/opt/dionaea/lib/dionaea/python/dionaea/*.

**Describe alternatives you've considered**
For example, I tried to harden MSSQL service exposed by Dionaea by changing dionaea:/opt/dionaea/lib/dionaea/python/dionaea/mssql/mssql.py, line 259 to

`r.VersionToken.Offset = 25`

However, I cannot put the modified python file back inside the container as the filesystem is mounted read-only.

**Comment by t3chn0m4g3** [comment]
Thanks for taking the time to open the issue. Since we are using Dionaea from [here](https://github.com/DinoTools/dionaea), I'd recommend to open a PR with them. Once proposed changes are in the Dionaea code base it will be available for us.
Thanks again and for understanding.
