### ISSUE TITLE
sicherheitstacho.eu still has a link to the old github org

### ISSUE THREAD

**Issue by shaderecker** [telekom-security/tpotce#741]
On https://www.sicherheitstacho.eu/start/main in the left navigation bar is the link "Star us on GitHub" which still points to https://github.com/dtag-dev-sec.
The link should point to the new https://github.com/telekom-security.

Not sure where else to address this issue, so here it is 😀

**Comment by t3chn0m4g3** [comment]
@sp3t3rs Can you change the link, please?
@shaderecker Thanks!

**Comment by sp3t3rs** [comment]
Sorry for the late response! Nice heads-up, thanks! @shaderecker. Fixed in prod.
