### ISSUE TITLE
Installation fails: "no kernel modules were found"

### ISSUE THREAD

**Issue by vim4edit** [telekom-security/tpotce#748]
The installation of tpot.iso fails because "no kernel modules were found"

vim4edit

**Comment by t3chn0m4g3** [comment]
I just tested with the latest release ISO and it works perfectly fine with a german mirror. What mirror did you use?

**Comment by vim4edit** [comment]
I just tried it again... with different mirrors.
I am using T-Pot 20.06.01 under Oracle-Virtualbox 6.1. On a Debian Buster System.
The error appears after choosing the mirror. Regardless of which one I choose.

**Comment by t3chn0m4g3** [comment]
The error is usually reproducible for me, however this time it works perfectly fine here if the latest ISO of T-Pot is used. This might be an isolated issue with your setup.

Since the workaround worked I am closing this issue.
