### ISSUE TITLE
Insert daemon.json 

### ISSUE THREAD

**Issue by thgeese** [telekom-security/tpotce#751]
When running with default settings I got routing Problem with random Neworks used by Docker. 

To work around this I add a daemon.json under /etc/docker/ to configure a default subnet used for Docker. 

{
  "default-address-pools":
  [
    {"base":"172.80.0.0/16","size":24}
  ]
}

Would also be nice if you can configure this durinng Setup.

**Comment by t3chn0m4g3** [comment]
This depends on individual setups and we are keeping the docker defaults. Please also be aware that your proposed settings are outside of the RFC1918 address space, which for your setup might work, for others probably not.

Thanks for understanding.
