### ISSUE TITLE
Using tpotce offline

### ISSUE THREAD

**Issue by joroMaser** [telekom-security/tpotce#758]
That will be great  if we can configure tpotce to work offline,without internet connection. 

Configure to tpotce path to pcap file to analyze that refill each time with new pcap and tpotce will parse them

**Comment by t3chn0m4g3** [comment]
T-Pot is created to only work with an active or passive internet connection.

**Comment by joroMaser** [comment]
@t3chn0m4g3 What do you mean passive internet connection?

**Comment by t3chn0m4g3** [comment]
Proxied / NATed if deployed in LAN, DMZ, etc.
