### ISSUE TITLE
Blank screen while accessing Kibana and other tools after t-pot installation

### ISSUE THREAD

**Issue by setu1993** [telekom-security/tpotce#766]
We have installed in VM Debian, with 8GM RAM.

Let me know what else will be required from my side.

**Comment by ehnwebmaster** [comment]
Execute this command to check if containers are up and healthy

/opt/tpot/bin/dps.sh 1

And check if everything is up (green)

> We have installed in VM Debian, with 8GM RAM.
> 
> Let me know what else will be required from my side.

**Comment by setu1993** [comment]
we are getting blank screen while accessing kibana, and dps.sh, screenshot is attached.
![dps](https://user-images.githubusercontent.com/31838836/107343723-a0a3a180-6ae7-11eb-9335-679976d6ff3e.png)

**Comment by setu1993** [comment]
@ehnwebmaster need help in that, I have used the spec informed in installation steps. 
what else is required.

**Comment by ehnwebmaster** [comment]
As you can see some containers are down. Why? That's the question.

Just check the status and see error log to see what's wrong: 

`systemctl status tpot`

Check logs

`journalctl`
