### ISSUE TITLE
add folder output por cowrie honeypot

### ISSUE THREAD

**Issue by ehnwebmaster** [telekom-security/tpotce#767]
Hello,

Please add the folder "output" to make available some "output" from cowrie or 3rd party scripts won't work.

I've sucessfully installed TPOT but want to sent some reports to AbuseIPDB, VirusTotal, DShield (SANS ISC), etc.

Also need to made cowrie.cfg persistent.

Edit file

/opt/tpot/etc/tpot.yml

add cowrie container config

```
# cowrie.cfg persistent
      - /data/cowrie/config/cowrie.cfg:/home/cowrie/cowrie/cowrie.cfg
 # folder output (third party scripts)
      - /data/cowrie/src/output:/home/cowrie/cowrie/src/output
 #  need abuseipdb folder for dump_path
      - /data/cowrie/abuseipdb:/home/cowrie/cowrie/abuseipdb
```

And of course copy cowrie.cfg and output folder.

Example output folder:
sudo cp -r /var/lib/docker/overlay2/f42b3ac1782d333a9d7ea6f4c28b06340c786a97bbe2eff02f9741312f830f7e/merged/home/cowrie/cowrie/src/cowrie/output /data/cowrie/src

And then edit as desired:
/data/cowrie/config/cowrie.cfg

Examples:

```
[output_dshield]
enabled = true
userid = xxx
auth_key = xxxx
batch_size = 100
```

```
# Reports login attempts to AbuseIPDB. A short guide is in the original
# pull request on GitHub: https://github.com/cowrie/cowrie/pull/1346
[output_abuseipdb]
enabled = true
api_key = xxxx
rereport_after = 2
#tolerance_window is in minutes
tolerance_window = 120
tolerance_attempts = 3
# WARNING: A binary file is read from this directory on start-up. Do not
# change unless you understand the security implications!
dump_path = ${honeypot:state_path}/abuseipdb
```

```
# VirusTotal output module
# You must signup for an api key.
#
[output_virustotal]
enabled = true
api_key = xxx
upload = True
debug = False
scan_file = True
```

Well I know the cowrie.cfg is "pre-configured" is better way, but even doing changes cowrie.cfg from output will not work, becasue folder doesn't exists.

For example:
https://isc.sans.edu/forums/diary/TPOTs+Cowrie+to+ISC+Logs/25976/

Thank you very much.

**Comment by t3chn0m4g3** [comment]
Please follow this [example](https://github.com/telekom-security/tpotce/wiki/Reconfigure-logstash.conf) in our Wiki on how to work with docker volumes. By default we do not want to expose configs to the host.
