### ISSUE TITLE
T-Pot working on a Raspberry Pi 4 (platform independent)

### ISSUE THREAD

**Issue by ehnwebmaster** [telekom-security/tpotce#768]
Hello,

Yes, sounds crazy, because requirements are 8GB and 128GB SDD but with new Raspberry Pi 4B 8gb ram and attached USB 3.1 UASP +128GB SSD is possible and read write to disk are really, really fast

Main problem are not requirements, is the docker images are amd64 (x86_64) and Raspberry is arm (usual errors like : exec user process caused: exec format error) I'm not asking for support., just want to share some information and feature request

Finally i've managed to run all the containers (except 3) emulating architecture (using https://github.com/dbhi/qus (qemu for for containers) with docker run --rm --privileged aptman/qus -s -- -p x86_64

```
ERROR: for nginx  "host" network_mode is incompatible with port_bindings
ERROR: for ciscoasa  "host" network_mode is incompatible with port_bindings
```
those have easy solution....

but the 3 problematic containers are:

```
ERROR: for kibana  Container "088220a85eb1" is unhealthy.
ERROR: for head  Container "088220a85eb1" is unhealthy.
ERROR: for logstash  Container "088220a85eb1" is unhealthy.
```

surprisingly some java (platform independent), and yes are dependent each other

Examples
java error:
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled

elasticsearch 
```
[2021-02-07T18:14:08,065][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-sql],
[2021-02-07T18:14:08,075][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-stack],
[2021-02-07T18:14:08,096][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-voting-only-node],
[2021-02-07T18:14:08,108][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-watcher],
[2021-02-07T18:14:08,521][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] no plugins loaded,
[2021-02-07T18:14:14,244][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] using [1] data paths, mounts [[/data (/dev/root)]], net usable_space [17.4gb], net total_space [28.9gb], types [ext4],
[2021-02-07T18:14:14,291][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] heap size [1.9gb], compressed ordinary object pointers [true],
#,
# A fatal error has been detected by the Java Runtime Environment:,
#,
#  SIGSEGV (0xb) at pc=0x000000400a57c9e2, pid=73, tid=135,
#,
# JRE version: OpenJDK Runtime Environment (11.0.9+11) (build 11.0.9+11-alpine-r0),
# Java VM: OpenJDK 64-Bit Server VM (11.0.9+11-alpine-r0, mixed mode, tiered, compressed oops, serial gc, linux-amd64),
# Problematic frame:,
# J 5 c1 java.lang.String.isLatin1()Z java.base@11.0.9 (19 bytes) @ 0x000000400a57c9e2 [0x000000400a57c9c0+0x0000000000000022],
#,
# Core dump will be written. Default location: /usr/share/elasticsearch/core,
#,
# An error report file with more information is saved as:,
# /usr/share/elasticsearch/hs_err_pid73.log,
Compiled method (c1)    6936    5       3       java.lang.String::isLatin1 (19 bytes),
 total in heap  [0x000000400a57c810,0x000000400a57cb80] = 880,
 relocation     [0x000000400a57c988,0x000000400a57c9b8] = 48,
 main code      [0x000000400a57c9c0,0x000000400a57cb00] = 320,
 stub code      [0x000000400a57cb00,0x000000400a57cb30] = 48,
 metadata       [0x000000400a57cb30,0x000000400a57cb38] = 8,
 scopes data    [0x000000400a57cb38,0x000000400a57cb48] = 16,
 scopes pcs     [0x000000400a57cb48,0x000000400a57cb78] = 48,
 dependencies   [0x000000400a57cb78,0x000000400a57cb80] = 8,
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled,
#,
# If you would like to submit a bug report, please visit:,
#   https://gitlab.alpinelinux.org/alpine/aports/issues,
#,
bin/elasticsearch-keystore: line 6:    73 Aborted                 (core dumped) ES_MAIN_CLASS=org.elasticsearch.common.settings.KeyStoreCli ES_ADDITIONAL_CLASSPATH_DIRECTORIES=lib/tools/keystore-cli "`dirname "$0"`"/elasticsearch-cli "$@",
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.,

```

I did the post-install

```
git clone https://github.com/telekom-security/tpotce
cd tpotce/iso/installer/
./install.sh --type=user
```

FYI my machine name generated by you (random) is crowdedcucumber xDDDD (really funmy name) yes
(Create funny words for hostnames) you nailed!

But i think is possible to run, yes need more time for testing

Anyway thanks for the project, is awesome

**Comment by t3chn0m4g3** [comment]
Thanks for the valued feedback, sounds great! As a remark: Please ensure not to run any containers in `privileged` mode. 

We moved away from RPi back in 2015 for the simple reason that x64 is by far the most requested architecture and while there is the possibility of multi arch builds we decided to only provide images for x64.

Should AARCH64 be more requested than x64 we will re-evaluate that decision.

Thanks for understanding.

**Comment by ehnwebmaster** [comment]
Hello again,

Can you prove this?

`docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t dtagdevsec/cowrie --push`

multi-CPU architecture support

Buildx (Experimental)

Docker is now making it easier than ever to develop containers on, and for Arm servers and devices. Using the standard Docker tooling and processes, you can start to build, push, pull, and run images seamlessly on different compute architectures. Note that you don’t have to make any changes to Dockerfiles or source code to start building for Arm.

Docker introduces a new CLI command called buildx. You can use the buildx command on Docker Desktop for Mac and Windows to build multi-arch images, link them together with a manifest file, and push them all to a registry using a single command. With the included emulation, you can transparently build more than just native images. Buildx accomplishes this by adding new builder instances based on BuildKit, and leveraging Docker Desktop’s technology stack to run non-native binaries.

https://docs.docker.com/docker-for-mac/multi-arch/

**Comment by Firesphere** [comment]
@ehnwebmaster What exactly did you do, to get it all running using qemu?
I mean, step by step and/or config updates?
