### ISSUE TITLE
TPOT 20.06 - ElasticSearch License Error: Cluster client cannot be used after it has been closed

### ISSUE THREAD

**Issue by UncleRaymondo** [telekom-security/tpotce#776]
M,

Any idea what could be causing this? I've just tried to log on to the host after the web portal was showing Kibana Server not Ready. I've also just patched the box via update.sh

![image](https://user-images.githubusercontent.com/5147133/108454672-e834e500-72c0-11eb-9d84-3d1706f49177.png)

dps.sh is showing everything up and healthy?

![image](https://user-images.githubusercontent.com/5147133/108454794-2af6bd00-72c1-11eb-9f70-d2d83f4d32cb.png)

ES Cluster Head is showing not connected and won't connect when I click connect either.

There's been no modifications to anything, it's primarily a default install... I'm stumped... any ideas?

Thanks mate :)

Cheers,
R

**Comment by t3chn0m4g3** [comment]
To rule out a general issue I performed several installs which turned out to be fine.
The error however seems to be related to Kibana or Logstash not being able to retrieve a license from the Elasticsearch node which is odd since they occupy the same isolated docker network. Googling only reveals bugs related to 7.5.x which were resolved.
I will be pushing 7.11.1 today, maybe this will help. If not you might want to `systemctl stop tpot`, `rm -rf /var/lib/docker` and `docker-compose -f /opt/tpot/etc/tpot.yml pull` and see if the new image pull is fixing it.

**Comment by UncleRaymondo** [comment]
Looks like that last command failed... :(

![image](https://user-images.githubusercontent.com/5147133/108615259-7393af00-7456-11eb-9ce3-fe044556adcb.png)

**Comment by t3chn0m4g3** [comment]
Sorry, forgot docker ...
```
systemctl stop tpot
rm -rf /var/lib/docker
systemctl stop docker
systemctl start docker
docker-compose -f /opt/tpot/etc/tpot.yml pull
systemctl start tpot
```

**Comment by UncleRaymondo** [comment]
Yep, looking different now that it was yesterday.... didn't see that downloading and extracting part... 

![image](https://user-images.githubusercontent.com/5147133/108718852-fb6edb80-7572-11eb-87bf-aad1ab323183.png)

Will update more later (it's 1am lol)

**Comment by UncleRaymondo** [comment]
Looks like the same thing... even though dps.sh shows it all up and healthy :( 

![image](https://user-images.githubusercontent.com/5147133/108775720-9be5ef80-75b5-11eb-8e4d-c6f6b3a35295.png)

![image](https://user-images.githubusercontent.com/5147133/108775764-aa340b80-75b5-11eb-9bc9-ec62ed1f3c9f.png)

Any ideas?

Cheers,
R

**Comment by UncleRaymondo** [comment]
Yeah it's very weird... I have no idea what is going on... I tried running some commands to get some checks as follows:

![image](https://user-images.githubusercontent.com/5147133/108821940-7935f400-7612-11eb-8584-8f7b5c03f540.png)

Let me try the command above and see what happens

-R

**Comment by UncleRaymondo** [comment]
That curl command is taking forever to respond... I'm watching the elasticsearch logs on another screen which are just getting flooded... lots of timeouts and issues....

![image](https://user-images.githubusercontent.com/5147133/108822546-56f0a600-7613-11eb-8455-49b6175ba16c.png)

I can't connect to the ES Head... it won't connect... Might be time to rebuild this box... 

before I do though... is there a way for me to export the kibana dashboards I created - I'd rather not have to go work those out again 😂🤦‍♂️

**Comment by t3chn0m4g3** [comment]
Sorry to hear that 😢 
Fear not, you can [export](https://github.com/telekom-security/tpotce/wiki/Import---Export-Kibana-Objects) all Kibana objects 😄

**Comment by UncleRaymondo** [comment]
Eh.. it's not a mission critical system so rebuilding it would be quick and easy...
Umm... if Kibana is not loading, how can I export the objects - is there another way?

![image](https://user-images.githubusercontent.com/5147133/108824040-58bb6900-7615-11eb-8dbd-759a55aebdbd.png)

**Comment by t3chn0m4g3** [comment]
🤦 Ugh, correct, there was that. Sorry, but I fear the dashboards are toast if you made no backup 😢

**Comment by UncleRaymondo** [comment]
Only backup I have would probably be a screenshot of the dashboard somewhere 😂😂
All good... another project for a weekend soon
Thanks buddy!

**Comment by UncleRaymondo** [comment]
By the way, there are ways to export dashboards via the CLI if you want to add to the docs somewhere
https://discuss.elastic.co/t/dashboard-export-with-command-line/184016

But Kibana needs to actually be running too... 😂😂🤦‍♂️🤦‍♂️

**Comment by xcampax** [comment]
I had the same issue. I played around with tips from [this thread](https://github.com/telekom-security/tpotce/issues/410). Noticed a message that my .kibana_4 index was stuck in migration, so I deleted and re-created it, and re-imported all objects, now everything is fine again.

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo In the `/opt/tpot/bin` folder you will also find tools export and import the Kibana objects, but this also requires a running Kibana.

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo Hope this works now, if not let me know.
