### ISSUE TITLE
Option to Configure or Setup Login for Server User Account 

### ISSUE THREAD

**Issue by waitesgithub** [telekom-security/tpotce#778]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I want to perform an update and have to keep changing the Security Groups to go to SSH and try to login to change or update TPOT just to go into the TPOT Admin Server User Account. 

**Describe the solution you'd like**
I would like for a solution to provided within either the setup script to configure Cockpit to setup a TPOT Admin Server User Account, or have users be able to configure there own Cockpit solution to allow for logging into the TPOT Admin Server User Account. The default passwords tsec/tsec and assigned credentials will not allow users to login into the TPOT Admin Server groups on AWS, Azure, or GCP. 

I would also like to see official documentation developed or setup of TPOT within AWS, Azure and GCP. I successfully have TPOT running on AWS but unable to get the TPOT Server User Account to authenticate. So I am unable to access this page using AWS:

![cockpit2](https://user-images.githubusercontent.com/16434853/108612882-7f319800-73ba-11eb-98f5-a409e72b16ab.png)

**Describe alternatives you've considered**
Solution 1. Reconfigure the installation script to allow users to setup a TPOT Admin Server User Account credentials 
Solution 2. Allow users to setup there own Cockpit installation to view the admin portal for T-POT as an option. 
Solution 3. Allow user account setup for TPOT Admin Server, due to the fact that git install is not allowing users to see the admin account since they are not installing with the ISO. 

<img width="1408" alt="TPOT Cockpit Admin User" src="https://user-images.githubusercontent.com/16434853/108612743-7a201900-73b9-11eb-9004-e1e329026d84.png">

**Comment by shaderecker** [comment]
Hi @waitesgithub 
We have some documentation regarding AWS here (https://github.com/telekom-security/tpotce/tree/master/cloud/terraform).
There the deployment is done via Terraform.

Regarding the login to the Cockpit: You need the credentials of your OS (linux user, linux password).
I assume that on AWS there is no password set during EC2 creation, but login only over SSH key.
To "fix" this you can set a password for your linux user during VM creation with cloud init.
See here how this can be done: https://github.com/telekom-security/tpotce/blob/master/cloud/terraform/cloud-init.yaml#L13-L15

**Comment by waitesgithub** [comment]
Thanks for providing the link. I would need a better explanation of how you would execute cloudint during the TPOT setup to enable the admin account. I rather you provide a list of commands so I can get a better understanding. Is there a way also to perform these actions after the TPOT setup? Once TPOT completes the installation I am unable to ssh back into TPOT to add the information provided.

**Comment by shaderecker** [comment]
Regarding ssh login after the tpot installation, see: https://github.com/telekom-security/tpotce#ssh
SSH then runs on port tcp/64295 (not the default 22). There you are still able to login with your ssh key.

Cloud-Init is independent from tpot, you would use this during EC2 creation.
I can recommend reading how to use cloud-init with AWS here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-cloud-init
In short: you add some custom User Data like this:
The #cloud-config line at the top is required in order to identify the commands as cloud-init directives.
```
#cloud-config
password: mysupersecretpassw0rd
chpasswd:
  expire: false
```

For after the tpot installation, you can login on said ssh port and manually set the password of your linux user:
`sudo passwd your-ec2-user`
Then you are able to login to the Web Cockpit with `your-ec2-user` and the new password you just set.

**Comment by waitesgithub** [comment]
Unable to SSH on tcp/64295 with aws. Do I need to include the port number? I would love to see your list of commands to show me an example of how you would add a user for logging into Cockpit. Should be part of the installation process and part of the script to add that information in so that I wouldn't have to keep going back to ssh every time just to add a user. I am still not able to login in the Cockpit interface.

**Comment by waitesgithub** [comment]
ssh -i -p 64295 "XXXX.pem" XXXX@ec2-XX-XXX-XX-XX-us-east-2.compute.amazonaws.com command and was not able to login ssh. Do I need to add a hosts under /etc/hosts? What should the file name be when I add the #config-cloud, and where do I save this in the file directory for TPOT. I also would like to see this for Kubernetes as well... Didnt see any instructions for deployment on Kubernetes.

**Comment by shaderecker** [comment]
`"Do I need to include the port number?"`
Yes

`"I would love to see your list of commands to show me an example of how you would add a user for logging into Cockpit."`
Literally the command I posted in my last comment: I don't add any new user, just set the password of the existing user:  
`sudo passwd your-ec2-user`

`"command and was not able to login ssh."`
Please provide the actual error message that occurs, it is impossible to debug when I don't see any logs.
Pay attention to the order of your arguments in the ssh command (the XXXX.pem goes directly after the `-i`):
`ssh -i "XXXX.pem" -p 64295 XXXX@ec2-XX-XXX-XX-XX-us-east-2.compute.amazonaws.com`

`"What should the file name be when I add the #config-cloud, on the ec-2 instance and where do I save the #config-cloud in the file directory for TPOT"`
The cloud-config file is only used during EC2 creation. It isn't of any use on the VM itself.
Please read the official AWS instructions on how to add User Data with Cloud-Init:  
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-cloud-init


`" also would like to see TPOT deployment instructions for Kubernetes as well"`
Currently we have no guide for Kubernetes. But contributions are welcome!

`"I would like your recomended commands for me to add the admin login information for Cockpit"`
Please see https://github.com/telekom-security/tpotce/issues/778#issuecomment-782884096
