### ISSUE TITLE
Could not locate that index-pattern-field

### ISSUE THREAD

**Issue by xcampax** [telekom-security/tpotce#779]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Debian 10, 4.19.171-2

- What T-Pot version are you currently using?
20.06.2

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- NextGen

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
no

- How long has your installation been running?
a while...

- Did you install upgrades, packages or use the update script?
yes, this morning, but the error showed already before, which is why I attempted the update

- Did you modify any scripts or configs? If yes, please attach the changes.
no

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/9562968/108860264-52fe5d00-75ee-11eb-9b68-001a13992cd7.png)

![image](https://user-images.githubusercontent.com/9562968/108860353-67425a00-75ee-11eb-9d35-cdbd647252df.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/9562968/108860472-8214ce80-75ee-11eb-8497-566d4cd30308.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/9562968/108860549-9789f880-75ee-11eb-93e6-ce3ed969efc8.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/9562968/108860812-db7cfd80-75ee-11eb-85db-b09fd62848c7.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/9562968/108860969-049d8e00-75ef-11eb-9865-de9589127add.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

My issue is that several metrics in various dashboards show the following error (example, field name varies):
![image](https://user-images.githubusercontent.com/9562968/108861651-c2288100-75ef-11eb-8ecc-5f5e42ace2c7.png)

Please let me know how to fix this.

Thank you.
Nora

**Comment by t3chn0m4g3** [comment]
Please try https://github.com/telekom-security/tpotce/wiki/Import---Export-Kibana-Objects

**Comment by infoinline** [comment]
I ma gaving the same issue. Have tried to import the Kabana Objects but has made no difference. Still missing CVE metrics ect. Anything else you can reccomend? FYI I had have a temp tpot runing fine on google cloud have set up the same on new VPS but missing around 30 pages on the index patterns.

**Comment by t3chn0m4g3** [comment]
@xcampax @infoinline This is also expected behavior if no corresponding event was detected which results in an empty field that cannot be rendered by Kibana.
