### ISSUE TITLE
Error in docker-compose configurations for conpot

### ISSUE THREAD

**Issue by adskee** [telekom-security/tpotce#781]
The ports specified are the correct numbers, but a few protocols require UDP instead of TCP:

SNMP (161), BACnet (47808), IPMI (623), and TFTP (69)

Docker-compose's documentation isn't super clear on this, but if you don't specify the protocol (i.e. "161:161/udp"), it defaults to TCP, **not both TCP/UDP**.

It's possible other honeypots also have UDP services that aren't correctly exposed, but I haven't done a thorough check.

Ref: https://github.com/mushorg/conpot/blob/master/docker-compose.yml

**Comment by ehnwebmaster** [comment]
I agree, not well documented. You can see doing /opt/tpot/bin/dps.sh

161 says TCP, need to be UDP instead? Only 69 is listen udp

Here's my own (very useful) list: port, protcol, service

cowrie --> 22 (ssh) -23 (telnet) tcp
mailoney --> 25 (smtp) tcp
snare (tanner) --> 80 tcp
citrixhoneypot --> 443 tcp
rdpy --> 3389 tcp
dionaea --> 445 tcp (samba), 69 udp (tftp), 135 (rpc), 3306 (MySQL), 21 (ftp), 81 1433 (SQL)
heralding --> 110 (pop), 143 (imap), 993 (imaps), 995 (pop3s), 1080 (socks5), 5432 (PostgreSQL), 5900 (vnc)
adbhoney -> 5555 (tcp)
dicompot --> 11112
ciscoasa -->   5000/udp  8443 (tcp)
Conpot IEC104 -->    161 udp (snmp) and 2404
Conpot guardian_ast --> 10001
Conpot ipmi --> 623 (udp)
Conpot kamstrup_382 --> 1025 y 50100
HoneySAP --> 3299
Medpot --> 2575

Anyone know wich "service" is port is 81 tcp?

**Comment by t3chn0m4g3** [comment]
Thanks 🙏  for the heads up, will fix.

**Comment by t3chn0m4g3** [comment]
In order to receive the updated compose files you need to run `/opt/tpot/update.sh`.
