### ISSUE TITLE
T-pot ''Database'' receiving data from other T-pot.

### ISSUE THREAD

**Issue by ItsaSHE** [telekom-security/tpotce#784]
Hi im a student wondering if its possible to have many T-pots working together.

I would like that our virtualized T-pots can send data to ONE T-pot. So basically 1 T-pot will be our ''Database'' platform and recieve data from other T-pots.  

Why? i want to have 1 T-pot with certain honeypots on and another T-pot containing other honeypots.

If you cant have T-pot sending data to another T-pot i understand that you can send data to Graylog. But my main focus is the task i have with T-pot as my Database.

Could you give me instructions on how to do that?

Kind Regards!

**Comment by t3chn0m4g3** [comment]
Please review #250
