### ISSUE TITLE
Logstash parse error for some tanner.json

### ISSUE THREAD

**Issue by adskee** [telekom-security/tpotce#787]
I've had a T-Pot running for a bit now to include Snare/Tanner.

First indicator: On Tanner's Kibana dashboard, "/data/tanner/log/tanner_report.json" is #2 on my "Tanner URI - Top 10" dashboard item. I think 'interesting - attackers maybe assume it's running Tanner and try to attack the instance?" - but I dig a little deeper.

In the underlying data, I discover a number of entries (matching the number in the Top 10 URI dashboard item) tagged as "_jsonparsefailure". These entries are saved a bit differently than the standard Tanner parsed entries - the entire JSON entry that failed to parse is saved in the "message" field, while the path *to* the .json file that failed to parse is saved in the "path" field, and the entry is tagged as Type: Tanner. The "Tanner URI - Top 10" dashboard item is looking for the top entries for this "path" field, which would normally be populated with the HTTP path that the attacker passed a GET/POST/etc. command for.

I dig through my data - I have 187 such entries, and curiously enough, all the json entries are for POSTs to the the path "/". 

I can't figure out why. Other POST HTTP requests are parsed fine - only when it's a POST to / does it fail to parse.
I checked and there are no correctly parsed POSTs to /. And the only entries tagged as the json parse failure are POSTs to /.

From my inspection, the json log entry for a POST to / and a POST to another URL look nearly identical - no mismatch in brackets, JSON format errors, etc. So it doesn't look like an error on the part of the Tanner json logger.

Let me know if I can help solve this with some log entries/screenshots/etc.

**Comment by t3chn0m4g3** [comment]
Please provide logs. Thanks.
