### ISSUE TITLE
I can ssh into T-Pot without setting up RSA/KeyGen with vulgar password

### ISSUE THREAD

**Issue by jiggaracci** [telekom-security/tpotce#788]
Thank you I feel 10x smarter lol.  Please remove this issue as it is not one.

**Comment by shaderecker** [comment]
Hi @jiggaracci I guess you are logging into port 22 on your machine?
That is where the Cowrie SSH honeypot is listening.
And since these options (https://github.com/telekom-security/tpotce/blob/master/docker/cowrie/dist/cowrie.cfg#L17-L18) are set, you can login with any user/password combination.
See the cowrie default config (https://github.com/cowrie/cowrie/blob/master/etc/cowrie.cfg.dist#L182-L188) for an explanation of the parameters.

For logging into the real backend of your machine, have a look here https://github.com/telekom-security/tpotce#ssh

**Comment by jiggaracci** [comment]
Then why does it let me just log in with that specific admin/password.  I'm not using anything random. I mean that would explain why it took that vulgar pwd, but why wont it take anything else as u mentioned.

**Comment by jiggaracci** [comment]
Thanks for the explanation btw, and even still, this would be a huge opening no?

**Comment by jiggaracci** [comment]
I literally changed the view to 15 mins, I then tried to login 3 times with admin, as u can clearly see in the pic.  I would love to accept your answer, but todo so would be going against what is actually happening.  

![image](https://user-images.githubusercontent.com/12088529/110550510-d4331500-8101-11eb-81bc-f198f1847708.png)

**Comment by jiggaracci** [comment]
I can only login with user admin and password of 'thishshitsucks'
Maybe I got a bad iso?  But I got it from this site.

**Comment by shaderecker** [comment]
> Thanks for the explanation btw, and even still, this would be a huge opening no?

It is a SSH Honeypot after all. So this is its purpose :)

**Comment by jiggaracci** [comment]
I can log in EVERYTIME with that user password combo.  We're currently testing this iso on another machine to see if the random login occurs.  or if it will just accept this 1 user/pwd combo.  if it was random, I would expect to be able to login randomly and at different times.  This has been consistent for the last 5 hours, after reboot and all.  But if I reinstall this using the same iso and can only log in with that username/combo, I wouldn't say that's random...  I literally just did that with the pic I included.  I just dont want anyone to log in and then be able to access teh box, even if it's on a dmz, since it's a physical box and not a vm.

**Comment by shaderecker** [comment]
Not quite sure about the behaviour.

But anyways: If somebody log into that ssh honeypot, he still doesn't have access to your machine.
He is confined in a fake filesystem (https://cowrie.readthedocs.io/en/latest/README.html#features).

**Comment by jiggaracci** [comment]
I just got it, so it's caching that information.  I feel like such an idiot, lmao,  thanks man!!!
