### ISSUE TITLE
Azure instance often become unresponded

### ISSUE THREAD

**Issue by dj4n60** [telekom-security/tpotce#797]
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
![image](https://user-images.githubusercontent.com/36102669/111904794-5223e400-8a51-11eb-8e51-1c774d0a62a0.png)
- What T-Pot version are you currently using?
Latest available
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Cloud VM on azure 
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No Error
- How long has your installation been running?
24-48 Hours approximately 
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
/etc/Crontab Commented the updates on Sunday
- Please provide a screenshot of `glances` and `htop`.
![glance](https://user-images.githubusercontent.com/36102669/111904731-0c671b80-8a51-11eb-8210-334a96b2ac70.png)
- How much free disk space is available (`df -h`)?
I started with 30 GB and planning to expand if become stable
![df](https://user-images.githubusercontent.com/36102669/111904944-edb55480-8a51-11eb-9457-d4cf2d9b8564.png)
- What is the current container status (`dps.sh`)?
 ![dps](https://user-images.githubusercontent.com/36102669/111904730-0bce8500-8a51-11eb-9231-3cc83a1ff24b.png)
- What is the status of the T-Pot service (`systemctl status tpot`)?
 ![status](https://user-images.githubusercontent.com/36102669/111904726-0709d100-8a51-11eb-9899-68f8b0c65b52.png)
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

The problem is that the VM won't work sometimes and only after many restarts or stops , which mean deloacation from azure, is working again but despite that sometimes services like elastic or kibana wont work at all also the ssh access stop working most of the times, so i have to restart all the installation this mean i have already lost my data because i could not access the vm through ssh.

##Update
My new elastic dashboard
![image](https://user-images.githubusercontent.com/36102669/111905044-6caa8d00-8a52-11eb-86bc-4a4bbf7b03fe.png)

**Comment by t3chn0m4g3** [comment]
This has beed discussed before. Please search existing issues for `azure`. We have no influence on how hyperscalers such as AWS, Azure or GCP execute their machines. We are running our testing against Open Telekom Cloud which works fine and is based on Open Stack.
Please review the other issues which suggested to re-enable IPv6 support for T-Pot.
