### ISSUE TITLE
Using T-Pot 20.06.2 (High)

### ISSUE THREAD

**Issue by ScorpionKing34** [telekom-security/tpotce#800]
Dear T-pot developers,

I have installed T-Pot 20.06.2 and I can connect to ssh 64295, Admin ui 64294 and Web ui 64297.
But, when I start kibana and click one of the dashboards, I get the following error: Could not locate that index-pattern-field (id: type.keyword).

Also how can I add account in the Admin ui https://<your.ip>:64294 to manage dockers ectra.
I can only login with tsec account en not root.
 

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

- What T-Pot version are you currently using? 20.06.2
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running? first time user
- Did you install upgrades, packages or use the update script? NO
- Did you modify any scripts or configs? If yes, please attach the changes. NO
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M   12M  787M   2% /run
/dev/sda2       484G  7.7G  452G   2% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/8f06b2a62a024207043d95399205fa707d5a4c876547c255ba99c20ed78ed3c9/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/cc15b87662c4b70928d493dc9be67d9238df94c06655c4151cb6b57328a8b328/merged
shm              64M     0   64M   0% /var/lib/docker/containers/a41c449ef5c007707d49c1d4f4bbebb69b0e48a7d8cec68533755fa3ba10a52b/mounts/shm
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/f1bf0a261fdaab01fc0b7bdb3edf3a7493ccc9e5f59ff858a815dafc4dd8036b/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/655e4c89ccb2dffa60a97ac14273e5956c72fda90fdf443b7b32ed2e06d424ff/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/5b19e4503d5733131781b9e053fb79c3ca3d096794febc862c78c2cf88001631/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/e3ee481b7871f4adae478255d36ae4fa904959adc678e0b7dffe20dcb9402823/merged
shm              64M     0   64M   0% /var/lib/docker/containers/10a42febde59ec4cca48350bf00d1a11df8761455ad44e9fe49ac76afaf51f8b/mounts/shm
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/5f9f86728055f374762dcb23e1ec539e9d845ecca509f6015e7b32222f254526/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/dac507da8d4e3dd8067eae766519d515d43f23b82a964d5eae31da5a4df86ca6/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/019052d2efcaf5a7d7e3718185feb633e131207bfaca835238269701d936b64a/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/abc450d5f21d38cab249d87272d7029c763994b32316e7fb6d1348278a71bd14/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/87eb749eed7f4c9072214f031ad0a28878153a218ae09f89886381e50525bc25/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/1aa71e7c928a0d7b840eabe8bd742e4259466c23d4b457a4ccb48854c1a6ec05/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/f27c11d45f9a7cd1f2b3f028cdb0b6d71f2440381dcf62ade60213a733b34af9/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/3cdbc0dc3332b7181823a02248473623b396dd2b67f69ca8ac9ad1dacde9a708/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/07bf523cb5a752d93bec821e340c7ebbd2adebf9f8bdd96a2419c1c77ec46408/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/6ccac1aae1fefef45e943f7065ed56f8bf7d5d24cd4fdda493eddfaf7c79f793/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/655c7b874af24d65ee387db99bf58a208a22b107fd512bd911892ac0b547d178/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/f768a676ea487357b370f0a66f84a0e5f3555817ace0855e7acd62c9efcbcdbe/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/e28139eb0a5b080c64f07ad2e9fac90440c0a701153cec88bc532c1338367987/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/6f56ca75edbe81c7b5c8b98f2702f7ca2fee53c68ff7cbe4dbf3c802188a39da/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/aff21d8fbd0174653206b433a07f5d309db4a197007e00dac79c3080bcede2a7/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/e01f55c02077890e3a5efccb10b621bc83f9a25643fa7d44452d8ea671f7ff2e/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/ad566be977fb3410c07b4a07a30d56e64c70183ebbe5381cd3db501ea0d21cf0/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/a4aa8ea7108258b703df35724f7d1ee249ee5638eae0513152b55a2bf0c4d10f/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/8af63a0ef6866290d9946a9455bceb36503e8326d9fd58fee0753ef5e649e17c/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/f231ffd86e321bcadac269cf3da7df9cba24b26d4798f1a4735a4ad4714b1174/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/d32711efceba875489e7648faa450bef8577586a7d0393ef1b4a98114e949af5/merged
shm              64M     0   64M   0% /var/lib/docker/containers/d24bd48f282148eed4460748ef3ee2a4f7f16c24babcbb6d43dfc0116f6af00f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/b588c0bf7d9324b8ae1e12fa8972075d09fa1c487aa3e4e5d903e4d73a665cf7/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/2cd7251a77fcc2e094653b1c6b5f3d7dba0852820a8a723c98f02795bf63b341/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1d812b01649d73238285424b0367345adc7af14b73d6c70da333a71f8901f42d/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/6e539a44897460b520ed56dd05c98a040f6a5480e4256bdfa2c3fd4ebeb0477f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/53842a6b1a7f99055d2bec35983bd4e41772843d90d14add64559146ee4e0078/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/0ac0d03eb63b7e52387594346665adb353a46277dc03b58809ab6447fb0254bb/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/3b2ef2644dfe4e6d78b668875f8488211c43a14e1fb4ba9a7a74926fa69bcffc/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bba42813ee49e811647966384e010a962b0573ddb7d27aae6248a1298428db41/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d02424f08da067c87a7e8baebbf7c77135a43bbffe8aa267a59070b23a6dd4b3/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d9c9f5a359e0a71efa0c66c86b5d8c670d7ceaca09edd0a199e82cdc3dd14e63/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/0eb2abd3fdd47d71c7e498d2479daf9815037b3ccd208a8ca09e91df0435d1c6/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/dfda55f9b0026969728e00a198056b8a55786901bd148828d9f33354811c70f7/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d883929f352a6cd92364184254377105ab9bf2420bb7052935d388fc46ecd6e6/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/5feb41d7a022765a9cc096349cacec9fc727618e89d47de70971e7049cd75e3a/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d4fd80d867a47f3092fd996585f944d4de380bfa9f428790449908a5e604f379/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/31b50da04361db7e66de04e77b549580c7740c149968bc00bfb5e72bb524c2ec/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/57b3bb13bebdc68904c91bc12a3a66afc393c5f36904e3f5b58e34f2de30ccbf/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/ffaabab75d768c85f55a6dc842502a40829beae930b950bf78830a9003d2db3c/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e1ee93679865008054e537ec21a066a98d65c5aeb005c2586970ccbc73a0fae8/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c6edf4104ecf04a9ca74e4b83045556b36b4556fc3ea2359673c8e2909ed4643/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/aacc70f0da1c91cfe167731ec171197a2f8700e19e579388c05ac9f8e537ba3a/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e5a22b4cfc339d8a3e680910e8feceb278fd8f7166efd8daa8a65ad817cac394/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/03cb014840b3e88796d2c422b7c1f7913e0463dc334b7c0f4570204dd92608df/mounts/shm
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/970ab852a8d3a032a3b4d8e7a25976f91b85de90b4747b8cfe0c721ed3e3c909/merged
shm              64M     0   64M   0% /var/lib/docker/containers/5d3527910b95dddebd0bce71c93a920a0161da93bfac313f4016b5250de042a0/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/154ad0d6d06c6b8841f9c7adf45cedd20419ff33aa6f2ada01667d3a700e1389/mounts/shm
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/d615573cf2fa60ffe94ff1a909a606d3c337ccca9f08324735735d9e042bd16f/merged
shm              64M     0   64M   0% /var/lib/docker/containers/a8dcc918a1f22932609e492fd70871bbffa62a557abc07d2c158af93c412e6be/mounts/shm
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/1e244cb2cd506db60a04dbfc75a2c3c88bae184991917ec4bd2825ff0c066685/merged
shm              64M   20K   64M   1% /var/lib/docker/containers/a93c638cf938effcb54db12de1dc177d67631fc10479bf406ba4b19778e855e0/mounts/shm
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/266c29e4fb1f5fcef60b5536e6fc46603fb923e7f379abe182fae75a4a1282df/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/9e1fefc4d8cc6e6463b5320c07a7fb49bcaf4264cfdd6c403764458425afd50a/merged
overlay         484G  7.7G  452G   2% /var/lib/docker/overlay2/10f868ad507db68c87657e6d3d13f3a492611aeafb1d91a5f513a7facada8505/merged
shm              64M     0   64M   0% /var/lib/docker/containers/444d7eacb94316b9b98f01e37a4e8c09174edae93c5a002e649964847d6e2e3f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c1f1ef3d7b170413aeda538acf9080d9c11dbcbae460e2a49152aa32c7095212/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/0d0f7b07c61be7ee67528ec1f8e8d18dce3e103cb9bc8bda3173cd4f708ab2f9/mounts/shm
tmpfs           798M     0  798M   0% /run/user/1000

- What is the current container status (`dps.sh`)? Can not locate file permission denied.
- What is the status of the T-Pot service (`systemctl status tpot`)?
tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-24 10:49:26 UTC; 29min ago
  Process: 822 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 846 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 892 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 900 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 906 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 918 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 930 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 942 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 958 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code
  Process: 964 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exit
  Process: 970 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited,
  Process: 976 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 1053 (docker-compose)
    Tasks: 35 (limit: 4915)
   Memory: 97.2M
   CGroup: /system.slice/tpot.service
           └─1053 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
 netstat -tulpen
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 127.0.0.1:61209         0.0.0.0:*               LISTEN      0          16368      -
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16184      -
tcp        0      0 0.0.0.0:64297           0.0.0.0:*               LISTEN      0          144994     -
tcp        0      0 127.0.0.1:64298         0.0.0.0:*               LISTEN      0          146725     -
tcp        0      0 127.0.0.1:64299         0.0.0.0:*               LISTEN      0          147020     -
tcp        0      0 127.0.0.1:64303         0.0.0.0:*               LISTEN      0          146995     -
tcp        0      0 127.0.0.1:42607         0.0.0.0:*               LISTEN      1000       64815      9572/cockpit-bridge
tcp        0      0 127.0.0.1:64304         0.0.0.0:*               LISTEN      0          144973     -
tcp6       0      0 :::10001                :::*                    LISTEN      0          151553     -
tcp6       0      0 :::5555                 :::*                    LISTEN      0          150669     -
tcp6       0      0 :::50100                :::*                    LISTEN      0          146802     -
tcp6       0      0 :::22                   :::*                    LISTEN      0          146882     -
tcp6       0      0 :::23                   :::*                    LISTEN      0          146668     -
tcp6       0      0 :::1080                 :::*                    LISTEN      0          151964     -
tcp6       0      0 :::5432                 :::*                    LISTEN      0          150568     -
tcp6       0      0 :::25                   :::*                    LISTEN      0          147085     -
tcp6       0      0 :::443                  :::*                    LISTEN      0          150965     -
tcp6       0      0 :::3389                 :::*                    LISTEN      0          146767     -
tcp6       0      0 :::1025                 :::*                    LISTEN      0          146946     -
tcp6       0      0 :::3299                 :::*                    LISTEN      0          151216     -
tcp6       0      0 :::5060                 :::*                    LISTEN      0          151639     -
tcp6       0      0 :::2404                 :::*                    LISTEN      0          150934     -
tcp6       0      0 :::5061                 :::*                    LISTEN      0          150442     -
tcp6       0      0 :::64294                :::*                    LISTEN      0          12764      -
tcp6       0      0 :::64295                :::*                    LISTEN      0          16195      -
tcp6       0      0 :::11112                :::*                    LISTEN      0          147142     -
tcp6       0      0 :::27017                :::*                    LISTEN      0          146973     -
tcp6       0      0 :::5900                 :::*                    LISTEN      0          147116     -
tcp6       0      0 :::2575                 :::*                    LISTEN      0          151544     -
tcp6       0      0 :::9200                 :::*                    LISTEN      0          151779     -
udp        0      0 xx.x.x.xx:123           0.0.0.0:*                           0          16076      -
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          16074      -
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          16070      -
udp        0      0 0.0.0.0:5000            0.0.0.0:*                           2000       151724     -
udp        0      0 0.0.0.0:52134           0.0.0.0:*                           2000       151738     -
udp6       0      0 :::123                  :::*                                0          16067      -
udp6       0      0 :::623                  :::*                                0          147071     -

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Please login as `tsec`, gain root access `sudo su -` and provide all the info. Thanks.

**Comment by ScorpionKing34** [comment]
/opt/tpot/bin/dps.sh
========| System |========
    Date:  Wed 24 Mar 2021 12:18:19 PM UTC
  Uptime:  12:18:19 up  1:29,  2 users,  load average: 0.71, 1.15, 1.45

NAME                  STATUS                       PORTS
adbhoney              Up About an hour             0.0.0.0:5555->5555/tcp
ciscoasa              Up About an hour
citrixhoneypot        Up About an hour             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up About an hour             0.0.0.0:10001->10001/tcp
conpot_iec104         Up About an hour             0.0.0.0:161->161/udp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up About an hour             0.0.0.0:623->623/udp
conpot_kamstrup_382   Up About an hour             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up About an hour             0.0.0.0:22-23->22-23/tcp
cyberchef             Up About an hour (healthy)   127.0.0.1:64299->8000/tcp
dicompot              Up About an hour             0.0.0.0:11112->11112/tcp
dionaea               Up About an hour             0.0.0.0:20-21->20-21/tcp, 0.0.0.0:42->42/tcp, 0.0.0.0:81->81/tcp, 0.0.0.0:135->135/tcp, 0.0.0.0:445->445/tcp, 0.0.0.0:1433->1433/tcp, 0.0.0.0:1723->1723/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:3306->3306/tcp, 0.0.0.0:69->69/udp, 0.0.0.0:5060-5061->5060-5061/tcp, 0.0.0.0:27017->27017/tcp, 0.0.0.0:5060->5060/udp
elasticpot            Up About an hour             0.0.0.0:9200->9200/tcp
elasticsearch         Up About an hour (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up About an hour
fatt                  Up About an hour
head                  Up About an hour (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up About an hour             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:465->465/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeysap              Up About an hour             0.0.0.0:3299->3299/tcp
honeytrap             Up About an hour
kibana                Up About an hour (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up About an hour (healthy)
mailoney              Up About an hour             0.0.0.0:25->25/tcp
medpot                Up About an hour             0.0.0.0:2575->2575/tcp
nginx                 Up About an hour
p0f                   Up About an hour
rdpy                  Up About an hour             0.0.0.0:3389->3389/tcp
snare                 Up About an hour             0.0.0.0:80->80/tcp
spiderfoot            Up About an hour (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up About an hour
tanner                Up About an hour
tanner_api            Up About an hour
tanner_phpox          Up About an hour
tanner_redis          Up About an hour             6379/tcp

And how can I add account to manage the docker containers? And why I get the error 'Could not locate that index-pattern-field (id: type.keyword)'in kibana?

Is there also a manual how to analyze logs in kibana and Elasticsearch head? In your wiki is not mutch to find.

Please provide a screenshot of glances and htop

 glances image
![afbeelding](https://user-images.githubusercontent.com/39624641/112310107-788d8d80-8ca4-11eb-8142-17de04a8ea89.png)

htop image
![afbeelding](https://user-images.githubusercontent.com/39624641/112310206-9824b600-8ca4-11eb-99ef-edbb2b7bb077.png)

**Comment by ScorpionKing34** [comment]
Also I find out that my honeypot make too much outside connections to different IP addresses on port 80 and 443.

**Comment by t3chn0m4g3** [comment]
Please find the architecture overview for external connections.
Your machine seems to be (at least at times) overloaded, please make sure you meet all requirements.

**Comment by ScorpionKing34** [comment]
My system is 8 GB RAM and 500 GB storage with Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz

tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-24 13:16:04 UTC; 4min 6s ago
  Process: 12187 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 12291 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 12365 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 12368 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 12371 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 12383 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 12395 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 12407 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 12422 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCC
  Process: 12428 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 12434 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 12440 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 12512 (docker-compose)
    Tasks: 35 (limit: 4915)
   Memory: 48.5M
   CGroup: /system.slice/tpot.service
           └─12512 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |     response = self._open(req, data)
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |     result = self._call_chain(self.handle_open, protocol, protocol +
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |     result = func(*args)
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |   File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |     return self.do_open(http.client.HTTPSConnection, req,
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |   File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             |     raise URLError(err)
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot             | urllib.error.URLError: <urlopen error [Errno 99] Address not available>

**Comment by t3chn0m4g3** [comment]
> Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | response = self._open(req, data)
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | result = self._call_chain(self.handle_open, protocol, protocol +
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | result = func(*args)
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | return self.do_open(http.client.HTTPSConnection, req,
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | raise URLError(err)
Mar 24 13:20:11 digitalgray docker-compose[12512]: elasticpot | urllib.error.URLError: <urlopen error [Errno 99] Address not available>

There seems to be some sort of IP address conflict.

**Comment by ScorpionKing34** [comment]
On the VLAN there is only one machine, namely the T-pot with his own static IP, gateway and DNS.

**And how can I add account in Cockpit to manage the docker containers?** I can only login with tsec and I don't no the root password. 

And why I get the error 'Could not locate that index-pattern-field (id: type.keyword)'in Kibana dashboards?
Tomorrow I will make a list of dashboards that shows the error and give you a list per dashboard which panels I see, so that you can tell which panels I miss and how to add them manually.
  
Is there also a manual how to analyse logs in Kibana T-pot data and using Elasticsearch head? 
In your wiki is not much to find.

The reason I ask a lot of questions is, because I am doing research in honeypots and how to use them to make beter detection rules and is also for school as my final research project to get my degree in Bachelor of Science Cyber security. 

So I hope you can help me with al the questions I have.

**Comment by t3chn0m4g3** [comment]
1. Even that might be the adress conflict, as the log shows. Please search issues for ip conflicts.
2. Please check the Cockpit manual, it's part of the OS and out of the scope of T-Pot.
3. This is probably to some install error / address conflict, but you did not provide the logs.
4. No, there is no manual.
5. We provide T-Pot as is and are happy to help if there is a reproducable issue at hand, but as far as I can see the issues were discussed before. Send logs please and we can have a look what went wrong during install.

**Comment by ScorpionKing34** [comment]
Oke, tomorrow I look for the logs and read the Cockpit manual.

Anyway, thanks in advance for your help and commitment. Every bit helps.
;)

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
