### ISSUE TITLE
Own certificate - only partial success

### ISSUE THREAD

**Issue by xcampax** [telekom-security/tpotce#801]
I would like to use my own certificate and have been partially successful so far: 
- I generated a CSR,
- Had it signed by our PKI,
- Copied the private key to /data/nginx/cert/nginx.key and the public certificate to /data/nginx/cert/nginx.crt, and
- Executed `docker container restart nginx`.

The main portal at :64297 is looking good, but when going to the Cockpit, which includes a redirect to port :64294, the certificate does not seem to take anymore. The certificate details mention a hostname and issue date from the time when the system was initially installed (but the hostname has changed in the meantime). Please let me know what to change to make the current certificate effective for the cockpit as well.

Thank you.
Nora

**Comment by t3chn0m4g3** [comment]
Cockpit is a different web server. Please check the cockpit documentation for all the details.
