### ISSUE TITLE
T-Pot 20.06.2 shows no dashboard panels

### ISSUE THREAD

**Issue by ScorpionKing34** [telekom-security/tpotce#803]
Do to closed Issue that I have, I start all over again.
I had network storage issue and had not the time to reinstall T-pot in test environment.
Now, I have at home a backup computer consist of the following hardware:
- Intel i7 Gen 9, 3 GHz
- 16 GB RAM
- 500 SDD Hard disk
- 1 Gbps network interface card 

Still I do not see all dashboard panels.

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
lsb_release -a:
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

uname -a:
Linux firmblackboard 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

- What T-Pot version are you currently using? 20.06.2
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? Standard
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. The following installation errors are:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
Possible missing firmware /lib/firmware/rtl_nic/rtl8107e-2.fw for module r8169

- How long has your installation been running? Today about a hour, is newly installed.
- Did you install upgrades, packages or use the update script? No
- Did you modify any scripts or configs? If yes, please attach the changes. No
- Please provide a screenshot of `glances` and `htop`.
![afbeelding](https://user-images.githubusercontent.com/39624641/112744662-5fd1f000-8fa2-11eb-8743-e1b8373546a9.png)

- How much free disk space is available (`df -h`)?
![afbeelding](https://user-images.githubusercontent.com/39624641/112744704-bc350f80-8fa2-11eb-8389-b1d9f9ba82e0.png)

- What is the current container status (`dps.sh`)?
![afbeelding](https://user-images.githubusercontent.com/39624641/112749793-00390c00-8fc5-11eb-9f06-1a123a45374c.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
systemctl status tpot
 tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2021-03-28 10:55:01 UTC; 1min 43s ago
  Process: 13628 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 13732 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 13857 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 13860 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 13863 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 13887 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 13911 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 13935 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 13963 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 13969 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 13975 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 13981 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 14056 (docker-compose)
    Tasks: 35 (limit: 4915)
   Memory: 50.3M
   CGroup: /system.slice/tpot.service
           └─14056 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Mar 28 10:56:35 firmblackboard docker-compose[14056]: ewsposter              |  => Send Limit is set to : 5000. Adapting to limit!
Mar 28 10:56:35 firmblackboard docker-compose[14056]: ewsposter              |     -> 0 EWS alert records send ...
Mar 28 10:56:35 firmblackboard docker-compose[14056]: ewsposter              |  => Starting FATT Honeypot Modul.
Mar 28 10:56:35 firmblackboard docker-compose[14056]: ewsposter              |  => Send Limit is set to : 5000. Adapting to limit!
Mar 28 10:56:35 firmblackboard docker-compose[14056]: ewsposter              |     -> 0 EWS alert records send ...
Mar 28 10:56:35 firmblackboard docker-compose[14056]: ewsposter              |  => Sleeping for 18 seconds ....
Mar 28 10:56:37 firmblackboard docker-compose[14056]: spiderfoot             | 2021-03-28 10:56:37,496 [INFO] 127.0.0.1 - - [28/Mar/2021:10:56:37] "GET /spiderfoot/ HTTP/1.1" 200 5083 "" "curl/7.74.0"
Mar 28 10:56:38 firmblackboard docker-compose[14056]: cyberchef              | [Sun Mar 28 2021 10:56:38 GMT+0000 (Coordinated Universal Time)]  "GET /" "curl/7.66.0"
Mar 28 10:56:39 firmblackboard docker-compose[14056]: head                   | [2021-03-28T10:56:39.396Z]  "GET /" "curl/7.74.0"
Mar 28 10:56:39 firmblackboard docker-compose[14056]: kibana                 | {"type":"response","@timestamp":"2021-03-28T10:56:39+00:00","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"
lines 1-31/31 (END)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![afbeelding](https://user-images.githubusercontent.com/39624641/112744754-1cc44c80-8fa3-11eb-9d4a-1f19ead8784c.png)

After starting T-pot systemctl status tpot shows the following:

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

Enabled port forwarding for the following ports from internet to my t-pot:
cowrie --> 22   (ssh) tcp -23 (telnet) tcp
--
mailoney --> 25 (smtp) tcp
snare (tanner) --> 80 tcp
citrixhoneypot --> 443 tcp
rdpy --> 3389 (rdp) tcp
dionaea --> 445 tcp (samba), 69 udp   (tftp), 135 (rpc (TCP/UPD)), 3306 (MySQL (TCP/UPD)), 21 (ftp (TCP), 81   (TCP/UPD), 1433 (SQL TCP/UPD)
heralding --> 110 (pop (TCP/UPD)), 143   (imap (TCP/UPD)), 993 (imaps (TCP/UPD)), 995 (pop3s (TCP/UPD)), 1080 (socks5   (TCP/UPD)), 5432 (PostgreSQL (TCP/UPD)), 5900 (vnc (TCP/UPD))
adbhoney -> 5555 (tcp)
dicompot --> 11112 (tcp)
ciscoasa --> 5000/udp 8443 (tcp)
Conpot IEC104 --> 161 udp (snmp) and   2404 (tcp)
Conpot guardian_ast --> 10001 (tcp)
Conpot ipmi --> 623 (udp)
Conpot kamstrup_382 --> 1025 (tcp) and   50100 (tcp)
HoneySAP --> 3299 (tcp)
Medpot --> 2575 (tcp)

Panel thats shows and panels thats has a error in them:

T-Pot Dashboard
- panel => Honeypot Attacks - Top 10 (shows info)
- panel => Honeypot Attacks Histogram (shows info)
- panel => Honeypot Attack Map (shows info) 
- panel => Attacks by Destination Port Histogram (shows info)
- panel => Attacks by Honeypot Histogram (shows info)  
- panel => Attacks by Country Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Attacks by Honeypot (shows info)
- panel => P0f OS Distribution (shows info)
- panel => Attacks by Country No results found (need fix)
- panel => Attacks by Country and Port No results found (need fix)
- panel => Suricata Alert Signature - Top 10 (shows info)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Attacker AS/N - Top 10 No results found (need fix)
- panel => Attacker Source IP - Top 10 (shows info)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Suricata Alert siganture (shows info)

Adbhoney Dashboard	(TCP port 5555 forward to my internal HP)
- panel => Adbhoney Attacks Bar No results found (need fix)
- panel => Adbhoney Attacks No results found (need fix)
- panel => Adbhoney Attack Map No results found (need fix)
- panel => Adbhoney Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Adbhoney - Attacks by Country No results found (need fix)
- panel => Adbhoney - Attacks by Country Histogram No results found (need fix)
- panel => Adbhoney - Attacker AS/N - Top 10 No results found (need fix)
- panel => Adbhoney - Attacker Src IP - Top 10 No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)

Ciscoasa Dashboard (TCP and UDP ports (5000/udp 8443/tcp)) forward to my internal HP)
- panel => Ciscoasa Attacks Bar (shows info)
- panel => Ciscoasa Attacks (shows info)
- panel => Ciscoasa Attack Map No results found (need fix)
- panel => Ciscoasa Attacks Histogram (shows info)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Ciscoasa - Attacks by Country No results found (need fix)
- panel => Ciscoasa - Attacks by Country Histogram No results found (need fix)
- panel => Ciscoasa - Attacker Src IP - Top 10 No results found (need fix)
- panel => Ciscoasa - Attacker AS/N - Top 10 No results found (need fix)

CitrixHoneypot Dashboard (TCP port 443 forward to my HP)
- panel => CitrixHoneypot Attacks Bar No results found (need fix)
- panel => CitrixHoneypot Attacks No results found (need fix)
- panel => CitrixHoneypot Attack Map No results found (need fix)
- panel => CitrixHoneypot Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword)
- panel => CitrixHoneypot - Attacks by Country No results found (need fix)
- panel => CitrixHoneypot - Attacks by Country Histogram No results found (need fix)
- panel => CitrixHoneypot - Attacker AS/N - Top 10 No results found (need fix)
- panel => CitrixHoneypot - Attacker Src IP - Top 10 No results found (need fix)
- panel => CitrixHoneypot Filenames - Top 10 No results found (need fix)

Conpot Dashboard (TCP and UDP ports (80/tct, 102/tcp or udp, 502/tcp or udp, 1025/tcp or udp, 44818/tcp or udp, 47808/tcp or udp, 161/udp, 2404/tcp, 10001/tcp, 623/udp 1025/tcp) and 50100/tcp) forward to my HP) 
- panel => Conpot Attacks Bar No results found (need fix)
- panel => Conpot Attacks No results found (need fix)
- panel => Conpot Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: data_type.keyword) (need fix)
- panel => Conpot - Attacks by Country No results found (need fix)
- panel => Conpot - Attacks by Country Histogram No results found (need fix)
- panel => Conpot Event Type No results found (need fix)
- panel => Conpot - Attacks by Destination Ports Histogram (need fix)
- panel => Conpot - Attacker AS/N - Top 10 No results found (need fix)
- panel => Conpot - Attacker Src IP - Top 10 No results found (need fix)
- panel => Could not locate that index-pattern-field (id: data_type.keyword) (need fix)

Cowrie Dashboard 	(TCP ports (22/tcp 23/tcp) forwarded to my HP)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Cowrie - Attacks by Destination Ports Histogram Incoming No results found (need fix)
- panel => Cowrie - Attacks by Destination Ports Histogram No results found (need fix)
- panel => Cowrie - Attacks by Country Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Cowrie - Attacks by Country No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Cowrie - Attacks by Port (shows info)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)

Dicompot Dashboard (TCP port 11112 forwarded to my HP)
- panel => Dicompot Attacks Bar No results found (need fix)
- panel => Dicompot Attacks No results found (need fix)
- panel => Dicompot Attack Map No results found (need fix)
- panel => Dicompot Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Dicompot - Attacks by Country Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Dicompot - Attacker AS/N - Top 10 No results found (need fix)
- panel => Dicompot - Attacker Src IP - Top 10 No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)

Dionaea Dashboard  (TCP and UDP ports (445/TCP, 69/UDP, 135/TCP, 3306/TCP, 21/TCP, 81/TCP, 1433/TCP, 42/TCP, 8081/TCP, 443/TCP, 1433/TCP, 1723/TCP, 1883/TCP, 1900/UDP, 5060/UDP, 5061/UDP) forwarded to my HP)
- panel => Dionaea Attacks Bar No results found (need fix)
- panel => Dionaea Attacks No results found (need fix)
- panel => Dionaea Attack Map No results found (need fix)
- panel => Dionaea Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Dionaea - Attacks by Country No results found (need fix)
- panel => Dionaea - Attacks by Country Histogram (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Dionaea - Attacks by Port No results found (need fix)
- panel => Dionaea - Attacks by Destination Ports Histogram (need fix)
- panel => Dionaea - Attacks by Country Histogram No results found  (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => Dionaea - Attacker AS/N - Top 10 (need fix)
- panel => Dionaea - Attacker Src IP - Top 10 (need fix)

ElasticPot Dashboard (TCP port 9200 forwarded to my HP)
- panel => ElasticPot Attacks Bar No results found (need fix)
- panel => ElasticPot Attacks No results found (need fix)
- panel => ElasticPot Attack Map No results found (need fix)
- panel => ElasticPot Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: hassh.keyword) (need fix)
- panel => ElasticPot - Attacks by Country No results found (need fix)
- panel => ElasticPot - Attacks by Country Histogram No results found (need fix)
- panel => ElasticPot - Event Types No results found (need fix)
- panel => ElasticPot - User Agent - Top 10 (need fix)
- panel => ElasticPot - Request Method - Top 5 No results found (need fix)
- panel => ElasticPot - Attacker AS/N - Top 10 No results found (need fix)
- panel => ElasticPot - Attacker Src IP - Top 10 No results found (need fix)
- panel => ElasticPot Query - Top 10 No results found (need fix)

Fatt Dashboard (No tcp/udp to forward to my HP)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Fatt Attack Map (Shows some info)
- panel => Fatt Destination Ports Histogram (Shows some info)
- panel => Fatt Events by Country Histogram (Shows some info)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Fatt Countries - Top 10 No results found (Shows some info)
- panel => Fatt Protocols - Top 10 No results found (Shows some info)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Fatt - IP / TLS-JA3 - Pie No results found (Shows some info)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: fatt_http.clientHeaderHash.keyword) (need fix)
- panel => Fatt AS/N - Top 10 No results found (Shows some info)
- panel => Fatt Source IP - Top 10 No results found (Shows some info)

Heralding Dashboard  (TCP Ports (110, 143, 993, 995, 1080, 5432, 5900, 465) forwarded to my HP) 
- panel => Heralding Attacks Bar (Shows some info)
- panel => Heralding Attacks No (Shows some info)
- panel => Heralding Attack Map No results found (need fix)
- panel => Heralding Attacks Histogram No results found (need fix)
- panel => Heralding Protocols Histogram No results found (need fix)
- panel => Heralding - Attacks by Country Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Heralding - Attacks by Country No results found (need fix)
- panel => Heralding - Attacks by Port No results found (need fix)
- panel => Could not locate that index-pattern-field (id: username.keyword) (need fix)
- panel => Could not locate that index-pattern-field (id: username.keyword) (need fix)
- panel => Heralding - Attacker AS/N - Top 10 No results found (need fix)
- panel => Heralding - Attacker Src IP - Top 10 No results found (need fix)
- panel => Could not locate that index-pattern-field (id: username.keyword)(need fix)

Honeysap Dashboard (TCP Port 3299 forwarded to my HP)
- panel => Honeysap Attacks Bar No results found (need fix)
- panel => Honeysap Attacks No results found (need fix)
- panel => Honeysap Attack Map No results found (need fix)
- panel => Honeysap Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: data.keyword) (need fix)
- panel => Honeysap - Attacks by Country No results found (need fix)
- panel => Honeysap - Attacks by Country Histogram No results found (need fix)
- panel => Honeysap - Event Types No results found (need fix)
- panel => Honeysap - Attacker AS/N - Top 10 (need fix)
- panel => Honeysap - Attacker Src IP - Top 10 (need fix)

Mailoney Dashboard (TCP Port 25 forwarded to my HP)
- panel => Mailoney Attacks Bar No results found (need fix)
- panel => Mailoney Attacks No results found (need fix)
- panel => Mailoney Attacks Histogram No results found (need fix)
- panel => Mailoney Attack Map No results found (need fix)
- panel => Mailoney - Attacks by Country No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Mailoney - Attacks by Country Histogram No results found (need fix)
- panel => Mailoney - Attacker AS/N - Top 10 No results found (need fix)
- panel => Mailoney - Attacker Src IP - Top 10 No results found (need fix)
- panel => Could not locate that index-pattern-field (id: smtp_input.keyword) (need fix)

Medpot Dashboard (TCP Port 2575 forwarded to my HP)
- panel => Medpot Attacks Bar No results found (need fix)
- panel => Medpot Attacks No results found (need fix)
- panel => Medpot Attack Map No results found (need fix)
- panel => Medpot Attacks Histogram No results found (need fix)
- panel => Could not locate that index-pattern-field (id: ip_rep.keyword) (need fix)
- panel => Medpot - Attacks by Country No results found (need fix) 
- panel => Medpot - Attacks by Country Histogram No results found (need fix)
- panel => Medpot - Attacker AS/N - Top 10 No results found (need fix)
- panel => Medpot - Attacker Src IP - Top 10 No results found (need fix)
- panel => Could not locate that index-pattern-field (id: data.keyword) (need fix)

NGINX Dashboard
- panel => NGINX Events Bar
- panel => NGINX Events
- panel => NGINX Events Histogram
- panel => NGINX Username Tagcloud
- panel => NGINX Top Users Histogram
- panel => NGINX Events by Country Histogram No results found
- panel => NGINX Countries - Top 10
- panel => NGINX HTTP Method Pie - Top 10
- panel => NGINX HTTP Status Code Pie - Top 10
- panel => NGINX HTTP User Agent Pie - Top 10
- panel => NGINX - AS/N - Top 10  No results found
- panel =>  NGINX Source IP - Top 10

Missing rdpy dashboards (TCP Port 3389 forwarded to my HP)
Missing snare & tanner dashboards (TCP Port 80 forwarded to my HP)

I hope you can help me to solve the problems I having.

**Comment by t3chn0m4g3** [comment]
Looks perfectly fine. T-Pot just did not collect events yet.

And again you failed to provide the logs.

This is no T-Pot problem, post questions and alike in discussions.

Thanks for understanding.

**Comment by ScorpionKing34** [comment]
Tonight i will look for the logs and send it to you or upload in git.

I am now not at home.

With kind regards from

Scorpionking37 (Ben)

Op zo 28 mrt. 2021 14:04 schreef Marco Ochse ***@***.***>:

**Comment by ScorpionKing34** [comment]
Can you reopen this issue, which logs do you need?
