### ISSUE TITLE
hello-I am from China and would like to participate in this project

### ISSUE THREAD

**Issue by PINGXcpost** [telekom-security/tpotce#812]
Hello, this is China's information security practitioners, I think your project is very helpful to us, I want to be a part of you, I can translate the program let China need more to realize this great project, and completely as you are completely free, so hope to ask for your approval, I can start translation work. You can contact me at testhook233@gmail.com

**Comment by t3chn0m4g3** [comment]
Thank you, but currently T-Pot does not provide the basis to offer different language options.
