### ISSUE TITLE
Docker: rdpy - Dependency issue

### ISSUE THREAD

**Issue by lgpaulsen** [telekom-security/tpotce#817]
Trying to build the docker for rpdy fails due to dependency issues. 
In dockerfile 

Error log snip
```
Collection rsa
  Downloading https://files.pythonhosted.org/packages/2d/d3/41b3db87f262debadb153900d4e6f8d61aa87187dd6fedd855ed24e8526d/rsa-4.7.1.tar.gz
rsa requires Python '>=3.5, <4' but the running Python is 2.7.18
ERROR: Service 'rdpy' failed to build: The command '/bin/sh -c s
```

RSA packages just had a major update, dropping support for python2. 
https://pypi.org/project/rsa/
Version 4.0 was the last version to support Python 2 and 3.4. Version 4.1 is compatible with Python 3.5+ only.

Fix: need to specify what version of rsa to use in the pip install procedure. 
**rsa==4.0**

File: tpotce/docker/rdpy/Dockerfile: Line: 31

```
# Install deps
    pip install --no-cache-dir --upgrade cffi && \
    pip install --no-cache-dir \
                hpfeeds \
                twisted \
                pyopenssl \
                qt4reactor \
                service_identity \
                rsa==4.0 \
                pyasn1 && \
```

**Comment by t3chn0m4g3** [comment]
This is fixed and pinned to the last known supported version of `rsa==4.5`. However the number of days we will actively support RDPY is limited now. The only docker image this is (securely) working on properly is Alpine 3.11 which only in the last couple of days received an update for apk tools to fix a security issue, hence rebuilding the image. As support will be ending in November it will be only a matter of time before a security issue will arise forcing us to pull the image. A port to other Linux based images revealed even more security issues. For now this is the best we can do. While there a Python 3 branch is existing and building fine it is failing to start properly.
