### ISSUE TITLE
JSON parse error logstash

### ISSUE THREAD

**Issue by RichardPhilipsRoy** [telekom-security/tpotce#828]
Hi, I'm using TPOT sensor to send data to another ec2 instance on AWS running kibana and elastic search.  and I'm getting this error when I start self-installed logstash on tpot sensor. I'm using this exact configuration file (https://github.com/telekom-security/tpotce/blob/master/docker/elk/logstash/dist/logstash.conf) 

the log is generated from this file "/data/tanner/log/tanner_report.json"

Logstash version: logstash 7.12.1

[ERROR] 2021-05-08 10:05:30.310 [[main]<file] json - JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Invalid FieldReference: `0x[]`>, :data=>"{\"method\": \"POST\", \"path\": \"/\", \"headers\": {\"host\": \"54.90.21.149\", \"user-agent\": \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36\", \"accept-encoding\": \"gzip, deflate\", \"accept\": \"*/*\", \"connection\": \"keep-alive\", \"content-length\": \"20\", \"content-type\": \"application/x-www-form-urlencoded\"}, \"uuid\": \"f79d9391-3271-4c5c-a795-be3f5000eb8f\", \"peer\": {\"ip\": \"160.177.125.92\", \"port\": 64174}, \"status\": 200, \"post_data\": {\"0x[]\": \"androxgh0st\"}, \"cookies\": {\"sess_uuid\": null}, \"response_msg\": {\"version\": \"0.6.0\", \"response\": {\"message\": {\"detection\": {\"name\": \"unknown\", \"order\": 0, \"type\": 1, \"version\": \"0.6.0\"}, \"sess_uuid\": \"d2e2823e-e8ca-4f7b-ba91-fa880df013e0\"}}}, \"timestamp\": \"2021-05-07T23:56:36.467915\"}"}

**Comment by t3chn0m4g3** [comment]
Thanks for the heads-up. When we move to Elastic 7.12.x we will have a look into it. However it does not seem to be a general issue for Tanner, but I recommend to open an issue [upstream](https://github.com/mushorg/tanner).
