### ISSUE TITLE
Failed to install TPOT20

### ISSUE THREAD

**Issue by ZhuShaoQiang** [telekom-security/tpotce#829]
while I am trying to install TPOT20 based debian10.x, during the installation, I ran into such a problem.(

`Execution of preseeded command "in-target apt-get -y install grub-pc; in-target
grub-install --force $(debconf-get partman-auto/disk); update-dev; in-target update-grub;
in-target git clone --depth=1 https://github.com/telekom-security/tpotce /opt/tpot;
in-target sed -i 's/allow-hotplug/auto/g' /etc/network/interfaces; cp
/target/opt/tpot/iso/installer/rc.local.install /target/etc/rc.local; cp
/target/opt/tpot/iso/installer -R /target/root/;" failed with exit code 1.`

My installation environment:
1. VMware Workstation 16 Player
2. Windows 10 家庭中文版 20H2. 19042.985  2021/3/17
3. and I select "Linux debian 10.x 64 bit" when I config VM settings.
And, I can access to github when this error occured.(I had tried to install this tpot.iso for three times)

Please help me to fast-track this problem. Thanks very much!!!!
![tpot20](https://user-images.githubusercontent.com/29882699/118139334-d1bea580-b439-11eb-97dc-48fedc860a86.png)

**Comment by Tango9191** [comment]
I have the same problem. How to solve?

**Comment by ct9915** [comment]
@Tango9191  , do you solve this issues? I encountered the same issue

**Comment by Tango9191** [comment]
No, unfortunately not.
See: https://github.com/telekom-security/tpotce/issues/840

**Comment by Zer0F00L** [comment]
i have the same issue has anyone solve this yet?
