### ISSUE TITLE
tpot service fails to start

### ISSUE THREAD

**Issue by timomezcla** [telekom-security/tpotce#835]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? 
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Linux diversemiddle 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
- What T-Pot version are you currently using?
tpot version 20.06.2
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
open stack cloud (Open Telekom Cloud)
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
not really, but the files are attached.
[install.log](https://github.com/telekom-security/tpotce/files/6501833/install.log)
[install.err.log](https://github.com/telekom-security/tpotce/files/6501843/install.err.log)
- How long has your installation been running?
it never worked properly.
- Did you install upgrades, packages or use the update script?
no
- Did you modify any scripts or configs? If yes, please attach the changes.
no
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/67780840/118664715-fdeb7500-b7f1-11eb-8165-20bb52572224.png)
![image](https://user-images.githubusercontent.com/67780840/118664847-19ef1680-b7f2-11eb-9aab-b606446f3027.png)
- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/67780840/118665042-4440d400-b7f2-11eb-9af2-ae5cb03afa2c.png)
- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/67780840/118665405-92ee6e00-b7f2-11eb-81c5-e1dfb643a124.png)
- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/67780840/118666136-3475bf80-b7f3-11eb-9db7-6a407c254b02.png)
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/67780840/118666346-6555f480-b7f3-11eb-92f9-8ec51d0eabc0.png)
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
all containers are down

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this, but it seems some images could not be downloaded. According to the error.log I see the following info `error pulling image configuration: read tcp 192.168.76.132:36676->104.18.123.25:443: read: connection reset by peer`. Since images are pulled from DockerHub, this might be the result of a quota issue introduced by DockerHub last October for free accounts.

**Comment by shaderecker** [comment]
After chatting with @t3chn0m4g3 we were able to boil down the problem to this error message:
`ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`

Fixed it by changing the docker network range like in #751

**Comment by t3chn0m4g3** [comment]
Awesome. Closing 😃
