### ISSUE TITLE
Failed to install TPOT20 

### ISSUE THREAD

**Issue by Tango9191** [telekom-security/tpotce#840]
Hello,
I have the same problem as "[Failed to install TPOT20 #829](https://github.com/telekom-security/tpotce/issues/829)" which just has been closed without description of the solution.
I'm trying to install it on VMWare behind a proxy which has to be used mandatory.

Kind regards and thanks in advance!

**Comment by t3chn0m4g3** [comment]
Recommend installing T- Pot on top of an existing Debian installation. Please set Readme for more details on install options.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.

**Comment by Tango9191** [comment]
Thanks. So ISO-Installation is not usable/corrupt. Sad to hear. You should point that out in the docs.
