### ISSUE TITLE
ISO install's without error but no docker images running

### ISSUE THREAD

**Issue by lauben79** [telekom-security/tpotce#841]
Hello,

I've tried a number of times to install T-Pot on multiple virtual platforms (ESX and UnraidVM) via both the ISO also via a clone of the github repo, but each time while the install seems to work without error none of the docker images/containers are able to be started and while the webadmin interface works the web page for T-Pot dose not (no surprise given none of the docker images are running).

I've even tried to run the docker command associated with the Tpot service (docker-compose -f /opt/tpot/etc/tpot.yml up) and this returns the following error 
```
Creating network "etc_rdpy_local" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
So I'm guessing this is the issue but I don't know why this is happing or how to solve it.

Please find the basic support information below:-

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
> -Linux broadoffence 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
> -Taken from the T-Pot 20.06.2 pre-built ISO image

- What T-Pot version are you currently using?
> -T-Pot 20.06.2
> -Pre-built ISO hosted on Github
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
> -Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
> -VMWare ESX 6.7, Unraid 6.9.1, VMWare Fusion 11 
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
> -Not really only
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.21 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
Created symlink /etc/systemd/system/multi-user.target.wants/tpot.service → /etc/systemd/system/tpot.service.

- How long has your installation been running?
> -Not been running
- Did you install upgrades, packages or use the update script?
> -Nope
- Did you modify any scripts or configs? If yes, please attach the changes.
> -Nope
- Please provide a screenshot of `glances` and `htop`.

- How much free disk space is available (`df -h`)?
> -Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M   91M  708M  12% /run
/dev/sda2       149G  7.8G  134G   6% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           798M     0  798M   0% /run/user/1000
- What is the current container status (`dps.sh`)?
```
=======| System |========
    Date:  Sat 22 May 2021 08:54:55 PM UTC
  Uptime:  20:54:55 up 40 min,  1 user,  load average: 0.93, 0.96, 0.86

NAME                  STATUS                       PORTS
adbhoney              DOWN                  
ciscoasa              DOWN                  
citrixhoneypot        DOWN                  
conpot_guardian_ast   DOWN                  
conpot_iec104         DOWN                  
conpot_ipmi           DOWN                  
conpot_kamstrup_382   DOWN                  
cowrie                DOWN                  
cyberchef             DOWN                  
dicompot              DOWN                  
dionaea               DOWN                  
elasticpot            DOWN                  
elasticsearch         DOWN                  
ewsposter             DOWN                  
fatt                  DOWN                  
head                  DOWN                  
heralding             DOWN                  
honeysap              DOWN                  
honeytrap             DOWN                  
kibana                DOWN                  
logstash              DOWN                  
mailoney              DOWN                  
medpot                DOWN                  
nginx                 DOWN                  
p0f                   DOWN                  
rdpy                  DOWN                  
snare                 DOWN                  
spiderfoot            DOWN                  
suricata              DOWN                  
tanner                DOWN                  
tanner_api            DOWN                  
tanner_phpox          DOWN                  
tanner_redis          DOWN             
```
- What is the status of the T-Pot service (`systemctl status tpot`)?
> -● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Sat 2021-05-22 20:55:39 UTC; 3s ago
  Process: 32385 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 32409 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 32455 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
Cntrl PID: 406 (docker-compose)
    Tasks: 1 (limit: 4915)
   Memory: 30.6M
   CGroup: /system.slice/tpot.service
           └─406 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
> -(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16274      -                   
tcp        0      0 127.0.0.1:61209         0.0.0.0:*               LISTEN      0          16849      -                   
tcp6       0      0 :::64294                :::*                    LISTEN      0          13092      -                   
tcp6       0      0 :::64295                :::*                    LISTEN      0          16276      -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          14760      -                   
udp        0      0 192.168.42.149:123      0.0.0.0:*                           0          331715     -                   
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          331713     -                   
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          331709     -                   
udp6       0      0 :::123                  :::*                                0          331706     -                   
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
> -All docker containers show as down

Any help on how to address this would be great.

**Comment by t3chn0m4g3** [comment]
#835

**Comment by lauben79** [comment]
Hello,

I've tried to the suggested fix but still have no docker images running and the tpot service is showing 

```
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-05-23 13:33:24 UTC; 3s ago
  Process: 22211 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 22235 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 22281 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 22284 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 22287 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 22302 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 22316 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 22330 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FA
  Process: 22346 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:
  Process: 22352 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]
  Process: 22358 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:
  Process: 22364 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
  Process: 22436 ExecStart=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color (code=exited, status=1/FAILURE)
  Process: 23177 ExecStopPost=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset (code=exited, status=0/SUCCESS)
 Main PID: 22436 (code=exited, status=1/FAILURE)
```

I've also had the same overlapping network issue when trying to bring up the tpot.yml directly:-

```
docker-compose -f /opt/tpot/etc/tpot.yml up
Creating network "etc_adbhoney_local" with the default driver
Creating network "etc_citrixhoneypot_local" with the default driver
Creating network "etc_conpot_local_IEC104" with the default driver
Creating network "etc_conpot_local_guardian_ast" with the default driver
Creating network "etc_conpot_local_ipmi" with the default driver
Creating network "etc_conpot_local_kamstrup_382" with the default driver
Creating network "etc_cowrie_local" with the default driver
Creating network "etc_dicompot_local" with the default driver
Creating network "etc_dionaea_local" with the default driver
Creating network "etc_elasticpot_local" with the default driver
Creating network "etc_heralding_local" with the default driver
Creating network "etc_honeysap_local" with the default driver
Creating network "etc_mailoney_local" with the default driver
Creating network "etc_medpot_local" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

Any other ideas?

**Comment by t3chn0m4g3** [comment]
No, shows same error and as such you still seem to use an overlapping network.

**Comment by lauben79** [comment]
Okay, I've been able to get it to work but had to set the default network pool to 10.0.0.0/8 not sure why this worked but not /16  but I have it working now.

So my /etc/docker/daemon.json now reads:-
```
{
 "default-address-pools":
 [
    {"base":"10.0.0.0/8","size":24}
 ]
}
```

Just incase it help anyone else.
