### ISSUE TITLE
kibana, Logstash and Elasticsearch are down.

### ISSUE THREAD

**Issue by yasser-48** [telekom-security/tpotce#842]
Hello! I ve installed the last version of T-pot, everything was going well until Kiabana, Logstash and Elasticsearch services went down. I don't know where is the problem, I ve tried so many solutions but in vain.
ps: I have all the requirements needed to run T-pot and it was going so well when I first installed it.
Help!! Thank you .
![error](https://user-images.githubusercontent.com/65678273/119361034-20263c80-bca3-11eb-9e43-8031cd3d6083.PNG)

**Comment by thedevilworm** [comment]
Hello, the same thing happens to me too ... with the ISO version ... in vitualbox ... it starts everything ... but less KIBANA. I will be attentive if there is any solution, if someone can help us ... thank you !!!

**Comment by t3chn0m4g3** [comment]
#813

**Comment by thedevilworm** [comment]
@t3chn0m4g3 friend try that thread. I changed the ram memory of elk AND elasticsearch to 4096 .. but I still can't enter .. to kibana .. 
![errror1](https://user-images.githubusercontent.com/84260563/119403350-2ff64e80-bcac-11eb-8a47-a275bdda04cd.jpg)
![erro2](https://user-images.githubusercontent.com/84260563/119403458-62a04700-bcac-11eb-8ab0-ceca5c53af59.jpg)
![error3](https://user-images.githubusercontent.com/84260563/119403466-6633ce00-bcac-11eb-8cd7-318b71035bd7.jpg)

**Comment by thedevilworm** [comment]
@t3chn0m4g3 @yasser-48  
![error6](https://user-images.githubusercontent.com/84260563/119408953-90898980-bcb4-11eb-9f05-af4fdfab4d9c.jpg)

**Comment by t3chn0m4g3** [comment]
Solution described [here](https://github.com/telekom-security/tpotce/issues/813#issuecomment-832924242).

**Comment by yasser-48** [comment]
I ve already tried , but in vain
I reinstalled tpot and gave it more than 8g RAM.
I also increased the ES_JAVA-OPTS memory setting from 2048 to 4096 on both applications (in this file  vi /opt/tpot/etc/tpot.yml), but didnt work for me, I don't know why.
Thank you anyway .

**Comment by t3chn0m4g3** [comment]
From the screenshot it looks that T-Pot is starting up as expected. Just try `docker logs [containername_here] -f` for either `logstash, elasticsearch,kibana` to see error messages. At best reboot the machine beforehand.

**Comment by t3chn0m4g3** [comment]
I made some changes, just run the `update.sh` in `/opt/tpot/` which will lift some of the Java constraints we had in the past in moving to Java 16.

**Comment by yasser-48** [comment]
Do I have to change again the memory limit and the ES_JAVA-OPTS memory setting from 2048 to 4096 in /opt/tpot/etc/tpot.yml after updating ? 
Thank you.

**Comment by t3chn0m4g3** [comment]
If you executed the `update.sh` script, then there is no need for adjustments. You can review `/opt/tpot/etc/tpot.yml` and should the corresponding lines commented. This works now, because with Java 16 es and logstash make use of automatic heap management.
