### ISSUE TITLE
Problems with ELASTIC TPOT 2006

### ISSUE THREAD

**Issue by thedevilworm** [telekom-security/tpotce#843]
Hello friends, good evening, I have TPOT running, after a clean installation through ISO on a VMwarePRO system. and when executing the KIBANA dashboard I get an error related to longstash ... could you help me?

![1](https://user-images.githubusercontent.com/84260563/119431684-ff7cd780-bce0-11eb-8c88-0ea2539397d5.jpg)
![2](https://user-images.githubusercontent.com/84260563/119431696-03105e80-bce1-11eb-945b-58b9fa407aef.jpg)
![3](https://user-images.githubusercontent.com/84260563/119431704-06a3e580-bce1-11eb-8311-f143de69e217.jpg)

![4](https://user-images.githubusercontent.com/84260563/119431820-3d79fb80-bce1-11eb-8cb2-66d61dbc7103.jpg)

THANK UUUUUUU!!!!! MY FRIENDS!!!!

**Comment by t3chn0m4g3** [comment]
Looks like logstash has a problem.
Reboot the machine and run a `docker logs logstash -f` (once you see all the containers running) and post the output.

**Comment by thedevilworm** [comment]
@t3chn0m4g3 
> Looks like logstash has a problem.
> Reboot the machine and run a `docker logs logstash -f` (once you see all the containers running) and post the output.

Friend, thank you very much for helping me ... I appreciate it very much! .. Look, I executed that command that you just told me ... it prints many lines ... but what I was able to rescue was the following ... do you see any anomaly?

![1](https://user-images.githubusercontent.com/84260563/119514499-10f6cb80-bd43-11eb-94c1-4699ce886e4f.jpg)
![2](https://user-images.githubusercontent.com/84260563/119514512-13592580-bd43-11eb-9450-396a3019f49c.jpg)
![3](https://user-images.githubusercontent.com/84260563/119514799-51564980-bd43-11eb-94b0-b3f8058df43b.jpg)
![4](https://user-images.githubusercontent.com/84260563/119514807-53200d00-bd43-11eb-8e7c-64847bf956c9.jpg)
![5](https://user-images.githubusercontent.com/84260563/119514814-54e9d080-bd43-11eb-8ea8-df6ebe161176.jpg)

thank u my hero!!!!

**Comment by thedevilworm** [comment]
@t3chn0m4g3  I made a modification in the pot.yml file. going from 4 ram to 8 ram ...
but now the service is falling ...
![10](https://user-images.githubusercontent.com/84260563/119528410-27a31f80-bd4f-11eb-995f-768097f2126d.jpg)
![11](https://user-images.githubusercontent.com/84260563/119528429-2a057980-bd4f-11eb-9f3e-69ed71ec1b37.jpg)
![12](https://user-images.githubusercontent.com/84260563/119528436-2bcf3d00-bd4f-11eb-926c-755abad42bfd.jpg)
![13](https://user-images.githubusercontent.com/84260563/119528441-2d990080-bd4f-11eb-98b2-590f646c8872.jpg)
![14](https://user-images.githubusercontent.com/84260563/119528458-3093f100-bd4f-11eb-9e1f-ce0d702d2b48.jpg)
![17w](https://user-images.githubusercontent.com/84260563/119528475-338ee180-bd4f-11eb-8646-54e8ad8aa90d.jpg)

**Comment by t3chn0m4g3** [comment]
With 8G of RAM, the maximum you can set is 2048 for each. If you set it higher you are overcommitting which may result in a service crash. You may try with 3072 each or provide more RAM to the VM.

**Comment by thedevilworm** [comment]
@t3chn0m4g3 
> With 8G of RAM, the maximum you can set is 2048 for each. If you set it higher you are overcommitting which may result in a service crash. You may try with 3072 each or provide more RAM to the VM.

spectacular !!!!!!! at least now it shows some results, set the memory to 3 as you indicated .. and at least it does not give longstash problems, leave all the fields in 3ram, and it works .... Now, we only have to wait for the results of the attacks?

![31](https://user-images.githubusercontent.com/84260563/119534598-165d1180-bd55-11eb-95ba-44c3d99d53d2.jpg)
![32](https://user-images.githubusercontent.com/84260563/119534608-19f09880-bd55-11eb-870f-0d5eecd742b6.jpg)
![34](https://user-images.githubusercontent.com/84260563/119534619-1ceb8900-bd55-11eb-894f-cad22ce21e46.jpg)
![35](https://user-images.githubusercontent.com/84260563/119534625-1eb54c80-bd55-11eb-8684-13023b6dca92.jpg)

**Comment by thedevilworm** [comment]
@t3chn0m4g3  WORKING!!!!! MY HERO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! YEAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 
![40](https://user-images.githubusercontent.com/84260563/119535808-6ab4c100-bd56-11eb-8c56-aafb835b883c.jpg)

**Comment by t3chn0m4g3** [comment]
Awesome. Glad I could help. Enjoy :bowtie:
