### ISSUE TITLE
Problems with Longstash TPOT 2006 : bug

### ISSUE THREAD

**Issue by thedevilworm** [telekom-security/tpotce#844]
Hi friends. good afternoon, I hope for your kind help .. after working one day very well .. the tpot service, it stops working ... sending this BUG message

![Screenshot_1](https://user-images.githubusercontent.com/84260563/119717804-c9506c80-be34-11eb-8c1f-fae5d2641d1b.png)
I have stopped the service, and have started again ... manually ..
![Screenshot_3](https://user-images.githubusercontent.com/84260563/119719717-1f261400-be37-11eb-8649-572f5347b33e.png)

once the service started .., I hope all this UP .. waiting for the longstah start ..
![Screenshot_4](https://user-images.githubusercontent.com/84260563/119719837-42e95a00-be37-11eb-8b3b-40b7cc7246f8.png)
and it falls again ... longstash ...
![Screenshot_8](https://user-images.githubusercontent.com/84260563/119720414-ef2b4080-be37-11eb-8970-af4215e974e9.png)

![Screenshot_9](https://user-images.githubusercontent.com/84260563/119720583-2568c000-be38-11eb-9402-4f81c6017e53.png)
I have kibana open .. yesterday I registered and did test .. and it worked very well .. but now .. longstash falls and falls .. could you help me please ..

Excuse me for being a little ignorant in these processes ... but this project is very beautiful.
this is a screenshot of yesterday ... working .. today I did tests and nothing ...
![Screenshot_10](https://user-images.githubusercontent.com/84260563/119720888-87c1c080-be38-11eb-926a-e7b11af51450.png)

thank uuu!!!!! friends! 

@t3chn0m4g3

**Comment by t3chn0m4g3** [comment]
Run the update.sh script in /opt/tpot, made some changes today that might fix it.

**Comment by thedevilworm** [comment]
> 
> 
> Run the update.sh script in /opt/tpot, made some changes today that might fix it.

youuuu areeeee amazing! thank u my bro!!!!!!!!!!!!!!!

perform the update ... the system told me that the tpot configuration file would return by default .. and just leave it as default and restart the virtual machine ... I did not make the JAVA modification that I had done previously ... so I only left it by default in the logstash and ELK lines

now they were commented. just leave the same.
![Screenshot_12](https://user-images.githubusercontent.com/84260563/119725058-7a5b0500-be3d-11eb-87b4-59140e3b37f8.png)


DPS OK! 
![Screenshot_13](https://user-images.githubusercontent.com/84260563/119725079-7fb84f80-be3d-11eb-9f7f-457bddadaf6e.png)

TESTING AND!!!::.. 
![Screenshot_14](https://user-images.githubusercontent.com/84260563/119725118-8d6dd500-be3d-11eb-8c05-c16ff573d9cc.png)
Works!! 

thank u!! Again my bro!!!!!!!!! @t3chn0m4g3 
I will invite you some beers for you friend. greetings from Chile!

**Comment by t3chn0m4g3** [comment]
Glad it works. Enjoy 😊
