### ISSUE TITLE
T-Pot Failed to Run Preseeded Command Issue

### ISSUE THREAD

**Issue by reben-f5** [telekom-security/tpotce#848]
While I am trying to install T-Pot instance on VirtualBox facing this error "Failed to run preseeded command" 
and have tried different other ways to get install it successfully but didn't happened. Any ideas or help please?
![t-pot](https://user-images.githubusercontent.com/59086062/120505181-a554d400-c3bc-11eb-8c6b-a98f6a20a8ef.PNG)

**Comment by t3chn0m4g3** [comment]
Seems to be VirtualBox related. Works perfectly fine in VMWare.

You can always install T-Pot on top of an existing Debian installation; described in the Readme.

**Comment by reben-f5** [comment]
Well I wonder what had caused this error, is not given any clear indication where did go wrong and if it was VirtualBox then I am using the latest version... also I had tried on different computer it is the same issue.

**Comment by t3chn0m4g3** [comment]
If the VM meets the requirements there unfortunately there is nothing I can do about. For such compatability issues we are offering T-Pot with a post-install method.
