### ISSUE TITLE
TPot service is not starting

### ISSUE THREAD

**Issue by devamtech** [telekom-security/tpotce#849]
steps to Repro

1) Installed Debian 10.4 
2) executed below commands
  a) git clone https://github.com/telekom-security/tpotce
  b) cd tpotce/iso/installer/
  c) cp tpot.conf.dist tpot.conf
   d) ./install.sh --type=auto --conf=tpot.conf

Tpot service is not starting. 

![tpot](https://user-images.githubusercontent.com/42437274/120600873-e3a6cd80-c466-11eb-80fa-af40f791ad9c.png)

Note: One month back, I have tried same steps on the same OS.  I was successfully deployed tpot 3time,

**Comment by devamtech** [comment]
tried to restart tpot service and its not starting
![Uploading tpotservice.png…]()

**Comment by t3chn0m4g3** [comment]
Please use the latest Debian which is 10.9.

**Comment by devamtech** [comment]
![debian10-9](https://user-images.githubusercontent.com/42437274/120651346-4ebec700-c49c-11eb-9528-b119ffeed39c.png)
Thank you Marco for you response.

Still, Tpot service is not loading on Debian 10.9
can you please help me to get one back Tpot version.

**Comment by t3chn0m4g3** [comment]
Logs are cut off.

Please run ...
```
systemctl stop tpot
docker-compose -f /opt/tpot/etc/tpot.yml up
```
... and post the output as text.

**Comment by devamtech** [comment]
Hi Macro,
thank you for your response. I have deployed Tpot 19 Version.  Now Tpot is up and running.

**Comment by t3chn0m4g3** [comment]
Happy to know it works.
