### ISSUE TITLE
Inquiry - TPOT Elastic data to Elasticsearch SIEM

### ISSUE THREAD

**Issue by NetEyes** [telekom-security/tpotce#854]
Greetings,

This is more an inquiry.
Now that I managed to run tpot. 
We have an Elasticsearch SIEM and I would like to capture tpot logs to our SIEM. Please advise how to do that.
How to I transfer those elastic data from tpot and elasticsearch siem (to another elasticsearch)

**Comment by t3chn0m4g3** [comment]
#720 and #437 are covering the basics for this. To get familiar with volumes have a look in the [Wiki](https://github.com/telekom-security/tpotce/wiki).
