### ISSUE TITLE
T-POT 2006 [xxx] login: incorrect

### ISSUE THREAD

**Issue by foenuw** [telekom-security/tpotce#858]
I,

I can no longer access WebUI, T-POT 2006 [xxxx] login: Incorrect login.

Access the web user interface: https: // <your.ip>: 64297?
Impossible: HP Desktop -> T-POT -> Wifi phone (one connection)

Creation of an additional user and unable to connect to WebUI.
https://github.com/telekom-security/tpotce/issues/157

The pc is not connected to the network when collecting information. 

lsb_release -a 
No LSB modules are availabe.
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)

uname -a 
Linux standardmale 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux

Which versions are used?
20.06.2

What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard

Run the system: real hardware or in a virtual machine?
Hardware - HP Desktop 8Go - disk seagate 160Go Sata - Debian Debian 10 buster
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/

Did you have any problems during the install? No

How long has your installation been running? 1 Day

Did you install upgrades, packages or use the update script? Yes. Sscript (./update.sh -y)
Did you modify any scripts or configs? No.

Please provide a screenshot of `glances` and `htop`. (How to take a capture? )
![Glances](https://user-images.githubusercontent.com/86566067/123553842-be636180-d77d-11eb-8c79-1f07a704634e.JPG)
![Htop](https://user-images.githubusercontent.com/86566067/123553844-c02d2500-d77d-11eb-840b-77d0a4e3b6df.JPG)

How much free disk space is available (`df -h`)?
Filesystem 	Size	Used	Avail	Use%	Mounted on
udev		3.9G	0	3.9G	0% 	/dev
tmpfs		798M	9.1M	789M	2% 	/run
/dev/sda2	139G	7.7G	124G	6% 	/
tmpfs		3.9G	0	3.9G	0% 	/dev/shm
tmpfs		5.0M	0	5.0M	0% 	/run/lock
tmpfs		3.9G	0	3.9G	0%	/sys/fs/cgroup
tmpfs		798M	0	798M	0% 	/run/user/1000

What is the current container status (`dps.sh`)? All down.
What is the status of the T-Pot service (`systemctl status tpot`)? active (running)
Process: 9683 ExecStartPre=/bin/bas -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
Process: 9697 ExecStartPre=/bin/bas -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
Process: 9711 ExecStartPre=/bin/bas -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
Process: 9725 ExecStartPre=/bin/bas -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)

What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
(Not all processes could be identified, non-owned process info will not be shown,
you would have to be root to see it all.)
Active Internet connections (only servers)
Proto	Inode	PID			Foreign Address	State
tcp	0	0 127.0.0.1:61209	0.0.0.0*	listen
0	16821	  -
tcp	0	0 0.0.0.0:64295		0.0.0.0*	listen
0	15150 	  -
tcp6	0	0 :::64294		:::*		listen
0	14058	  -
tcp6	0	0 :::64295		:::*		listen
0	15152	  -
udp	0	0 0.0.0.0:68		0.0.0.0*
0	15680	  -
udp	0	0 127.0.0.1:123		0.0.0.0*
0	16540
udp	0	0 0.0.0.0:123		0.0.0.0*
0	16536
udp6	0	0 :::123		:::*
0	16533

Thanks

**Comment by doguile** [comment]
Hey, did you fix it? Can you share the solutions please

**Comment by foenuw** [comment]
No, I haven't fixed it. 
I haven't found a solution yet. :-(
