### ISSUE TITLE
[ERROR] checkCFG mission File!

### ISSUE THREAD

**Issue by acg001** [telekom-security/tpotce#872]
### Discussed in https://github.com/telekom-security/tpotce/discussions/871

<div type='discussions-op-text'>

<sup>Originally posted by **acg001** July 24, 2021</sup>
After rebooting the host, I am getting this when I check the status of tpot.

Jul 24 15:38:03 supportingprotection docker-compose[15124]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/mailoney/log/commands.log. Abort!

The docker object in the web admin also shows as "no carrier".

I have tried the steps detailed in this thread "https://github.com/telekom-security/tpotce/issues/514", but it's still the same. I have also tried running the update.sh. Still i get the same error. This only happened after i rebooted the host, and when i tried on other installation, it happens when i restarted the tpot service..

The version i am using is 20.06.2 ISO package.</div>

**Comment by securitytime** [comment]
I installed T-Pot last week on CentOS 8.

Today I noticed that the server shut down.

Doing some troubleshooting, I found that the HD is full. I found some very large log files:

41G /var/log/daemon.log.1
15G /var/log/syslog
27G /var/log/syslog.1

Looking into these files, they contain this section over and over again:

Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              | EWS Poster v1.20 (c) by Markus Schroer <markus.schroer@telekom.de>
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Create lock socket successfull.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => ESend: checking spooldir and resend alert
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |     -> [INFO] No jobs to send in spooldir: /opt/ewsposter/spool/.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting DIONAEA Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting HONEYTRAP Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |     -> Calculate MD5Sum for payload files and rename files.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting CONPOT Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting COWRIE Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting ELASTICPOT Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting RDPY Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => Starting MAILONEY Honeypot Modul.
Jul 22 10:02:27 exceptionaltwilight docker-compose[1018]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/mailoney/log/commands.log. Abort!

**Comment by acg001** [comment]
I also had a full disk, but after cleaning up. The same status appears.

# systemctl status tpot
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-07-26 08:26:37 UTC; 3min 54s ago
  Process: 755 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 783 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 893 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 901 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 904 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 920 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 935 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 950 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 969 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 975 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 981 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 987 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 1063 (docker-compose)
    Tasks: 35 (limit: 4915)
   Memory: 45.4M
   CGroup: /system.slice/tpot.service
           └─1063 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |     -> [INFO] No jobs to send in spooldir: /opt/ewsposter/spool/.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting DIONAEA Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting HONEYTRAP Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |     -> Calculate MD5Sum for payload files and rename files.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting CONPOT Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting COWRIE Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting ELASTICPOT Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting RDPY Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => Starting MAILONEY Honeypot Modul.
Jul 26 08:30:28 underlyingfirewall docker-compose[1063]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/mailoney/log/commands.log. Abort!
# df -h /var
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       118G   42G   71G  37% /

**Comment by acg001** [comment]
In the daemon log, i see this over and over again.

Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              | EWS Poster v1.20 (c) by Markus Schroer <markus.schroer@telekom.de>
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Create lock socket successfull.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => ESend: checking spooldir and resend alert
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |     -> [INFO] No jobs to send in spooldir: /opt/ewsposter/spool/.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting DIONAEA Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting HONEYTRAP Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |     -> Calculate MD5Sum for payload files and rename files.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting CONPOT Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting COWRIE Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting ELASTICPOT Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting RDPY Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting MAILONEY Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/mailoney/log/commands.log. Abort!
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              | EWS Poster v1.20 (c) by Markus Schroer <markus.schroer@telekom.de>
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Create lock socket successfull.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => ESend: checking spooldir and resend alert
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |     -> [INFO] No jobs to send in spooldir: /opt/ewsposter/spool/.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting DIONAEA Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting HONEYTRAP Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |     -> Calculate MD5Sum for payload files and rename files.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting CONPOT Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting COWRIE Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting ELASTICPOT Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting RDPY Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting MAILONEY Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/mailoney/log/commands.log. Abort!
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              | EWS Poster v1.20 (c) by Markus Schroer <markus.schroer@telekom.de>
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Create lock socket successfull.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => ESend: checking spooldir and resend alert
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |     -> [INFO] No jobs to send in spooldir: /opt/ewsposter/spool/.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting DIONAEA Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting HONEYTRAP Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |     -> Calculate MD5Sum for payload files and rename files.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting CONPOT Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting COWRIE Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting ELASTICPOT Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting RDPY Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => Starting MAILONEY Honeypot Modul.
Jul 26 13:54:47 in2inf docker-compose[1588]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/mailoney/log/commands.log. Abort!

**Comment by t3chn0m4g3** [comment]
@trixam Can you have a look?

**Comment by acg001** [comment]
The error was solved by touching a file indicated in the error, in this case, /data/mailoney/log/commands.log

**Comment by securitytime** [comment]
After touching this file, the same issue appeared for other files, e.g. /data/adbhoney/log/adbhoney.json:

Aug  1 00:01:32 exceptionaltwilight docker-compose[1132]: ewsposter              |  => [ERROR] checkCFG mission File! logfile = /data/adbhoney/log/adbhoney.json. Abort!

Again the HD was full due to /var/log.

**Comment by ceylanb** [comment]
Same issue.

**Comment by acg001** [comment]
> After touching this file, the same issue appeared for other files, e.g. /data/adbhoney/log/adbhoney.json:
> 
> Aug 1 00:01:32 exceptionaltwilight docker-compose[1132]: ewsposter | => [ERROR] checkCFG mission File! logfile = /data/adbhoney/log/adbhoney.json. Abort!
> 
> Again the HD was full due to /var/log.

If the file is missing, do a "touch" again to create the file.

**Comment by t3chn0m4g3** [comment]
I opened an [issue](https://github.com/telekom-security/ewsposter/issues/4).
