### ISSUE TITLE
Missing Entrys in Dashboards

### ISSUE THREAD

**Issue by rainbowcat1989** [telekom-security/tpotce#885]
Just installed the Tpot and recognize that some objects are not found.

I used both ways of installing the Tpot.  Buster first and your ISO in case i missed something.

I already updated  Tpot with your instructions and also import the latest kibina-objects

When i search the Objects in the "Discover" function i also can not find it.

The Picture is just an example. More Objects are missing.

![image](https://user-images.githubusercontent.com/64091338/131480273-99ca0915-632f-4c45-89a2-0896dfca8857.png)

**Comment by t3chn0m4g3** [comment]
This is normal behavior, once T-Pot has had events the fields are populated properly to the index pattern and the errors disappear.

**Comment by t3chn0m4g3** [comment]
Please report back should this not be resolved in time.
