### ISSUE TITLE
Conpot false attack detection from local docker

### ISSUE THREAD

**Issue by zhovner** [telekom-security/tpotce#893]
Conpot sensor detecting false attack from internal docker ip. I have latest T-Pot installation from ISO release `20.06.2`

Attacker source IP: `172.20.0.1`  
DST port: `161`  

```
/data/conpot/log/conpot_IEC104.json:

{"sensorid": "conpot", "id": "-", "src_ip": "172.20.0.1", "src_port": 56516, "dst_ip": "172.20.0.2", "dst_port": 161, "public_ip": "hidden", "data_type": "snmp", "request": {"oid": "1.3.6.1.2.1.1.1.0", "val": ""}, "response": {"oid": "1.3.6.1.2.1.1.1.0", "val": "Siemens, SIMATIC, S7-300"}, "event_type": "SNMPv2 Get"}
```

<img width="400" src="https://user-images.githubusercontent.com/774290/134537376-44d6cade-29d2-4522-8c08-fbf63be041e9.png" />

**Comment by t3chn0m4g3** [comment]
This is a known limitation of docker.

**Comment by zhovner** [comment]
@t3chn0m4g3 Thanks. What solution you can advice?

**Comment by t3chn0m4g3** [comment]
Well, public IPs and accesses are being NATed into the container. As such you find the T-Pot External IP in the message.

**Comment by zhovner** [comment]
My T-Pot is located on LAN under the NAT withour direct access from internet.
I don't get what actually this Conpot message means. Can you please explain more?

**Comment by t3chn0m4g3** [comment]
This is to be expected. Conpot provides a simple SNMP interface for some of its services, which is triggered if any machine in your network tries to reach it. The IP address shown is from the inside of the docker container.
For more details about Conpot and documentation please visit the developers' GitHub page which is linked in the Readme.
