### ISSUE TITLE
Issue installing 

### ISSUE THREAD

**Issue by killmasta93** [telekom-security/tpotce#896]
Hi,
Currently trying to install the ISO, but i keep getting no kernel modules were found
I checked something similar on this issue but it seemed to be resolved on 20.06.2
https://github.com/telekom-security/tpotce/issues/733

I tried on vmware, virtualbox and proxmox and same issue not sure what else to try
I tried installing on ubuntu 18.04 with the auto script but says that its not supported

Thank you

**Comment by t3chn0m4g3** [comment]
Thanks. This usually happens when kernel modules are being updated bei Debian. I updated the [release](https://github.com/telekom-security/tpotce/releases/edit/20.06.2) and things are working again.

**Comment by killmasta93** [comment]
thank you so much that did the trick
