### ISSUE TITLE
vmware esxi 7.02b + tpot.iso : no disk drive detected

### ISSUE THREAD

**Issue by lcia-projects** [telekom-security/tpotce#914]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

been running tpot for years on a vmware esx server. got new physcial hardware for vmware esx. installed the latest community edition,  7.02b 

when i try to install tpot.iso i get the following error during installation:
"No disk drive was detected. if you know the driver needed by your disk drive, select from list"

i did a standard vmware virtual machine, debian 64 bit profile, 4 cpu's, 16gb of ram, 250gb of storage. 

i've tried changing storage settings with no luck. other OS's install fine.

any ideas?

**Comment by t3chn0m4g3** [comment]
In cases where the ISO does not work we recommend the post install method as described in the readme.
