### ISSUE TITLE
Kibana - Fetching listing failed

### ISSUE THREAD

**Issue by nednones** [telekom-security/tpotce#915]
When loading the Kibana app, no dashboard is shown. The reported error is as follows:
_"Configuration missing

server.publicBaseUrl is missing and should be configured when running in a production environment. Some features may not behave correctly"_

A red banner also listed on the page states: The dashboard listing could not be fetched: getaddrinfo ENOTFOUND elasticsearch.

I've tried the following but to no prevail: Stack Management -> Saved Objects -> Import -> uploaded kibana_export.ndjson and then uploaded this config, which rejects the file stating: the file could not be processed due to error: "Service Unavailable: getaddrinfo ENOTFOUND elasticsearch"

**Comment by nednones** [comment]
Added screenshot to highlight the problem relating to the issue. I have deployed this on a Droplet Debian V10.x and tried twice ensuring the required container specs for hosting match that in the setup?

![Screenshot 2021-11-03 at 07 54 08](https://user-images.githubusercontent.com/4564152/140025515-44fadde8-1c01-4d91-9686-dd380353da3c.png)
m:

**Comment by t3chn0m4g3** [comment]
Duplicate #912
