### ISSUE TITLE
scp?

### ISSUE THREAD

**Issue by s3ldondev** [telekom-security/tpotce#923]
Installed on AWS EC2 Debian 10 image via auto installer. Now trying to copy files back to my local machine for further analysis. I use the following command: 

scp -i key.pem admin@xxx.xxx.xxx.xxx:/root/data .

I am prompted for admin's password. In EC2 instances, no password is set. I went into ssh_config to add one and it isn't taking it. Assuming this a basic linux issue that I am struggling with but any help would be appreciated!

**Comment by t3chn0m4g3** [comment]
You are trying to connect to the honeypot. Please review the Readme for correct ports, i.e. 64295 for SSH.
