### ISSUE TITLE
openjdk16-jre isn't provided by alpine testing

### ISSUE THREAD

**Issue by alonek1** [telekom-security/tpotce#927]
hi,
in the Dockerfile of elasticsearch (docker/elk/elasticsearch/Dockerfile). it's mentioned to download openjdk16-jre from alpine testing:

apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing openjdk16-jre 
but it isn't provided by alpine testing and it's not in it repository and when using docker-compose up it leads to an error:

ERROR: unable to select packages:
  openjdk16-jre (no such package):

PS: the community  repository of alpine provide this version:

http://dl-cdn.alpinelinux.org/alpine/edge/community openjdk16-jre

**Comment by t3chn0m4g3** [comment]
Yes, they moved it from `testing` to `community`.
This will be fixed when we build a new Docker Image.
