### ISSUE TITLE
elastic is unable to create log files 

### ISSUE THREAD

**Issue by alonek1** [telekom-security/tpotce#928]
Hi,
I'm trying to run tpot dockers using ```docker-compose up --build``` command, for elastic search i get the following error:

```

ERROR Unable to create file /data/elk/log/tpotcluster_deprecation.log java.io.IOException: Could not create directory /data/elk/log
```
Is it about a problem in user permission ?

I actually check it for the permission and it seems ok .

**Comment by t3chn0m4g3** [comment]
You need to run the installer, as described in the Readme.

**Comment by alonek1** [comment]
hi i changed the path in ```dist/elasticsearch.yml``` file  to ```/var/log/elasticsearch/``` and it solved:
```
    logs: /var/log/elasticsearch/
    data: /var/log/elasticsearch/

```
