### ISSUE TITLE
web and admin portal

### ISSUE THREAD

**Issue by Concieted** [telekom-security/tpotce#950]
Good day I just did an installation of a honeypot, the honeypot itself has been installed however it's failing to generate the web as well as the admin URLs

I've made use of the T pot ISO on a virtual machine.
the machine has met all minimum requirements as well.

Please kindly advise.

**Comment by t3chn0m4g3** [comment]
Please provide basic support info as requested on opening this issue.

**Comment by Concieted** [comment]
could you kindly give me steps as to how I can go about generating and extract installation logs please as I am a newbie

**Comment by t3chn0m4g3** [comment]
When you open an issue you find the corresponding steps to do so (the ones you previously ignored).

**Comment by Concieted** [comment]
apologies I am having trouble extracting the /install.log could you kindly advise as to how I go about that? Would a screen dump suffice?

**Comment by Concieted** [comment]
- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- Linux  blushingadvertising 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64
- What T-Pot version are you currently using?
- Haven't ran any honeypot since the installation 
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- 
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Vsphere
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- Yes. see attached screen dumps, please
![1](https://user-images.githubusercontent.com/60706489/144803347-c6313c8c-b8b0-40d3-a98d-961bb22038c5.png)
![2](https://user-images.githubusercontent.com/60706489/144803364-daf75c92-37f8-4b5d-8f1d-087e5dc5a436.png)
![3](https://user-images.githubusercontent.com/60706489/144803408-c1e2315b-c0f8-4b91-9cb6-cf593e425f9b.png)
![4](https://user-images.githubusercontent.com/60706489/144803419-188a58c5-fde9-4197-b618-a4af3531b96c.png)
![5](https://user-images.githubusercontent.com/60706489/144803438-ebfdf77b-d0f6-4a5c-b3bd-930665fedd0c.png)
![6](https://user-images.githubusercontent.com/60706489/144803455-867b5e0d-7db0-46bc-9bdd-847c1ca26724.png)
![7](https://user-images.githubusercontent.com/60706489/144803484-b3e413e5-8519-42d4-9067-3a12c2c60638.png)
![8](https://user-images.githubusercontent.com/60706489/144803511-33e5e649-adfa-4d82-97e5-c25226fc8e95.png) 
![9](https://user-images.githubusercontent.com/60706489/144803561-c76e3829-6f7e-4b82-9384-0442ed712eb0.png)
![10](https://user-images.githubusercontent.com/60706489/144803591-ce0c1996-d508-4664-b244-469183c6c19b.png)
- How long has your installation been running?
- 2021-12-02
- Did you install upgrades, packages, or use the update script?
- no
- Did you modify any scripts or configs? If yes, please attach the changes.
- no
- Please provide a screenshot of `glances` and `htop`.
![status ](https://user-images.githubusercontent.com/60706489/144803789-a08c936b-83bc-4e6a-a004-f5c0d9783ce3.png)
- How much free disk space is available (`df -h`)?
- 128 GB
- What is the current container status (`dps.sh`)?
![status ](https://user-images.githubusercontent.com/60706489/144803712-844b20f1-5e83-45ac-9514-78b2bdf02d9c.png)


- it hasn't generated a web or an Admin porta
![issue](https://user-images.githubusercontent.com/60706489/144812037-d5e707e4-598d-4897-937d-8057aaa8a3a8.png)
l

**Comment by t3chn0m4g3** [comment]
For some reason not all packages got installed.
Please provide `/install.err`.

**Comment by Concieted** [comment]
HI please see the image below;
![insall err (2)](https://user-images.githubusercontent.com/60706489/145003024-12a46a56-f834-4e7e-8d10-bffc957d1c31.png)

**Comment by t3chn0m4g3** [comment]
This confirms my suspicion, as part of the install some packages were not installed which resulted in a faulty install.
I can only recommend to reinstall and check if all resources for the installation are available. Since even the `curl` fails traffic seems to be blocked at some point.

**Comment by Concieted** [comment]
Thank you so much.

I'll follow suit and update accordingly
