### ISSUE TITLE
traid to use the latest iso and didnt work for me ,please help.

### ISSUE THREAD

**Issue by Tamirmaidani** [telekom-security/tpotce#951]
im traing for some time to use the T-Pot 20.06.2 iso on virtualbox
i put on parametrs : debain 64 bit.
and it starting to install the files on the blue screen ,but allways in the end it 
restart to the same starting point of instalation.(debain GNU installer menu)
im kind of new to it all please it will be a majore help if you can guide me with that...
thanx .

**Comment by t3chn0m4g3** [comment]
Try to eject the ISO from the virtual drive. If you like more help please provide the info we kindly ask for when opening issues.
