### ISSUE TITLE
WebUI Unable to Connect

### ISSUE THREAD

**Issue by ApplenBlackberryPi** [telekom-security/tpotce#954]
Issue : I have installed a fresh instance of the most recent TPot VM version onto VMWare with no apparent issues during install.  Upon reboot and start of the honeypot, I can access the Admin UI (port 64294) in a browser and via SSH (port 64295) in Putty / CMD, but I am unable to connect via the Web UI (port 64297) from a browser.  

I have tried using Microsoft Edge, Firefox and Chrome, but same issues of not being able to connect.
I have allocated 128GB storage, over 8GB RAM and 4 cores to the VM.

                  ********************************************************************************************************
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)
                  ********************************************************************************************************

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

![image](https://user-images.githubusercontent.com/42312486/144630687-245c0abf-38af-4d7d-a397-16f046ec93b9.png)

uname -a : Linux recentshanty 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

- What T-Pot version are you currently using?       20.06.2
 
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?      Standard

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? VMWare Workstation Pro 16.2.1 build-18811642

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
![image](https://user-images.githubusercontent.com/42312486/144631341-f6218213-ef4b-4317-9fc4-3feaf19c2819.png)

- How long has your installation been running?  I have never been able to get this to work.

- Did you install upgrades, packages or use the update script? Yes, I have since ran ./update.sh and still the same issue.

- Did you modify any scripts or configs? No

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/42312486/144631967-257b7783-3f38-45e7-a610-9f7c529855db.png)

![image](https://user-images.githubusercontent.com/42312486/144631982-605d5be1-c3d4-4011-b7ad-da4ea2132d72.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/42312486/144632019-15070791-48d4-461a-9c72-78d27a347017.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/42312486/144632045-534190e1-3c93-4c1b-8315-83a11de119e9.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/42312486/144632079-a8ef520f-55a2-4b1c-a7c1-34709ca7df3a.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/42312486/144632102-077f6f19-4a9a-4573-bb34-0758da2bc76d.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Thanks, it is refreshing to see someone actually posting logs to their issue 😄 
Sorry for the inconvenience, but it looks for some reason DockerHub's domains do not resolve properly on your end (see the `install.err`, hence no docker images are downloaded resulting in a problematic install.

**Comment by ApplenBlackberryPi** [comment]
Thank you t3chn0m4g3.  Is there any advice that you can provide where to look for resolving the Dockerhub issue?

**Comment by t3chn0m4g3** [comment]
Not really, there is too many reasons for an error like this to occur. Either you block some outgoing requests, DNS is not resolving properly, etc. All you can do is to try again and check if your machine can reach the internet without obstructions.

**Comment by ApplenBlackberryPi** [comment]
t3chn0m4g3, I have looked through other issues raised with docker (relating to VMs) and have found (https://github.com/telekom-security/tpotce/issues/841) which maybe of relevance.  I had tried running the command 'docker-compose -f /opt/tpot/etc/tpot.yml up' and was met with the below message.  Does this shed any more light on the reason behind the webGUI / docker not resolving?  (P.S.  I have not altered the locations or contents of any files or directories.  Effectively, it is a standard install) : 
![image](https://user-images.githubusercontent.com/42312486/145180771-863118ae-4cc0-4b8c-8488-f9264c3d6ce5.png)

**Comment by t3chn0m4g3** [comment]
I am using ESXi and VMWare as daily driver, works perfectly fine. So unfortunately there is nothing more I can do as to what I already mentioned.

**Comment by ApplenBlackberryPi** [comment]
I had removed the TPot honeypot from the hypervisor and ran through a completely fresh install, still the same issues.  I have also done a ping test to 8..8.8.8 from within the fresh TPot VM and can get responses, so defintitely getting responses. Will persevere.

**Comment by ApplenBlackberryPi** [comment]
FYI : I have followed through the resolution from issue (https://github.com/telekom-security/tpotce/issues/841), by creating a daemon.json and changing the network pool.  This, for some reason seem to have worked : 
![image](https://user-images.githubusercontent.com/42312486/145185509-0e22a606-d99d-498c-80da-4a8db33d6852.png)

**Comment by solarplex** [comment]
@ApplenBlackberryPi Did that fix your issue? I'm able to see all dockers status as UP but i'm still unable to access nginx dashboard (Port 64297)

**Comment by ApplenBlackberryPi** [comment]
> @ApplenBlackberryPi Did that fix your issue? I'm able to see all dockers status as UP but i'm still unable to access nginx dashboard (Port 64297)

Hi, have had this up for a few hours now and yes it seems to have fixed it as I’m getting hits on all the honeypots I installed.

**Comment by ApplenBlackberryPi** [comment]
Also, I loaded up the admin gui in a browser first (64294) then opened a new tab for the web gui (64297). As simple as it is, for some reason that helped recognise the port as open and get me access in.
