### ISSUE TITLE
Setting the clock for accurate Kibana searches

### ISSUE THREAD

**Issue by amishrabbit** [telekom-security/tpotce#962]
Hi there. I've been running the 20.06 tpot "nextgen" build for several months.

I recently realized that when I am doing searches in Kibana of the various honeypot logs and I choose a relatively short time window (1-2 hours), I am getting zero data in any of the dashboards. I now realize that the data is being timestamped incorrectly and my searches are not querying the correct time window as a result.

I am based in the US in the Mountain (UTC -7) time zone. The hardware clock for this VM is set to local time. The Kibana time zone is set to "browser time" which is also UTC -7.

At 17:00 local time I ran both "date" and "hwclock" and it appears the system is set to UTC but the hour of the date is set to here, so it looks like everything is seven hours off here as well.

[tsec@x:~]$ date
Sun 12 Dec 2021 05:00:13 PM UTC
[tsec@x:~]$ sudo hwclock
2021-12-12 16:59:28.321918+00:00

As a result of this timezone confusion, logs in the UI are off by at least six hours. As I type this, it is 16:55 local time, and the most recent data for a Kibana query of "last six hours" shows barely any data at the oldest point in a histogram, with the latest timestamp at 18:10 (!) or about 1hr 15m in the future. 

There doesn't seem to be an easy way to determine what time Kibana thinks is "now" and I don't know how to resolve this timezone confusion. Can you please look in to whether there's a better way to set the clock and have the logs timestamped correctly so these searches are not offset by 6-7 hours?

(I have reviewed this ticket and tried to make sure everything is set to UTC but the problem persists: https://github.com/telekom-security/tpotce/issues/343)

Thanks!
![timezone confusion in kibana](https://user-images.githubusercontent.com/2653726/145735091-2b37f34a-8104-4b8d-ab54-767cece54523.png)
[bugticket_log.zip](https://github.com/telekom-security/tpotce/files/7700135/bugticket_log.zip)

**Comment by t3chn0m4g3** [comment]
T-Pot's timezone is set to UTC.
Kibana calculates timezone settings for display from your browser settings.
![image](https://user-images.githubusercontent.com/4318452/145805842-bf3ff390-5ea8-4107-81d5-e36870c1c324.png)

As long you have not changed the timezone for T-Pot it will always display the time correctly based on your OS settings.
