### ISSUE TITLE
sshd does not allow port after Match Group 

### ISSUE THREAD

**Issue by ekoyle** [telekom-security/tpotce#973]
Running the latest .iso image, ssh does not start because of a [recent change made to the sshd_config](https://github.com/telekom-security/tpotce/commit/b76f0f109f9e8ffc8716ba531f41387335adfd2e).

```
[root@steepcupcake:~]# service ssh start
Job for ssh.service failed because the control process exited with error code.
See "systemctl status ssh.service" and "journalctl -xe" for details.
[root@steepcupcake:~]# /usr/sbin/sshd 
/etc/ssh/sshd_config line 128: Directive 'Port' is not allowed within a Match block
```

The `Port` option in the sshd_config must come before the Match statement.

Here is a quick and dirty patch (the `update.sh` part is non-trivial, so I just commented it out).

```
diff --git a/iso/installer/install.sh b/iso/installer/install.sh
index 1d7d5b0..44c0bc1 100755
--- a/iso/installer/install.sh
+++ b/iso/installer/install.sh
@@ -159,10 +159,10 @@ ListenStream=
 ListenStream=64294
 "
 mySSHSETTINGS="
+Port 64295
 Match Group tpotlogs
         PermitOpen 127.0.0.1:64305
         ForceCommand /usr/bin/false
-Port 64295
 "
 myRANDOM_HOUR=$(shuf -i 2-22 -n 1)
 myRANDOM_MINUTE=$(shuf -i 0-59 -n 1)
diff --git a/update.sh b/update.sh
index 9e116f2..a2a1295 100755
--- a/update.sh
+++ b/update.sh
@@ -218,8 +218,8 @@ echo
 
 # Ensure some defaults
 echo "### Ensure some T-Pot defaults with regard to some folders, permissions and configs."
-sed -i '/^port/Id' /etc/ssh/sshd_config
-echo "Port 64295" >> /etc/ssh/sshd_config
+#sed -i '/^port/Ic Port 64295' /etc/ssh/sshd_config
+#echo "Port 64295" >> /etc/ssh/sshd_config
 echo
 
 ### Ensure creation of T-Pot related folders, just in case
```

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
```
[root@steepcupcake:~]# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
[root@steepcupcake:~]# uname -a
Linux steepcupcake 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
```
- What T-Pot version are you currently using?
master branch at commit fb93d851190109aadddda2c834c81107e2559583

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
standard

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
vmware esxi

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
no

- How long has your installation been running?
1 day

- Did you install upgrades, packages or use the update script?
Did not work, fixed manually, update script broke it again

**Comment by t3chn0m4g3** [comment]
Thanks for reporting.
Fix is pushed, let me know if update works for you now.
