### ISSUE TITLE
📢  Preparing for Elastic Stack 8.0 and the next T-Pot release!

### ISSUE THREAD

**Issue by t3chn0m4g3** [telekom-security/tpotce#987]
In order to properly prepare for the next Elastic Stack Major release some of the currently used 7.16.2 configurations needed changes which will result in you seeing more features in Kibana than needed by T-Pot. Those features are mostly not covered by the Elastic Basic license and some of them will not be supported by T-Pot in the near future.

*You need to import the latest T-Pot Kibana objects as described in the [Wiki](https://github.com/telekom-security/tpotce/wiki/Import---Export-Kibana-Objects) and update the `Spaces` to ensure proper operation:.*
1. Import the objects as described above.
2. Open Kibana => Stack Management => Spaces and adjust the available features of the `Default` space:
![image](https://user-images.githubusercontent.com/4318452/148782856-deb1e793-6ec5-46de-bf49-81d72782fec3.png)

These changes are necessary as part of the road to the next major T-Pot release and will help to provide an update path for existing installations.

Also feel free to run `/opt/tpot/update.sh` to enjoy some of the upcoming changes already today.

![image](https://user-images.githubusercontent.com/4318452/148582955-0e7d8401-3b3a-4d03-9ce4-d029225e8d8a.png)

**Comment by eschultze** [comment]
The live attack dashboard is awesome! I just tweaked it not to show my own IP as the refresher increases with time.

**Comment by t3chn0m4g3** [comment]
In an effort to provide an upgrade path from T-Pot 20.06 to 22.x ELK 7.17.0 is being deployed to 20.06.

**Comment by t3chn0m4g3** [comment]
Almost done, starting with final testing and documentation..., most likely next version of T-Pot is 22.04. Stay tuned 😄 

![image](https://user-images.githubusercontent.com/4318452/161095478-99313dc0-ef93-46dc-9d67-6cb74f8d5b72.png)
