### ISSUE TITLE
Cannot access dashboards connection times out. 

### ISSUE THREAD

**Issue by pauhaith360** [telekom-security/tpotce#996]
Hello,

I'm having issue with accessing the web dashboards. While TPOT service is running, I cannot ping or get connected to any of the dashboards. I get "ERR_CONNECTION_TIMED_OUT" when attempting to connect. But when the TPOT service is not running I can ping the server.  

I'm not the greatest with Docker. I did notice some failures when running the status on TPOT service status but I'm unsure if these are the cause. As the containers come up ok. Not all show as healthy though. I also noticed while on the log in screen to get to the web GUI it references port 64297 but I don't see that on the netstat output. 

Below is the information requested. Any help would be greatly appreciated. Thank you!

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
```
lsb_release -a
    No LSB Modules are available
    Distributor ID: Debian
    Description: Debian GNU/Linux 10 (buster)
    Release: 10
    Codename: Buster
```
```
uname -a
    Linux extensivequartz 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

```
- What T-Pot version are you currently using?
   ` 20.06.2
`
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
    `Standard`

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
   ` Cloud - Openstack Wallaby Qemu/KVM hypervisor
`
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
   ` None. `

- How long has your installation been running?
 `  20 hours, 9 minutes`

- Did you install upgrades, packages or use the update script?
    `I have run the update script.` 

- Did you modify any scripts or configs? If yes, please attach the changes.
  ` No modifications to any scripts or configs. `

- Please provide a screenshot of `glances` and `htop`.

    ![glances_tpot](https://user-images.githubusercontent.com/66434931/150585783-d42f2879-9b36-403f-affb-298ff21de0e1.PNG)

    ![htop_tpot](https://user-images.githubusercontent.com/66434931/150585817-88d1ded5-ddbb-4e47-a12a-364bb1b447ab.PNG)

- How much free disk space is available (`df -h`)?
    ![freespace_tpot](https://user-images.githubusercontent.com/66434931/150585945-c2260b4f-cde1-403e-8407-afb61606e540.PNG)

- What is the current container status (`dps.sh`)?
    
   ![dps_tpot](https://user-images.githubusercontent.com/66434931/150586409-bdd912fe-b5f3-4a24-a9aa-ae19b9ada9a5.PNG)

- What is the status of the T-Pot service (`systemctl status tpot`)?

    ![status_tpot](https://user-images.githubusercontent.com/66434931/150586729-70c7b868-9306-4d04-85be-c84fcdf62877.PNG)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
    
    ![netstat_tpot](https://user-images.githubusercontent.com/66434931/150586879-56a320f8-7c00-4ea7-84c4-cff36aa11558.PNG)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
    `No containers reported as down.`

**Comment by t3chn0m4g3** [comment]
Everything as it supposed to. You are trying to connect via `https://<your ip:64297`, yes?
Please wait until all containers are showing healthy (monitor via `dps.sh 2`) and open another console for `docker logs kibana -f` (once Kibana starts up logs can be monitored that way).

**Comment by pauhaith360** [comment]
Hello, thank you for the response. I am trying to reach via https://<my ip:64297>. Thats when I receive the ERR_CONNECTION_TIMED_OUT error. I get connection time outs when attempting to connect via ssh on 64295 and when trying to get to the admin console @ 64294 as well. From my PC. 

The control node of my Openstack setup can ping and connect via SSH on 64295 though. So, if everything is as it should be. I'm thinking its something on my end either firewall or VPN settings.

If I could ask a clarifying question and thank you for the monitoring command. I've used it to monitor for about 30 minutes now. The only containers showing as healthy are the ones in my original screen capture of dps.sh. Except Kibana, it no longer shows as starting but is still showing healthy. Is there something else I should be doing to get the rest of the containers to show as healthy? Thank you again for your help.

**Comment by t3chn0m4g3** [comment]
If you can't reach 64295 vis SSH even then something else seems to be going wrong.

Can you see an error message in the Kibana logs you were monitoring?

Everything shows as healthy, yes?

**Comment by pauhaith360** [comment]
-  This is what I see in the Kibana logs. Looks to be a UI error:

![kibana_tpot](https://user-images.githubusercontent.com/66434931/150602261-ab903555-4f7c-4204-94cb-bdc5b0cfb0ce.PNG)

- Everything is not showing as healthy. The same containers that were in my original screen cap are healthy but none of the other containers show as such. I tried restarting the adbhoney container to see if it would come back healthy but it did not.

![dps_tpot](https://user-images.githubusercontent.com/66434931/150602434-f295fb12-285c-4d2d-b81f-4f9f84b26833.PNG)

- In regards to SSH, I can reach it from the control node of my Openstack set up. But not from outside of it. Such as from my workstation that is connected via VPN. Which is making me believe its my firewall or VPN settings. Even though currently I have everything pretty wide open while troubleshooting this.

**Comment by pauhaith360** [comment]
Ok so I've found that it is definitely on my end. The TPOT is working as it should and working great. I'm going to close this issue. Sorry to have bothered you with this but I really really appreciate the help. Thank you!!

**Comment by t3chn0m4g3** [comment]
Welcome 🙏
